import Imscribing.Nuclear.IslandOfStability
import Imscribing.NumberTheory.ErdosStrausProof
import Imscribing.NumberTheory.GeneralizedStarkCorrespondence
import Imscribing.NumberTheory.GrammarStarkCorrespondence
import Imscribing.NumberTheory.HnGcdTheorem
import Imscribing.NumberTheory.PrattCertificateMonad
import Imscribing.NumberTheory.PrattOb3ectProtocol
import Imscribing.NumberTheory.PrattStratification
import Imscribing.NumberTheory.StarkSunitD2048
import Imscribing.NumberTheory.TwoThreeSierpinski
import Imscribing.Ob3ects.apply_criticality_absorbing_element_entering_b_scaffold
import Imscribing.Ob3ects.categorical_join_scaffold
import Imscribing.Ob3ects.classical_non_commutative_complement_to_the_quan_scaffold
import Imscribing.Ob3ects.descent_to_stark_unit_bottleneck_for_the_d_19_br_scaffold
import Imscribing.Ob3ects.enumerate_17_280_000_crystal_eigenstates_as_clas_scaffold
import Imscribing.Ob3ects.exact_density_matrix_recovery_with_zero_reconstr_scaffold
import Imscribing.Ob3ects.exact_sic_geometry_achieved_with_frame_potential_scaffold
import Imscribing.Ob3ects.extract_144_exact_sic_probabilities_from_the_qua_scaffold
import Imscribing.Ob3ects.fix_the_density_matrix_tomography_record_as_a_pe_scaffold
import Imscribing.Ob3ects.informational_completeness_duality_splitting_d_1_scaffold
import Imscribing.Ob3ects.initialize_empty_c_d_hilbert_space_before_basis_scaffold
import Imscribing.Ob3ects.seal_the_system_with_the_crystal_constraint_mani_scaffold
import Imscribing.Ob3ects.sic_povm_functor_scaffold
import Imscribing.Ob3ects.the_axiomatized_existence_of_a_d_12_weyl_heisenb_scaffold
import Imscribing.Ob3ects.the_bruce_codex_tensor_bottleneck_at_parity_its_scaffold
import Imscribing.Ob3ects.the_d_12_sic_fiducial_known_only_as_a_complex128_scaffold
import Imscribing.Ob3ects.the_navier_stokes_criticality_type_gate_blocked_scaffold
import Imscribing.Ob3ects.the_p_versus_np_separation_gate_blocked_under_al_scaffold
import Imscribing.Ob3ects.the_riemann_hypothesis_failing_to_reach_idempote_scaffold
import Imscribing.Ob3ects.the_rongorongo_corpus_at_structural_distance_d_1_scaffold
import Imscribing.Ob3ects.the_structurally_closed_birch_swinnerton_dyer_cl_scaffold
import Imscribing.Ob3ects.the_structurally_closed_hodge_conjecture_clay_ty_scaffold
import Imscribing.Ob3ects.the_unclosed_p_versus_np_separation_lacking_a_st_scaffold
import Imscribing.Ob3ects.the_unclosed_riemann_hypothesis_gate_universe_la_scaffold
import Imscribing.Ob3ects.the_vacuously_satisfied_navier_stokes_criticalit_scaffold
import Imscribing.Ob3ects.the_voynich_manuscript_as_a_universal_engine_wit_scaffold
import Imscribing.Ob3ects.the_witness_vessel_protocol_culminates_in_a_tran_scaffold
import Imscribing.Ob3ects.the_yang_mills_mass_gap_closing_under_u10_with_g_scaffold
import Imscribing.Ob3ects.the_yang_mills_mass_gap_reaching_idempotent_term_scaffold
import Imscribing.Ob3ects.the_zeros_of_s_correspond_to_the_eigenvalues_of_abe3fc55_scaffold
import Imscribing.Vox.ProofLift
/-!
Sweep: lift every theorem THIS repo declares and emit `name<TAB>word<TAB>axioms`
for Vox to verdict in bulk. The lifter is NOT restated here — it lives once, in
`Imscribing.Vox.ProofLift`. Every copy of it that stood in these files was a
generation behind: `isSorry` matched the spelling rather than the axiom, and
`isAssumed` did not exist at all, so a declared axiom lifted to ◻ and read as
proved.
-/
#eval ProofLift.sweepAll
