import Mathlib

/-!
# SIC_D12_ExistenceRing — ALL 143 overlap identities, exact in the constructed ring

Part of the d=12 axiom-drop build (target `crystal_forces_d12_sic`). Unlike
`SIC_D12_Norm`/`SIC_D12_Equiangularity` (which certify *pinned data*), this module
derives **both SIC conditions from the constructed coordinate tower itself**: the
entire d=12 fiducial lives in the commutative ring

  R = K16(s0, s1, s3, s9, i, c5, u1),   dim 2048 over ℚ,

where K16 = ℚ[g]/(g¹⁶−10g¹⁴+40g¹²−90g¹⁰+126g⁸−96g⁶+25g⁴+2g²+1) is the totally-real
moduli field, and the generators satisfy
 * `s_k² = N_k` for k ∈ {0,1,3,9} (magnitude double covers; N_k = |z_k|²),
 * `i² = −1`,
 * `c5² = −OA5·c5 − OB5` (the u5-phase fold layer),
 * `u1² = (c2 + i·s2)/2` with **c2, s2 ∈ K16** (the u1 phase is *quadratic* over
   K16(i): 2±C1 are both K16 squares — branch_probe11),
and the fifth cover collapses: **N1·N5·(OA5²−4·OB5) = RHO² in K16**, so
`s1·s5·(2c5+OA5) = RHO` and s5 is *derived* (branch_probe13). Consequently
ζ₁₂ = (√3+i)/2 lives in K16(c5, i) and every coordinate z_k = √N_k·u_k is an
explicit element of R (phases: ζ-powers for even k; u1 times the banked unit
cross-products X31 = ū₃u₁, X15 = ū₁u₅, P1 = ū₁u₇, P3 = ū₃u₉, and ū₅u₁₁ = −P1
for odd k).

**What is machine-checked here (all `native_decide`, pure ℚ arithmetic):**
 1. the relation web: RHO², C2V², S2V², S5² = N5, ζ₁₂ cyclotomic identities,
    unit moduli of X31/X15/P1, u1·ū1 = 1, u1² = E2;
 2. `coord_moduli`: z̄_k·z_k = N_k in R for all 12 coordinates;
 3. `norm_sum`: Σ_k N_k = 1 (trace-one);
 4. `stratum_0` … `stratum_11` / `existence_identities_all`: **all 143 overlap
    identities O_{a,b}·Ō_{a,b} = 1/13 hold exactly in R**, where
    O_{a,b} = Σ_j z̄_j ζ^{(j−a)b} z_{j−a} is the formal WH overlap.

The branch flip-audit (branch_probe12) showed every ℚ-algebra component of R is a
*harmless* branch combination, so these ring identities mean: **any ring hom R → ℂ
sends the formal coordinate tuple to a genuine d=12 SIC fiducial.** The remaining
step to discharge `crystal_forces_d12_sic` is the embedding capstone (exhibit one
such hom: real root g₀ of the K16 polynomial, positive square roots, a real c5
root, u1 = √E2 — every layer solvable in ℂ).

Ring elements are sparse assoc lists over 7-bit keys (cov s0|s1|s3|s9, e_i, e_c5,
e_u1), each coefficient a K16 power-basis vector. Generated by
gen_lean_existence.py from the banked exact data (re-verified in fractions before
emit; the generator runs the full Python engine as its gate) — do not edit.
-/

namespace SIC.D12.ExistenceRing

/-- Element of K16 as a length-16 coefficient vector in the power basis {1,g,…,g¹⁵}. -/
abbrev K16 := List ℚ

/-- Polynomial addition (zero-padded). -/
def padd : List ℚ → List ℚ → List ℚ
  | xs, [] => xs
  | [], ys => ys
  | x :: xs, y :: ys => (x + y) :: padd xs ys

/-- Scalar multiple. -/
def kscale (c : ℚ) (xs : List ℚ) : List ℚ := xs.map (c * ·)

/-- Polynomial multiplication (constant-first). -/
def pmul (xs ys : List ℚ) : List ℚ :=
  xs.foldr (fun a acc => padd (kscale a ys) ((0 : ℚ) :: acc)) []

/-- Subtract `ys` from the leading entries of `xs` (both aligned at the head). -/
def subHead : List ℚ → List ℚ → List ℚ
  | xs, [] => xs
  | [], _ => []
  | x :: xs, y :: ys => (x - y) :: subHead xs ys

/-- Reduction pass, highest-first: while deg ≥ 16, kill the top coefficient
    against the monic K16 defining polynomial. Fuel-bounded. -/
def reduceGo : ℕ → List ℚ → List ℚ
  | 0, xs => xs
  | fuel + 1, xs =>
    if xs.length ≤ 16 then xs
    else
      match xs with
      | [] => []
      | c :: rest =>
        -- g¹⁶ = 10g¹⁴ − 40g¹² + 90g¹⁰ − 126g⁸ + 96g⁶ − 25g⁴ − 2g² − 1, highest-first tail
        reduceGo fuel (subHead rest (kscale c [0, -10, 0, 40, 0, -90, 0, 126, 0, -96, 0, 25, 0, 2, 0, 1]))

/-- K16 multiplication: convolve, reduce mod the defining polynomial, pad to length 16. -/
def kmul (x y : K16) : K16 :=
  let r := (reduceGo 31 (pmul x y).reverse).reverse
  r ++ List.replicate (16 - r.length) (0 : ℚ)

/-- K16 addition. -/
def kadd (x y : K16) : K16 := padd x y

def one16 : K16 := [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
def two16 : K16 := [2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

def isZeroK (v : K16) : Bool := v.all (· == 0)

/-- Exact fiducial modulus |z0|² in the K16 power basis (build_k16_v3). -/
def M0 : K16 := [563/8541, 1207/17082, 13/657, -3322/8541, 971/5694, 57245/34164, -2560/8541, -21838/8541, 461/1898, 67735/34164, -77/657, -8159/8541, 263/8541, 8899/34164, -3/949, -953/34164]
/-- Exact fiducial modulus |z1|² in the K16 power basis (build_k16_v3). -/
def M1 : K16 := [475/2847, -8243/34164, 686/2847, 13475/11388, -2713/5694, -7255/2628, 638/2847, 2107/657, -31/5694, -18479/8541, -61/949, 7919/8541, 203/5694, -199/876, -5/949, 769/34164]
/-- Exact fiducial modulus |z2|² in the K16 power basis (build_k16_v3). -/
def M2 : K16 := [2113/17082, 2581/34164, -6467/8541, 26231/17082, 11477/5694, -189017/34164, -20656/8541, 123533/17082, 4717/2847, -176809/34164, -6203/8541, 78887/34164, 1565/8541, -9917/17082, -53/2847, 997/17082]
/-- Exact fiducial modulus |z3|² in the K16 power basis (build_k16_v3). -/
def M3 : K16 := [-595/5694, 1445/8541, 26/219, 1462/2847, 971/949, -8261/2628, -5120/2847, 37946/8541, 1383/949, -111655/34164, -154/219, 25361/17082, 526/2847, -4279/11388, -18/949, 1289/34164]
/-- Exact fiducial modulus |z4|² in the K16 power basis (build_k16_v3). -/
def M4 : K16 := [74/657, 10475/34164, 5791/8541, -12439/34164, -15361/5694, -13645/34164, 30896/8541, 16033/17082, -7483/2847, -13333/17082, 10207/8541, 3130/8541, -2617/8541, -3131/34164, 89/2847, 307/34164]
/-- Exact fiducial modulus |z5|² in the K16 power basis (build_k16_v3). -/
def M5 : K16 := [257/1898, 3241/34164, -285/949, -9307/5694, -100/2847, 12299/2628, 1922/2847, -97933/17082, -2059/2847, 135319/34164, 1184/2847, -58867/34164, -243/1898, 2429/5694, 14/949, -727/17082]
/-- Exact fiducial modulus |z6|² in the K16 power basis (build_k16_v3). -/
def M6 : K16 := [563/8541, -1207/17082, 13/657, 3322/8541, 971/5694, -57245/34164, -2560/8541, 21838/8541, 461/1898, -67735/34164, -77/657, 8159/8541, 263/8541, -8899/34164, -3/949, 953/34164]
/-- Exact fiducial modulus |z7|² in the K16 power basis (build_k16_v3). -/
def M7 : K16 := [475/2847, 8243/34164, 686/2847, -13475/11388, -2713/5694, 7255/2628, 638/2847, -2107/657, -31/5694, 18479/8541, -61/949, -7919/8541, 203/5694, 199/876, -5/949, -769/34164]
/-- Exact fiducial modulus |z8|² in the K16 power basis (build_k16_v3). -/
def M8 : K16 := [2113/17082, -2581/34164, -6467/8541, -26231/17082, 11477/5694, 189017/34164, -20656/8541, -123533/17082, 4717/2847, 176809/34164, -6203/8541, -78887/34164, 1565/8541, 9917/17082, -53/2847, -997/17082]
/-- Exact fiducial modulus |z9|² in the K16 power basis (build_k16_v3). -/
def M9 : K16 := [-595/5694, -1445/8541, 26/219, -1462/2847, 971/949, 8261/2628, -5120/2847, -37946/8541, 1383/949, 111655/34164, -154/219, -25361/17082, 526/2847, 4279/11388, -18/949, -1289/34164]
/-- Exact fiducial modulus |z10|² in the K16 power basis (build_k16_v3). -/
def M10 : K16 := [74/657, -10475/34164, 5791/8541, 12439/34164, -15361/5694, 13645/34164, 30896/8541, -16033/17082, -7483/2847, 13333/17082, 10207/8541, -3130/8541, -2617/8541, 3131/34164, 89/2847, -307/34164]
/-- Exact fiducial modulus |z11|² in the K16 power basis (build_k16_v3). -/
def M11 : K16 := [257/1898, -3241/34164, -285/949, 9307/5694, -100/2847, -12299/2628, 1922/2847, 97933/17082, -2059/2847, -135319/34164, 1184/2847, 58867/34164, -243/1898, -2429/5694, 14/949, 727/17082]
/-- sqrt3 carrier: C3W² = 3·N1·N5 in K16 (comp_cartography2). -/
def C3W : K16 := [0, 1193/5694, 0, -17467/11388, 0, 4171/876, 0, -5974/949, 0, 995/219, 0, -23483/11388, 0, 3031/5694, 0, -4/73]
/-- Magnitude square-class witness: CM2² = N2·N(pair) (magnitude_classes). -/
def CM2 : K16 := [0, -10/657, 0, 32693/34164, 0, -20632/8541, 0, 92687/34164, 0, -15242/8541, 0, 25267/34164, 0, -455/2628, 0, 281/17082]
/-- Magnitude square-class witness: CM4² = N4·N(pair) (magnitude_classes). -/
def CM4 : K16 := [-862/8541, -1240/8541, -1889/8541, 4730/8541, 614/949, -35599/34164, -4474/8541, 34961/34164, 707/2847, -5360/8541, -452/8541, 2116/8541, -83/17082, -1889/34164, 2/949, 43/8541]
/-- Magnitude square-class witness: CM6² = N6·N(pair) (magnitude_classes). -/
def CM6 : K16 := [0, -1207/17082, 0, 3322/8541, 0, -57245/34164, 0, 21838/8541, 0, -67735/34164, 0, 8159/8541, 0, -8899/34164, 0, 953/34164]
/-- Magnitude square-class witness: CM7² = N7·N(pair) (magnitude_classes). -/
def CM7 : K16 := [791/5694, 1370/8541, -275/2847, -51613/34164, -779/949, 118127/34164, 3878/2847, -31912/8541, -2953/2847, 20602/8541, 2713/5694, -33731/34164, -114/949, 1951/8541, 34/2847, -367/17082]
/-- Magnitude square-class witness: CM8² = N8·N(pair) (magnitude_classes). -/
def CM8 : K16 := [1187/17082, 10/657, -2734/8541, -32693/34164, -1171/5694, 20632/8541, 8326/8541, -92687/34164, -5501/5694, 15242/8541, 4553/8541, -25267/34164, -2713/17082, 455/2628, 17/949, -281/17082]
/-- Magnitude square-class witness: CM10² = N10·N(pair) (magnitude_classes). -/
def CM10 : K16 := [0, 1240/8541, 0, -4730/8541, 0, 35599/34164, 0, -34961/34164, 0, 5360/8541, 0, -2116/8541, 0, 1889/34164, 0, -43/8541]
/-- Magnitude square-class witness: CM11² = N11·N(pair) (magnitude_classes). -/
def CM11 : K16 := [791/5694, -1370/8541, -275/2847, 51613/34164, -779/949, -118127/34164, 3878/2847, 31912/8541, -2953/2847, -20602/8541, 2713/5694, 33731/34164, -114/949, -1951/8541, 34/2847, 367/17082]
/-- C1 = 2cos(4θ₁) = u1⁴ + u1⁻⁴ in K16 (a_full_probe5b). -/
def C1V : K16 := [35618/1971, 4688/219, -17576/1971, -386432/1971, -50492/657, 915736/1971, 266240/1971, -1015792/1971, -23972/219, 661880/1971, 104104/1971, -272288/1971, -27352/1971, 63688/1971, 104/73, -2024/657]
/-- c5 quadratic: c5² = −OA5·c5 − OB5 (oct factor over K16, a_full_probe5b). -/
def OA5 : K16 := [35618/1971, -4688/219, -17576/1971, 386432/1971, -50492/657, -915736/1971, 266240/1971, 1015792/1971, -23972/219, -661880/1971, 104104/1971, 272288/1971, -27352/1971, -63688/1971, 104/73, 2024/657]
/-- c5 quadratic constant term (a_full_probe5b). -/
def OB5 : K16 := [11831611/17739, -1770304/1971, -5786560/17739, 142747840/17739, -16623520/5913, -347570528/17739, 87654400/17739, 393909824/17739, -7892320/1971, -260311840/17739, 34274240/17739, 108681280/17739, -9005120/17739, -25833056/17739, 34240/657, 832096/5913]
/-- P1 = ubar1·u7 = (REP1 + i·IMP1)·s1·s5 (a6_probe4). -/
def REP1 : K16 := [-2344/657, 0, -52148/657, 0, 22516/219, 0, -11668/657, 0, -2276/73, 0, 21616/657, 0, -8632/657, 0, 124/73, 0]
/-- imaginary part of P1 over the s1·s5 cover (a6_probe4). -/
def IMP1 : K16 := [0, 13004/657, 0, -128776/657, 0, 276842/657, 0, -282160/657, 0, 174598/657, 0, -68192/657, 0, 14878/657, 0, -1322/657]
/-- P3 = ubar3·u9 = (REP3 + i·IMP3)·s3·s9 (a6_probe4). -/
def REP3 : K16 := [-35188/6351, 0, 27040/6351, 0, 77680/2117, 0, -409600/6351, 0, 110640/2117, 0, -160160/6351, 0, 42080/6351, 0, -1440/2117, 0]
/-- imaginary part of P3 over the s3·s9 cover (a6_probe4). -/
def IMP3 : K16 := [0, -10300/2117, 0, -30482/2117, 0, 282594/2117, 0, -420652/2117, 0, 316380/2117, 0, -146066/2117, 0, 37196/2117, 0, -3732/2117]
/-- X31 = ubar3·u1 = (REX31 + i·IMX31)·s1·s3 (a_cross_probe6). -/
def REX31 : K16 := [123404/19053, 142814/19053, 581008/19053, -514748/19053, -847792/19053, 1119508/19053, 125728/19053, -380708/6351, 289048/19053, 701600/19053, -286048/19053, -89458/6351, 115672/19053, 6102/2117, -15328/19053, -4430/19053]
/-- imaginary part of X31 over the s1·s3 cover (a_cross_probe6). -/
def IMX31 : K16 := [22424/6351, -246574/19053, -244672/6351, -471242/6351, 2148944/19053, 648700/2117, -2459392/19053, -7324850/19053, 1629976/19053, 1688624/6351, -681056/19053, -2170456/19053, 159392/19053, 515060/19053, -15040/19053, -48926/19053]
/-- X15 = ubar1·u5: Re = X15RA + X15RB·c5, cover-free (a_cross_probe9). -/
def X15RA : K16 := [3131/3942, -187/438, -2873/3942, 34649/7884, -16507/2628, -70933/7884, 21760/1971, 17158/1971, -7837/876, -10085/1971, 17017/3942, 14681/7884, -4471/3942, -1469/3942, 17/146, 20/657]
/-- c5-coefficient of Re X15 (a_cross_probe9). -/
def X15RB : K16 := [-689/3942, -133/438, 845/3942, 20653/7884, 4855/2628, -52667/7884, -6400/1971, 15443/1971, 2305/876, -20855/3942, -5005/3942, 17797/7884, 1315/3942, -1082/1971, -5/146, 71/1314]
/-- Im X15 = X15IA + X15IB·c5, cover-free (a_cross_probe9). -/
def X15IA : K16 := [1049/7884, -4231/3942, 11879/3942, -25859/7884, -31787/7884, 34219/1971, 154/219, -94357/3942, 9821/7884, 137273/7884, -183/146, -61837/7884, 329/657, 15599/7884, -259/3942, -1567/7884]
/-- c5-coefficient of Im X15 (a_cross_probe9). -/
def X15IB : K16 := [637/7884, -2729/3942, -5909/3942, -16753/7884, 59297/7884, 39829/3942, -2542/219, -53759/3942, 71065/7884, 77437/7884, -635/146, -34619/7884, 781/657, 8707/7884, -503/3942, -875/7884]
/-- c2 = 2cos(2θ₁) ∈ K16: C2V² = 2 + C1V (branch_probe11). -/
def C2V : K16 := [2492/657, 1472/657, -114/73, -15802/657, -8734/657, 30662/657, 4886/219, -27904/657, -11114/657, 15688/657, 1700/219, -5414/657, -1328/657, 976/657, 46/219, -68/657]
/-- s2 = 2sin(2θ₁) ∈ K16: S2V² = 2 − C1V (branch_probe11). -/
def S2V : K16 := [98/657, -3776/657, -8624/657, -11542/657, 3276/73, 63124/657, -38764/657, -88360/657, 9256/219, 64934/657, -12362/657, -29366/657, 3104/657, 7418/657, -104/219, -746/657]
/-- the cover-collapse witness: RHO² = N1·N5·(OA5²−4·OB5); s1·s5·(2c5+OA5) = RHO (branch_probe13). -/
def RHO : K16 := [-166/8541, -45166/8541, 126736/8541, -138577/8541, -385784/8541, 51221/657, 52320/949, -900742/8541, -325252/8541, 649414/8541, 47408/2847, -290561/8541, -11768/2847, 73102/8541, 3520/8541, -7346/8541]
/-- exact inverse of N1·N5 in K16 (property `in15_prop`). -/
def IN15 : K16 := [94328/657, 0, 35152/657, 0, 100984/219, 0, -532480/657, 0, 47944/73, 0, -208208/657, 0, 54704/657, 0, -624/73, 0]
/-- exact inverse of N0 in K16 (property `in0_prop`). -/
def IN0V : K16 := [6884/219, -6872/219, -1352/219, 52126/219, -3884/73, -155078/219, 20480/219, 201568/219, -5532/73, -145252/219, 8008/219, 66002/219, -2104/219, -17068/219, 72/73, 1760/219]
/-- exact inverse of N1 in K16 (property `in1_prop`). -/
def IN1V : K16 := [11008/657, 8404/657, -26128/657, -136426/657, -12668/657, 405626/657, 94448/657, -170642/219, -97720/657, 359830/657, 56152/657, -53074/219, -17572/657, 13384/219, 2056/657, -4066/657]
/-- exact inverse of N5 in K16 (property `in5_prop`). -/
def IN5V : K16 := [1808/73, -21224/657, 9160/219, 10748/73, 24320/657, -86216/219, -114928/657, 325442/657, 114316/657, -25510/73, -64160/657, 102400/657, 19676/657, -26000/657, -2272/657, 2642/657]
/-- exact inverse of D5 = OA5²−4·OB5 in K16 (property `id5_prop`). -/
def ID5V : K16 := [-10867/94608, -505/2628, 3211/23652, 37807/23652, 18449/15768, -201535/47304, -12160/5913, 121829/23652, 8759/5256, -167525/47304, -19019/23652, 36373/23652, 4997/23652, -18007/47304, -19/876, 599/15768]

/-- D5 = OA5² − 4·OB5, the discriminant of the c5 layer. -/
def D5V : K16 := kadd (kmul OA5 OA5) (kscale (-4) OB5)

theorem in15_prop : kmul (kmul M1 M5) IN15 = one16 := by native_decide
theorem in0_prop : kmul M0 IN0V = one16 := by native_decide
theorem in1_prop : kmul M1 IN1V = one16 := by native_decide
theorem in5_prop : kmul M5 IN5V = one16 := by native_decide
theorem id5_prop : kmul D5V ID5V = one16 := by native_decide

/-! ## The K16-level relation web -/

/-- The sqrt3 carrier: C3W² = 3·N1·N5. -/
theorem c3w_sq : kmul C3W C3W = kscale 3 (kmul M1 M5) := by native_decide
/-- c2 = 2cos2θ₁ ∈ K16: its square is 2 + C1. -/
theorem c2_sq : kmul C2V C2V = kadd two16 C1V := by native_decide
/-- s2 = 2sin2θ₁ ∈ K16: its square is 2 − C1. -/
theorem s2_sq : kmul S2V S2V = kadd two16 (kscale (-1) C1V) := by native_decide
/-- **The cover-collapse relation**: RHO² = N1·N5·D5, so s1·s5·(2c5+OA5) = RHO. -/
theorem rho_sq : kmul RHO RHO = kmul (kmul M1 M5) D5V := by native_decide
/-- Trace-one / norm condition: the twelve moduli sum to 1. -/
theorem norm_sum :
    kadd M0 (kadd M1 (kadd M2 (kadd M3 (kadd M4 (kadd M5 (kadd M6 (kadd M7
      (kadd M8 (kadd M9 (kadd M10 M11)))))))))) = one16 := by native_decide

/-! ## The ring R: sparse assoc lists over 7-bit keys -/

/-- Ring element: sorted assoc list, key = cov + 16·e_i + 32·e_c5 + 64·e_u1
    (cov = 4-bit mask over the covers s0,s1,s3,s9), value = nonzero K16 vector. -/
abbrev RElt := List (ℕ × K16)

/-- Insert-with-add into a sorted assoc list, dropping keys whose value cancels. -/
def insertAdd : RElt → ℕ → K16 → RElt
  | [], k, v => if isZeroK v then [] else [(k, v)]
  | (k', v') :: rest, k, v =>
    if k < k' then
      if isZeroK v then (k', v') :: rest else (k, v) :: (k', v') :: rest
    else if k == k' then
      let w := kadd v' v
      if isZeroK w then rest else (k, w) :: rest
    else (k', v') :: insertAdd rest k v

def radd (A B : RElt) : RElt := B.foldl (fun acc p => insertAdd acc p.1 p.2) A
def rneg (A : RElt) : RElt := A.map (fun p => (p.1, kscale (-1) p.2))
def rK (v : K16) : RElt := [(0, v)]
def rone : RElt := rK one16

def C2H : K16 := kscale (1/2) C2V
def S2H : K16 := kscale (1/2) S2V

def encKey (cov ei e5 e1 : ℕ) : ℕ := cov + 16 * ei + 32 * e5 + 64 * e1

/-- u1-layer reduction: u1² = (c2 + i·s2)/2. -/
def red1 (cov ei e5 e1 : ℕ) (c : K16) : List (ℕ × ℕ × ℕ × ℕ × K16) :=
  if e1 ≥ 2 then
    [(cov, ei, e5, e1 - 2, kmul c C2H), (cov, ei + 1, e5, e1 - 2, kmul c S2H)]
  else [(cov, ei, e5, e1, c)]

/-- i-layer reduction: i² = −1. -/
def red2 : ℕ × ℕ × ℕ × ℕ × K16 → ℕ × ℕ × ℕ × ℕ × K16
  | (cov, ei, e5, e1, c) =>
    if ei ≥ 2 then (cov, ei - 2, e5, e1, kscale (-1) c) else (cov, ei, e5, e1, c)

/-- c5-layer reduction: c5² = −OA5·c5 − OB5. -/
def red3 : ℕ × ℕ × ℕ × ℕ × K16 → List (ℕ × K16)
  | (cov, ei, e5, e1, c) =>
    if e5 ≥ 2 then
      [(encKey cov ei (e5 - 1) e1, kscale (-1) (kmul c OA5)),
       (encKey cov ei (e5 - 2) e1, kscale (-1) (kmul c OB5))]
    else [(encKey cov ei e5 e1, c)]

/-- Normalize one raw product key (exponent sums ≤ 2 per layer) into canonical keys. -/
def contrib (cov ei e5 e1 : ℕ) (c : K16) : List (ℕ × K16) :=
  ((red1 cov ei e5 e1 c).map red2).flatMap red3

/-- The cover squares N0, N1, N3, N9 by bit index. -/
def covK : ℕ → K16
  | 0 => M0
  | 1 => M1
  | 2 => M3
  | _ => M9

/-- Multiply in N_k for every cover bit shared by both factors (s_k² = N_k). -/
def covCorr (m : ℕ) (c : K16) : K16 :=
  (List.range 4).foldl (fun acc b => if (m >>> b) &&& 1 == 1 then kmul acc (covK b) else acc) c

/-- Ring multiplication. -/
def rmul (A B : RElt) : RElt :=
  A.foldl (init := ([] : RElt)) fun acc pa =>
    B.foldl (init := acc) fun acc pb =>
      let ka := pa.1; let kb := pb.1
      let coef := covCorr ((ka % 16) &&& (kb % 16)) (kmul pa.2 pb.2)
      (contrib ((ka % 16) ^^^ (kb % 16)) (ka / 16 % 2 + kb / 16 % 2)
        (ka / 32 % 2 + kb / 32 % 2) (ka / 64 + kb / 64) coef).foldl
        (fun a p => insertAdd a p.1 p.2) acc

/-- ū1 = conj(E2)·u1 = ((c2 − i·s2)/2)·u1 (unit phase, |E2| = 1). -/
def rU1i : RElt := [(64, C2H), (80, kscale (-1) S2H)]

/-- Formal conjugation: g, s_k, c5 fixed; i ↦ −i; u1 ↦ ū1. -/
def rconj (A : RElt) : RElt :=
  A.foldl (init := ([] : RElt)) fun acc p =>
    let v := if p.1 / 16 % 2 == 1 then kscale (-1) p.2 else p.2
    let base : RElt := [(p.1 % 64, v)]
    radd acc (if p.1 / 64 == 1 then rmul base rU1i else base)

/-! ## The constructed tower elements -/

def rU1 : RElt := [(64, one16)]
def rE2 : RElt := [(0, C2H), (16, S2H)]

/-- rho/D5 (the collapse quotient). -/
def RS : K16 := kmul RHO ID5V
/-- s5 as a derived element: s5 = RHO·(2c5+OA5)·s1/(D5·N1). -/
def rS5 : RElt := [(2, kmul (kmul RS IN1V) OA5), (34, kscale 2 (kmul RS IN1V))]
/-- s1·s5 = RHO·(2c5+OA5)/D5, cover-free. -/
def rS1S5 : RElt := [(0, kmul RS OA5), (32, kscale 2 RS)]

/-- ζ₁₂ = (√3 + i)/2 with √3 = C3W·(s1·s5)/(N1·N5) ∈ K16(c5). -/
def W3 : K16 := kmul (kmul C3W IN15) RS
def zeta : RElt := [(0, kscale (1/2) (kmul W3 OA5)), (16, kscale (1/2) one16), (32, W3)]
def zpow : ℕ → RElt
  | 0 => rone
  | n + 1 => rmul (zpow n) zeta

def rP1 : RElt := rmul [(0, REP1), (16, IMP1)] rS1S5
def rP3 : RElt := [(12, REP3), (28, IMP3)]
def rX31 : RElt := [(6, REX31), (22, IMX31)]
def rX31c : RElt := [(6, REX31), (22, kscale (-1) IMX31)]
def rX15 : RElt := [(0, X15RA), (16, X15IA), (32, X15RB), (48, X15IB)]

/-- Magnitude √N_k of each coordinate, as a ring element. -/
def rSQ : ℕ → RElt
  | 0 => [(1, one16)]
  | 1 => [(2, one16)]
  | 2 => [(1, kmul CM2 IN0V)]
  | 3 => [(4, one16)]
  | 4 => [(1, kmul CM4 IN0V)]
  | 5 => rS5
  | 6 => [(1, kmul CM6 IN0V)]
  | 7 => rmul (rK (kmul CM7 IN5V)) rS5
  | 8 => [(1, kmul CM8 IN0V)]
  | 9 => [(8, one16)]
  | 10 => [(1, kmul CM10 IN0V)]
  | _ => [(2, kmul CM11 IN1V)]

/-- Unit phase u_k of each coordinate. -/
def rUPH : ℕ → RElt
  | 0 => rone
  | 1 => rU1
  | 2 => zpow 7
  | 3 => rmul rX31c rU1
  | 4 => rone
  | 5 => rmul rX15 rU1
  | 6 => zpow 9
  | 7 => rmul rP1 rU1
  | 8 => zpow 10
  | 9 => rmul rP3 (rmul rX31c rU1)
  | 10 => zpow 9
  | _ => rneg (rmul rP1 (rmul rX15 rU1))

/-- Coordinate z_k = √N_k · u_k as an element of R. -/
def rZ (k : ℕ) : RElt := rmul (rSQ k) (rUPH k)
/-- Conjugate coordinate z̄_k. -/
def rZB (k : ℕ) : RElt := rconj (rZ k)

/-- Modulus data by index. -/
def modK : ℕ → K16
  | 0 => M0 | 1 => M1 | 2 => M2 | 3 => M3 | 4 => M4 | 5 => M5
  | 6 => M6 | 7 => M7 | 8 => M8 | 9 => M9 | 10 => M10 | _ => M11

/-! ## In-ring relation checks -/

/-- s5² = N5 through the collapse relation — the ring-level form of `rho_sq`. -/
theorem s5_sq : rmul rS5 rS5 = rK M5 := by native_decide
theorem s1s5_sq : rmul rS1S5 rS1S5 = rK (kmul M1 M5) := by native_decide
/-- ζ₁₂ is a primitive 12th root of unity in R. -/
theorem zeta_pow12 : zpow 12 = rone := by native_decide
theorem zeta_pow6 : zpow 6 = rneg rone := by native_decide
/-- Φ₁₂(ζ) = ζ⁴ − ζ² + 1 = 0. -/
theorem zeta_phi12 : radd (radd (zpow 4) (rneg (zpow 2))) rone = [] := by native_decide
/-- u1 is a unit phase: u1·ū1 = 1. -/
theorem u1_unit : rmul rU1 rU1i = rone := by native_decide
/-- The u1-layer relation: u1² = E2 = (c2 + i·s2)/2. -/
theorem u1_sq : rmul rU1 rU1 = rE2 := by native_decide
/-- X31, X15, P1 are unit phases in R. -/
theorem x31_unit : rmul rX31 rX31c = rone := by native_decide
theorem x15_unit : rmul rX15 (rconj rX15) = rone := by native_decide
theorem p1_unit : rmul rP1 (rconj rP1) = rone := by native_decide
/-- Every coordinate has the right modulus: z̄_k·z_k = N_k in R. -/
theorem coord_moduli :
    (List.range 12).all (fun k => rmul (rZB k) (rZ k) == rK (modK k)) = true := by
  native_decide

/-! ## The 143 overlap identities -/

/-- Target: the constant 1/13 = 1/(d+1) as a ring element. -/
def rT13 : RElt := rK [1/13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

/-- One WH stratum: for fixed shift a, check O_{a,b}·Ō_{a,b} = 1/13 for all b
    ((a,b) = (0,0) excluded). O_{a,b} = Σ_j z̄_j ζ^{(j−a)b} z_{j−a}. -/
def stratum (a : ℕ) : Bool :=
  let zps := (List.range 12).map zpow
  let T := (List.range 12).map fun j => rmul (rZB j) (rZ ((j + 12 - a) % 12))
  let TC := T.map rconj
  (List.range 12).all fun b =>
    (a == 0 && b == 0) ||
    (let O := (List.range 12).foldl (fun acc j =>
        radd acc (rmul T[j]! zps[((j + 12 - a) % 12 * b) % 12]!)) ([] : RElt)
     let Oc := (List.range 12).foldl (fun acc j =>
        radd acc (rmul TC[j]! zps[(12 - (j + 12 - a) % 12 * b % 12) % 12]!)) ([] : RElt)
     rmul O Oc == rT13)

theorem stratum_0 : stratum 0 = true := by native_decide
theorem stratum_1 : stratum 1 = true := by native_decide
theorem stratum_2 : stratum 2 = true := by native_decide
theorem stratum_3 : stratum 3 = true := by native_decide
theorem stratum_4 : stratum 4 = true := by native_decide
theorem stratum_5 : stratum 5 = true := by native_decide
theorem stratum_6 : stratum 6 = true := by native_decide
theorem stratum_7 : stratum 7 = true := by native_decide
theorem stratum_8 : stratum 8 = true := by native_decide
theorem stratum_9 : stratum 9 = true := by native_decide
theorem stratum_10 : stratum 10 = true := by native_decide
theorem stratum_11 : stratum 11 = true := by native_decide

/-- **All 143 overlap identities hold exactly in R** — the equiangularity half of
    IsSICPOVM derived from the constructed tower (with `norm_sum` the trace-one half,
    and `coord_moduli` tying the coordinates to the moduli). -/
theorem existence_identities_all : (List.range 12).all stratum = true := by
  native_decide

end SIC.D12.ExistenceRing
