/-
# The phase lattice of the Fibonacci anyon model

Measure every angle in **windings**, one winding being a full turn, so a phase is
an element of `ℚ / ℤ`. At level `k = 3` every phase native to the model is an
exact multiple of a tenth of a winding:

    θ_τ = R^{ττ}_1 = 4/10      R^{ττ}_τ = -3/10
    t   (Jones root) = 2/10    α (framing) = -1/10

and the two eigenvalues of the braid generator are `4/10` and `-3/10`.

Two things are proved here.

**The lattice is generated.** The subgroup of the tenths generated by the braid
generator's two eigenvalues is the whole of it, not a proper part. Written in
`ZMod 10`, where `n` stands for the winding `n/10`, the subgroup generated by
`4` and `7` is everything.

**The gate is not on it.** `T` is one eighth of a winding, and `1/8` is not a
multiple of `1/10`. So no product of the generators' *phases* is the phase of
`T`: the gate is off the lattice the model's phases live on, which is the
arithmetic fact under the need for gate compilation.

The second theorem is narrow by construction. It says nothing on its own about
whether some braid WORD realizes `T`, since the eigenvalues of a product of
non-commuting matrices need not lie in the group generated by the factors'
eigenvalues, and if they did the braid group image could not be dense. What is
proved here is that the phase lattice does not contain the gate.

The question about words is settled in `GateObstruction`, and not by the
lattice: no braid word realizes `T` or `S`, at any length, up to any phase,
because the braid matrices are written in `K = ℚ(ζ₅, √φ)` and `√2` is not in it.
`Z` is realized, by `σ₁⁵`.
-/

import Mathlib

namespace Imscribing.Quantum

/-! ## Windings as tenths -/

/-- A phase, in tenths of a winding. `(n : Tenth)` is the winding `n/10`. -/
abbrev Tenth := ZMod 10

/-- The topological spin of τ, `4/10` of a winding. Equal to `R^{ττ}_1`. -/
def thetaTau : Tenth := 4

/-- `R^{ττ}_τ`, `-3/10` of a winding. -/
def rTau : Tenth := -3

/-- The evaluation point of the Jones polynomial, `2/10` of a winding. -/
def jonesRoot : Tenth := 2

/-- The framing phase, `-1/10` of a winding. -/
def framing : Tenth := -1

/-! ## The lattice is generated by the braid generator's eigenvalues -/

/-- The two eigenvalues differ by a single tenth: `4/10 - (-3/10) = 7/10`, and
    `4/10 + 7/10 = 11/10 = 1/10`. One tenth is reachable from them. -/
theorem one_tenth_from_eigenvalues : thetaTau + (thetaTau - rTau) = 1 := by
  decide

/-- **The phase lattice.** The subgroup generated by the braid generator's two
    eigenvalues is the whole of the tenths.

    So the phases the model can build from its own generator are exactly the
    tenths: no finer, and no coarser. -/
theorem eigenvalues_generate :
    AddSubgroup.closure ({thetaTau, rTau} : Set Tenth) = ⊤ := by
  rw [eq_top_iff]
  intro x _
  -- one tenth is in the closure, and one tenth generates everything
  have h4 : thetaTau ∈ AddSubgroup.closure ({thetaTau, rTau} : Set Tenth) :=
    AddSubgroup.subset_closure (by simp)
  have h3 : rTau ∈ AddSubgroup.closure ({thetaTau, rTau} : Set Tenth) :=
    AddSubgroup.subset_closure (by simp)
  have h1 : (1 : Tenth) ∈ AddSubgroup.closure ({thetaTau, rTau} : Set Tenth) := by
    have : (1 : Tenth) = thetaTau + (thetaTau - rTau) := by decide
    rw [this]
    exact AddSubgroup.add_mem _ h4 (AddSubgroup.sub_mem _ h4 h3)
  -- every element of ZMod 10 is a multiple of 1
  have : x = (x.val : ℕ) • (1 : Tenth) := by
    simp [nsmul_eq_mul, ZMod.natCast_val, ZMod.cast_id]
  rw [this]
  exact AddSubgroup.nsmul_mem _ h1 _

/-- Every phase named by the model lies on the lattice, by construction: they
    are elements of `Tenth`. Stated so the list is checkable rather than
    asserted in prose. -/
theorem native_phases_on_lattice :
    thetaTau ∈ (⊤ : AddSubgroup Tenth) ∧ rTau ∈ (⊤ : AddSubgroup Tenth) ∧
    jonesRoot ∈ (⊤ : AddSubgroup Tenth) ∧ framing ∈ (⊤ : AddSubgroup Tenth) :=
  ⟨trivial, trivial, trivial, trivial⟩

/-- The framing phase has order ten: ten of them close the turn, and no fewer.
    This is the period the `T(2,n)` torus family exhibits. -/
theorem framing_order_ten :
    (10 : ℕ) • framing = 0 ∧ ∀ m : ℕ, 0 < m → m < 10 → (m : ℕ) • framing ≠ 0 := by
  refine ⟨by decide, ?_⟩
  intro m hm h10
  interval_cases m <;> decide

/-! ## The gate is not on the lattice -/

/-- **Incommensurability.** One eighth of a winding is not a multiple of one
    tenth. This is the `T` gate against the model's phases.

    Over `ℚ`: `1/8 = p/10` forces `10 = 8p`, and no integer satisfies it. -/
theorem eighth_not_a_tenth : ¬ ∃ p : ℤ, (1 : ℚ) / 8 = (p : ℚ) / 10 := by
  rintro ⟨p, hp⟩
  have h : (10 : ℚ) = 8 * p := by field_simp at hp; linarith
  have : (10 : ℤ) = 8 * p := by exact_mod_cast h
  omega

/-- The `S` gate, one quarter of a winding, is likewise off the lattice. -/
theorem quarter_not_a_tenth : ¬ ∃ p : ℤ, (1 : ℚ) / 4 = (p : ℚ) / 10 := by
  rintro ⟨p, hp⟩
  have h : (10 : ℚ) = 4 * p := by field_simp at hp; linarith
  have : (10 : ℤ) = 4 * p := by exact_mod_cast h
  omega

/-- `Z`, one half of a winding, IS on the lattice: `1/2 = 5/10`. The three
    together are the point — two of the standard gates are off the model's
    phases and one is on, so the obstruction is specific rather than generic. -/
theorem half_is_a_tenth : ∃ p : ℤ, (1 : ℚ) / 2 = (p : ℚ) / 10 :=
  ⟨5, by norm_num⟩

/-! ## What this does and does not settle -/

/-- The phase lattice contains `Z` and not `T`, so an argument that the model
    cannot reach `T` cannot be made from the lattice alone in a way that would
    also exclude `Z`. The separation is real. -/
theorem gate_separation :
    (∃ p : ℤ, (1 : ℚ) / 2 = (p : ℚ) / 10) ∧
    (¬ ∃ p : ℤ, (1 : ℚ) / 8 = (p : ℚ) / 10) :=
  ⟨half_is_a_tenth, eighth_not_a_tenth⟩

/-! ## Axiom dependencies

    Printed here rather than left to the reader: the boundary between what is
    proved and what is assumed should be visible in the output. -/
#print axioms eigenvalues_generate
#print axioms framing_order_ten
#print axioms eighth_not_a_tenth
#print axioms gate_separation

end Imscribing.Quantum
