import Imscribing.Millennium.Erdos.CollatzDepthSplit
open CollatzDepthSplit
#print axioms CollatzDepthSplit.imbalance_recursion
#print axioms CollatzDepthSplit.cnt_predStep_mod_nine
#print axioms CollatzDepthSplit.cnt_three_eq_sum_nine
