#!/usr/bin/env python3
"""Emit a Lean-checked enclosure for epsilon=1/10, c<=9.

Python proposes rational endpoints. Lean proves every log bound, every
triple bound, and coverage of the entire window. No native_decide is used.
"""
from fractions import Fraction as F
from math import gcd
from pathlib import Path


def bounds(x, m=6):
    z = (x - 1) / (x + 1)
    lo = 2 * sum((z**(2*i+1) / (2*i+1) for i in range(m)), F(0))
    return lo, lo + 2*z**(2*m+1)/(1-z*z)


def down(x):
    return F(x.numerator * 10**6 // x.denominator, 10**6)


def up(x):
    return -down(-x)


def lit(x):
    return f'({x.numerator} / {x.denominator})'


def radical(n):
    r = 1
    for p in range(2, n + 1):
        if n % p == 0:
            r *= p
            while n % p == 0:
                n //= p
    return r


def main():
    pairs = [(a, c-a) for c in range(2, 10) for a in range(1, c) if gcd(a, c-a) == 1]
    numbers = sorted({a+b for a, b in pairs} | {radical(a*b*(a+b)) for a, b in pairs})
    l2, u2 = map(lambda z: z, bounds(F(2)))
    l2, u2 = down(l2), up(u2)
    lines = ['import Imscribing.ABC_LogBounds', '',
             '/-! Generated by scripts/abc_emit_small_certificate.py. All claims are checked by Lean. -/',
             'namespace Imscribing.ABC', '', 'set_option maxRecDepth 4096',
             'set_option maxHeartbeats 2000000', '',
             f'private theorem log_two_certificate : ({lit(l2)} : ℝ) ≤ Real.log 2 ∧ Real.log 2 ≤ {lit(u2)} := by',
             '  have h := log_series_enclosure (x := 2) (by norm_num) 6',
             '  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h',
             '  constructor <;> linarith [h.1, h.2]', '']
    for n in numbers:
        k = n.bit_length() - 1
        x = F(n, 2**k)
        lo, hi = bounds(x)
        lo, hi = down(k*l2+lo), up(k*u2+hi)
        lines.extend([
            f'private noncomputable def logCertificate_{n} : LogEnclosure {n} := by',
            f'  have hx := log_series_enclosure (x := {lit(x)}) (by norm_num) 6',
            f'  have h := log_binary_enclosure (n := {n}) (x := {lit(x)}) {k}',
            '    (by norm_num) (by norm_num) log_two_certificate hx',
            '  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h',
            f'  refine ⟨{lit(lo)}, {lit(hi)}, ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]', ''])
    for a, b in pairs:
        c = a + b
        r = radical(a*b*c)
        lines.extend([
            f'private def sample_{a}_{b} : Triple := ⟨{a}, {b}, {c}, by decide, by decide, by decide, by decide⟩',
            f'private theorem sample_{a}_{b}_interval :',
            f'    (logCertificate_{c}.lower : ℝ) - (1 + (1/10 : ℝ)) * logCertificate_{r}.upper ≤',
            f'      discrepancy (1/10) sample_{a}_{b} ∧',
            f'    discrepancy (1/10) sample_{a}_{b} ≤',
            f'      (logCertificate_{c}.upper : ℝ) - (1 + (1/10 : ℝ)) * logCertificate_{r}.lower := by',
            f'  have hr : radical ({a} * {b} * {c}) = {r} := by',
            '    rw [radical_eq_primeFactors]',
            '    norm_num [Nat.primeFactors, Nat.primeFactorsList]',
            f'  let support : LogEnclosure (radical (sample_{a}_{b}.a * sample_{a}_{b}.b * sample_{a}_{b}.c)) :=',
            f'    ⟨logCertificate_{r}.lower, logCertificate_{r}.upper,',
            f'      by simpa only [sample_{a}_{b}, hr] using logCertificate_{r}.lower_le,',
            f'      by simpa only [sample_{a}_{b}, hr] using logCertificate_{r}.le_upper⟩',
            f'  have h := discrepancy_enclosure (1/10) (by norm_num) sample_{a}_{b} logCertificate_{c} support',
            f'  simpa only [support] using h', '',
            f'private theorem sample_{a}_{b}_upper : discrepancy (1/10) sample_{a}_{b} ≤ 227/1000 := by',
            f'  have h := sample_{a}_{b}_interval.2',
            f'  norm_num [logCertificate_{c}, logCertificate_{r}] at h',
            '  linarith', ''])
    lines.extend([
        'theorem certified_window_nine_upper (t : Triple) (hc : t.c ≤ 9) :',
        '    discrepancy (1/10) t ≤ 227/1000 := by',
        '  rcases t with ⟨a, b, c, ha, hb, hs, hcop⟩',
        '  dsimp only at hc', '  subst c',
        '  have h_a : a < 9 := by omega', '  have h_b : b < 9 := by omega',
        '  have cover : ∀ a b : Fin 9, 0 < a.val → 0 < b.val → a.val + b.val ≤ 9 →',
        '      Nat.Coprime a.val b.val →',
        '      ' + ' ∨ '.join(f'(a.val = {a} ∧ b.val = {b})' for a, b in pairs) + ' := by decide',
        '  have cases_all := cover ⟨a, h_a⟩ ⟨b, h_b⟩ ha hb hc hcop',
        '  rcases cases_all with ' + ' | '.join('h' for _ in pairs)])
    for a, b in pairs:
        lines.extend(['  · rcases h with ⟨h1, h2⟩', '    dsimp only at h1 h2',
                      '    subst a', '    subst b', f'    exact sample_{a}_{b}_upper'])
    r = radical(72)
    lines.extend(['',
        'theorem certified_window_nine_lower : (226/1000 : ℝ) ≤ windowMaximum (1/10) 7 := by',
        '  have h := sample_1_8_interval.1',
        f'  norm_num [logCertificate_9, logCertificate_{r}] at h',
        '  have hw : sample_1_8 ∈ arithmeticWindow 7 :=',
        '    (mem_arithmeticWindow 7 sample_1_8).mpr (by decide)',
        '  exact (by linarith : (226/1000 : ℝ) ≤ discrepancy (1/10) sample_1_8).trans',
        '    (discrepancy_le_windowMaximum _ _ _ hw)', '',
        'noncomputable def certifiedWindowNine : WindowEnclosure (1/10) 7 where',
        '  lower := 226/1000', '  upper := 227/1000',
        '  lower_le := certified_window_nine_lower',
        '  le_upper := windowMaximum_le _ _ _ (fun t ht =>',
        '    certified_window_nine_upper t ((mem_arithmeticWindow 7 t).mp ht))', '',
        'def certifiedWindowNineWitness :',
        '    Imscribing.Paraconsistent.DialetheicWitness.Verdict',
        '      ((226/1000 : ℝ) ≤ windowMaximum (1/10) 7) :=',
        '  .held certified_window_nine_lower certifiedWindowNine.le_upper',
        '',
        'theorem certifiedWindowNineWitness_is_B :',
        '    certifiedWindowNineWitness.classify = (true, true) := rfl', '',
        'end Imscribing.ABC', ''])
    output = Path(__file__).resolve().parents[1] / 'Imscribing' / 'ABC_SmallCertificate.lean'
    output.write_text('\n'.join(lines))
    print(f'Emitted {len(numbers)} log certificates and {len(pairs)} triple certificates to {output}')


if __name__ == '__main__':
    main()
