#!/usr/bin/env python3
"""Generate a complete Lean window enclosure for a rational epsilon.

The generator proposes the finite table and endpoints; Lean checks both.
Only a<=b is tabulated, using the proved summand-exchange symmetry.
"""
import argparse
from fractions import Fraction as F
from math import gcd
from pathlib import Path

from abc_emit_small_certificate import bounds, down, up, lit


def radical(n):
    result = 1
    p = 2
    while p * p <= n:
        if n % p == 0:
            result *= p
            while n % p == 0:
                n //= p
        p += 1
    return result * n


def emit(cutoff, epsilon, terms, endpoint_digits, output):
    pairs = [(a, c-a) for c in range(2, cutoff+1)
             for a in range(1, c//2+1) if gcd(a, c-a) == 1]
    radicals = {(a, b): radical(a*b*(a+b)) for a, b in pairs}
    numbers = sorted({a+b for a, b in pairs} | set(radicals.values()))
    l2, u2 = bounds(F(2), terms)
    l2, u2 = down(l2), up(u2)
    enclosures = {}
    for n in numbers:
        k = n.bit_length() - 1
        lo, hi = bounds(F(n, 2**k), terms)
        enclosures[n] = down(k*l2 + lo), up(k*u2 + hi)
    lower_candidates = {(a, b): enclosures[a+b][0] - (1+epsilon)*enclosures[radicals[a,b]][1]
                        for a, b in pairs}
    upper_candidates = {(a, b): enclosures[a+b][1] - (1+epsilon)*enclosures[radicals[a,b]][0]
                        for a, b in pairs}
    witness = max(lower_candidates, key=lower_candidates.get)
    unit = 10**endpoint_digits
    lower = F(lower_candidates[witness].numerator * unit // lower_candidates[witness].denominator, unit)
    top = max(upper_candidates.values())
    upper = F(-((-top.numerator * unit) // top.denominator), unit)
    eps = lit(epsilon)
    namespace = f'Window{cutoff}E{epsilon.numerator}_{epsilon.denominator}'
    lines = ['import Imscribing.ABC_Symmetry', '',
             '/-! Generated by scripts/abc_emit_window_certificate.py; all claims checked by Lean. -/',
             f'namespace Imscribing.ABC.{namespace}', '',
             'set_option maxRecDepth 8192', 'set_option maxHeartbeats 4000000',
             'set_option synthInstance.maxSize 16384', '',
             f'private theorem log_two_certificate : ({lit(l2)} : ℝ) ≤ Real.log 2 ∧ Real.log 2 ≤ {lit(u2)} := by',
             f'  have h := log_series_enclosure (x := 2) (by norm_num) {terms}',
             '  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h',
             '  constructor <;> linarith [h.1, h.2]', '']
    for n in numbers:
        k = n.bit_length() - 1
        x = F(n, 2**k)
        lo, hi = enclosures[n]
        lines.extend([
            f'private noncomputable def logCertificate_{n} : LogEnclosure {n} := by',
            f'  have hx := log_series_enclosure (x := {lit(x)}) (by norm_num) {terms}',
            f'  have h := log_binary_enclosure (n := {n}) (x := {lit(x)}) {k}',
            '    (by norm_num) (by norm_num) log_two_certificate hx',
            '  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h',
            f'  refine ⟨{lit(lo)}, {lit(hi)}, ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]', ''])
    for a, b in pairs:
        c, r = a+b, radicals[a,b]
        lines.extend([
            f'private def sample_{a}_{b} : Triple := ⟨{a}, {b}, {c}, by decide, by decide, by decide, by decide⟩',
            f'private theorem sample_{a}_{b}_interval :',
            f'    (logCertificate_{c}.lower : ℝ) - (1 + ({eps} : ℝ)) * logCertificate_{r}.upper ≤',
            f'      discrepancy {eps} sample_{a}_{b} ∧',
            f'    discrepancy {eps} sample_{a}_{b} ≤',
            f'      (logCertificate_{c}.upper : ℝ) - (1 + ({eps} : ℝ)) * logCertificate_{r}.lower := by',
            f'  have hr : radical ({a} * {b} * {c}) = {r} := by',
            '    rw [radical_eq_primeFactors]',
            '    norm_num [Nat.primeFactors, Nat.primeFactorsList]',
            f'  let support : LogEnclosure (radical (sample_{a}_{b}.a * sample_{a}_{b}.b * sample_{a}_{b}.c)) :=',
            f'    ⟨logCertificate_{r}.lower, logCertificate_{r}.upper,',
            f'      by simpa only [sample_{a}_{b}, hr] using logCertificate_{r}.lower_le,',
            f'      by simpa only [sample_{a}_{b}, hr] using logCertificate_{r}.le_upper⟩',
            f'  have h := discrepancy_enclosure {eps} (by norm_num) sample_{a}_{b} logCertificate_{c} support',
            '  simpa only [support] using h', '',
            f'private theorem sample_{a}_{b}_upper : discrepancy {eps} sample_{a}_{b} ≤ {lit(upper)} := by',
            f'  have h := sample_{a}_{b}_interval.2',
            f'  norm_num [logCertificate_{c}, logCertificate_{r}] at h',
            '  linarith', ''])
    lines.extend([
        f'theorem certified_upper (t : Triple) (hc : t.c ≤ {cutoff}) :',
        f'    discrepancy {eps} t ≤ {lit(upper)} := by',
        f'  apply window_upper_of_ordered {eps} {lit(upper)} {cutoff} ?_ t hc',
        '  intro t hc hab', '  rcases t with ⟨a, b, c, ha, hb, hs, hcop⟩',
        '  dsimp only at hc hab', '  subst c',
        f'  have h_a : a < {cutoff} := by omega', f'  have h_b : b < {cutoff} := by omega',
        f'  have cover : ∀ a b : Fin {cutoff}, 0 < a.val → 0 < b.val → a.val ≤ b.val →',
        f'      a.val + b.val ≤ {cutoff} → Nat.Coprime a.val b.val →',
        '      ' + ' ∨ '.join(f'(a.val = {a} ∧ b.val = {b})' for a, b in pairs) + ' := by decide',
        '  have cases_all := cover ⟨a, h_a⟩ ⟨b, h_b⟩ ha hb hab hc hcop'])
    if len(pairs) == 1:
        a, b = pairs[0]
        lines.extend(['  rcases cases_all with ⟨h1, h2⟩', '  dsimp only at h1 h2',
                      '  subst a', '  subst b', f'  exact sample_{a}_{b}_upper'])
    else:
        lines.append('  rcases cases_all with ' + ' | '.join('h' for _ in pairs))
        for a, b in pairs:
            lines.extend(['  · rcases h with ⟨h1, h2⟩', '    dsimp only at h1 h2',
                          '    subst a', '    subst b', f'    exact sample_{a}_{b}_upper'])
    a, b = witness
    r = radicals[witness]
    lines.extend(['',
        f'theorem certified_lower : ({lit(lower)} : ℝ) ≤ windowMaximum {eps} {cutoff-2} := by',
        f'  have h := sample_{a}_{b}_interval.1',
        f'  norm_num [logCertificate_{a+b}, logCertificate_{r}] at h',
        f'  have hw : sample_{a}_{b} ∈ arithmeticWindow {cutoff-2} :=',
        f'    (mem_arithmeticWindow {cutoff-2} sample_{a}_{b}).mpr (by decide)',
        f'  exact (by linarith : ({lit(lower)} : ℝ) ≤ discrepancy {eps} sample_{a}_{b}).trans',
        '    (discrepancy_le_windowMaximum _ _ _ hw)', '',
        f'noncomputable def enclosure : WindowEnclosure {eps} {cutoff-2} where',
        f'  lower := {lit(lower)}', f'  upper := {lit(upper)}',
        '  lower_le := certified_lower',
        '  le_upper := windowMaximum_le _ _ _ (fun t ht =>',
        f'    certified_upper t ((mem_arithmeticWindow {cutoff-2} t).mp ht))', '',
        f'end Imscribing.ABC.{namespace}', ''])
    output.write_text('\n'.join(lines))
    return {'cutoff': cutoff, 'epsilon': str(epsilon), 'log_certificates': len(numbers),
            'pair_representatives': len(pairs), 'lower': str(lower), 'upper': str(upper),
            'witness': [a, b, a+b], 'namespace': namespace, 'output': str(output)}


def main():
    import json
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--cutoff', type=int, default=32)
    parser.add_argument('--epsilon', type=F, default=F(1, 10))
    parser.add_argument('--terms', type=int, default=6)
    parser.add_argument('--endpoint-digits', type=int, default=3)
    parser.add_argument('--output', type=Path)
    args = parser.parse_args()
    if args.cutoff < 2 or args.epsilon <= 0 or args.terms < 1 or not 0 <= args.endpoint_digits <= 6:
        parser.error('cutoff >= 2, epsilon > 0, terms >= 1, and 0 <= endpoint-digits <= 6 required')
    output = args.output or Path(__file__).resolve().parents[1] / 'Imscribing' / (
        f'ABC_Window{args.cutoff}_E{args.epsilon.numerator}_{args.epsilon.denominator}.lean')
    print(json.dumps(emit(args.cutoff, args.epsilon, args.terms, args.endpoint_digits, output), indent=2))


if __name__ == '__main__':
    main()
