#!/usr/bin/env python3
"""Generate a complete Lean window enclosure for a rational epsilon.

The generator proposes the finite table and endpoints; Lean checks both.
Only a<=b is tabulated, using the proved summand-exchange symmetry.
"""
import argparse
from fractions import Fraction as F
from math import gcd
from pathlib import Path

from abc_emit_small_certificate import bounds, down, up, lit


def radical(n):
    result = 1
    p = 2
    while p * p <= n:
        if n % p == 0:
            result *= p
            while n % p == 0:
                n //= p
        p += 1
    return result * n


def emit(cutoff, epsilon, terms, endpoint_digits, output):
    pairs = [(a, c-a) for c in range(2, cutoff+1)
             for a in range(1, c//2+1) if gcd(a, c-a) == 1]
    radicals = {(a, b): radical(a*b*(a+b)) for a, b in pairs}
    numbers = sorted({a+b for a, b in pairs} | set(radicals.values()))
    l2, u2 = bounds(F(2), terms)
    l2, u2 = down(l2), up(u2)
    enclosures = {}
    for n in numbers:
        k = n.bit_length() - 1
        lo, hi = bounds(F(n, 2**k), terms)
        enclosures[n] = down(k*l2 + lo), up(k*u2 + hi)
    lower_candidates = {(a, b): enclosures[a+b][0] - (1+epsilon)*enclosures[radicals[a,b]][1]
                        for a, b in pairs}
    upper_candidates = {(a, b): enclosures[a+b][1] - (1+epsilon)*enclosures[radicals[a,b]][0]
                        for a, b in pairs}
    witness = max(lower_candidates, key=lower_candidates.get)
    unit = 10**endpoint_digits
    lower = F(lower_candidates[witness].numerator * unit // lower_candidates[witness].denominator, unit)
    top = max(upper_candidates.values())
    upper = F(-((-top.numerator * unit) // top.denominator), unit)
    eps = lit(epsilon)
    namespace = f'Window{cutoff}E{epsilon.numerator}_{epsilon.denominator}'

    # A single monolithic file holding 498 log certificates and 1494 sample
    # theorems (at cutoff=70) puts every one of those declarations' live
    # elaboration state (tactic metavariable contexts, norm_num/linarith proof
    # search state) in one Lean process at once, and that process OOMs well
    # before it reaches `certified_upper` -- confirmed by shrinking only the
    # covering-disjunction proof there and observing no change in peak memory.
    # A compiled .olean holds just the finished terms, not that live state, so
    # splitting the certificates and the samples into their own files, each
    # its own Lake target that the next one IMPORTS rather than textually
    # includes, bounds the live memory of every individual compile.
    module_prefix = output.parent.name
    stem = output.stem
    blocks, current, current_c = [], [], None
    for a, b in pairs:
        c = a + b
        if current and len(current) >= cutoff and c != current_c:
            blocks.append(current)
            current = []
        current.append((a, b))
        current_c = c
    if current:
        blocks.append(current)
    block_ranges = [(blk[0][0] + blk[0][1], blk[-1][0] + blk[-1][1]) for blk in blocks]

    def preamble(imports):
        return [*[f'import {m}' for m in imports], '',
                '/-! Generated by scripts/abc_emit_window_certificate.py; all claims checked by Lean. -/',
                f'namespace Imscribing.ABC.{namespace}', '',
                'set_option maxRecDepth 8192', 'set_option maxHeartbeats 4000000',
                'set_option synthInstance.maxSize 16384',
                'set_option synthInstance.maxHeartbeats 4000000', '']

    def write(path, lines):
        lines = lines + ['', f'end Imscribing.ABC.{namespace}', '']
        path.write_text('\n'.join(lines))

    # Files 1..C: the log-series certificate and the per-number log
    # certificates, chunked the same way as the samples below -- a single
    # file holding all 498 of these (each its own norm_num/ring/field_simp
    # search over Finset.sum_range_succ) was the actual memory sink, not the
    # covering-disjunction proof further down; splitting the samples alone
    # left this bottleneck untouched.
    number_chunks, current, = [], []
    for n in numbers:
        if len(current) >= cutoff:
            number_chunks.append(current)
            current = []
        current.append(n)
    if current:
        number_chunks.append(current)

    cert_modules = []
    prior_module = 'Imscribing.ABC_Symmetry'
    for i, chunk in enumerate(number_chunks, start=1):
        cert_lines = preamble([prior_module])
        if i == 1:
            cert_lines += [
                f'theorem log_two_certificate : ({lit(l2)} : ℝ) ≤ Real.log 2 ∧ Real.log 2 ≤ {lit(u2)} := by',
                f'  have h := log_series_enclosure (x := 2) (by norm_num) {terms}',
                '  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h',
                '  constructor <;> linarith [h.1, h.2]', '']
        for n in chunk:
            k = n.bit_length() - 1
            x = F(n, 2**k)
            lo, hi = enclosures[n]
            cert_lines.extend([
                f'noncomputable def logCertificate_{n} : LogEnclosure {n} := by',
                f'  have hx := log_series_enclosure (x := {lit(x)}) (by norm_num) {terms}',
                f'  have h := log_binary_enclosure (n := {n}) (x := {lit(x)}) {k}',
                '    (by norm_num) (by norm_num) log_two_certificate hx',
                '  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h',
                f'  refine ⟨{lit(lo)}, {lit(hi)}, ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]', ''])
        cert_module = f'{module_prefix}.{stem}_Certs{i}'
        write(output.parent / f'{stem}_Certs{i}.lean', cert_lines)
        cert_modules.append(cert_module)
        prior_module = cert_module

    # Files C+1..C+K: one file per pair-block, each importing the previous
    # module (chained), holding just that block's sample definitions and
    # interval/upper theorems.
    sample_modules = []
    prior_module = cert_modules[-1]
    for i, blk in enumerate(blocks, start=1):
        chunk_lines = preamble([prior_module])
        for a, b in blk:
            c, r = a+b, radicals[a,b]
            chunk_lines.extend([
                f'def sample_{a}_{b} : Triple := ⟨{a}, {b}, {c}, by decide, by decide, by decide, by decide⟩',
                f'theorem sample_{a}_{b}_interval :',
                f'    (logCertificate_{c}.lower : ℝ) - (1 + ({eps} : ℝ)) * logCertificate_{r}.upper ≤',
                f'      discrepancy {eps} sample_{a}_{b} ∧',
                f'    discrepancy {eps} sample_{a}_{b} ≤',
                f'      (logCertificate_{c}.upper : ℝ) - (1 + ({eps} : ℝ)) * logCertificate_{r}.lower := by',
                f'  have hr : radical ({a} * {b} * {c}) = {r} := by',
                '    rw [radical_eq_primeFactors]',
                '    norm_num [Nat.primeFactors, Nat.primeFactorsList]',
                f'  let support : LogEnclosure (radical (sample_{a}_{b}.a * sample_{a}_{b}.b * sample_{a}_{b}.c)) :=',
                f'    ⟨logCertificate_{r}.lower, logCertificate_{r}.upper,',
                f'      by simpa only [sample_{a}_{b}, hr] using logCertificate_{r}.lower_le,',
                f'      by simpa only [sample_{a}_{b}, hr] using logCertificate_{r}.le_upper⟩',
                f'  have h := discrepancy_enclosure {eps} (by norm_num) sample_{a}_{b} logCertificate_{c} support',
                '  simpa only [support] using h', '',
                f'theorem sample_{a}_{b}_upper : discrepancy {eps} sample_{a}_{b} ≤ {lit(upper)} := by',
                f'  have h := sample_{a}_{b}_interval.2',
                f'  norm_num [logCertificate_{c}, logCertificate_{r}] at h',
                '  linarith', ''])
        chunk_module = f'{module_prefix}.{stem}_Samples{i}'
        write(output.parent / f'{stem}_Samples{i}.lean', chunk_lines)
        sample_modules.append(chunk_module)
        prior_module = chunk_module

    def destructure(blk, indent):
        out = []
        if len(blk) == 1:
            a, b = blk[0]
            out.extend([f'{indent}rcases hcov with ⟨h1, h2⟩', f'{indent}dsimp only at h1 h2',
                        f'{indent}subst a', f'{indent}subst b', f'{indent}exact sample_{a}_{b}_upper'])
        else:
            out.append(f'{indent}rcases hcov with ' + ' | '.join('h' for _ in blk))
            for a, b in blk:
                out.extend([f'{indent}· rcases h with ⟨h1, h2⟩', f'{indent}  dsimp only at h1 h2',
                            f'{indent}  subst a', f'{indent}  subst b',
                            f'{indent}  exact sample_{a}_{b}_upper'])
        return out

    # Final file: only the covering dispatch and the two headline theorems,
    # importing the last (and, by the import chain, every) sample file.
    final_lines = preamble([sample_modules[-1]])
    final_lines.extend([
        f'theorem certified_upper (t : Triple) (hc : t.c ≤ {cutoff}) :',
        f'    discrepancy {eps} t ≤ {lit(upper)} := by',
        f'  apply window_upper_of_ordered {eps} {lit(upper)} {cutoff} ?_ t hc',
        '  intro t hc hab', '  rcases t with ⟨a, b, c, ha, hb, hs, hcop⟩',
        '  dsimp only at hc hab', '  subst c',
        f'  have h_a : a < {cutoff} := by omega', f'  have h_b : b < {cutoff} := by omega'])
    for i, (blk, (lo, hi)) in enumerate(zip(blocks, block_ranges), start=1):
        final_lines.extend([
            f'  have cover_block_{i} : ∀ a b : Fin {cutoff}, 0 < a.val → 0 < b.val → a.val ≤ b.val →',
            f'      {lo} ≤ a.val + b.val → a.val + b.val ≤ {hi} → Nat.Coprime a.val b.val →',
            '      ' + ' ∨ '.join(f'(a.val = {a} ∧ b.val = {b})' for a, b in blk) + ' := by decide'])
    # omega does not unfold `(⟨a, h_a⟩ : Fin cutoff).val` back to `a`, so the
    # lower-bound witness for block 1 must be a named `have` stated over the
    # plain ℕ variables; the elaborator then accepts it by defeq at the call,
    # same as it already does for ha/hb/hab/hc/hcop below.
    final_lines.append(f'  have hlo1 : {block_ranges[0][0]} ≤ a + b := by omega')
    if len(blocks) == 1:
        final_lines.append('  have hcov := cover_block_1 ⟨a, h_a⟩ ⟨b, h_b⟩ ha hb hab hlo1 hc hcop')
        final_lines.extend(destructure(blocks[0], '  '))
    else:
        dispatch = [f'a + b ≤ {block_ranges[0][1]}']
        for lo, hi in block_ranges[1:]:
            dispatch.append(f'({lo} ≤ a + b ∧ a + b ≤ {hi})')
        final_lines.append('  rcases (show ' + ' ∨ '.join(dispatch) + ' from by omega) with '
                            + ' | '.join('hblk' for _ in blocks))
        for i, blk in enumerate(blocks, start=1):
            if i == 1:
                final_lines.append('  · have hcov := cover_block_1 ⟨a, h_a⟩ ⟨b, h_b⟩ ha hb hab hlo1 hblk hcop')
            else:
                final_lines.append(f'  · have hcov := cover_block_{i} ⟨a, h_a⟩ ⟨b, h_b⟩ ha hb hab hblk.1 hblk.2 hcop')
            final_lines.extend(destructure(blk, '    '))
    a, b = witness
    r = radicals[witness]
    final_lines.extend(['',
        f'theorem certified_lower : ({lit(lower)} : ℝ) ≤ windowMaximum {eps} {cutoff-2} := by',
        f'  have h := sample_{a}_{b}_interval.1',
        f'  norm_num [logCertificate_{a+b}, logCertificate_{r}] at h',
        f'  have hw : sample_{a}_{b} ∈ arithmeticWindow {cutoff-2} :=',
        f'    (mem_arithmeticWindow {cutoff-2} sample_{a}_{b}).mpr (by decide)',
        f'  exact (by linarith : ({lit(lower)} : ℝ) ≤ discrepancy {eps} sample_{a}_{b}).trans',
        '    (discrepancy_le_windowMaximum _ _ _ hw)', '',
        f'noncomputable def enclosure : WindowEnclosure {eps} {cutoff-2} where',
        f'  lower := {lit(lower)}', f'  upper := {lit(upper)}',
        '  lower_le := certified_lower',
        '  le_upper := windowMaximum_le _ _ _ (fun t ht =>',
        f'    certified_upper t ((mem_arithmeticWindow {cutoff-2} t).mp ht))', '',
        f'def witness : Imscribing.Paraconsistent.DialetheicWitness.Verdict',
        f'    (({lit(lower)} : ℝ) ≤ windowMaximum {eps} {cutoff-2}) :=',
        f'  .held certified_lower (enclosure.le_upper)',
        '',
        'theorem witness_is_B : witness.classify = (true, true) := rfl'])
    write(output, final_lines)
    return {'cutoff': cutoff, 'epsilon': str(epsilon), 'log_certificates': len(numbers),
            'pair_representatives': len(pairs), 'sample_files': len(blocks),
            'lower': str(lower), 'upper': str(upper),
            'witness': [a, b, a+b], 'namespace': namespace, 'output': str(output)}


def main():
    import json
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--cutoff', type=int, default=32)
    parser.add_argument('--epsilon', type=F, default=F(1, 10))
    parser.add_argument('--terms', type=int, default=6)
    parser.add_argument('--endpoint-digits', type=int, default=3)
    parser.add_argument('--output', type=Path)
    args = parser.parse_args()
    if args.cutoff < 2 or args.epsilon <= 0 or args.terms < 1 or not 0 <= args.endpoint_digits <= 6:
        parser.error('cutoff >= 2, epsilon > 0, terms >= 1, and 0 <= endpoint-digits <= 6 required')
    output = args.output or Path(__file__).resolve().parents[1] / 'Imscribing' / (
        f'ABC_Window{args.cutoff}_E{args.epsilon.numerator}_{args.epsilon.denominator}.lean')
    print(json.dumps(emit(args.cutoff, args.epsilon, args.terms, args.endpoint_digits, output), indent=2))


if __name__ == '__main__':
    main()
