#!/usr/bin/env python3
"""Emit Imscribing/Millennium/OVMCatalog.lean — the coordinates the OVM
taxonomy is computed over, decoded from the catalog rather than typed.

Three sources, none of them this file:

  IG_catalog.json                  the seven question tuples and the seven
                                   theorem tuples, by catalog name
  ig-docs/OVMs/_new_theorems.tsv   the 25-entry theorem sample of the paper
  ig-docs/OVMs/_thm117.txt         the wider settled sample

The glyph -> constructor map is read out of Imscription.lean's `.shavian`
definitions, so a rename in Lean cannot drift from a rename here.

Usage:  python3 scripts/gen_ovm_catalog.py
"""

import io
import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
P4RAMILL = os.path.dirname(HERE)
PRIMITIVES = os.path.join(P4RAMILL, "Imscribing", "Primitives")
CATALOG = os.path.expanduser("~/imsgct/imscribing_grammar/IG_catalog.json")
OVMS = os.path.expanduser("~/imsgct/ig-docs/OVMs")
OUT = os.path.join(P4RAMILL, "Imscribing", "Millennium", "OVMCatalog.lean")

MARKS = ["⊢", "⊣", "≻", "≺", "⋈", "⊤", "∈", "∋", "⊙", "⊥", "⊞", "◻"]

# Lean field name per mark, in the order the twelve are written.
FIELDS = ["dim", "top", "rel", "pol", "fid", "kin",
          "gran", "gram", "crit", "chir", "stoi", "prot"]
AXES = ["Dimensionality", "Topology", "Relational", "Polarity", "Fidelity",
        "KineticChar", "Granularity", "Grammar", "Criticality", "Chirality",
        "Stoichiometry", "Protection"]

# The seven, question and theorem, by catalog name.
SEVEN = [
    ("riemann", "riemann_hypothesis", "riemann_theorem"),
    ("bsd", "birch_swinnerton_dyer", "birch_and_swinnerton_dyer_theorem_"),
    ("yangMills", "yang_mills_mass_gap",
     "yang–mills_existence_and_mass_gap_theorem_"),
    ("navierStokes", "navier_stokes", "navier_stokes_theorem"),
    ("pVsNP", "p_vs_np", "p_versus_np_theorem"),
    ("hodge", "hodge_conjecture", "hodge_lefschetz_11_theorem"),
    ("collatz", "collatz_conjecture", "collatz_theorem_proven"),
]


def read(path):
    return io.open(path, encoding="utf-8").read()


def glyph_maps():
    """axis name -> {glyph: constructor}, straight out of Imscription.lean."""
    src = read(os.path.join(PRIMITIVES, "Imscription.lean"))
    out = {}
    for m in re.finditer(r"def (\w+)\.shavian : \1 → String\n((?:\s*\|.*\n)+)", src):
        axis = m.group(1)
        table = {}
        for line in m.group(2).splitlines():
            mm = re.match(r"\s*\|\s*\.([A-Za-z_][A-Za-z0-9_']*)\s*=>\s*\"(.+?)\"", line)
            if mm:
                table[mm.group(2)] = mm.group(1)
        out[axis] = table
    missing = [a for a in AXES if a not in out]
    if missing:
        raise SystemExit(f"no shavian map for {missing}")
    return out


def decode(word, maps):
    """A twelve-glyph word -> the Lean structure literal."""
    glyphs = list(word)
    if len(glyphs) != 12:
        raise ValueError(f"{word!r} is {len(glyphs)} glyphs, not 12")
    parts = []
    for field, axis, g in zip(FIELDS, AXES, glyphs):
        ctor = maps[axis].get(g)
        if ctor is None:
            raise ValueError(f"{g!r} is not a {axis} value (word {word})")
        parts.append(f"{field} := .{ctor}")
    return "{ " + ", ".join(parts) + " }"


def lean_name(raw):
    s = re.sub(r"[^0-9a-zA-Z]+", "_", raw).strip("_")
    if s and s[0].isdigit():
        s = "e_" + s
    return s


def sample(path):
    rows = []
    for line in io.open(path, encoding="utf-8"):
        line = line.rstrip("\n")
        if not line.strip():
            continue
        parts = line.split("\t") if "\t" in line else line.split()
        if len(parts) < 2:
            continue
        rows.append((parts[0], parts[1]))
    return rows


def main():
    maps = glyph_maps()
    catalog = {e["name"]: e for e in json.load(io.open(CATALOG, encoding="utf-8"))}

    def word_of(name):
        e = catalog.get(name)
        if e is None:
            raise SystemExit(f"{name} is not in the catalog")
        return "".join(e[m] for m in MARKS)

    L = []
    add = L.append
    add("import Imscribing.Primitives.Imscription")
    add("")
    add("/-!")
    add("# OVMCatalog — the coordinates the OVM taxonomy is computed over")
    add("")
    add("GENERATED by `scripts/gen_ovm_catalog.py`. Do not edit by hand.")
    add("")
    add("The seven questions and the seven theorems are catalog entries, named.")
    add("The two samples are the lists the census in")
    add("`ig-docs/millennium_theorems_as_ovms.tex` was taken over, recorded in")
    add("`ig-docs/OVMs/_new_theorems.tsv` and `ig-docs/OVMs/_thm117.txt`.")
    add("")
    add("Each definition carries its catalog word in the docstring, and")
    add("`OVMTaxonomy.lean` checks the word back out of the structure by `rfl`.")
    add("-/")
    add("")
    add("namespace Imscribing.Millennium.OVMCatalog")
    add("open Imscribing.Primitives")
    add("")
    add("/- The seven, as the question the catalog holds and the theorem it holds. -/")
    add("")

    for stem, qname, tname in SEVEN:
        for kind, cname in (("Question", qname), ("Theorem", tname)):
            w = word_of(cname)
            add(f"/-- Catalog `{cname}` = ⟨{w}⟩. -/")
            add(f"def {stem}{kind} : Imscription := {decode(w, maps)}")
            add("")

    add("/-- The catalog word of each of the seven, question then theorem, as the")
    add("    catalog spells it. `OVMTaxonomy.seven_words_roundtrip` renders the")
    add("    structures above back to these. -/")
    add("def sevenCatalogWords : List (String × String × String) :=")
    wrows = ",\n".join(
        f'  ("{stem}", "{word_of(q)}", "{word_of(t)}")' for stem, q, t in SEVEN)
    add("[\n" + wrows + "\n]")
    add("")
    add("/-- The seven, question beside theorem, in the order the paper takes them. -/")
    add("def seven : List (String × Imscription × Imscription) :=")
    rows = ",\n".join(
        f'  ("{stem}", {stem}Question, {stem}Theorem)' for stem, _, _ in SEVEN)
    add("[\n" + rows + "\n]")
    add("")

    for lname, path, title in (
        ("newTheorems", os.path.join(OVMS, "_new_theorems.tsv"),
         "the 25-entry theorem sample"),
        ("settled", os.path.join(OVMS, "_thm117.txt"),
         "the wider settled sample"),
    ):
        rows = sample(path)
        add(f"/-- {title}: {len(rows)} entries, from `{os.path.basename(path)}`. -/")
        add(f"def {lname} : List (String × Imscription) :=")
        body = ",\n".join(
            f'  ("{lean_name(n)}", {decode(w, maps)})' for n, w in rows)
        add("[\n" + body + "\n]")
        add("")

    add("end Imscribing.Millennium.OVMCatalog")

    io.open(OUT, "w", encoding="utf-8").write("\n".join(L) + "\n")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
