import Imscribing.ABC_Window70_FromOS_Certs2

/-! Generated by scripts/abc_emit_window_certificate.py; all claims checked by Lean. -/
namespace Imscribing.ABC.Window70E1_10

set_option maxRecDepth 8192
set_option maxHeartbeats 4000000
set_option synthInstance.maxSize 16384
set_option synthInstance.maxHeartbeats 4000000

noncomputable def logCertificate_1482 : LogEnclosure 1482 := by
  have hx := log_series_enclosure (x := (741 / 512)) (by norm_num) 6
  have h := log_binary_enclosure (n := 1482) (x := (741 / 512)) 10
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(3650573 / 500000), (7301167 / 1000000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_1518 : LogEnclosure 1518 := by
  have hx := log_series_enclosure (x := (759 / 512)) (by norm_num) 6
  have h := log_binary_enclosure (n := 1518) (x := (759 / 512)) 10
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(7325147 / 1000000), (457823 / 62500), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_1554 : LogEnclosure 1554 := by
  have hx := log_series_enclosure (x := (777 / 512)) (by norm_num) 6
  have h := log_binary_enclosure (n := 1554) (x := (777 / 512)) 10
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(1469717 / 200000), (3674303 / 500000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_1590 : LogEnclosure 1590 := by
  have hx := log_series_enclosure (x := (795 / 512)) (by norm_num) 6
  have h := log_binary_enclosure (n := 1590) (x := (795 / 512)) 10
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(7371487 / 1000000), (1842877 / 250000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_1598 : LogEnclosure 1598 := by
  have hx := log_series_enclosure (x := (799 / 512)) (by norm_num) 6
  have h := log_binary_enclosure (n := 1598) (x := (799 / 512)) 10
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(3688253 / 500000), (7376527 / 1000000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_1610 : LogEnclosure 1610 := by
  have hx := log_series_enclosure (x := (805 / 512)) (by norm_num) 6
  have h := log_binary_enclosure (n := 1610) (x := (805 / 512)) 10
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(7383987 / 1000000), (923001 / 125000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_1722 : LogEnclosure 1722 := by
  have hx := log_series_enclosure (x := (861 / 512)) (by norm_num) 6
  have h := log_binary_enclosure (n := 1722) (x := (861 / 512)) 10
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(7451239 / 1000000), (372563 / 50000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_1770 : LogEnclosure 1770 := by
  have hx := log_series_enclosure (x := (885 / 512)) (by norm_num) 6
  have h := log_binary_enclosure (n := 1770) (x := (885 / 512)) 10
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(7478733 / 1000000), (3739377 / 500000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_1794 : LogEnclosure 1794 := by
  have hx := log_series_enclosure (x := (897 / 512)) (by norm_num) 6
  have h := log_binary_enclosure (n := 1794) (x := (897 / 512)) 10
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(7492201 / 1000000), (3746111 / 500000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_1798 : LogEnclosure 1798 := by
  have hx := log_series_enclosure (x := (899 / 512)) (by norm_num) 6
  have h := log_binary_enclosure (n := 1798) (x := (899 / 512)) 10
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(1873607 / 250000), (7494449 / 1000000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_1806 : LogEnclosure 1806 := by
  have hx := log_series_enclosure (x := (903 / 512)) (by norm_num) 6
  have h := log_binary_enclosure (n := 1806) (x := (903 / 512)) 10
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(7498867 / 1000000), (7498889 / 1000000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_1830 : LogEnclosure 1830 := by
  have hx := log_series_enclosure (x := (915 / 512)) (by norm_num) 6
  have h := log_binary_enclosure (n := 1830) (x := (915 / 512)) 10
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(7512069 / 1000000), (751209 / 100000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_1870 : LogEnclosure 1870 := by
  have hx := log_series_enclosure (x := (935 / 512)) (by norm_num) 6
  have h := log_binary_enclosure (n := 1870) (x := (935 / 512)) 10
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(7533691 / 1000000), (7533713 / 1000000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_1886 : LogEnclosure 1886 := by
  have hx := log_series_enclosure (x := (943 / 512)) (by norm_num) 6
  have h := log_binary_enclosure (n := 1886) (x := (943 / 512)) 10
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(7542211 / 1000000), (942779 / 125000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_1914 : LogEnclosure 1914 := by
  have hx := log_series_enclosure (x := (957 / 512)) (by norm_num) 6
  have h := log_binary_enclosure (n := 1914) (x := (957 / 512)) 10
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(1889237 / 250000), (755697 / 100000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_1938 : LogEnclosure 1938 := by
  have hx := log_series_enclosure (x := (969 / 512)) (by norm_num) 6
  have h := log_binary_enclosure (n := 1938) (x := (969 / 512)) 10
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(7569409 / 1000000), (7569431 / 1000000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_1974 : LogEnclosure 1974 := by
  have hx := log_series_enclosure (x := (987 / 512)) (by norm_num) 6
  have h := log_binary_enclosure (n := 1974) (x := (987 / 512)) 10
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(1517563 / 200000), (7587837 / 1000000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_2010 : LogEnclosure 2010 := by
  have hx := log_series_enclosure (x := (1005 / 512)) (by norm_num) 6
  have h := log_binary_enclosure (n := 2010) (x := (1005 / 512)) 10
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(118842 / 15625), (760591 / 100000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_2030 : LogEnclosure 2030 := by
  have hx := log_series_enclosure (x := (1015 / 512)) (by norm_num) 6
  have h := log_binary_enclosure (n := 2030) (x := (1015 / 512)) 10
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(7615789 / 1000000), (7615811 / 1000000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_2046 : LogEnclosure 2046 := by
  have hx := log_series_enclosure (x := (1023 / 512)) (by norm_num) 6
  have h := log_binary_enclosure (n := 2046) (x := (1023 / 512)) 10
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(190591 / 25000), (3811831 / 500000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_2090 : LogEnclosure 2090 := by
  have hx := log_series_enclosure (x := (1045 / 1024)) (by norm_num) 6
  have h := log_binary_enclosure (n := 2090) (x := (1045 / 1024)) 11
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(7644917 / 1000000), (382247 / 50000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_2146 : LogEnclosure 2146 := by
  have hx := log_series_enclosure (x := (1073 / 1024)) (by norm_num) 6
  have h := log_binary_enclosure (n := 2146) (x := (1073 / 1024)) 11
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(3835679 / 500000), (7671381 / 1000000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_2162 : LogEnclosure 2162 := by
  have hx := log_series_enclosure (x := (1081 / 1024)) (by norm_num) 6
  have h := log_binary_enclosure (n := 2162) (x := (1081 / 1024)) 11
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(7678787 / 1000000), (767881 / 100000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_2170 : LogEnclosure 2170 := by
  have hx := log_series_enclosure (x := (1085 / 1024)) (by norm_num) 6
  have h := log_binary_enclosure (n := 2170) (x := (1085 / 1024)) 11
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(96031 / 12500), (7682503 / 1000000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_2226 : LogEnclosure 2226 := by
  have hx := log_series_enclosure (x := (1113 / 1024)) (by norm_num) 6
  have h := log_binary_enclosure (n := 2226) (x := (1113 / 1024)) 11
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(7707959 / 1000000), (3853991 / 500000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_2262 : LogEnclosure 2262 := by
  have hx := log_series_enclosure (x := (1131 / 1024)) (by norm_num) 6
  have h := log_binary_enclosure (n := 2262) (x := (1131 / 1024)) 11
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(3862001 / 500000), (308961 / 40000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_2278 : LogEnclosure 2278 := by
  have hx := log_series_enclosure (x := (1139 / 1024)) (by norm_num) 6
  have h := log_binary_enclosure (n := 2278) (x := (1139 / 1024)) 11
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(7731051 / 1000000), (3865537 / 500000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_2310 : LogEnclosure 2310 := by
  have hx := log_series_enclosure (x := (1155 / 1024)) (by norm_num) 6
  have h := log_binary_enclosure (n := 2310) (x := (1155 / 1024)) 11
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(1549 / 200), (7745023 / 1000000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_2346 : LogEnclosure 2346 := by
  have hx := log_series_enclosure (x := (1173 / 1024)) (by norm_num) 6
  have h := log_binary_enclosure (n := 2346) (x := (1173 / 1024)) 11
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(1552093 / 200000), (970061 / 125000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_2418 : LogEnclosure 2418 := by
  have hx := log_series_enclosure (x := (1209 / 1024)) (by norm_num) 6
  have h := log_binary_enclosure (n := 2418) (x := (1209 / 1024)) 11
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(3895347 / 500000), (7790717 / 1000000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_2442 : LogEnclosure 2442 := by
  have hx := log_series_enclosure (x := (1221 / 1024)) (by norm_num) 6
  have h := log_binary_enclosure (n := 2442) (x := (1221 / 1024)) 11
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(780057 / 100000), (7800593 / 1000000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_2470 : LogEnclosure 2470 := by
  have hx := log_series_enclosure (x := (1235 / 1024)) (by norm_num) 6
  have h := log_binary_enclosure (n := 2470) (x := (1235 / 1024)) 11
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(7811971 / 1000000), (3905997 / 500000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_2478 : LogEnclosure 2478 := by
  have hx := log_series_enclosure (x := (1239 / 1024)) (by norm_num) 6
  have h := log_binary_enclosure (n := 2478) (x := (1239 / 1024)) 11
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(1563041 / 200000), (1953807 / 250000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_2530 : LogEnclosure 2530 := by
  have hx := log_series_enclosure (x := (1265 / 1024)) (by norm_num) 6
  have h := log_binary_enclosure (n := 2530) (x := (1265 / 1024)) 11
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(1958993 / 250000), (1567199 / 200000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_2562 : LogEnclosure 2562 := by
  have hx := log_series_enclosure (x := (1281 / 1024)) (by norm_num) 6
  have h := log_binary_enclosure (n := 2562) (x := (1281 / 1024)) 11
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(7848541 / 1000000), (1962141 / 250000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_2590 : LogEnclosure 2590 := by
  have hx := log_series_enclosure (x := (1295 / 1024)) (by norm_num) 6
  have h := log_binary_enclosure (n := 2590) (x := (1295 / 1024)) 11
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(7859411 / 1000000), (3929717 / 500000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_2618 : LogEnclosure 2618 := by
  have hx := log_series_enclosure (x := (1309 / 1024)) (by norm_num) 6
  have h := log_binary_enclosure (n := 2618) (x := (1309 / 1024)) 11
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(7870163 / 1000000), (3935093 / 500000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_2622 : LogEnclosure 2622 := by
  have hx := log_series_enclosure (x := (1311 / 1024)) (by norm_num) 6
  have h := log_binary_enclosure (n := 2622) (x := (1311 / 1024)) 11
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(787169 / 100000), (7871713 / 1000000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_2706 : LogEnclosure 2706 := by
  have hx := log_series_enclosure (x := (1353 / 1024)) (by norm_num) 6
  have h := log_binary_enclosure (n := 2706) (x := (1353 / 1024)) 11
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(987903 / 125000), (7903247 / 1000000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_2730 : LogEnclosure 2730 := by
  have hx := log_series_enclosure (x := (1365 / 1024)) (by norm_num) 6
  have h := log_binary_enclosure (n := 2730) (x := (1365 / 1024)) 11
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(3956027 / 500000), (7912077 / 1000000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_2814 : LogEnclosure 2814 := by
  have hx := log_series_enclosure (x := (1407 / 1024)) (by norm_num) 6
  have h := log_binary_enclosure (n := 2814) (x := (1407 / 1024)) 11
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(198559 / 25000), (7942383 / 1000000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_2838 : LogEnclosure 2838 := by
  have hx := log_series_enclosure (x := (1419 / 1024)) (by norm_num) 6
  have h := log_binary_enclosure (n := 2838) (x := (1419 / 1024)) 11
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(1987713 / 250000), (63607 / 8000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_2886 : LogEnclosure 2886 := by
  have hx := log_series_enclosure (x := (1443 / 1024)) (by norm_num) 6
  have h := log_binary_enclosure (n := 2886) (x := (1443 / 1024)) 11
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(995953 / 125000), (7967647 / 1000000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_2914 : LogEnclosure 2914 := by
  have hx := log_series_enclosure (x := (1457 / 1024)) (by norm_num) 6
  have h := log_binary_enclosure (n := 2914) (x := (1457 / 1024)) 11
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(24929 / 3125), (7977303 / 1000000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_2926 : LogEnclosure 2926 := by
  have hx := log_series_enclosure (x := (1463 / 1024)) (by norm_num) 6
  have h := log_binary_enclosure (n := 2926) (x := (1463 / 1024)) 11
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(7981389 / 1000000), (1995353 / 250000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_2958 : LogEnclosure 2958 := by
  have hx := log_series_enclosure (x := (1479 / 1024)) (by norm_num) 6
  have h := log_binary_enclosure (n := 2958) (x := (1479 / 1024)) 11
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(3996133 / 500000), (7992289 / 1000000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_2990 : LogEnclosure 2990 := by
  have hx := log_series_enclosure (x := (1495 / 1024)) (by norm_num) 6
  have h := log_binary_enclosure (n := 2990) (x := (1495 / 1024)) 11
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(4001513 / 500000), (8003049 / 1000000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_3010 : LogEnclosure 3010 := by
  have hx := log_series_enclosure (x := (1505 / 1024)) (by norm_num) 6
  have h := log_binary_enclosure (n := 3010) (x := (1505 / 1024)) 11
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(8009693 / 1000000), (2002429 / 250000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_3034 : LogEnclosure 3034 := by
  have hx := log_series_enclosure (x := (1517 / 1024)) (by norm_num) 6
  have h := log_binary_enclosure (n := 3034) (x := (1517 / 1024)) 11
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(1603527 / 200000), (4008829 / 500000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_3102 : LogEnclosure 3102 := by
  have hx := log_series_enclosure (x := (1551 / 1024)) (by norm_num) 6
  have h := log_binary_enclosure (n := 3102) (x := (1551 / 1024)) 11
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(40199 / 5000), (8039823 / 1000000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_3162 : LogEnclosure 3162 := by
  have hx := log_series_enclosure (x := (1581 / 1024)) (by norm_num) 6
  have h := log_binary_enclosure (n := 3162) (x := (1581 / 1024)) 11
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(4029479 / 500000), (8058981 / 1000000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_3190 : LogEnclosure 3190 := by
  have hx := log_series_enclosure (x := (1595 / 1024)) (by norm_num) 6
  have h := log_binary_enclosure (n := 3190) (x := (1595 / 1024)) 11
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(4033887 / 500000), (8067797 / 1000000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_3198 : LogEnclosure 3198 := by
  have hx := log_series_enclosure (x := (1599 / 1024)) (by norm_num) 6
  have h := log_binary_enclosure (n := 3198) (x := (1599 / 1024)) 11
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(4035139 / 500000), (8070301 / 1000000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_3290 : LogEnclosure 3290 := by
  have hx := log_series_enclosure (x := (1645 / 1024)) (by norm_num) 6
  have h := log_binary_enclosure (n := 3290) (x := (1645 / 1024)) 11
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(101233 / 12500), (8098663 / 1000000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_3306 : LogEnclosure 3306 := by
  have hx := log_series_enclosure (x := (1653 / 1024)) (by norm_num) 6
  have h := log_binary_enclosure (n := 3306) (x := (1653 / 1024)) 11
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(2025873 / 250000), (1620703 / 200000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_3354 : LogEnclosure 3354 := by
  have hx := log_series_enclosure (x := (1677 / 1024)) (by norm_num) 6
  have h := log_binary_enclosure (n := 3354) (x := (1677 / 1024)) 11
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(4058953 / 500000), (8117929 / 1000000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_3410 : LogEnclosure 3410 := by
  have hx := log_series_enclosure (x := (1705 / 1024)) (by norm_num) 6
  have h := log_binary_enclosure (n := 3410) (x := (1705 / 1024)) 11
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(1626893 / 200000), (1016811 / 125000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_3422 : LogEnclosure 3422 := by
  have hx := log_series_enclosure (x := (1711 / 1024)) (by norm_num) 6
  have h := log_binary_enclosure (n := 3422) (x := (1711 / 1024)) 11
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(4068989 / 500000), (8138001 / 1000000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_3458 : LogEnclosure 3458 := by
  have hx := log_series_enclosure (x := (1729 / 1024)) (by norm_num) 6
  have h := log_binary_enclosure (n := 3458) (x := (1729 / 1024)) 11
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(8148443 / 1000000), (4074233 / 500000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_3498 : LogEnclosure 3498 := by
  have hx := log_series_enclosure (x := (1749 / 1024)) (by norm_num) 6
  have h := log_binary_enclosure (n := 3498) (x := (1749 / 1024)) 11
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(1019993 / 125000), (8159967 / 1000000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_3526 : LogEnclosure 3526 := by
  have hx := log_series_enclosure (x := (1763 / 1024)) (by norm_num) 6
  have h := log_binary_enclosure (n := 3526) (x := (1763 / 1024)) 11
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(8167917 / 1000000), (408397 / 50000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_3534 : LogEnclosure 3534 := by
  have hx := log_series_enclosure (x := (1767 / 1024)) (by norm_num) 6
  have h := log_binary_enclosure (n := 3534) (x := (1767 / 1024)) 11
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(8170183 / 1000000), (4085103 / 500000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_3538 : LogEnclosure 3538 := by
  have hx := log_series_enclosure (x := (1769 / 1024)) (by norm_num) 6
  have h := log_binary_enclosure (n := 3538) (x := (1769 / 1024)) 11
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(4085657 / 500000), (8171337 / 1000000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_3570 : LogEnclosure 3570 := by
  have hx := log_series_enclosure (x := (1785 / 1024)) (by norm_num) 6
  have h := log_binary_enclosure (n := 3570) (x := (1785 / 1024)) 11
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(4090159 / 500000), (8180341 / 1000000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_3666 : LogEnclosure 3666 := by
  have hx := log_series_enclosure (x := (1833 / 1024)) (by norm_num) 6
  have h := log_binary_enclosure (n := 3666) (x := (1833 / 1024)) 11
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(4103427 / 500000), (8206877 / 1000000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_3710 : LogEnclosure 3710 := by
  have hx := log_series_enclosure (x := (1855 / 1024)) (by norm_num) 6
  have h := log_binary_enclosure (n := 3710) (x := (1855 / 1024)) 11
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(1643757 / 200000), (1027351 / 125000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_3774 : LogEnclosure 3774 := by
  have hx := log_series_enclosure (x := (1887 / 1024)) (by norm_num) 6
  have h := log_binary_enclosure (n := 3774) (x := (1887 / 1024)) 11
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(514743 / 62500), (1029489 / 125000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_3782 : LogEnclosure 3782 := by
  have hx := log_series_enclosure (x := (1891 / 1024)) (by norm_num) 6
  have h := log_binary_enclosure (n := 3782) (x := (1891 / 1024)) 11
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(4119003 / 500000), (8238029 / 1000000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_3894 : LogEnclosure 3894 := by
  have hx := log_series_enclosure (x := (1947 / 1024)) (by norm_num) 6
  have h := log_binary_enclosure (n := 3894) (x := (1947 / 1024)) 11
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(826719 / 100000), (8267213 / 1000000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_3910 : LogEnclosure 3910 := by
  have hx := log_series_enclosure (x := (1955 / 1024)) (by norm_num) 6
  have h := log_binary_enclosure (n := 3910) (x := (1955 / 1024)) 11
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(827129 / 100000), (4135657 / 500000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]


end Imscribing.ABC.Window70E1_10
