import Imscribing.ABC_Window70_FromOS_Certs3

/-! Generated by scripts/abc_emit_window_certificate.py; all claims checked by Lean. -/
namespace Imscribing.ABC.Window70E1_10

set_option maxRecDepth 8192
set_option maxHeartbeats 4000000
set_option synthInstance.maxSize 16384
set_option synthInstance.maxHeartbeats 4000000

noncomputable def logCertificate_3922 : LogEnclosure 3922 := by
  have hx := log_series_enclosure (x := (1961 / 1024)) (by norm_num) 6
  have h := log_binary_enclosure (n := 3922) (x := (1961 / 1024)) 11
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(4137177 / 500000), (4137189 / 500000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_3990 : LogEnclosure 3990 := by
  have hx := log_series_enclosure (x := (1995 / 1024)) (by norm_num) 6
  have h := log_binary_enclosure (n := 3990) (x := (1995 / 1024)) 11
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(1036443 / 125000), (518223 / 62500), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_4002 : LogEnclosure 4002 := by
  have hx := log_series_enclosure (x := (2001 / 1024)) (by norm_num) 6
  have h := log_binary_enclosure (n := 4002) (x := (2001 / 1024)) 11
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(8294547 / 1000000), (8294571 / 1000000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_4030 : LogEnclosure 4030 := by
  have hx := log_series_enclosure (x := (2015 / 1024)) (by norm_num) 6
  have h := log_binary_enclosure (n := 4030) (x := (2015 / 1024)) 11
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(8301519 / 1000000), (8301543 / 1000000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_4042 : LogEnclosure 4042 := by
  have hx := log_series_enclosure (x := (2021 / 1024)) (by norm_num) 6
  have h := log_binary_enclosure (n := 4042) (x := (2021 / 1024)) 11
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(2076123 / 250000), (2076129 / 250000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_4130 : LogEnclosure 4130 := by
  have hx := log_series_enclosure (x := (2065 / 2048)) (by norm_num) 6
  have h := log_binary_enclosure (n := 4130) (x := (2065 / 2048)) 12
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(832603 / 100000), (1665211 / 200000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_4134 : LogEnclosure 4134 := by
  have hx := log_series_enclosure (x := (2067 / 2048)) (by norm_num) 6
  have h := log_binary_enclosure (n := 4134) (x := (2067 / 2048)) 12
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(4163499 / 500000), (8327023 / 1000000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_4182 : LogEnclosure 4182 := by
  have hx := log_series_enclosure (x := (2091 / 2048)) (by norm_num) 6
  have h := log_binary_enclosure (n := 4182) (x := (2091 / 2048)) 12
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(4169271 / 500000), (8338567 / 1000000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_4186 : LogEnclosure 4186 := by
  have hx := log_series_enclosure (x := (2093 / 2048)) (by norm_num) 6
  have h := log_binary_enclosure (n := 4186) (x := (2093 / 2048)) 12
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(4169749 / 500000), (8339523 / 1000000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_4218 : LogEnclosure 4218 := by
  have hx := log_series_enclosure (x := (2109 / 2048)) (by norm_num) 6
  have h := log_binary_enclosure (n := 4218) (x := (2109 / 2048)) 12
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(4173557 / 500000), (8347139 / 1000000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_4270 : LogEnclosure 4270 := by
  have hx := log_series_enclosure (x := (2135 / 2048)) (by norm_num) 6
  have h := log_binary_enclosure (n := 4270) (x := (2135 / 2048)) 12
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(4179683 / 500000), (8359391 / 1000000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_4278 : LogEnclosure 4278 := by
  have hx := log_series_enclosure (x := (2139 / 2048)) (by norm_num) 6
  have h := log_binary_enclosure (n := 4278) (x := (2139 / 2048)) 12
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(4180619 / 500000), (8361263 / 1000000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_4290 : LogEnclosure 4290 := by
  have hx := log_series_enclosure (x := (2145 / 2048)) (by norm_num) 6
  have h := log_binary_enclosure (n := 4290) (x := (2145 / 2048)) 12
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(8364039 / 1000000), (261377 / 31250), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_4386 : LogEnclosure 4386 := by
  have hx := log_series_enclosure (x := (2193 / 2048)) (by norm_num) 6
  have h := log_binary_enclosure (n := 4386) (x := (2193 / 2048)) 12
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(838617 / 100000), (1677239 / 200000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_4422 : LogEnclosure 4422 := by
  have hx := log_series_enclosure (x := (2211 / 2048)) (by norm_num) 6
  have h := log_binary_enclosure (n := 4422) (x := (2211 / 2048)) 12
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(1678869 / 200000), (839437 / 100000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_4466 : LogEnclosure 4466 := by
  have hx := log_series_enclosure (x := (2233 / 2048)) (by norm_num) 6
  have h := log_binary_enclosure (n := 4466) (x := (2233 / 2048)) 12
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(4202123 / 500000), (8404271 / 1000000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_4522 : LogEnclosure 4522 := by
  have hx := log_series_enclosure (x := (2261 / 2048)) (by norm_num) 6
  have h := log_binary_enclosure (n := 4522) (x := (2261 / 2048)) 12
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(8416707 / 1000000), (2104183 / 250000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_4674 : LogEnclosure 4674 := by
  have hx := log_series_enclosure (x := (2337 / 2048)) (by norm_num) 6
  have h := log_binary_enclosure (n := 4674) (x := (2337 / 2048)) 12
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(1056221 / 125000), (8449793 / 1000000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_4690 : LogEnclosure 4690 := by
  have hx := log_series_enclosure (x := (2345 / 2048)) (by norm_num) 6
  have h := log_binary_enclosure (n := 4690) (x := (2345 / 2048)) 12
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(1690637 / 200000), (845321 / 100000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_4758 : LogEnclosure 4758 := by
  have hx := log_series_enclosure (x := (2379 / 2048)) (by norm_num) 6
  have h := log_binary_enclosure (n := 4758) (x := (2379 / 2048)) 12
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(423379 / 50000), (1693521 / 200000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_4794 : LogEnclosure 4794 := by
  have hx := log_series_enclosure (x := (2397 / 2048)) (by norm_num) 6
  have h := log_binary_enclosure (n := 4794) (x := (2397 / 2048)) 12
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(4237559 / 500000), (8475143 / 1000000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_4810 : LogEnclosure 4810 := by
  have hx := log_series_enclosure (x := (2405 / 2048)) (by norm_num) 6
  have h := log_binary_enclosure (n := 4810) (x := (2405 / 2048)) 12
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(169569 / 20000), (339139 / 40000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_4830 : LogEnclosure 4830 := by
  have hx := log_series_enclosure (x := (2415 / 2048)) (by norm_num) 6
  have h := log_binary_enclosure (n := 4830) (x := (2415 / 2048)) 12
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(8482599 / 1000000), (132541 / 15625), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_4902 : LogEnclosure 4902 := by
  have hx := log_series_enclosure (x := (2451 / 2048)) (by norm_num) 6
  have h := log_binary_enclosure (n := 4902) (x := (2451 / 2048)) 12
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(2124349 / 250000), (8497421 / 1000000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_4930 : LogEnclosure 4930 := by
  have hx := log_series_enclosure (x := (2465 / 2048)) (by norm_num) 6
  have h := log_binary_enclosure (n := 4930) (x := (2465 / 2048)) 12
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(2125773 / 250000), (8503117 / 1000000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_5074 : LogEnclosure 5074 := by
  have hx := log_series_enclosure (x := (2537 / 2048)) (by norm_num) 6
  have h := log_binary_enclosure (n := 5074) (x := (2537 / 2048)) 12
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(4265941 / 500000), (8531907 / 1000000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_5106 : LogEnclosure 5106 := by
  have hx := log_series_enclosure (x := (2553 / 2048)) (by norm_num) 6
  have h := log_binary_enclosure (n := 5106) (x := (2553 / 2048)) 12
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(8538169 / 1000000), (4269097 / 500000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_5170 : LogEnclosure 5170 := by
  have hx := log_series_enclosure (x := (2585 / 2048)) (by norm_num) 6
  have h := log_binary_enclosure (n := 5170) (x := (2585 / 2048)) 12
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(13681 / 1600), (171013 / 20000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_5226 : LogEnclosure 5226 := by
  have hx := log_series_enclosure (x := (2613 / 2048)) (by norm_num) 6
  have h := log_binary_enclosure (n := 5226) (x := (2613 / 2048)) 12
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(8561399 / 1000000), (535089 / 62500), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_5358 : LogEnclosure 5358 := by
  have hx := log_series_enclosure (x := (2679 / 2048)) (by norm_num) 6
  have h := log_binary_enclosure (n := 5358) (x := (2679 / 2048)) 12
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(8586343 / 1000000), (134162 / 15625), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_5394 : LogEnclosure 5394 := by
  have hx := log_series_enclosure (x := (2697 / 2048)) (by norm_num) 6
  have h := log_binary_enclosure (n := 5394) (x := (2697 / 2048)) 12
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(107413 / 12500), (1718613 / 200000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_5406 : LogEnclosure 5406 := by
  have hx := log_series_enclosure (x := (2703 / 2048)) (by norm_num) 6
  have h := log_binary_enclosure (n := 5406) (x := (2703 / 2048)) 12
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(4297631 / 500000), (8595287 / 1000000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_5510 : LogEnclosure 5510 := by
  have hx := log_series_enclosure (x := (2755 / 2048)) (by norm_num) 6
  have h := log_binary_enclosure (n := 5510) (x := (2755 / 2048)) 12
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(8614317 / 1000000), (4307171 / 500000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_5610 : LogEnclosure 5610 := by
  have hx := log_series_enclosure (x := (2805 / 2048)) (by norm_num) 6
  have h := log_binary_enclosure (n := 5610) (x := (2805 / 2048)) 12
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(8632303 / 1000000), (1079041 / 125000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_5642 : LogEnclosure 5642 := by
  have hx := log_series_enclosure (x := (2821 / 2048)) (by norm_num) 6
  have h := log_binary_enclosure (n := 5642) (x := (2821 / 2048)) 12
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(8637991 / 1000000), (134969 / 15625), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_5658 : LogEnclosure 5658 := by
  have hx := log_series_enclosure (x := (2829 / 2048)) (by norm_num) 6
  have h := log_binary_enclosure (n := 5658) (x := (2829 / 2048)) 12
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(8640823 / 1000000), (540053 / 62500), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_5698 : LogEnclosure 5698 := by
  have hx := log_series_enclosure (x := (2849 / 2048)) (by norm_num) 6
  have h := log_binary_enclosure (n := 5698) (x := (2849 / 2048)) 12
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(2161967 / 250000), (8647893 / 1000000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_5830 : LogEnclosure 5830 := by
  have hx := log_series_enclosure (x := (2915 / 2048)) (by norm_num) 6
  have h := log_binary_enclosure (n := 5830) (x := (2915 / 2048)) 12
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(867077 / 100000), (1734159 / 200000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_5890 : LogEnclosure 5890 := by
  have hx := log_series_enclosure (x := (2945 / 2048)) (by norm_num) 6
  have h := log_binary_enclosure (n := 5890) (x := (2945 / 2048)) 12
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(8681009 / 1000000), (4340517 / 500000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_5934 : LogEnclosure 5934 := by
  have hx := log_series_enclosure (x := (2967 / 2048)) (by norm_num) 6
  have h := log_binary_enclosure (n := 5934) (x := (2967 / 2048)) 12
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(8688451 / 1000000), (2172119 / 250000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_6006 : LogEnclosure 6006 := by
  have hx := log_series_enclosure (x := (3003 / 2048)) (by norm_num) 6
  have h := log_binary_enclosure (n := 6006) (x := (3003 / 2048)) 12
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(271891 / 31250), (8700537 / 1000000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_6018 : LogEnclosure 6018 := by
  have hx := log_series_enclosure (x := (3009 / 2048)) (by norm_num) 6
  have h := log_binary_enclosure (n := 6018) (x := (3009 / 2048)) 12
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(2175627 / 250000), (8702533 / 1000000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_6042 : LogEnclosure 6042 := by
  have hx := log_series_enclosure (x := (3021 / 2048)) (by norm_num) 6
  have h := log_binary_enclosure (n := 6042) (x := (3021 / 2048)) 12
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(1088311 / 125000), (8706513 / 1000000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_6090 : LogEnclosure 6090 := by
  have hx := log_series_enclosure (x := (3045 / 2048)) (by norm_num) 6
  have h := log_binary_enclosure (n := 6090) (x := (3045 / 2048)) 12
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(8714401 / 1000000), (4357213 / 500000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_6110 : LogEnclosure 6110 := by
  have hx := log_series_enclosure (x := (3055 / 2048)) (by norm_num) 6
  have h := log_binary_enclosure (n := 6110) (x := (3055 / 2048)) 12
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(8717679 / 1000000), (1089713 / 125000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_6222 : LogEnclosure 6222 := by
  have hx := log_series_enclosure (x := (3111 / 2048)) (by norm_num) 6
  have h := log_binary_enclosure (n := 6222) (x := (3111 / 2048)) 12
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(2183961 / 250000), (8735869 / 1000000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_6270 : LogEnclosure 6270 := by
  have hx := log_series_enclosure (x := (3135 / 2048)) (by norm_num) 6
  have h := log_binary_enclosure (n := 6270) (x := (3135 / 2048)) 12
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(8743529 / 1000000), (4371777 / 500000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_6290 : LogEnclosure 6290 := by
  have hx := log_series_enclosure (x := (3145 / 2048)) (by norm_num) 6
  have h := log_binary_enclosure (n := 6290) (x := (3145 / 2048)) 12
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(4373357 / 500000), (8746739 / 1000000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_6466 : LogEnclosure 6466 := by
  have hx := log_series_enclosure (x := (3233 / 2048)) (by norm_num) 6
  have h := log_binary_enclosure (n := 6466) (x := (3233 / 2048)) 12
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(877431 / 100000), (1754867 / 200000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_6486 : LogEnclosure 6486 := by
  have hx := log_series_enclosure (x := (3243 / 2048)) (by norm_num) 6
  have h := log_binary_enclosure (n := 6486) (x := (3243 / 2048)) 12
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(8777399 / 1000000), (548589 / 62500), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_6490 : LogEnclosure 6490 := by
  have hx := log_series_enclosure (x := (3245 / 2048)) (by norm_num) 6
  have h := log_binary_enclosure (n := 6490) (x := (3245 / 2048)) 12
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(1755603 / 200000), (219451 / 25000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_6510 : LogEnclosure 6510 := by
  have hx := log_series_enclosure (x := (3255 / 2048)) (by norm_num) 6
  have h := log_binary_enclosure (n := 6510) (x := (3255 / 2048)) 12
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(2195273 / 250000), (8781117 / 1000000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_6630 : LogEnclosure 6630 := by
  have hx := log_series_enclosure (x := (3315 / 2048)) (by norm_num) 6
  have h := log_binary_enclosure (n := 6630) (x := (3315 / 2048)) 12
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(8799357 / 1000000), (4399691 / 500000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_6710 : LogEnclosure 6710 := by
  have hx := log_series_enclosure (x := (3355 / 2048)) (by norm_num) 6
  have h := log_binary_enclosure (n := 6710) (x := (3355 / 2048)) 12
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(1101419 / 125000), (8811377 / 1000000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_6726 : LogEnclosure 6726 := by
  have hx := log_series_enclosure (x := (3363 / 2048)) (by norm_num) 6
  have h := log_binary_enclosure (n := 6726) (x := (3363 / 2048)) 12
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(8813733 / 1000000), (4406879 / 500000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_6834 : LogEnclosure 6834 := by
  have hx := log_series_enclosure (x := (3417 / 2048)) (by norm_num) 6
  have h := log_binary_enclosure (n := 6834) (x := (3417 / 2048)) 12
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(8829663 / 1000000), (1103711 / 125000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_6882 : LogEnclosure 6882 := by
  have hx := log_series_enclosure (x := (3441 / 2048)) (by norm_num) 6
  have h := log_binary_enclosure (n := 6882) (x := (3441 / 2048)) 12
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(4418331 / 500000), (8836687 / 1000000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_6890 : LogEnclosure 6890 := by
  have hx := log_series_enclosure (x := (3445 / 2048)) (by norm_num) 6
  have h := log_binary_enclosure (n := 6890) (x := (3445 / 2048)) 12
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(138091 / 15625), (8837849 / 1000000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_6954 : LogEnclosure 6954 := by
  have hx := log_series_enclosure (x := (3477 / 2048)) (by norm_num) 6
  have h := log_binary_enclosure (n := 6954) (x := (3477 / 2048)) 12
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(884707 / 100000), (1769419 / 200000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_7134 : LogEnclosure 7134 := by
  have hx := log_series_enclosure (x := (3567 / 2048)) (by norm_num) 6
  have h := log_binary_enclosure (n := 7134) (x := (3567 / 2048)) 12
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(70981 / 8000), (177453 / 20000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_7198 : LogEnclosure 7198 := by
  have hx := log_series_enclosure (x := (3599 / 2048)) (by norm_num) 6
  have h := log_binary_enclosure (n := 7198) (x := (3599 / 2048)) 12
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(2220389 / 250000), (8881581 / 1000000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_7310 : LogEnclosure 7310 := by
  have hx := log_series_enclosure (x := (3655 / 2048)) (by norm_num) 6
  have h := log_binary_enclosure (n := 7310) (x := (3655 / 2048)) 12
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(2224249 / 250000), (8897021 / 1000000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_7314 : LogEnclosure 7314 := by
  have hx := log_series_enclosure (x := (3657 / 2048)) (by norm_num) 6
  have h := log_binary_enclosure (n := 7314) (x := (3657 / 2048)) 12
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(8897543 / 1000000), (278049 / 31250), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_7378 : LogEnclosure 7378 := by
  have hx := log_series_enclosure (x := (3689 / 2048)) (by norm_num) 6
  have h := log_binary_enclosure (n := 7378) (x := (3689 / 2048)) 12
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(1781251 / 200000), (222657 / 25000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_7410 : LogEnclosure 7410 := by
  have hx := log_series_enclosure (x := (3705 / 2048)) (by norm_num) 6
  have h := log_binary_enclosure (n := 7410) (x := (3705 / 2048)) 12
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(8910583 / 1000000), (556913 / 62500), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_7462 : LogEnclosure 7462 := by
  have hx := log_series_enclosure (x := (3731 / 2048)) (by norm_num) 6
  have h := log_binary_enclosure (n := 7462) (x := (3731 / 2048)) 12
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(1114697 / 125000), (8917601 / 1000000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_7590 : LogEnclosure 7590 := by
  have hx := log_series_enclosure (x := (3795 / 2048)) (by norm_num) 6
  have h := log_binary_enclosure (n := 7590) (x := (3795 / 2048)) 12
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(1116823 / 125000), (893461 / 100000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_7638 : LogEnclosure 7638 := by
  have hx := log_series_enclosure (x := (3819 / 2048)) (by norm_num) 6
  have h := log_binary_enclosure (n := 7638) (x := (3819 / 2048)) 12
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(1117611 / 125000), (4470457 / 500000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_7770 : LogEnclosure 7770 := by
  have hx := log_series_enclosure (x := (3885 / 2048)) (by norm_num) 6
  have h := log_binary_enclosure (n := 7770) (x := (3885 / 2048)) 12
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(8958023 / 1000000), (279939 / 31250), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]

noncomputable def logCertificate_7826 : LogEnclosure 7826 := by
  have hx := log_series_enclosure (x := (3913 / 2048)) (by norm_num) 6
  have h := log_binary_enclosure (n := 7826) (x := (3913 / 2048)) 12
    (by norm_num) (by norm_num) log_two_certificate hx
  norm_num [logSeriesLower, logSeriesUpper, Finset.sum_range_succ] at h
  refine ⟨(2241301 / 250000), (896523 / 100000), ?_, ?_⟩ <;> norm_num <;> linarith [h.1, h.2]


end Imscribing.ABC.Window70E1_10
