import Imscribing.ABC_Window70_FromOS_Samples4

/-! Generated by scripts/abc_emit_window_certificate.py; all claims checked by Lean. -/
namespace Imscribing.ABC.Window70E1_10

set_option maxRecDepth 8192
set_option maxHeartbeats 4000000
set_option synthInstance.maxSize 16384
set_option synthInstance.maxHeartbeats 4000000

def sample_1_44 : Triple := ⟨1, 44, 45, by decide, by decide, by decide, by decide⟩
theorem sample_1_44_interval :
    (logCertificate_45.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_330.upper ≤
      discrepancy (1 / 10) sample_1_44 ∧
    discrepancy (1 / 10) sample_1_44 ≤
      (logCertificate_45.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_330.lower := by
  have hr : radical (1 * 44 * 45) = 330 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_1_44.a * sample_1_44.b * sample_1_44.c)) :=
    ⟨logCertificate_330.lower, logCertificate_330.upper,
      by simpa only [sample_1_44, hr] using logCertificate_330.lower_le,
      by simpa only [sample_1_44, hr] using logCertificate_330.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_1_44 logCertificate_45 support
  simpa only [support] using h

theorem sample_1_44_upper : discrepancy (1 / 10) sample_1_44 ≤ (227 / 1000) := by
  have h := sample_1_44_interval.2
  norm_num [logCertificate_45, logCertificate_330] at h
  linarith

def sample_2_43 : Triple := ⟨2, 43, 45, by decide, by decide, by decide, by decide⟩
theorem sample_2_43_interval :
    (logCertificate_45.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1290.upper ≤
      discrepancy (1 / 10) sample_2_43 ∧
    discrepancy (1 / 10) sample_2_43 ≤
      (logCertificate_45.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1290.lower := by
  have hr : radical (2 * 43 * 45) = 1290 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_2_43.a * sample_2_43.b * sample_2_43.c)) :=
    ⟨logCertificate_1290.lower, logCertificate_1290.upper,
      by simpa only [sample_2_43, hr] using logCertificate_1290.lower_le,
      by simpa only [sample_2_43, hr] using logCertificate_1290.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_2_43 logCertificate_45 support
  simpa only [support] using h

theorem sample_2_43_upper : discrepancy (1 / 10) sample_2_43 ≤ (227 / 1000) := by
  have h := sample_2_43_interval.2
  norm_num [logCertificate_45, logCertificate_1290] at h
  linarith

def sample_4_41 : Triple := ⟨4, 41, 45, by decide, by decide, by decide, by decide⟩
theorem sample_4_41_interval :
    (logCertificate_45.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1230.upper ≤
      discrepancy (1 / 10) sample_4_41 ∧
    discrepancy (1 / 10) sample_4_41 ≤
      (logCertificate_45.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1230.lower := by
  have hr : radical (4 * 41 * 45) = 1230 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_4_41.a * sample_4_41.b * sample_4_41.c)) :=
    ⟨logCertificate_1230.lower, logCertificate_1230.upper,
      by simpa only [sample_4_41, hr] using logCertificate_1230.lower_le,
      by simpa only [sample_4_41, hr] using logCertificate_1230.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_4_41 logCertificate_45 support
  simpa only [support] using h

theorem sample_4_41_upper : discrepancy (1 / 10) sample_4_41 ≤ (227 / 1000) := by
  have h := sample_4_41_interval.2
  norm_num [logCertificate_45, logCertificate_1230] at h
  linarith

def sample_7_38 : Triple := ⟨7, 38, 45, by decide, by decide, by decide, by decide⟩
theorem sample_7_38_interval :
    (logCertificate_45.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_3990.upper ≤
      discrepancy (1 / 10) sample_7_38 ∧
    discrepancy (1 / 10) sample_7_38 ≤
      (logCertificate_45.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_3990.lower := by
  have hr : radical (7 * 38 * 45) = 3990 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_7_38.a * sample_7_38.b * sample_7_38.c)) :=
    ⟨logCertificate_3990.lower, logCertificate_3990.upper,
      by simpa only [sample_7_38, hr] using logCertificate_3990.lower_le,
      by simpa only [sample_7_38, hr] using logCertificate_3990.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_7_38 logCertificate_45 support
  simpa only [support] using h

theorem sample_7_38_upper : discrepancy (1 / 10) sample_7_38 ≤ (227 / 1000) := by
  have h := sample_7_38_interval.2
  norm_num [logCertificate_45, logCertificate_3990] at h
  linarith

def sample_8_37 : Triple := ⟨8, 37, 45, by decide, by decide, by decide, by decide⟩
theorem sample_8_37_interval :
    (logCertificate_45.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1110.upper ≤
      discrepancy (1 / 10) sample_8_37 ∧
    discrepancy (1 / 10) sample_8_37 ≤
      (logCertificate_45.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1110.lower := by
  have hr : radical (8 * 37 * 45) = 1110 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_8_37.a * sample_8_37.b * sample_8_37.c)) :=
    ⟨logCertificate_1110.lower, logCertificate_1110.upper,
      by simpa only [sample_8_37, hr] using logCertificate_1110.lower_le,
      by simpa only [sample_8_37, hr] using logCertificate_1110.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_8_37 logCertificate_45 support
  simpa only [support] using h

theorem sample_8_37_upper : discrepancy (1 / 10) sample_8_37 ≤ (227 / 1000) := by
  have h := sample_8_37_interval.2
  norm_num [logCertificate_45, logCertificate_1110] at h
  linarith

def sample_11_34 : Triple := ⟨11, 34, 45, by decide, by decide, by decide, by decide⟩
theorem sample_11_34_interval :
    (logCertificate_45.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_5610.upper ≤
      discrepancy (1 / 10) sample_11_34 ∧
    discrepancy (1 / 10) sample_11_34 ≤
      (logCertificate_45.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_5610.lower := by
  have hr : radical (11 * 34 * 45) = 5610 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_11_34.a * sample_11_34.b * sample_11_34.c)) :=
    ⟨logCertificate_5610.lower, logCertificate_5610.upper,
      by simpa only [sample_11_34, hr] using logCertificate_5610.lower_le,
      by simpa only [sample_11_34, hr] using logCertificate_5610.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_11_34 logCertificate_45 support
  simpa only [support] using h

theorem sample_11_34_upper : discrepancy (1 / 10) sample_11_34 ≤ (227 / 1000) := by
  have h := sample_11_34_interval.2
  norm_num [logCertificate_45, logCertificate_5610] at h
  linarith

def sample_13_32 : Triple := ⟨13, 32, 45, by decide, by decide, by decide, by decide⟩
theorem sample_13_32_interval :
    (logCertificate_45.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_390.upper ≤
      discrepancy (1 / 10) sample_13_32 ∧
    discrepancy (1 / 10) sample_13_32 ≤
      (logCertificate_45.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_390.lower := by
  have hr : radical (13 * 32 * 45) = 390 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_13_32.a * sample_13_32.b * sample_13_32.c)) :=
    ⟨logCertificate_390.lower, logCertificate_390.upper,
      by simpa only [sample_13_32, hr] using logCertificate_390.lower_le,
      by simpa only [sample_13_32, hr] using logCertificate_390.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_13_32 logCertificate_45 support
  simpa only [support] using h

theorem sample_13_32_upper : discrepancy (1 / 10) sample_13_32 ≤ (227 / 1000) := by
  have h := sample_13_32_interval.2
  norm_num [logCertificate_45, logCertificate_390] at h
  linarith

def sample_14_31 : Triple := ⟨14, 31, 45, by decide, by decide, by decide, by decide⟩
theorem sample_14_31_interval :
    (logCertificate_45.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_6510.upper ≤
      discrepancy (1 / 10) sample_14_31 ∧
    discrepancy (1 / 10) sample_14_31 ≤
      (logCertificate_45.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_6510.lower := by
  have hr : radical (14 * 31 * 45) = 6510 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_14_31.a * sample_14_31.b * sample_14_31.c)) :=
    ⟨logCertificate_6510.lower, logCertificate_6510.upper,
      by simpa only [sample_14_31, hr] using logCertificate_6510.lower_le,
      by simpa only [sample_14_31, hr] using logCertificate_6510.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_14_31 logCertificate_45 support
  simpa only [support] using h

theorem sample_14_31_upper : discrepancy (1 / 10) sample_14_31 ≤ (227 / 1000) := by
  have h := sample_14_31_interval.2
  norm_num [logCertificate_45, logCertificate_6510] at h
  linarith

def sample_16_29 : Triple := ⟨16, 29, 45, by decide, by decide, by decide, by decide⟩
theorem sample_16_29_interval :
    (logCertificate_45.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_870.upper ≤
      discrepancy (1 / 10) sample_16_29 ∧
    discrepancy (1 / 10) sample_16_29 ≤
      (logCertificate_45.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_870.lower := by
  have hr : radical (16 * 29 * 45) = 870 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_16_29.a * sample_16_29.b * sample_16_29.c)) :=
    ⟨logCertificate_870.lower, logCertificate_870.upper,
      by simpa only [sample_16_29, hr] using logCertificate_870.lower_le,
      by simpa only [sample_16_29, hr] using logCertificate_870.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_16_29 logCertificate_45 support
  simpa only [support] using h

theorem sample_16_29_upper : discrepancy (1 / 10) sample_16_29 ≤ (227 / 1000) := by
  have h := sample_16_29_interval.2
  norm_num [logCertificate_45, logCertificate_870] at h
  linarith

def sample_17_28 : Triple := ⟨17, 28, 45, by decide, by decide, by decide, by decide⟩
theorem sample_17_28_interval :
    (logCertificate_45.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_3570.upper ≤
      discrepancy (1 / 10) sample_17_28 ∧
    discrepancy (1 / 10) sample_17_28 ≤
      (logCertificate_45.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_3570.lower := by
  have hr : radical (17 * 28 * 45) = 3570 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_17_28.a * sample_17_28.b * sample_17_28.c)) :=
    ⟨logCertificate_3570.lower, logCertificate_3570.upper,
      by simpa only [sample_17_28, hr] using logCertificate_3570.lower_le,
      by simpa only [sample_17_28, hr] using logCertificate_3570.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_17_28 logCertificate_45 support
  simpa only [support] using h

theorem sample_17_28_upper : discrepancy (1 / 10) sample_17_28 ≤ (227 / 1000) := by
  have h := sample_17_28_interval.2
  norm_num [logCertificate_45, logCertificate_3570] at h
  linarith

def sample_19_26 : Triple := ⟨19, 26, 45, by decide, by decide, by decide, by decide⟩
theorem sample_19_26_interval :
    (logCertificate_45.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_7410.upper ≤
      discrepancy (1 / 10) sample_19_26 ∧
    discrepancy (1 / 10) sample_19_26 ≤
      (logCertificate_45.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_7410.lower := by
  have hr : radical (19 * 26 * 45) = 7410 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_19_26.a * sample_19_26.b * sample_19_26.c)) :=
    ⟨logCertificate_7410.lower, logCertificate_7410.upper,
      by simpa only [sample_19_26, hr] using logCertificate_7410.lower_le,
      by simpa only [sample_19_26, hr] using logCertificate_7410.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_19_26 logCertificate_45 support
  simpa only [support] using h

theorem sample_19_26_upper : discrepancy (1 / 10) sample_19_26 ≤ (227 / 1000) := by
  have h := sample_19_26_interval.2
  norm_num [logCertificate_45, logCertificate_7410] at h
  linarith

def sample_22_23 : Triple := ⟨22, 23, 45, by decide, by decide, by decide, by decide⟩
theorem sample_22_23_interval :
    (logCertificate_45.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_7590.upper ≤
      discrepancy (1 / 10) sample_22_23 ∧
    discrepancy (1 / 10) sample_22_23 ≤
      (logCertificate_45.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_7590.lower := by
  have hr : radical (22 * 23 * 45) = 7590 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_22_23.a * sample_22_23.b * sample_22_23.c)) :=
    ⟨logCertificate_7590.lower, logCertificate_7590.upper,
      by simpa only [sample_22_23, hr] using logCertificate_7590.lower_le,
      by simpa only [sample_22_23, hr] using logCertificate_7590.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_22_23 logCertificate_45 support
  simpa only [support] using h

theorem sample_22_23_upper : discrepancy (1 / 10) sample_22_23 ≤ (227 / 1000) := by
  have h := sample_22_23_interval.2
  norm_num [logCertificate_45, logCertificate_7590] at h
  linarith

def sample_1_45 : Triple := ⟨1, 45, 46, by decide, by decide, by decide, by decide⟩
theorem sample_1_45_interval :
    (logCertificate_46.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_690.upper ≤
      discrepancy (1 / 10) sample_1_45 ∧
    discrepancy (1 / 10) sample_1_45 ≤
      (logCertificate_46.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_690.lower := by
  have hr : radical (1 * 45 * 46) = 690 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_1_45.a * sample_1_45.b * sample_1_45.c)) :=
    ⟨logCertificate_690.lower, logCertificate_690.upper,
      by simpa only [sample_1_45, hr] using logCertificate_690.lower_le,
      by simpa only [sample_1_45, hr] using logCertificate_690.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_1_45 logCertificate_46 support
  simpa only [support] using h

theorem sample_1_45_upper : discrepancy (1 / 10) sample_1_45 ≤ (227 / 1000) := by
  have h := sample_1_45_interval.2
  norm_num [logCertificate_46, logCertificate_690] at h
  linarith

def sample_3_43 : Triple := ⟨3, 43, 46, by decide, by decide, by decide, by decide⟩
theorem sample_3_43_interval :
    (logCertificate_46.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_5934.upper ≤
      discrepancy (1 / 10) sample_3_43 ∧
    discrepancy (1 / 10) sample_3_43 ≤
      (logCertificate_46.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_5934.lower := by
  have hr : radical (3 * 43 * 46) = 5934 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_3_43.a * sample_3_43.b * sample_3_43.c)) :=
    ⟨logCertificate_5934.lower, logCertificate_5934.upper,
      by simpa only [sample_3_43, hr] using logCertificate_5934.lower_le,
      by simpa only [sample_3_43, hr] using logCertificate_5934.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_3_43 logCertificate_46 support
  simpa only [support] using h

theorem sample_3_43_upper : discrepancy (1 / 10) sample_3_43 ≤ (227 / 1000) := by
  have h := sample_3_43_interval.2
  norm_num [logCertificate_46, logCertificate_5934] at h
  linarith

def sample_5_41 : Triple := ⟨5, 41, 46, by decide, by decide, by decide, by decide⟩
theorem sample_5_41_interval :
    (logCertificate_46.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_9430.upper ≤
      discrepancy (1 / 10) sample_5_41 ∧
    discrepancy (1 / 10) sample_5_41 ≤
      (logCertificate_46.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_9430.lower := by
  have hr : radical (5 * 41 * 46) = 9430 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_5_41.a * sample_5_41.b * sample_5_41.c)) :=
    ⟨logCertificate_9430.lower, logCertificate_9430.upper,
      by simpa only [sample_5_41, hr] using logCertificate_9430.lower_le,
      by simpa only [sample_5_41, hr] using logCertificate_9430.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_5_41 logCertificate_46 support
  simpa only [support] using h

theorem sample_5_41_upper : discrepancy (1 / 10) sample_5_41 ≤ (227 / 1000) := by
  have h := sample_5_41_interval.2
  norm_num [logCertificate_46, logCertificate_9430] at h
  linarith

def sample_7_39 : Triple := ⟨7, 39, 46, by decide, by decide, by decide, by decide⟩
theorem sample_7_39_interval :
    (logCertificate_46.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_12558.upper ≤
      discrepancy (1 / 10) sample_7_39 ∧
    discrepancy (1 / 10) sample_7_39 ≤
      (logCertificate_46.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_12558.lower := by
  have hr : radical (7 * 39 * 46) = 12558 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_7_39.a * sample_7_39.b * sample_7_39.c)) :=
    ⟨logCertificate_12558.lower, logCertificate_12558.upper,
      by simpa only [sample_7_39, hr] using logCertificate_12558.lower_le,
      by simpa only [sample_7_39, hr] using logCertificate_12558.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_7_39 logCertificate_46 support
  simpa only [support] using h

theorem sample_7_39_upper : discrepancy (1 / 10) sample_7_39 ≤ (227 / 1000) := by
  have h := sample_7_39_interval.2
  norm_num [logCertificate_46, logCertificate_12558] at h
  linarith

def sample_9_37 : Triple := ⟨9, 37, 46, by decide, by decide, by decide, by decide⟩
theorem sample_9_37_interval :
    (logCertificate_46.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_5106.upper ≤
      discrepancy (1 / 10) sample_9_37 ∧
    discrepancy (1 / 10) sample_9_37 ≤
      (logCertificate_46.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_5106.lower := by
  have hr : radical (9 * 37 * 46) = 5106 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_9_37.a * sample_9_37.b * sample_9_37.c)) :=
    ⟨logCertificate_5106.lower, logCertificate_5106.upper,
      by simpa only [sample_9_37, hr] using logCertificate_5106.lower_le,
      by simpa only [sample_9_37, hr] using logCertificate_5106.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_9_37 logCertificate_46 support
  simpa only [support] using h

theorem sample_9_37_upper : discrepancy (1 / 10) sample_9_37 ≤ (227 / 1000) := by
  have h := sample_9_37_interval.2
  norm_num [logCertificate_46, logCertificate_5106] at h
  linarith

def sample_11_35 : Triple := ⟨11, 35, 46, by decide, by decide, by decide, by decide⟩
theorem sample_11_35_interval :
    (logCertificate_46.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_17710.upper ≤
      discrepancy (1 / 10) sample_11_35 ∧
    discrepancy (1 / 10) sample_11_35 ≤
      (logCertificate_46.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_17710.lower := by
  have hr : radical (11 * 35 * 46) = 17710 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_11_35.a * sample_11_35.b * sample_11_35.c)) :=
    ⟨logCertificate_17710.lower, logCertificate_17710.upper,
      by simpa only [sample_11_35, hr] using logCertificate_17710.lower_le,
      by simpa only [sample_11_35, hr] using logCertificate_17710.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_11_35 logCertificate_46 support
  simpa only [support] using h

theorem sample_11_35_upper : discrepancy (1 / 10) sample_11_35 ≤ (227 / 1000) := by
  have h := sample_11_35_interval.2
  norm_num [logCertificate_46, logCertificate_17710] at h
  linarith

def sample_13_33 : Triple := ⟨13, 33, 46, by decide, by decide, by decide, by decide⟩
theorem sample_13_33_interval :
    (logCertificate_46.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_19734.upper ≤
      discrepancy (1 / 10) sample_13_33 ∧
    discrepancy (1 / 10) sample_13_33 ≤
      (logCertificate_46.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_19734.lower := by
  have hr : radical (13 * 33 * 46) = 19734 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_13_33.a * sample_13_33.b * sample_13_33.c)) :=
    ⟨logCertificate_19734.lower, logCertificate_19734.upper,
      by simpa only [sample_13_33, hr] using logCertificate_19734.lower_le,
      by simpa only [sample_13_33, hr] using logCertificate_19734.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_13_33 logCertificate_46 support
  simpa only [support] using h

theorem sample_13_33_upper : discrepancy (1 / 10) sample_13_33 ≤ (227 / 1000) := by
  have h := sample_13_33_interval.2
  norm_num [logCertificate_46, logCertificate_19734] at h
  linarith

def sample_15_31 : Triple := ⟨15, 31, 46, by decide, by decide, by decide, by decide⟩
theorem sample_15_31_interval :
    (logCertificate_46.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_21390.upper ≤
      discrepancy (1 / 10) sample_15_31 ∧
    discrepancy (1 / 10) sample_15_31 ≤
      (logCertificate_46.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_21390.lower := by
  have hr : radical (15 * 31 * 46) = 21390 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_15_31.a * sample_15_31.b * sample_15_31.c)) :=
    ⟨logCertificate_21390.lower, logCertificate_21390.upper,
      by simpa only [sample_15_31, hr] using logCertificate_21390.lower_le,
      by simpa only [sample_15_31, hr] using logCertificate_21390.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_15_31 logCertificate_46 support
  simpa only [support] using h

theorem sample_15_31_upper : discrepancy (1 / 10) sample_15_31 ≤ (227 / 1000) := by
  have h := sample_15_31_interval.2
  norm_num [logCertificate_46, logCertificate_21390] at h
  linarith

def sample_17_29 : Triple := ⟨17, 29, 46, by decide, by decide, by decide, by decide⟩
theorem sample_17_29_interval :
    (logCertificate_46.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_22678.upper ≤
      discrepancy (1 / 10) sample_17_29 ∧
    discrepancy (1 / 10) sample_17_29 ≤
      (logCertificate_46.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_22678.lower := by
  have hr : radical (17 * 29 * 46) = 22678 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_17_29.a * sample_17_29.b * sample_17_29.c)) :=
    ⟨logCertificate_22678.lower, logCertificate_22678.upper,
      by simpa only [sample_17_29, hr] using logCertificate_22678.lower_le,
      by simpa only [sample_17_29, hr] using logCertificate_22678.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_17_29 logCertificate_46 support
  simpa only [support] using h

theorem sample_17_29_upper : discrepancy (1 / 10) sample_17_29 ≤ (227 / 1000) := by
  have h := sample_17_29_interval.2
  norm_num [logCertificate_46, logCertificate_22678] at h
  linarith

def sample_19_27 : Triple := ⟨19, 27, 46, by decide, by decide, by decide, by decide⟩
theorem sample_19_27_interval :
    (logCertificate_46.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_2622.upper ≤
      discrepancy (1 / 10) sample_19_27 ∧
    discrepancy (1 / 10) sample_19_27 ≤
      (logCertificate_46.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_2622.lower := by
  have hr : radical (19 * 27 * 46) = 2622 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_19_27.a * sample_19_27.b * sample_19_27.c)) :=
    ⟨logCertificate_2622.lower, logCertificate_2622.upper,
      by simpa only [sample_19_27, hr] using logCertificate_2622.lower_le,
      by simpa only [sample_19_27, hr] using logCertificate_2622.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_19_27 logCertificate_46 support
  simpa only [support] using h

theorem sample_19_27_upper : discrepancy (1 / 10) sample_19_27 ≤ (227 / 1000) := by
  have h := sample_19_27_interval.2
  norm_num [logCertificate_46, logCertificate_2622] at h
  linarith

def sample_21_25 : Triple := ⟨21, 25, 46, by decide, by decide, by decide, by decide⟩
theorem sample_21_25_interval :
    (logCertificate_46.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_4830.upper ≤
      discrepancy (1 / 10) sample_21_25 ∧
    discrepancy (1 / 10) sample_21_25 ≤
      (logCertificate_46.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_4830.lower := by
  have hr : radical (21 * 25 * 46) = 4830 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_21_25.a * sample_21_25.b * sample_21_25.c)) :=
    ⟨logCertificate_4830.lower, logCertificate_4830.upper,
      by simpa only [sample_21_25, hr] using logCertificate_4830.lower_le,
      by simpa only [sample_21_25, hr] using logCertificate_4830.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_21_25 logCertificate_46 support
  simpa only [support] using h

theorem sample_21_25_upper : discrepancy (1 / 10) sample_21_25 ≤ (227 / 1000) := by
  have h := sample_21_25_interval.2
  norm_num [logCertificate_46, logCertificate_4830] at h
  linarith

def sample_1_46 : Triple := ⟨1, 46, 47, by decide, by decide, by decide, by decide⟩
theorem sample_1_46_interval :
    (logCertificate_47.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_2162.upper ≤
      discrepancy (1 / 10) sample_1_46 ∧
    discrepancy (1 / 10) sample_1_46 ≤
      (logCertificate_47.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_2162.lower := by
  have hr : radical (1 * 46 * 47) = 2162 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_1_46.a * sample_1_46.b * sample_1_46.c)) :=
    ⟨logCertificate_2162.lower, logCertificate_2162.upper,
      by simpa only [sample_1_46, hr] using logCertificate_2162.lower_le,
      by simpa only [sample_1_46, hr] using logCertificate_2162.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_1_46 logCertificate_47 support
  simpa only [support] using h

theorem sample_1_46_upper : discrepancy (1 / 10) sample_1_46 ≤ (227 / 1000) := by
  have h := sample_1_46_interval.2
  norm_num [logCertificate_47, logCertificate_2162] at h
  linarith

def sample_2_45 : Triple := ⟨2, 45, 47, by decide, by decide, by decide, by decide⟩
theorem sample_2_45_interval :
    (logCertificate_47.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1410.upper ≤
      discrepancy (1 / 10) sample_2_45 ∧
    discrepancy (1 / 10) sample_2_45 ≤
      (logCertificate_47.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1410.lower := by
  have hr : radical (2 * 45 * 47) = 1410 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_2_45.a * sample_2_45.b * sample_2_45.c)) :=
    ⟨logCertificate_1410.lower, logCertificate_1410.upper,
      by simpa only [sample_2_45, hr] using logCertificate_1410.lower_le,
      by simpa only [sample_2_45, hr] using logCertificate_1410.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_2_45 logCertificate_47 support
  simpa only [support] using h

theorem sample_2_45_upper : discrepancy (1 / 10) sample_2_45 ≤ (227 / 1000) := by
  have h := sample_2_45_interval.2
  norm_num [logCertificate_47, logCertificate_1410] at h
  linarith

def sample_3_44 : Triple := ⟨3, 44, 47, by decide, by decide, by decide, by decide⟩
theorem sample_3_44_interval :
    (logCertificate_47.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_3102.upper ≤
      discrepancy (1 / 10) sample_3_44 ∧
    discrepancy (1 / 10) sample_3_44 ≤
      (logCertificate_47.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_3102.lower := by
  have hr : radical (3 * 44 * 47) = 3102 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_3_44.a * sample_3_44.b * sample_3_44.c)) :=
    ⟨logCertificate_3102.lower, logCertificate_3102.upper,
      by simpa only [sample_3_44, hr] using logCertificate_3102.lower_le,
      by simpa only [sample_3_44, hr] using logCertificate_3102.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_3_44 logCertificate_47 support
  simpa only [support] using h

theorem sample_3_44_upper : discrepancy (1 / 10) sample_3_44 ≤ (227 / 1000) := by
  have h := sample_3_44_interval.2
  norm_num [logCertificate_47, logCertificate_3102] at h
  linarith

def sample_4_43 : Triple := ⟨4, 43, 47, by decide, by decide, by decide, by decide⟩
theorem sample_4_43_interval :
    (logCertificate_47.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_4042.upper ≤
      discrepancy (1 / 10) sample_4_43 ∧
    discrepancy (1 / 10) sample_4_43 ≤
      (logCertificate_47.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_4042.lower := by
  have hr : radical (4 * 43 * 47) = 4042 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_4_43.a * sample_4_43.b * sample_4_43.c)) :=
    ⟨logCertificate_4042.lower, logCertificate_4042.upper,
      by simpa only [sample_4_43, hr] using logCertificate_4042.lower_le,
      by simpa only [sample_4_43, hr] using logCertificate_4042.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_4_43 logCertificate_47 support
  simpa only [support] using h

theorem sample_4_43_upper : discrepancy (1 / 10) sample_4_43 ≤ (227 / 1000) := by
  have h := sample_4_43_interval.2
  norm_num [logCertificate_47, logCertificate_4042] at h
  linarith

def sample_5_42 : Triple := ⟨5, 42, 47, by decide, by decide, by decide, by decide⟩
theorem sample_5_42_interval :
    (logCertificate_47.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_9870.upper ≤
      discrepancy (1 / 10) sample_5_42 ∧
    discrepancy (1 / 10) sample_5_42 ≤
      (logCertificate_47.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_9870.lower := by
  have hr : radical (5 * 42 * 47) = 9870 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_5_42.a * sample_5_42.b * sample_5_42.c)) :=
    ⟨logCertificate_9870.lower, logCertificate_9870.upper,
      by simpa only [sample_5_42, hr] using logCertificate_9870.lower_le,
      by simpa only [sample_5_42, hr] using logCertificate_9870.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_5_42 logCertificate_47 support
  simpa only [support] using h

theorem sample_5_42_upper : discrepancy (1 / 10) sample_5_42 ≤ (227 / 1000) := by
  have h := sample_5_42_interval.2
  norm_num [logCertificate_47, logCertificate_9870] at h
  linarith

def sample_6_41 : Triple := ⟨6, 41, 47, by decide, by decide, by decide, by decide⟩
theorem sample_6_41_interval :
    (logCertificate_47.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_11562.upper ≤
      discrepancy (1 / 10) sample_6_41 ∧
    discrepancy (1 / 10) sample_6_41 ≤
      (logCertificate_47.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_11562.lower := by
  have hr : radical (6 * 41 * 47) = 11562 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_6_41.a * sample_6_41.b * sample_6_41.c)) :=
    ⟨logCertificate_11562.lower, logCertificate_11562.upper,
      by simpa only [sample_6_41, hr] using logCertificate_11562.lower_le,
      by simpa only [sample_6_41, hr] using logCertificate_11562.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_6_41 logCertificate_47 support
  simpa only [support] using h

theorem sample_6_41_upper : discrepancy (1 / 10) sample_6_41 ≤ (227 / 1000) := by
  have h := sample_6_41_interval.2
  norm_num [logCertificate_47, logCertificate_11562] at h
  linarith

def sample_7_40 : Triple := ⟨7, 40, 47, by decide, by decide, by decide, by decide⟩
theorem sample_7_40_interval :
    (logCertificate_47.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_3290.upper ≤
      discrepancy (1 / 10) sample_7_40 ∧
    discrepancy (1 / 10) sample_7_40 ≤
      (logCertificate_47.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_3290.lower := by
  have hr : radical (7 * 40 * 47) = 3290 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_7_40.a * sample_7_40.b * sample_7_40.c)) :=
    ⟨logCertificate_3290.lower, logCertificate_3290.upper,
      by simpa only [sample_7_40, hr] using logCertificate_3290.lower_le,
      by simpa only [sample_7_40, hr] using logCertificate_3290.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_7_40 logCertificate_47 support
  simpa only [support] using h

theorem sample_7_40_upper : discrepancy (1 / 10) sample_7_40 ≤ (227 / 1000) := by
  have h := sample_7_40_interval.2
  norm_num [logCertificate_47, logCertificate_3290] at h
  linarith

def sample_8_39 : Triple := ⟨8, 39, 47, by decide, by decide, by decide, by decide⟩
theorem sample_8_39_interval :
    (logCertificate_47.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_3666.upper ≤
      discrepancy (1 / 10) sample_8_39 ∧
    discrepancy (1 / 10) sample_8_39 ≤
      (logCertificate_47.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_3666.lower := by
  have hr : radical (8 * 39 * 47) = 3666 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_8_39.a * sample_8_39.b * sample_8_39.c)) :=
    ⟨logCertificate_3666.lower, logCertificate_3666.upper,
      by simpa only [sample_8_39, hr] using logCertificate_3666.lower_le,
      by simpa only [sample_8_39, hr] using logCertificate_3666.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_8_39 logCertificate_47 support
  simpa only [support] using h

theorem sample_8_39_upper : discrepancy (1 / 10) sample_8_39 ≤ (227 / 1000) := by
  have h := sample_8_39_interval.2
  norm_num [logCertificate_47, logCertificate_3666] at h
  linarith

def sample_9_38 : Triple := ⟨9, 38, 47, by decide, by decide, by decide, by decide⟩
theorem sample_9_38_interval :
    (logCertificate_47.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_5358.upper ≤
      discrepancy (1 / 10) sample_9_38 ∧
    discrepancy (1 / 10) sample_9_38 ≤
      (logCertificate_47.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_5358.lower := by
  have hr : radical (9 * 38 * 47) = 5358 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_9_38.a * sample_9_38.b * sample_9_38.c)) :=
    ⟨logCertificate_5358.lower, logCertificate_5358.upper,
      by simpa only [sample_9_38, hr] using logCertificate_5358.lower_le,
      by simpa only [sample_9_38, hr] using logCertificate_5358.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_9_38 logCertificate_47 support
  simpa only [support] using h

theorem sample_9_38_upper : discrepancy (1 / 10) sample_9_38 ≤ (227 / 1000) := by
  have h := sample_9_38_interval.2
  norm_num [logCertificate_47, logCertificate_5358] at h
  linarith

def sample_10_37 : Triple := ⟨10, 37, 47, by decide, by decide, by decide, by decide⟩
theorem sample_10_37_interval :
    (logCertificate_47.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_17390.upper ≤
      discrepancy (1 / 10) sample_10_37 ∧
    discrepancy (1 / 10) sample_10_37 ≤
      (logCertificate_47.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_17390.lower := by
  have hr : radical (10 * 37 * 47) = 17390 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_10_37.a * sample_10_37.b * sample_10_37.c)) :=
    ⟨logCertificate_17390.lower, logCertificate_17390.upper,
      by simpa only [sample_10_37, hr] using logCertificate_17390.lower_le,
      by simpa only [sample_10_37, hr] using logCertificate_17390.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_10_37 logCertificate_47 support
  simpa only [support] using h

theorem sample_10_37_upper : discrepancy (1 / 10) sample_10_37 ≤ (227 / 1000) := by
  have h := sample_10_37_interval.2
  norm_num [logCertificate_47, logCertificate_17390] at h
  linarith

def sample_11_36 : Triple := ⟨11, 36, 47, by decide, by decide, by decide, by decide⟩
theorem sample_11_36_interval :
    (logCertificate_47.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_3102.upper ≤
      discrepancy (1 / 10) sample_11_36 ∧
    discrepancy (1 / 10) sample_11_36 ≤
      (logCertificate_47.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_3102.lower := by
  have hr : radical (11 * 36 * 47) = 3102 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_11_36.a * sample_11_36.b * sample_11_36.c)) :=
    ⟨logCertificate_3102.lower, logCertificate_3102.upper,
      by simpa only [sample_11_36, hr] using logCertificate_3102.lower_le,
      by simpa only [sample_11_36, hr] using logCertificate_3102.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_11_36 logCertificate_47 support
  simpa only [support] using h

theorem sample_11_36_upper : discrepancy (1 / 10) sample_11_36 ≤ (227 / 1000) := by
  have h := sample_11_36_interval.2
  norm_num [logCertificate_47, logCertificate_3102] at h
  linarith

def sample_12_35 : Triple := ⟨12, 35, 47, by decide, by decide, by decide, by decide⟩
theorem sample_12_35_interval :
    (logCertificate_47.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_9870.upper ≤
      discrepancy (1 / 10) sample_12_35 ∧
    discrepancy (1 / 10) sample_12_35 ≤
      (logCertificate_47.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_9870.lower := by
  have hr : radical (12 * 35 * 47) = 9870 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_12_35.a * sample_12_35.b * sample_12_35.c)) :=
    ⟨logCertificate_9870.lower, logCertificate_9870.upper,
      by simpa only [sample_12_35, hr] using logCertificate_9870.lower_le,
      by simpa only [sample_12_35, hr] using logCertificate_9870.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_12_35 logCertificate_47 support
  simpa only [support] using h

theorem sample_12_35_upper : discrepancy (1 / 10) sample_12_35 ≤ (227 / 1000) := by
  have h := sample_12_35_interval.2
  norm_num [logCertificate_47, logCertificate_9870] at h
  linarith

def sample_13_34 : Triple := ⟨13, 34, 47, by decide, by decide, by decide, by decide⟩
theorem sample_13_34_interval :
    (logCertificate_47.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_20774.upper ≤
      discrepancy (1 / 10) sample_13_34 ∧
    discrepancy (1 / 10) sample_13_34 ≤
      (logCertificate_47.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_20774.lower := by
  have hr : radical (13 * 34 * 47) = 20774 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_13_34.a * sample_13_34.b * sample_13_34.c)) :=
    ⟨logCertificate_20774.lower, logCertificate_20774.upper,
      by simpa only [sample_13_34, hr] using logCertificate_20774.lower_le,
      by simpa only [sample_13_34, hr] using logCertificate_20774.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_13_34 logCertificate_47 support
  simpa only [support] using h

theorem sample_13_34_upper : discrepancy (1 / 10) sample_13_34 ≤ (227 / 1000) := by
  have h := sample_13_34_interval.2
  norm_num [logCertificate_47, logCertificate_20774] at h
  linarith

def sample_14_33 : Triple := ⟨14, 33, 47, by decide, by decide, by decide, by decide⟩
theorem sample_14_33_interval :
    (logCertificate_47.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_21714.upper ≤
      discrepancy (1 / 10) sample_14_33 ∧
    discrepancy (1 / 10) sample_14_33 ≤
      (logCertificate_47.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_21714.lower := by
  have hr : radical (14 * 33 * 47) = 21714 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_14_33.a * sample_14_33.b * sample_14_33.c)) :=
    ⟨logCertificate_21714.lower, logCertificate_21714.upper,
      by simpa only [sample_14_33, hr] using logCertificate_21714.lower_le,
      by simpa only [sample_14_33, hr] using logCertificate_21714.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_14_33 logCertificate_47 support
  simpa only [support] using h

theorem sample_14_33_upper : discrepancy (1 / 10) sample_14_33 ≤ (227 / 1000) := by
  have h := sample_14_33_interval.2
  norm_num [logCertificate_47, logCertificate_21714] at h
  linarith

def sample_15_32 : Triple := ⟨15, 32, 47, by decide, by decide, by decide, by decide⟩
theorem sample_15_32_interval :
    (logCertificate_47.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1410.upper ≤
      discrepancy (1 / 10) sample_15_32 ∧
    discrepancy (1 / 10) sample_15_32 ≤
      (logCertificate_47.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1410.lower := by
  have hr : radical (15 * 32 * 47) = 1410 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_15_32.a * sample_15_32.b * sample_15_32.c)) :=
    ⟨logCertificate_1410.lower, logCertificate_1410.upper,
      by simpa only [sample_15_32, hr] using logCertificate_1410.lower_le,
      by simpa only [sample_15_32, hr] using logCertificate_1410.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_15_32 logCertificate_47 support
  simpa only [support] using h

theorem sample_15_32_upper : discrepancy (1 / 10) sample_15_32 ≤ (227 / 1000) := by
  have h := sample_15_32_interval.2
  norm_num [logCertificate_47, logCertificate_1410] at h
  linarith

def sample_16_31 : Triple := ⟨16, 31, 47, by decide, by decide, by decide, by decide⟩
theorem sample_16_31_interval :
    (logCertificate_47.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_2914.upper ≤
      discrepancy (1 / 10) sample_16_31 ∧
    discrepancy (1 / 10) sample_16_31 ≤
      (logCertificate_47.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_2914.lower := by
  have hr : radical (16 * 31 * 47) = 2914 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_16_31.a * sample_16_31.b * sample_16_31.c)) :=
    ⟨logCertificate_2914.lower, logCertificate_2914.upper,
      by simpa only [sample_16_31, hr] using logCertificate_2914.lower_le,
      by simpa only [sample_16_31, hr] using logCertificate_2914.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_16_31 logCertificate_47 support
  simpa only [support] using h

theorem sample_16_31_upper : discrepancy (1 / 10) sample_16_31 ≤ (227 / 1000) := by
  have h := sample_16_31_interval.2
  norm_num [logCertificate_47, logCertificate_2914] at h
  linarith

def sample_17_30 : Triple := ⟨17, 30, 47, by decide, by decide, by decide, by decide⟩
theorem sample_17_30_interval :
    (logCertificate_47.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_23970.upper ≤
      discrepancy (1 / 10) sample_17_30 ∧
    discrepancy (1 / 10) sample_17_30 ≤
      (logCertificate_47.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_23970.lower := by
  have hr : radical (17 * 30 * 47) = 23970 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_17_30.a * sample_17_30.b * sample_17_30.c)) :=
    ⟨logCertificate_23970.lower, logCertificate_23970.upper,
      by simpa only [sample_17_30, hr] using logCertificate_23970.lower_le,
      by simpa only [sample_17_30, hr] using logCertificate_23970.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_17_30 logCertificate_47 support
  simpa only [support] using h

theorem sample_17_30_upper : discrepancy (1 / 10) sample_17_30 ≤ (227 / 1000) := by
  have h := sample_17_30_interval.2
  norm_num [logCertificate_47, logCertificate_23970] at h
  linarith

def sample_18_29 : Triple := ⟨18, 29, 47, by decide, by decide, by decide, by decide⟩
theorem sample_18_29_interval :
    (logCertificate_47.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_8178.upper ≤
      discrepancy (1 / 10) sample_18_29 ∧
    discrepancy (1 / 10) sample_18_29 ≤
      (logCertificate_47.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_8178.lower := by
  have hr : radical (18 * 29 * 47) = 8178 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_18_29.a * sample_18_29.b * sample_18_29.c)) :=
    ⟨logCertificate_8178.lower, logCertificate_8178.upper,
      by simpa only [sample_18_29, hr] using logCertificate_8178.lower_le,
      by simpa only [sample_18_29, hr] using logCertificate_8178.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_18_29 logCertificate_47 support
  simpa only [support] using h

theorem sample_18_29_upper : discrepancy (1 / 10) sample_18_29 ≤ (227 / 1000) := by
  have h := sample_18_29_interval.2
  norm_num [logCertificate_47, logCertificate_8178] at h
  linarith

def sample_19_28 : Triple := ⟨19, 28, 47, by decide, by decide, by decide, by decide⟩
theorem sample_19_28_interval :
    (logCertificate_47.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_12502.upper ≤
      discrepancy (1 / 10) sample_19_28 ∧
    discrepancy (1 / 10) sample_19_28 ≤
      (logCertificate_47.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_12502.lower := by
  have hr : radical (19 * 28 * 47) = 12502 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_19_28.a * sample_19_28.b * sample_19_28.c)) :=
    ⟨logCertificate_12502.lower, logCertificate_12502.upper,
      by simpa only [sample_19_28, hr] using logCertificate_12502.lower_le,
      by simpa only [sample_19_28, hr] using logCertificate_12502.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_19_28 logCertificate_47 support
  simpa only [support] using h

theorem sample_19_28_upper : discrepancy (1 / 10) sample_19_28 ≤ (227 / 1000) := by
  have h := sample_19_28_interval.2
  norm_num [logCertificate_47, logCertificate_12502] at h
  linarith

def sample_20_27 : Triple := ⟨20, 27, 47, by decide, by decide, by decide, by decide⟩
theorem sample_20_27_interval :
    (logCertificate_47.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1410.upper ≤
      discrepancy (1 / 10) sample_20_27 ∧
    discrepancy (1 / 10) sample_20_27 ≤
      (logCertificate_47.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1410.lower := by
  have hr : radical (20 * 27 * 47) = 1410 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_20_27.a * sample_20_27.b * sample_20_27.c)) :=
    ⟨logCertificate_1410.lower, logCertificate_1410.upper,
      by simpa only [sample_20_27, hr] using logCertificate_1410.lower_le,
      by simpa only [sample_20_27, hr] using logCertificate_1410.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_20_27 logCertificate_47 support
  simpa only [support] using h

theorem sample_20_27_upper : discrepancy (1 / 10) sample_20_27 ≤ (227 / 1000) := by
  have h := sample_20_27_interval.2
  norm_num [logCertificate_47, logCertificate_1410] at h
  linarith

def sample_21_26 : Triple := ⟨21, 26, 47, by decide, by decide, by decide, by decide⟩
theorem sample_21_26_interval :
    (logCertificate_47.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_25662.upper ≤
      discrepancy (1 / 10) sample_21_26 ∧
    discrepancy (1 / 10) sample_21_26 ≤
      (logCertificate_47.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_25662.lower := by
  have hr : radical (21 * 26 * 47) = 25662 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_21_26.a * sample_21_26.b * sample_21_26.c)) :=
    ⟨logCertificate_25662.lower, logCertificate_25662.upper,
      by simpa only [sample_21_26, hr] using logCertificate_25662.lower_le,
      by simpa only [sample_21_26, hr] using logCertificate_25662.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_21_26 logCertificate_47 support
  simpa only [support] using h

theorem sample_21_26_upper : discrepancy (1 / 10) sample_21_26 ≤ (227 / 1000) := by
  have h := sample_21_26_interval.2
  norm_num [logCertificate_47, logCertificate_25662] at h
  linarith

def sample_22_25 : Triple := ⟨22, 25, 47, by decide, by decide, by decide, by decide⟩
theorem sample_22_25_interval :
    (logCertificate_47.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_5170.upper ≤
      discrepancy (1 / 10) sample_22_25 ∧
    discrepancy (1 / 10) sample_22_25 ≤
      (logCertificate_47.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_5170.lower := by
  have hr : radical (22 * 25 * 47) = 5170 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_22_25.a * sample_22_25.b * sample_22_25.c)) :=
    ⟨logCertificate_5170.lower, logCertificate_5170.upper,
      by simpa only [sample_22_25, hr] using logCertificate_5170.lower_le,
      by simpa only [sample_22_25, hr] using logCertificate_5170.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_22_25 logCertificate_47 support
  simpa only [support] using h

theorem sample_22_25_upper : discrepancy (1 / 10) sample_22_25 ≤ (227 / 1000) := by
  have h := sample_22_25_interval.2
  norm_num [logCertificate_47, logCertificate_5170] at h
  linarith

def sample_23_24 : Triple := ⟨23, 24, 47, by decide, by decide, by decide, by decide⟩
theorem sample_23_24_interval :
    (logCertificate_47.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_6486.upper ≤
      discrepancy (1 / 10) sample_23_24 ∧
    discrepancy (1 / 10) sample_23_24 ≤
      (logCertificate_47.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_6486.lower := by
  have hr : radical (23 * 24 * 47) = 6486 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_23_24.a * sample_23_24.b * sample_23_24.c)) :=
    ⟨logCertificate_6486.lower, logCertificate_6486.upper,
      by simpa only [sample_23_24, hr] using logCertificate_6486.lower_le,
      by simpa only [sample_23_24, hr] using logCertificate_6486.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_23_24 logCertificate_47 support
  simpa only [support] using h

theorem sample_23_24_upper : discrepancy (1 / 10) sample_23_24 ≤ (227 / 1000) := by
  have h := sample_23_24_interval.2
  norm_num [logCertificate_47, logCertificate_6486] at h
  linarith

def sample_1_47 : Triple := ⟨1, 47, 48, by decide, by decide, by decide, by decide⟩
theorem sample_1_47_interval :
    (logCertificate_48.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_282.upper ≤
      discrepancy (1 / 10) sample_1_47 ∧
    discrepancy (1 / 10) sample_1_47 ≤
      (logCertificate_48.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_282.lower := by
  have hr : radical (1 * 47 * 48) = 282 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_1_47.a * sample_1_47.b * sample_1_47.c)) :=
    ⟨logCertificate_282.lower, logCertificate_282.upper,
      by simpa only [sample_1_47, hr] using logCertificate_282.lower_le,
      by simpa only [sample_1_47, hr] using logCertificate_282.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_1_47 logCertificate_48 support
  simpa only [support] using h

theorem sample_1_47_upper : discrepancy (1 / 10) sample_1_47 ≤ (227 / 1000) := by
  have h := sample_1_47_interval.2
  norm_num [logCertificate_48, logCertificate_282] at h
  linarith

def sample_5_43 : Triple := ⟨5, 43, 48, by decide, by decide, by decide, by decide⟩
theorem sample_5_43_interval :
    (logCertificate_48.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1290.upper ≤
      discrepancy (1 / 10) sample_5_43 ∧
    discrepancy (1 / 10) sample_5_43 ≤
      (logCertificate_48.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1290.lower := by
  have hr : radical (5 * 43 * 48) = 1290 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_5_43.a * sample_5_43.b * sample_5_43.c)) :=
    ⟨logCertificate_1290.lower, logCertificate_1290.upper,
      by simpa only [sample_5_43, hr] using logCertificate_1290.lower_le,
      by simpa only [sample_5_43, hr] using logCertificate_1290.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_5_43 logCertificate_48 support
  simpa only [support] using h

theorem sample_5_43_upper : discrepancy (1 / 10) sample_5_43 ≤ (227 / 1000) := by
  have h := sample_5_43_interval.2
  norm_num [logCertificate_48, logCertificate_1290] at h
  linarith

def sample_7_41 : Triple := ⟨7, 41, 48, by decide, by decide, by decide, by decide⟩
theorem sample_7_41_interval :
    (logCertificate_48.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1722.upper ≤
      discrepancy (1 / 10) sample_7_41 ∧
    discrepancy (1 / 10) sample_7_41 ≤
      (logCertificate_48.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1722.lower := by
  have hr : radical (7 * 41 * 48) = 1722 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_7_41.a * sample_7_41.b * sample_7_41.c)) :=
    ⟨logCertificate_1722.lower, logCertificate_1722.upper,
      by simpa only [sample_7_41, hr] using logCertificate_1722.lower_le,
      by simpa only [sample_7_41, hr] using logCertificate_1722.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_7_41 logCertificate_48 support
  simpa only [support] using h

theorem sample_7_41_upper : discrepancy (1 / 10) sample_7_41 ≤ (227 / 1000) := by
  have h := sample_7_41_interval.2
  norm_num [logCertificate_48, logCertificate_1722] at h
  linarith

def sample_11_37 : Triple := ⟨11, 37, 48, by decide, by decide, by decide, by decide⟩
theorem sample_11_37_interval :
    (logCertificate_48.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_2442.upper ≤
      discrepancy (1 / 10) sample_11_37 ∧
    discrepancy (1 / 10) sample_11_37 ≤
      (logCertificate_48.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_2442.lower := by
  have hr : radical (11 * 37 * 48) = 2442 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_11_37.a * sample_11_37.b * sample_11_37.c)) :=
    ⟨logCertificate_2442.lower, logCertificate_2442.upper,
      by simpa only [sample_11_37, hr] using logCertificate_2442.lower_le,
      by simpa only [sample_11_37, hr] using logCertificate_2442.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_11_37 logCertificate_48 support
  simpa only [support] using h

theorem sample_11_37_upper : discrepancy (1 / 10) sample_11_37 ≤ (227 / 1000) := by
  have h := sample_11_37_interval.2
  norm_num [logCertificate_48, logCertificate_2442] at h
  linarith

def sample_13_35 : Triple := ⟨13, 35, 48, by decide, by decide, by decide, by decide⟩
theorem sample_13_35_interval :
    (logCertificate_48.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_2730.upper ≤
      discrepancy (1 / 10) sample_13_35 ∧
    discrepancy (1 / 10) sample_13_35 ≤
      (logCertificate_48.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_2730.lower := by
  have hr : radical (13 * 35 * 48) = 2730 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_13_35.a * sample_13_35.b * sample_13_35.c)) :=
    ⟨logCertificate_2730.lower, logCertificate_2730.upper,
      by simpa only [sample_13_35, hr] using logCertificate_2730.lower_le,
      by simpa only [sample_13_35, hr] using logCertificate_2730.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_13_35 logCertificate_48 support
  simpa only [support] using h

theorem sample_13_35_upper : discrepancy (1 / 10) sample_13_35 ≤ (227 / 1000) := by
  have h := sample_13_35_interval.2
  norm_num [logCertificate_48, logCertificate_2730] at h
  linarith

def sample_17_31 : Triple := ⟨17, 31, 48, by decide, by decide, by decide, by decide⟩
theorem sample_17_31_interval :
    (logCertificate_48.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_3162.upper ≤
      discrepancy (1 / 10) sample_17_31 ∧
    discrepancy (1 / 10) sample_17_31 ≤
      (logCertificate_48.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_3162.lower := by
  have hr : radical (17 * 31 * 48) = 3162 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_17_31.a * sample_17_31.b * sample_17_31.c)) :=
    ⟨logCertificate_3162.lower, logCertificate_3162.upper,
      by simpa only [sample_17_31, hr] using logCertificate_3162.lower_le,
      by simpa only [sample_17_31, hr] using logCertificate_3162.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_17_31 logCertificate_48 support
  simpa only [support] using h

theorem sample_17_31_upper : discrepancy (1 / 10) sample_17_31 ≤ (227 / 1000) := by
  have h := sample_17_31_interval.2
  norm_num [logCertificate_48, logCertificate_3162] at h
  linarith

def sample_19_29 : Triple := ⟨19, 29, 48, by decide, by decide, by decide, by decide⟩
theorem sample_19_29_interval :
    (logCertificate_48.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_3306.upper ≤
      discrepancy (1 / 10) sample_19_29 ∧
    discrepancy (1 / 10) sample_19_29 ≤
      (logCertificate_48.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_3306.lower := by
  have hr : radical (19 * 29 * 48) = 3306 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_19_29.a * sample_19_29.b * sample_19_29.c)) :=
    ⟨logCertificate_3306.lower, logCertificate_3306.upper,
      by simpa only [sample_19_29, hr] using logCertificate_3306.lower_le,
      by simpa only [sample_19_29, hr] using logCertificate_3306.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_19_29 logCertificate_48 support
  simpa only [support] using h

theorem sample_19_29_upper : discrepancy (1 / 10) sample_19_29 ≤ (227 / 1000) := by
  have h := sample_19_29_interval.2
  norm_num [logCertificate_48, logCertificate_3306] at h
  linarith

def sample_23_25 : Triple := ⟨23, 25, 48, by decide, by decide, by decide, by decide⟩
theorem sample_23_25_interval :
    (logCertificate_48.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_690.upper ≤
      discrepancy (1 / 10) sample_23_25 ∧
    discrepancy (1 / 10) sample_23_25 ≤
      (logCertificate_48.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_690.lower := by
  have hr : radical (23 * 25 * 48) = 690 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_23_25.a * sample_23_25.b * sample_23_25.c)) :=
    ⟨logCertificate_690.lower, logCertificate_690.upper,
      by simpa only [sample_23_25, hr] using logCertificate_690.lower_le,
      by simpa only [sample_23_25, hr] using logCertificate_690.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_23_25 logCertificate_48 support
  simpa only [support] using h

theorem sample_23_25_upper : discrepancy (1 / 10) sample_23_25 ≤ (227 / 1000) := by
  have h := sample_23_25_interval.2
  norm_num [logCertificate_48, logCertificate_690] at h
  linarith

def sample_1_48 : Triple := ⟨1, 48, 49, by decide, by decide, by decide, by decide⟩
theorem sample_1_48_interval :
    (logCertificate_49.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_42.upper ≤
      discrepancy (1 / 10) sample_1_48 ∧
    discrepancy (1 / 10) sample_1_48 ≤
      (logCertificate_49.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_42.lower := by
  have hr : radical (1 * 48 * 49) = 42 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_1_48.a * sample_1_48.b * sample_1_48.c)) :=
    ⟨logCertificate_42.lower, logCertificate_42.upper,
      by simpa only [sample_1_48, hr] using logCertificate_42.lower_le,
      by simpa only [sample_1_48, hr] using logCertificate_42.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_1_48 logCertificate_49 support
  simpa only [support] using h

theorem sample_1_48_upper : discrepancy (1 / 10) sample_1_48 ≤ (227 / 1000) := by
  have h := sample_1_48_interval.2
  norm_num [logCertificate_49, logCertificate_42] at h
  linarith

def sample_2_47 : Triple := ⟨2, 47, 49, by decide, by decide, by decide, by decide⟩
theorem sample_2_47_interval :
    (logCertificate_49.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_658.upper ≤
      discrepancy (1 / 10) sample_2_47 ∧
    discrepancy (1 / 10) sample_2_47 ≤
      (logCertificate_49.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_658.lower := by
  have hr : radical (2 * 47 * 49) = 658 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_2_47.a * sample_2_47.b * sample_2_47.c)) :=
    ⟨logCertificate_658.lower, logCertificate_658.upper,
      by simpa only [sample_2_47, hr] using logCertificate_658.lower_le,
      by simpa only [sample_2_47, hr] using logCertificate_658.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_2_47 logCertificate_49 support
  simpa only [support] using h

theorem sample_2_47_upper : discrepancy (1 / 10) sample_2_47 ≤ (227 / 1000) := by
  have h := sample_2_47_interval.2
  norm_num [logCertificate_49, logCertificate_658] at h
  linarith

def sample_3_46 : Triple := ⟨3, 46, 49, by decide, by decide, by decide, by decide⟩
theorem sample_3_46_interval :
    (logCertificate_49.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_966.upper ≤
      discrepancy (1 / 10) sample_3_46 ∧
    discrepancy (1 / 10) sample_3_46 ≤
      (logCertificate_49.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_966.lower := by
  have hr : radical (3 * 46 * 49) = 966 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_3_46.a * sample_3_46.b * sample_3_46.c)) :=
    ⟨logCertificate_966.lower, logCertificate_966.upper,
      by simpa only [sample_3_46, hr] using logCertificate_966.lower_le,
      by simpa only [sample_3_46, hr] using logCertificate_966.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_3_46 logCertificate_49 support
  simpa only [support] using h

theorem sample_3_46_upper : discrepancy (1 / 10) sample_3_46 ≤ (227 / 1000) := by
  have h := sample_3_46_interval.2
  norm_num [logCertificate_49, logCertificate_966] at h
  linarith

def sample_4_45 : Triple := ⟨4, 45, 49, by decide, by decide, by decide, by decide⟩
theorem sample_4_45_interval :
    (logCertificate_49.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_210.upper ≤
      discrepancy (1 / 10) sample_4_45 ∧
    discrepancy (1 / 10) sample_4_45 ≤
      (logCertificate_49.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_210.lower := by
  have hr : radical (4 * 45 * 49) = 210 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_4_45.a * sample_4_45.b * sample_4_45.c)) :=
    ⟨logCertificate_210.lower, logCertificate_210.upper,
      by simpa only [sample_4_45, hr] using logCertificate_210.lower_le,
      by simpa only [sample_4_45, hr] using logCertificate_210.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_4_45 logCertificate_49 support
  simpa only [support] using h

theorem sample_4_45_upper : discrepancy (1 / 10) sample_4_45 ≤ (227 / 1000) := by
  have h := sample_4_45_interval.2
  norm_num [logCertificate_49, logCertificate_210] at h
  linarith

def sample_5_44 : Triple := ⟨5, 44, 49, by decide, by decide, by decide, by decide⟩
theorem sample_5_44_interval :
    (logCertificate_49.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_770.upper ≤
      discrepancy (1 / 10) sample_5_44 ∧
    discrepancy (1 / 10) sample_5_44 ≤
      (logCertificate_49.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_770.lower := by
  have hr : radical (5 * 44 * 49) = 770 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_5_44.a * sample_5_44.b * sample_5_44.c)) :=
    ⟨logCertificate_770.lower, logCertificate_770.upper,
      by simpa only [sample_5_44, hr] using logCertificate_770.lower_le,
      by simpa only [sample_5_44, hr] using logCertificate_770.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_5_44 logCertificate_49 support
  simpa only [support] using h

theorem sample_5_44_upper : discrepancy (1 / 10) sample_5_44 ≤ (227 / 1000) := by
  have h := sample_5_44_interval.2
  norm_num [logCertificate_49, logCertificate_770] at h
  linarith

def sample_6_43 : Triple := ⟨6, 43, 49, by decide, by decide, by decide, by decide⟩
theorem sample_6_43_interval :
    (logCertificate_49.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1806.upper ≤
      discrepancy (1 / 10) sample_6_43 ∧
    discrepancy (1 / 10) sample_6_43 ≤
      (logCertificate_49.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1806.lower := by
  have hr : radical (6 * 43 * 49) = 1806 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_6_43.a * sample_6_43.b * sample_6_43.c)) :=
    ⟨logCertificate_1806.lower, logCertificate_1806.upper,
      by simpa only [sample_6_43, hr] using logCertificate_1806.lower_le,
      by simpa only [sample_6_43, hr] using logCertificate_1806.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_6_43 logCertificate_49 support
  simpa only [support] using h

theorem sample_6_43_upper : discrepancy (1 / 10) sample_6_43 ≤ (227 / 1000) := by
  have h := sample_6_43_interval.2
  norm_num [logCertificate_49, logCertificate_1806] at h
  linarith

def sample_8_41 : Triple := ⟨8, 41, 49, by decide, by decide, by decide, by decide⟩
theorem sample_8_41_interval :
    (logCertificate_49.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_574.upper ≤
      discrepancy (1 / 10) sample_8_41 ∧
    discrepancy (1 / 10) sample_8_41 ≤
      (logCertificate_49.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_574.lower := by
  have hr : radical (8 * 41 * 49) = 574 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_8_41.a * sample_8_41.b * sample_8_41.c)) :=
    ⟨logCertificate_574.lower, logCertificate_574.upper,
      by simpa only [sample_8_41, hr] using logCertificate_574.lower_le,
      by simpa only [sample_8_41, hr] using logCertificate_574.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_8_41 logCertificate_49 support
  simpa only [support] using h

theorem sample_8_41_upper : discrepancy (1 / 10) sample_8_41 ≤ (227 / 1000) := by
  have h := sample_8_41_interval.2
  norm_num [logCertificate_49, logCertificate_574] at h
  linarith

def sample_9_40 : Triple := ⟨9, 40, 49, by decide, by decide, by decide, by decide⟩
theorem sample_9_40_interval :
    (logCertificate_49.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_210.upper ≤
      discrepancy (1 / 10) sample_9_40 ∧
    discrepancy (1 / 10) sample_9_40 ≤
      (logCertificate_49.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_210.lower := by
  have hr : radical (9 * 40 * 49) = 210 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_9_40.a * sample_9_40.b * sample_9_40.c)) :=
    ⟨logCertificate_210.lower, logCertificate_210.upper,
      by simpa only [sample_9_40, hr] using logCertificate_210.lower_le,
      by simpa only [sample_9_40, hr] using logCertificate_210.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_9_40 logCertificate_49 support
  simpa only [support] using h

theorem sample_9_40_upper : discrepancy (1 / 10) sample_9_40 ≤ (227 / 1000) := by
  have h := sample_9_40_interval.2
  norm_num [logCertificate_49, logCertificate_210] at h
  linarith

def sample_10_39 : Triple := ⟨10, 39, 49, by decide, by decide, by decide, by decide⟩
theorem sample_10_39_interval :
    (logCertificate_49.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_2730.upper ≤
      discrepancy (1 / 10) sample_10_39 ∧
    discrepancy (1 / 10) sample_10_39 ≤
      (logCertificate_49.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_2730.lower := by
  have hr : radical (10 * 39 * 49) = 2730 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_10_39.a * sample_10_39.b * sample_10_39.c)) :=
    ⟨logCertificate_2730.lower, logCertificate_2730.upper,
      by simpa only [sample_10_39, hr] using logCertificate_2730.lower_le,
      by simpa only [sample_10_39, hr] using logCertificate_2730.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_10_39 logCertificate_49 support
  simpa only [support] using h

theorem sample_10_39_upper : discrepancy (1 / 10) sample_10_39 ≤ (227 / 1000) := by
  have h := sample_10_39_interval.2
  norm_num [logCertificate_49, logCertificate_2730] at h
  linarith

def sample_11_38 : Triple := ⟨11, 38, 49, by decide, by decide, by decide, by decide⟩
theorem sample_11_38_interval :
    (logCertificate_49.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_2926.upper ≤
      discrepancy (1 / 10) sample_11_38 ∧
    discrepancy (1 / 10) sample_11_38 ≤
      (logCertificate_49.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_2926.lower := by
  have hr : radical (11 * 38 * 49) = 2926 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_11_38.a * sample_11_38.b * sample_11_38.c)) :=
    ⟨logCertificate_2926.lower, logCertificate_2926.upper,
      by simpa only [sample_11_38, hr] using logCertificate_2926.lower_le,
      by simpa only [sample_11_38, hr] using logCertificate_2926.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_11_38 logCertificate_49 support
  simpa only [support] using h

theorem sample_11_38_upper : discrepancy (1 / 10) sample_11_38 ≤ (227 / 1000) := by
  have h := sample_11_38_interval.2
  norm_num [logCertificate_49, logCertificate_2926] at h
  linarith

def sample_12_37 : Triple := ⟨12, 37, 49, by decide, by decide, by decide, by decide⟩
theorem sample_12_37_interval :
    (logCertificate_49.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1554.upper ≤
      discrepancy (1 / 10) sample_12_37 ∧
    discrepancy (1 / 10) sample_12_37 ≤
      (logCertificate_49.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1554.lower := by
  have hr : radical (12 * 37 * 49) = 1554 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_12_37.a * sample_12_37.b * sample_12_37.c)) :=
    ⟨logCertificate_1554.lower, logCertificate_1554.upper,
      by simpa only [sample_12_37, hr] using logCertificate_1554.lower_le,
      by simpa only [sample_12_37, hr] using logCertificate_1554.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_12_37 logCertificate_49 support
  simpa only [support] using h

theorem sample_12_37_upper : discrepancy (1 / 10) sample_12_37 ≤ (227 / 1000) := by
  have h := sample_12_37_interval.2
  norm_num [logCertificate_49, logCertificate_1554] at h
  linarith

def sample_13_36 : Triple := ⟨13, 36, 49, by decide, by decide, by decide, by decide⟩
theorem sample_13_36_interval :
    (logCertificate_49.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_546.upper ≤
      discrepancy (1 / 10) sample_13_36 ∧
    discrepancy (1 / 10) sample_13_36 ≤
      (logCertificate_49.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_546.lower := by
  have hr : radical (13 * 36 * 49) = 546 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_13_36.a * sample_13_36.b * sample_13_36.c)) :=
    ⟨logCertificate_546.lower, logCertificate_546.upper,
      by simpa only [sample_13_36, hr] using logCertificate_546.lower_le,
      by simpa only [sample_13_36, hr] using logCertificate_546.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_13_36 logCertificate_49 support
  simpa only [support] using h

theorem sample_13_36_upper : discrepancy (1 / 10) sample_13_36 ≤ (227 / 1000) := by
  have h := sample_13_36_interval.2
  norm_num [logCertificate_49, logCertificate_546] at h
  linarith

def sample_15_34 : Triple := ⟨15, 34, 49, by decide, by decide, by decide, by decide⟩
theorem sample_15_34_interval :
    (logCertificate_49.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_3570.upper ≤
      discrepancy (1 / 10) sample_15_34 ∧
    discrepancy (1 / 10) sample_15_34 ≤
      (logCertificate_49.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_3570.lower := by
  have hr : radical (15 * 34 * 49) = 3570 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_15_34.a * sample_15_34.b * sample_15_34.c)) :=
    ⟨logCertificate_3570.lower, logCertificate_3570.upper,
      by simpa only [sample_15_34, hr] using logCertificate_3570.lower_le,
      by simpa only [sample_15_34, hr] using logCertificate_3570.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_15_34 logCertificate_49 support
  simpa only [support] using h

theorem sample_15_34_upper : discrepancy (1 / 10) sample_15_34 ≤ (227 / 1000) := by
  have h := sample_15_34_interval.2
  norm_num [logCertificate_49, logCertificate_3570] at h
  linarith

def sample_16_33 : Triple := ⟨16, 33, 49, by decide, by decide, by decide, by decide⟩
theorem sample_16_33_interval :
    (logCertificate_49.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_462.upper ≤
      discrepancy (1 / 10) sample_16_33 ∧
    discrepancy (1 / 10) sample_16_33 ≤
      (logCertificate_49.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_462.lower := by
  have hr : radical (16 * 33 * 49) = 462 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_16_33.a * sample_16_33.b * sample_16_33.c)) :=
    ⟨logCertificate_462.lower, logCertificate_462.upper,
      by simpa only [sample_16_33, hr] using logCertificate_462.lower_le,
      by simpa only [sample_16_33, hr] using logCertificate_462.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_16_33 logCertificate_49 support
  simpa only [support] using h

theorem sample_16_33_upper : discrepancy (1 / 10) sample_16_33 ≤ (227 / 1000) := by
  have h := sample_16_33_interval.2
  norm_num [logCertificate_49, logCertificate_462] at h
  linarith

def sample_17_32 : Triple := ⟨17, 32, 49, by decide, by decide, by decide, by decide⟩
theorem sample_17_32_interval :
    (logCertificate_49.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_238.upper ≤
      discrepancy (1 / 10) sample_17_32 ∧
    discrepancy (1 / 10) sample_17_32 ≤
      (logCertificate_49.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_238.lower := by
  have hr : radical (17 * 32 * 49) = 238 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_17_32.a * sample_17_32.b * sample_17_32.c)) :=
    ⟨logCertificate_238.lower, logCertificate_238.upper,
      by simpa only [sample_17_32, hr] using logCertificate_238.lower_le,
      by simpa only [sample_17_32, hr] using logCertificate_238.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_17_32 logCertificate_49 support
  simpa only [support] using h

theorem sample_17_32_upper : discrepancy (1 / 10) sample_17_32 ≤ (227 / 1000) := by
  have h := sample_17_32_interval.2
  norm_num [logCertificate_49, logCertificate_238] at h
  linarith

def sample_18_31 : Triple := ⟨18, 31, 49, by decide, by decide, by decide, by decide⟩
theorem sample_18_31_interval :
    (logCertificate_49.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1302.upper ≤
      discrepancy (1 / 10) sample_18_31 ∧
    discrepancy (1 / 10) sample_18_31 ≤
      (logCertificate_49.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1302.lower := by
  have hr : radical (18 * 31 * 49) = 1302 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_18_31.a * sample_18_31.b * sample_18_31.c)) :=
    ⟨logCertificate_1302.lower, logCertificate_1302.upper,
      by simpa only [sample_18_31, hr] using logCertificate_1302.lower_le,
      by simpa only [sample_18_31, hr] using logCertificate_1302.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_18_31 logCertificate_49 support
  simpa only [support] using h

theorem sample_18_31_upper : discrepancy (1 / 10) sample_18_31 ≤ (227 / 1000) := by
  have h := sample_18_31_interval.2
  norm_num [logCertificate_49, logCertificate_1302] at h
  linarith

def sample_19_30 : Triple := ⟨19, 30, 49, by decide, by decide, by decide, by decide⟩
theorem sample_19_30_interval :
    (logCertificate_49.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_3990.upper ≤
      discrepancy (1 / 10) sample_19_30 ∧
    discrepancy (1 / 10) sample_19_30 ≤
      (logCertificate_49.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_3990.lower := by
  have hr : radical (19 * 30 * 49) = 3990 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_19_30.a * sample_19_30.b * sample_19_30.c)) :=
    ⟨logCertificate_3990.lower, logCertificate_3990.upper,
      by simpa only [sample_19_30, hr] using logCertificate_3990.lower_le,
      by simpa only [sample_19_30, hr] using logCertificate_3990.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_19_30 logCertificate_49 support
  simpa only [support] using h

theorem sample_19_30_upper : discrepancy (1 / 10) sample_19_30 ≤ (227 / 1000) := by
  have h := sample_19_30_interval.2
  norm_num [logCertificate_49, logCertificate_3990] at h
  linarith

def sample_20_29 : Triple := ⟨20, 29, 49, by decide, by decide, by decide, by decide⟩
theorem sample_20_29_interval :
    (logCertificate_49.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_2030.upper ≤
      discrepancy (1 / 10) sample_20_29 ∧
    discrepancy (1 / 10) sample_20_29 ≤
      (logCertificate_49.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_2030.lower := by
  have hr : radical (20 * 29 * 49) = 2030 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_20_29.a * sample_20_29.b * sample_20_29.c)) :=
    ⟨logCertificate_2030.lower, logCertificate_2030.upper,
      by simpa only [sample_20_29, hr] using logCertificate_2030.lower_le,
      by simpa only [sample_20_29, hr] using logCertificate_2030.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_20_29 logCertificate_49 support
  simpa only [support] using h

theorem sample_20_29_upper : discrepancy (1 / 10) sample_20_29 ≤ (227 / 1000) := by
  have h := sample_20_29_interval.2
  norm_num [logCertificate_49, logCertificate_2030] at h
  linarith

def sample_22_27 : Triple := ⟨22, 27, 49, by decide, by decide, by decide, by decide⟩
theorem sample_22_27_interval :
    (logCertificate_49.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_462.upper ≤
      discrepancy (1 / 10) sample_22_27 ∧
    discrepancy (1 / 10) sample_22_27 ≤
      (logCertificate_49.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_462.lower := by
  have hr : radical (22 * 27 * 49) = 462 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_22_27.a * sample_22_27.b * sample_22_27.c)) :=
    ⟨logCertificate_462.lower, logCertificate_462.upper,
      by simpa only [sample_22_27, hr] using logCertificate_462.lower_le,
      by simpa only [sample_22_27, hr] using logCertificate_462.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_22_27 logCertificate_49 support
  simpa only [support] using h

theorem sample_22_27_upper : discrepancy (1 / 10) sample_22_27 ≤ (227 / 1000) := by
  have h := sample_22_27_interval.2
  norm_num [logCertificate_49, logCertificate_462] at h
  linarith

def sample_23_26 : Triple := ⟨23, 26, 49, by decide, by decide, by decide, by decide⟩
theorem sample_23_26_interval :
    (logCertificate_49.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_4186.upper ≤
      discrepancy (1 / 10) sample_23_26 ∧
    discrepancy (1 / 10) sample_23_26 ≤
      (logCertificate_49.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_4186.lower := by
  have hr : radical (23 * 26 * 49) = 4186 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_23_26.a * sample_23_26.b * sample_23_26.c)) :=
    ⟨logCertificate_4186.lower, logCertificate_4186.upper,
      by simpa only [sample_23_26, hr] using logCertificate_4186.lower_le,
      by simpa only [sample_23_26, hr] using logCertificate_4186.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_23_26 logCertificate_49 support
  simpa only [support] using h

theorem sample_23_26_upper : discrepancy (1 / 10) sample_23_26 ≤ (227 / 1000) := by
  have h := sample_23_26_interval.2
  norm_num [logCertificate_49, logCertificate_4186] at h
  linarith

def sample_24_25 : Triple := ⟨24, 25, 49, by decide, by decide, by decide, by decide⟩
theorem sample_24_25_interval :
    (logCertificate_49.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_210.upper ≤
      discrepancy (1 / 10) sample_24_25 ∧
    discrepancy (1 / 10) sample_24_25 ≤
      (logCertificate_49.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_210.lower := by
  have hr : radical (24 * 25 * 49) = 210 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_24_25.a * sample_24_25.b * sample_24_25.c)) :=
    ⟨logCertificate_210.lower, logCertificate_210.upper,
      by simpa only [sample_24_25, hr] using logCertificate_210.lower_le,
      by simpa only [sample_24_25, hr] using logCertificate_210.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_24_25 logCertificate_49 support
  simpa only [support] using h

theorem sample_24_25_upper : discrepancy (1 / 10) sample_24_25 ≤ (227 / 1000) := by
  have h := sample_24_25_interval.2
  norm_num [logCertificate_49, logCertificate_210] at h
  linarith


end Imscribing.ABC.Window70E1_10
