import Imscribing.ABC_Window70_FromOS_Samples1

/-! Generated by scripts/abc_emit_window_certificate.py; all claims checked by Lean. -/
namespace Imscribing.ABC.Window70E1_10

set_option maxRecDepth 8192
set_option maxHeartbeats 4000000
set_option synthInstance.maxSize 16384
set_option synthInstance.maxHeartbeats 4000000

def sample_1_21 : Triple := ⟨1, 21, 22, by decide, by decide, by decide, by decide⟩
theorem sample_1_21_interval :
    (logCertificate_22.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_462.upper ≤
      discrepancy (1 / 10) sample_1_21 ∧
    discrepancy (1 / 10) sample_1_21 ≤
      (logCertificate_22.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_462.lower := by
  have hr : radical (1 * 21 * 22) = 462 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_1_21.a * sample_1_21.b * sample_1_21.c)) :=
    ⟨logCertificate_462.lower, logCertificate_462.upper,
      by simpa only [sample_1_21, hr] using logCertificate_462.lower_le,
      by simpa only [sample_1_21, hr] using logCertificate_462.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_1_21 logCertificate_22 support
  simpa only [support] using h

theorem sample_1_21_upper : discrepancy (1 / 10) sample_1_21 ≤ (227 / 1000) := by
  have h := sample_1_21_interval.2
  norm_num [logCertificate_22, logCertificate_462] at h
  linarith

def sample_3_19 : Triple := ⟨3, 19, 22, by decide, by decide, by decide, by decide⟩
theorem sample_3_19_interval :
    (logCertificate_22.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1254.upper ≤
      discrepancy (1 / 10) sample_3_19 ∧
    discrepancy (1 / 10) sample_3_19 ≤
      (logCertificate_22.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1254.lower := by
  have hr : radical (3 * 19 * 22) = 1254 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_3_19.a * sample_3_19.b * sample_3_19.c)) :=
    ⟨logCertificate_1254.lower, logCertificate_1254.upper,
      by simpa only [sample_3_19, hr] using logCertificate_1254.lower_le,
      by simpa only [sample_3_19, hr] using logCertificate_1254.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_3_19 logCertificate_22 support
  simpa only [support] using h

theorem sample_3_19_upper : discrepancy (1 / 10) sample_3_19 ≤ (227 / 1000) := by
  have h := sample_3_19_interval.2
  norm_num [logCertificate_22, logCertificate_1254] at h
  linarith

def sample_5_17 : Triple := ⟨5, 17, 22, by decide, by decide, by decide, by decide⟩
theorem sample_5_17_interval :
    (logCertificate_22.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1870.upper ≤
      discrepancy (1 / 10) sample_5_17 ∧
    discrepancy (1 / 10) sample_5_17 ≤
      (logCertificate_22.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1870.lower := by
  have hr : radical (5 * 17 * 22) = 1870 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_5_17.a * sample_5_17.b * sample_5_17.c)) :=
    ⟨logCertificate_1870.lower, logCertificate_1870.upper,
      by simpa only [sample_5_17, hr] using logCertificate_1870.lower_le,
      by simpa only [sample_5_17, hr] using logCertificate_1870.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_5_17 logCertificate_22 support
  simpa only [support] using h

theorem sample_5_17_upper : discrepancy (1 / 10) sample_5_17 ≤ (227 / 1000) := by
  have h := sample_5_17_interval.2
  norm_num [logCertificate_22, logCertificate_1870] at h
  linarith

def sample_7_15 : Triple := ⟨7, 15, 22, by decide, by decide, by decide, by decide⟩
theorem sample_7_15_interval :
    (logCertificate_22.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_2310.upper ≤
      discrepancy (1 / 10) sample_7_15 ∧
    discrepancy (1 / 10) sample_7_15 ≤
      (logCertificate_22.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_2310.lower := by
  have hr : radical (7 * 15 * 22) = 2310 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_7_15.a * sample_7_15.b * sample_7_15.c)) :=
    ⟨logCertificate_2310.lower, logCertificate_2310.upper,
      by simpa only [sample_7_15, hr] using logCertificate_2310.lower_le,
      by simpa only [sample_7_15, hr] using logCertificate_2310.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_7_15 logCertificate_22 support
  simpa only [support] using h

theorem sample_7_15_upper : discrepancy (1 / 10) sample_7_15 ≤ (227 / 1000) := by
  have h := sample_7_15_interval.2
  norm_num [logCertificate_22, logCertificate_2310] at h
  linarith

def sample_9_13 : Triple := ⟨9, 13, 22, by decide, by decide, by decide, by decide⟩
theorem sample_9_13_interval :
    (logCertificate_22.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_858.upper ≤
      discrepancy (1 / 10) sample_9_13 ∧
    discrepancy (1 / 10) sample_9_13 ≤
      (logCertificate_22.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_858.lower := by
  have hr : radical (9 * 13 * 22) = 858 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_9_13.a * sample_9_13.b * sample_9_13.c)) :=
    ⟨logCertificate_858.lower, logCertificate_858.upper,
      by simpa only [sample_9_13, hr] using logCertificate_858.lower_le,
      by simpa only [sample_9_13, hr] using logCertificate_858.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_9_13 logCertificate_22 support
  simpa only [support] using h

theorem sample_9_13_upper : discrepancy (1 / 10) sample_9_13 ≤ (227 / 1000) := by
  have h := sample_9_13_interval.2
  norm_num [logCertificate_22, logCertificate_858] at h
  linarith

def sample_1_22 : Triple := ⟨1, 22, 23, by decide, by decide, by decide, by decide⟩
theorem sample_1_22_interval :
    (logCertificate_23.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_506.upper ≤
      discrepancy (1 / 10) sample_1_22 ∧
    discrepancy (1 / 10) sample_1_22 ≤
      (logCertificate_23.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_506.lower := by
  have hr : radical (1 * 22 * 23) = 506 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_1_22.a * sample_1_22.b * sample_1_22.c)) :=
    ⟨logCertificate_506.lower, logCertificate_506.upper,
      by simpa only [sample_1_22, hr] using logCertificate_506.lower_le,
      by simpa only [sample_1_22, hr] using logCertificate_506.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_1_22 logCertificate_23 support
  simpa only [support] using h

theorem sample_1_22_upper : discrepancy (1 / 10) sample_1_22 ≤ (227 / 1000) := by
  have h := sample_1_22_interval.2
  norm_num [logCertificate_23, logCertificate_506] at h
  linarith

def sample_2_21 : Triple := ⟨2, 21, 23, by decide, by decide, by decide, by decide⟩
theorem sample_2_21_interval :
    (logCertificate_23.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_966.upper ≤
      discrepancy (1 / 10) sample_2_21 ∧
    discrepancy (1 / 10) sample_2_21 ≤
      (logCertificate_23.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_966.lower := by
  have hr : radical (2 * 21 * 23) = 966 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_2_21.a * sample_2_21.b * sample_2_21.c)) :=
    ⟨logCertificate_966.lower, logCertificate_966.upper,
      by simpa only [sample_2_21, hr] using logCertificate_966.lower_le,
      by simpa only [sample_2_21, hr] using logCertificate_966.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_2_21 logCertificate_23 support
  simpa only [support] using h

theorem sample_2_21_upper : discrepancy (1 / 10) sample_2_21 ≤ (227 / 1000) := by
  have h := sample_2_21_interval.2
  norm_num [logCertificate_23, logCertificate_966] at h
  linarith

def sample_3_20 : Triple := ⟨3, 20, 23, by decide, by decide, by decide, by decide⟩
theorem sample_3_20_interval :
    (logCertificate_23.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_690.upper ≤
      discrepancy (1 / 10) sample_3_20 ∧
    discrepancy (1 / 10) sample_3_20 ≤
      (logCertificate_23.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_690.lower := by
  have hr : radical (3 * 20 * 23) = 690 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_3_20.a * sample_3_20.b * sample_3_20.c)) :=
    ⟨logCertificate_690.lower, logCertificate_690.upper,
      by simpa only [sample_3_20, hr] using logCertificate_690.lower_le,
      by simpa only [sample_3_20, hr] using logCertificate_690.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_3_20 logCertificate_23 support
  simpa only [support] using h

theorem sample_3_20_upper : discrepancy (1 / 10) sample_3_20 ≤ (227 / 1000) := by
  have h := sample_3_20_interval.2
  norm_num [logCertificate_23, logCertificate_690] at h
  linarith

def sample_4_19 : Triple := ⟨4, 19, 23, by decide, by decide, by decide, by decide⟩
theorem sample_4_19_interval :
    (logCertificate_23.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_874.upper ≤
      discrepancy (1 / 10) sample_4_19 ∧
    discrepancy (1 / 10) sample_4_19 ≤
      (logCertificate_23.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_874.lower := by
  have hr : radical (4 * 19 * 23) = 874 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_4_19.a * sample_4_19.b * sample_4_19.c)) :=
    ⟨logCertificate_874.lower, logCertificate_874.upper,
      by simpa only [sample_4_19, hr] using logCertificate_874.lower_le,
      by simpa only [sample_4_19, hr] using logCertificate_874.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_4_19 logCertificate_23 support
  simpa only [support] using h

theorem sample_4_19_upper : discrepancy (1 / 10) sample_4_19 ≤ (227 / 1000) := by
  have h := sample_4_19_interval.2
  norm_num [logCertificate_23, logCertificate_874] at h
  linarith

def sample_5_18 : Triple := ⟨5, 18, 23, by decide, by decide, by decide, by decide⟩
theorem sample_5_18_interval :
    (logCertificate_23.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_690.upper ≤
      discrepancy (1 / 10) sample_5_18 ∧
    discrepancy (1 / 10) sample_5_18 ≤
      (logCertificate_23.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_690.lower := by
  have hr : radical (5 * 18 * 23) = 690 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_5_18.a * sample_5_18.b * sample_5_18.c)) :=
    ⟨logCertificate_690.lower, logCertificate_690.upper,
      by simpa only [sample_5_18, hr] using logCertificate_690.lower_le,
      by simpa only [sample_5_18, hr] using logCertificate_690.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_5_18 logCertificate_23 support
  simpa only [support] using h

theorem sample_5_18_upper : discrepancy (1 / 10) sample_5_18 ≤ (227 / 1000) := by
  have h := sample_5_18_interval.2
  norm_num [logCertificate_23, logCertificate_690] at h
  linarith

def sample_6_17 : Triple := ⟨6, 17, 23, by decide, by decide, by decide, by decide⟩
theorem sample_6_17_interval :
    (logCertificate_23.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_2346.upper ≤
      discrepancy (1 / 10) sample_6_17 ∧
    discrepancy (1 / 10) sample_6_17 ≤
      (logCertificate_23.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_2346.lower := by
  have hr : radical (6 * 17 * 23) = 2346 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_6_17.a * sample_6_17.b * sample_6_17.c)) :=
    ⟨logCertificate_2346.lower, logCertificate_2346.upper,
      by simpa only [sample_6_17, hr] using logCertificate_2346.lower_le,
      by simpa only [sample_6_17, hr] using logCertificate_2346.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_6_17 logCertificate_23 support
  simpa only [support] using h

theorem sample_6_17_upper : discrepancy (1 / 10) sample_6_17 ≤ (227 / 1000) := by
  have h := sample_6_17_interval.2
  norm_num [logCertificate_23, logCertificate_2346] at h
  linarith

def sample_7_16 : Triple := ⟨7, 16, 23, by decide, by decide, by decide, by decide⟩
theorem sample_7_16_interval :
    (logCertificate_23.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_322.upper ≤
      discrepancy (1 / 10) sample_7_16 ∧
    discrepancy (1 / 10) sample_7_16 ≤
      (logCertificate_23.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_322.lower := by
  have hr : radical (7 * 16 * 23) = 322 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_7_16.a * sample_7_16.b * sample_7_16.c)) :=
    ⟨logCertificate_322.lower, logCertificate_322.upper,
      by simpa only [sample_7_16, hr] using logCertificate_322.lower_le,
      by simpa only [sample_7_16, hr] using logCertificate_322.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_7_16 logCertificate_23 support
  simpa only [support] using h

theorem sample_7_16_upper : discrepancy (1 / 10) sample_7_16 ≤ (227 / 1000) := by
  have h := sample_7_16_interval.2
  norm_num [logCertificate_23, logCertificate_322] at h
  linarith

def sample_8_15 : Triple := ⟨8, 15, 23, by decide, by decide, by decide, by decide⟩
theorem sample_8_15_interval :
    (logCertificate_23.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_690.upper ≤
      discrepancy (1 / 10) sample_8_15 ∧
    discrepancy (1 / 10) sample_8_15 ≤
      (logCertificate_23.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_690.lower := by
  have hr : radical (8 * 15 * 23) = 690 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_8_15.a * sample_8_15.b * sample_8_15.c)) :=
    ⟨logCertificate_690.lower, logCertificate_690.upper,
      by simpa only [sample_8_15, hr] using logCertificate_690.lower_le,
      by simpa only [sample_8_15, hr] using logCertificate_690.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_8_15 logCertificate_23 support
  simpa only [support] using h

theorem sample_8_15_upper : discrepancy (1 / 10) sample_8_15 ≤ (227 / 1000) := by
  have h := sample_8_15_interval.2
  norm_num [logCertificate_23, logCertificate_690] at h
  linarith

def sample_9_14 : Triple := ⟨9, 14, 23, by decide, by decide, by decide, by decide⟩
theorem sample_9_14_interval :
    (logCertificate_23.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_966.upper ≤
      discrepancy (1 / 10) sample_9_14 ∧
    discrepancy (1 / 10) sample_9_14 ≤
      (logCertificate_23.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_966.lower := by
  have hr : radical (9 * 14 * 23) = 966 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_9_14.a * sample_9_14.b * sample_9_14.c)) :=
    ⟨logCertificate_966.lower, logCertificate_966.upper,
      by simpa only [sample_9_14, hr] using logCertificate_966.lower_le,
      by simpa only [sample_9_14, hr] using logCertificate_966.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_9_14 logCertificate_23 support
  simpa only [support] using h

theorem sample_9_14_upper : discrepancy (1 / 10) sample_9_14 ≤ (227 / 1000) := by
  have h := sample_9_14_interval.2
  norm_num [logCertificate_23, logCertificate_966] at h
  linarith

def sample_10_13 : Triple := ⟨10, 13, 23, by decide, by decide, by decide, by decide⟩
theorem sample_10_13_interval :
    (logCertificate_23.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_2990.upper ≤
      discrepancy (1 / 10) sample_10_13 ∧
    discrepancy (1 / 10) sample_10_13 ≤
      (logCertificate_23.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_2990.lower := by
  have hr : radical (10 * 13 * 23) = 2990 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_10_13.a * sample_10_13.b * sample_10_13.c)) :=
    ⟨logCertificate_2990.lower, logCertificate_2990.upper,
      by simpa only [sample_10_13, hr] using logCertificate_2990.lower_le,
      by simpa only [sample_10_13, hr] using logCertificate_2990.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_10_13 logCertificate_23 support
  simpa only [support] using h

theorem sample_10_13_upper : discrepancy (1 / 10) sample_10_13 ≤ (227 / 1000) := by
  have h := sample_10_13_interval.2
  norm_num [logCertificate_23, logCertificate_2990] at h
  linarith

def sample_11_12 : Triple := ⟨11, 12, 23, by decide, by decide, by decide, by decide⟩
theorem sample_11_12_interval :
    (logCertificate_23.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1518.upper ≤
      discrepancy (1 / 10) sample_11_12 ∧
    discrepancy (1 / 10) sample_11_12 ≤
      (logCertificate_23.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1518.lower := by
  have hr : radical (11 * 12 * 23) = 1518 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_11_12.a * sample_11_12.b * sample_11_12.c)) :=
    ⟨logCertificate_1518.lower, logCertificate_1518.upper,
      by simpa only [sample_11_12, hr] using logCertificate_1518.lower_le,
      by simpa only [sample_11_12, hr] using logCertificate_1518.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_11_12 logCertificate_23 support
  simpa only [support] using h

theorem sample_11_12_upper : discrepancy (1 / 10) sample_11_12 ≤ (227 / 1000) := by
  have h := sample_11_12_interval.2
  norm_num [logCertificate_23, logCertificate_1518] at h
  linarith

def sample_1_23 : Triple := ⟨1, 23, 24, by decide, by decide, by decide, by decide⟩
theorem sample_1_23_interval :
    (logCertificate_24.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_138.upper ≤
      discrepancy (1 / 10) sample_1_23 ∧
    discrepancy (1 / 10) sample_1_23 ≤
      (logCertificate_24.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_138.lower := by
  have hr : radical (1 * 23 * 24) = 138 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_1_23.a * sample_1_23.b * sample_1_23.c)) :=
    ⟨logCertificate_138.lower, logCertificate_138.upper,
      by simpa only [sample_1_23, hr] using logCertificate_138.lower_le,
      by simpa only [sample_1_23, hr] using logCertificate_138.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_1_23 logCertificate_24 support
  simpa only [support] using h

theorem sample_1_23_upper : discrepancy (1 / 10) sample_1_23 ≤ (227 / 1000) := by
  have h := sample_1_23_interval.2
  norm_num [logCertificate_24, logCertificate_138] at h
  linarith

def sample_5_19 : Triple := ⟨5, 19, 24, by decide, by decide, by decide, by decide⟩
theorem sample_5_19_interval :
    (logCertificate_24.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_570.upper ≤
      discrepancy (1 / 10) sample_5_19 ∧
    discrepancy (1 / 10) sample_5_19 ≤
      (logCertificate_24.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_570.lower := by
  have hr : radical (5 * 19 * 24) = 570 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_5_19.a * sample_5_19.b * sample_5_19.c)) :=
    ⟨logCertificate_570.lower, logCertificate_570.upper,
      by simpa only [sample_5_19, hr] using logCertificate_570.lower_le,
      by simpa only [sample_5_19, hr] using logCertificate_570.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_5_19 logCertificate_24 support
  simpa only [support] using h

theorem sample_5_19_upper : discrepancy (1 / 10) sample_5_19 ≤ (227 / 1000) := by
  have h := sample_5_19_interval.2
  norm_num [logCertificate_24, logCertificate_570] at h
  linarith

def sample_7_17 : Triple := ⟨7, 17, 24, by decide, by decide, by decide, by decide⟩
theorem sample_7_17_interval :
    (logCertificate_24.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_714.upper ≤
      discrepancy (1 / 10) sample_7_17 ∧
    discrepancy (1 / 10) sample_7_17 ≤
      (logCertificate_24.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_714.lower := by
  have hr : radical (7 * 17 * 24) = 714 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_7_17.a * sample_7_17.b * sample_7_17.c)) :=
    ⟨logCertificate_714.lower, logCertificate_714.upper,
      by simpa only [sample_7_17, hr] using logCertificate_714.lower_le,
      by simpa only [sample_7_17, hr] using logCertificate_714.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_7_17 logCertificate_24 support
  simpa only [support] using h

theorem sample_7_17_upper : discrepancy (1 / 10) sample_7_17 ≤ (227 / 1000) := by
  have h := sample_7_17_interval.2
  norm_num [logCertificate_24, logCertificate_714] at h
  linarith

def sample_11_13 : Triple := ⟨11, 13, 24, by decide, by decide, by decide, by decide⟩
theorem sample_11_13_interval :
    (logCertificate_24.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_858.upper ≤
      discrepancy (1 / 10) sample_11_13 ∧
    discrepancy (1 / 10) sample_11_13 ≤
      (logCertificate_24.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_858.lower := by
  have hr : radical (11 * 13 * 24) = 858 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_11_13.a * sample_11_13.b * sample_11_13.c)) :=
    ⟨logCertificate_858.lower, logCertificate_858.upper,
      by simpa only [sample_11_13, hr] using logCertificate_858.lower_le,
      by simpa only [sample_11_13, hr] using logCertificate_858.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_11_13 logCertificate_24 support
  simpa only [support] using h

theorem sample_11_13_upper : discrepancy (1 / 10) sample_11_13 ≤ (227 / 1000) := by
  have h := sample_11_13_interval.2
  norm_num [logCertificate_24, logCertificate_858] at h
  linarith

def sample_1_24 : Triple := ⟨1, 24, 25, by decide, by decide, by decide, by decide⟩
theorem sample_1_24_interval :
    (logCertificate_25.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_30.upper ≤
      discrepancy (1 / 10) sample_1_24 ∧
    discrepancy (1 / 10) sample_1_24 ≤
      (logCertificate_25.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_30.lower := by
  have hr : radical (1 * 24 * 25) = 30 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_1_24.a * sample_1_24.b * sample_1_24.c)) :=
    ⟨logCertificate_30.lower, logCertificate_30.upper,
      by simpa only [sample_1_24, hr] using logCertificate_30.lower_le,
      by simpa only [sample_1_24, hr] using logCertificate_30.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_1_24 logCertificate_25 support
  simpa only [support] using h

theorem sample_1_24_upper : discrepancy (1 / 10) sample_1_24 ≤ (227 / 1000) := by
  have h := sample_1_24_interval.2
  norm_num [logCertificate_25, logCertificate_30] at h
  linarith

def sample_2_23 : Triple := ⟨2, 23, 25, by decide, by decide, by decide, by decide⟩
theorem sample_2_23_interval :
    (logCertificate_25.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_230.upper ≤
      discrepancy (1 / 10) sample_2_23 ∧
    discrepancy (1 / 10) sample_2_23 ≤
      (logCertificate_25.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_230.lower := by
  have hr : radical (2 * 23 * 25) = 230 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_2_23.a * sample_2_23.b * sample_2_23.c)) :=
    ⟨logCertificate_230.lower, logCertificate_230.upper,
      by simpa only [sample_2_23, hr] using logCertificate_230.lower_le,
      by simpa only [sample_2_23, hr] using logCertificate_230.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_2_23 logCertificate_25 support
  simpa only [support] using h

theorem sample_2_23_upper : discrepancy (1 / 10) sample_2_23 ≤ (227 / 1000) := by
  have h := sample_2_23_interval.2
  norm_num [logCertificate_25, logCertificate_230] at h
  linarith

def sample_3_22 : Triple := ⟨3, 22, 25, by decide, by decide, by decide, by decide⟩
theorem sample_3_22_interval :
    (logCertificate_25.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_330.upper ≤
      discrepancy (1 / 10) sample_3_22 ∧
    discrepancy (1 / 10) sample_3_22 ≤
      (logCertificate_25.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_330.lower := by
  have hr : radical (3 * 22 * 25) = 330 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_3_22.a * sample_3_22.b * sample_3_22.c)) :=
    ⟨logCertificate_330.lower, logCertificate_330.upper,
      by simpa only [sample_3_22, hr] using logCertificate_330.lower_le,
      by simpa only [sample_3_22, hr] using logCertificate_330.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_3_22 logCertificate_25 support
  simpa only [support] using h

theorem sample_3_22_upper : discrepancy (1 / 10) sample_3_22 ≤ (227 / 1000) := by
  have h := sample_3_22_interval.2
  norm_num [logCertificate_25, logCertificate_330] at h
  linarith

def sample_4_21 : Triple := ⟨4, 21, 25, by decide, by decide, by decide, by decide⟩
theorem sample_4_21_interval :
    (logCertificate_25.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_210.upper ≤
      discrepancy (1 / 10) sample_4_21 ∧
    discrepancy (1 / 10) sample_4_21 ≤
      (logCertificate_25.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_210.lower := by
  have hr : radical (4 * 21 * 25) = 210 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_4_21.a * sample_4_21.b * sample_4_21.c)) :=
    ⟨logCertificate_210.lower, logCertificate_210.upper,
      by simpa only [sample_4_21, hr] using logCertificate_210.lower_le,
      by simpa only [sample_4_21, hr] using logCertificate_210.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_4_21 logCertificate_25 support
  simpa only [support] using h

theorem sample_4_21_upper : discrepancy (1 / 10) sample_4_21 ≤ (227 / 1000) := by
  have h := sample_4_21_interval.2
  norm_num [logCertificate_25, logCertificate_210] at h
  linarith

def sample_6_19 : Triple := ⟨6, 19, 25, by decide, by decide, by decide, by decide⟩
theorem sample_6_19_interval :
    (logCertificate_25.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_570.upper ≤
      discrepancy (1 / 10) sample_6_19 ∧
    discrepancy (1 / 10) sample_6_19 ≤
      (logCertificate_25.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_570.lower := by
  have hr : radical (6 * 19 * 25) = 570 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_6_19.a * sample_6_19.b * sample_6_19.c)) :=
    ⟨logCertificate_570.lower, logCertificate_570.upper,
      by simpa only [sample_6_19, hr] using logCertificate_570.lower_le,
      by simpa only [sample_6_19, hr] using logCertificate_570.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_6_19 logCertificate_25 support
  simpa only [support] using h

theorem sample_6_19_upper : discrepancy (1 / 10) sample_6_19 ≤ (227 / 1000) := by
  have h := sample_6_19_interval.2
  norm_num [logCertificate_25, logCertificate_570] at h
  linarith

def sample_7_18 : Triple := ⟨7, 18, 25, by decide, by decide, by decide, by decide⟩
theorem sample_7_18_interval :
    (logCertificate_25.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_210.upper ≤
      discrepancy (1 / 10) sample_7_18 ∧
    discrepancy (1 / 10) sample_7_18 ≤
      (logCertificate_25.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_210.lower := by
  have hr : radical (7 * 18 * 25) = 210 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_7_18.a * sample_7_18.b * sample_7_18.c)) :=
    ⟨logCertificate_210.lower, logCertificate_210.upper,
      by simpa only [sample_7_18, hr] using logCertificate_210.lower_le,
      by simpa only [sample_7_18, hr] using logCertificate_210.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_7_18 logCertificate_25 support
  simpa only [support] using h

theorem sample_7_18_upper : discrepancy (1 / 10) sample_7_18 ≤ (227 / 1000) := by
  have h := sample_7_18_interval.2
  norm_num [logCertificate_25, logCertificate_210] at h
  linarith

def sample_8_17 : Triple := ⟨8, 17, 25, by decide, by decide, by decide, by decide⟩
theorem sample_8_17_interval :
    (logCertificate_25.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_170.upper ≤
      discrepancy (1 / 10) sample_8_17 ∧
    discrepancy (1 / 10) sample_8_17 ≤
      (logCertificate_25.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_170.lower := by
  have hr : radical (8 * 17 * 25) = 170 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_8_17.a * sample_8_17.b * sample_8_17.c)) :=
    ⟨logCertificate_170.lower, logCertificate_170.upper,
      by simpa only [sample_8_17, hr] using logCertificate_170.lower_le,
      by simpa only [sample_8_17, hr] using logCertificate_170.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_8_17 logCertificate_25 support
  simpa only [support] using h

theorem sample_8_17_upper : discrepancy (1 / 10) sample_8_17 ≤ (227 / 1000) := by
  have h := sample_8_17_interval.2
  norm_num [logCertificate_25, logCertificate_170] at h
  linarith

def sample_9_16 : Triple := ⟨9, 16, 25, by decide, by decide, by decide, by decide⟩
theorem sample_9_16_interval :
    (logCertificate_25.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_30.upper ≤
      discrepancy (1 / 10) sample_9_16 ∧
    discrepancy (1 / 10) sample_9_16 ≤
      (logCertificate_25.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_30.lower := by
  have hr : radical (9 * 16 * 25) = 30 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_9_16.a * sample_9_16.b * sample_9_16.c)) :=
    ⟨logCertificate_30.lower, logCertificate_30.upper,
      by simpa only [sample_9_16, hr] using logCertificate_30.lower_le,
      by simpa only [sample_9_16, hr] using logCertificate_30.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_9_16 logCertificate_25 support
  simpa only [support] using h

theorem sample_9_16_upper : discrepancy (1 / 10) sample_9_16 ≤ (227 / 1000) := by
  have h := sample_9_16_interval.2
  norm_num [logCertificate_25, logCertificate_30] at h
  linarith

def sample_11_14 : Triple := ⟨11, 14, 25, by decide, by decide, by decide, by decide⟩
theorem sample_11_14_interval :
    (logCertificate_25.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_770.upper ≤
      discrepancy (1 / 10) sample_11_14 ∧
    discrepancy (1 / 10) sample_11_14 ≤
      (logCertificate_25.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_770.lower := by
  have hr : radical (11 * 14 * 25) = 770 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_11_14.a * sample_11_14.b * sample_11_14.c)) :=
    ⟨logCertificate_770.lower, logCertificate_770.upper,
      by simpa only [sample_11_14, hr] using logCertificate_770.lower_le,
      by simpa only [sample_11_14, hr] using logCertificate_770.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_11_14 logCertificate_25 support
  simpa only [support] using h

theorem sample_11_14_upper : discrepancy (1 / 10) sample_11_14 ≤ (227 / 1000) := by
  have h := sample_11_14_interval.2
  norm_num [logCertificate_25, logCertificate_770] at h
  linarith

def sample_12_13 : Triple := ⟨12, 13, 25, by decide, by decide, by decide, by decide⟩
theorem sample_12_13_interval :
    (logCertificate_25.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_390.upper ≤
      discrepancy (1 / 10) sample_12_13 ∧
    discrepancy (1 / 10) sample_12_13 ≤
      (logCertificate_25.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_390.lower := by
  have hr : radical (12 * 13 * 25) = 390 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_12_13.a * sample_12_13.b * sample_12_13.c)) :=
    ⟨logCertificate_390.lower, logCertificate_390.upper,
      by simpa only [sample_12_13, hr] using logCertificate_390.lower_le,
      by simpa only [sample_12_13, hr] using logCertificate_390.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_12_13 logCertificate_25 support
  simpa only [support] using h

theorem sample_12_13_upper : discrepancy (1 / 10) sample_12_13 ≤ (227 / 1000) := by
  have h := sample_12_13_interval.2
  norm_num [logCertificate_25, logCertificate_390] at h
  linarith

def sample_1_25 : Triple := ⟨1, 25, 26, by decide, by decide, by decide, by decide⟩
theorem sample_1_25_interval :
    (logCertificate_26.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_130.upper ≤
      discrepancy (1 / 10) sample_1_25 ∧
    discrepancy (1 / 10) sample_1_25 ≤
      (logCertificate_26.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_130.lower := by
  have hr : radical (1 * 25 * 26) = 130 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_1_25.a * sample_1_25.b * sample_1_25.c)) :=
    ⟨logCertificate_130.lower, logCertificate_130.upper,
      by simpa only [sample_1_25, hr] using logCertificate_130.lower_le,
      by simpa only [sample_1_25, hr] using logCertificate_130.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_1_25 logCertificate_26 support
  simpa only [support] using h

theorem sample_1_25_upper : discrepancy (1 / 10) sample_1_25 ≤ (227 / 1000) := by
  have h := sample_1_25_interval.2
  norm_num [logCertificate_26, logCertificate_130] at h
  linarith

def sample_3_23 : Triple := ⟨3, 23, 26, by decide, by decide, by decide, by decide⟩
theorem sample_3_23_interval :
    (logCertificate_26.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1794.upper ≤
      discrepancy (1 / 10) sample_3_23 ∧
    discrepancy (1 / 10) sample_3_23 ≤
      (logCertificate_26.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1794.lower := by
  have hr : radical (3 * 23 * 26) = 1794 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_3_23.a * sample_3_23.b * sample_3_23.c)) :=
    ⟨logCertificate_1794.lower, logCertificate_1794.upper,
      by simpa only [sample_3_23, hr] using logCertificate_1794.lower_le,
      by simpa only [sample_3_23, hr] using logCertificate_1794.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_3_23 logCertificate_26 support
  simpa only [support] using h

theorem sample_3_23_upper : discrepancy (1 / 10) sample_3_23 ≤ (227 / 1000) := by
  have h := sample_3_23_interval.2
  norm_num [logCertificate_26, logCertificate_1794] at h
  linarith

def sample_5_21 : Triple := ⟨5, 21, 26, by decide, by decide, by decide, by decide⟩
theorem sample_5_21_interval :
    (logCertificate_26.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_2730.upper ≤
      discrepancy (1 / 10) sample_5_21 ∧
    discrepancy (1 / 10) sample_5_21 ≤
      (logCertificate_26.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_2730.lower := by
  have hr : radical (5 * 21 * 26) = 2730 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_5_21.a * sample_5_21.b * sample_5_21.c)) :=
    ⟨logCertificate_2730.lower, logCertificate_2730.upper,
      by simpa only [sample_5_21, hr] using logCertificate_2730.lower_le,
      by simpa only [sample_5_21, hr] using logCertificate_2730.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_5_21 logCertificate_26 support
  simpa only [support] using h

theorem sample_5_21_upper : discrepancy (1 / 10) sample_5_21 ≤ (227 / 1000) := by
  have h := sample_5_21_interval.2
  norm_num [logCertificate_26, logCertificate_2730] at h
  linarith

def sample_7_19 : Triple := ⟨7, 19, 26, by decide, by decide, by decide, by decide⟩
theorem sample_7_19_interval :
    (logCertificate_26.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_3458.upper ≤
      discrepancy (1 / 10) sample_7_19 ∧
    discrepancy (1 / 10) sample_7_19 ≤
      (logCertificate_26.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_3458.lower := by
  have hr : radical (7 * 19 * 26) = 3458 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_7_19.a * sample_7_19.b * sample_7_19.c)) :=
    ⟨logCertificate_3458.lower, logCertificate_3458.upper,
      by simpa only [sample_7_19, hr] using logCertificate_3458.lower_le,
      by simpa only [sample_7_19, hr] using logCertificate_3458.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_7_19 logCertificate_26 support
  simpa only [support] using h

theorem sample_7_19_upper : discrepancy (1 / 10) sample_7_19 ≤ (227 / 1000) := by
  have h := sample_7_19_interval.2
  norm_num [logCertificate_26, logCertificate_3458] at h
  linarith

def sample_9_17 : Triple := ⟨9, 17, 26, by decide, by decide, by decide, by decide⟩
theorem sample_9_17_interval :
    (logCertificate_26.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1326.upper ≤
      discrepancy (1 / 10) sample_9_17 ∧
    discrepancy (1 / 10) sample_9_17 ≤
      (logCertificate_26.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1326.lower := by
  have hr : radical (9 * 17 * 26) = 1326 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_9_17.a * sample_9_17.b * sample_9_17.c)) :=
    ⟨logCertificate_1326.lower, logCertificate_1326.upper,
      by simpa only [sample_9_17, hr] using logCertificate_1326.lower_le,
      by simpa only [sample_9_17, hr] using logCertificate_1326.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_9_17 logCertificate_26 support
  simpa only [support] using h

theorem sample_9_17_upper : discrepancy (1 / 10) sample_9_17 ≤ (227 / 1000) := by
  have h := sample_9_17_interval.2
  norm_num [logCertificate_26, logCertificate_1326] at h
  linarith

def sample_11_15 : Triple := ⟨11, 15, 26, by decide, by decide, by decide, by decide⟩
theorem sample_11_15_interval :
    (logCertificate_26.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_4290.upper ≤
      discrepancy (1 / 10) sample_11_15 ∧
    discrepancy (1 / 10) sample_11_15 ≤
      (logCertificate_26.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_4290.lower := by
  have hr : radical (11 * 15 * 26) = 4290 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_11_15.a * sample_11_15.b * sample_11_15.c)) :=
    ⟨logCertificate_4290.lower, logCertificate_4290.upper,
      by simpa only [sample_11_15, hr] using logCertificate_4290.lower_le,
      by simpa only [sample_11_15, hr] using logCertificate_4290.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_11_15 logCertificate_26 support
  simpa only [support] using h

theorem sample_11_15_upper : discrepancy (1 / 10) sample_11_15 ≤ (227 / 1000) := by
  have h := sample_11_15_interval.2
  norm_num [logCertificate_26, logCertificate_4290] at h
  linarith

def sample_1_26 : Triple := ⟨1, 26, 27, by decide, by decide, by decide, by decide⟩
theorem sample_1_26_interval :
    (logCertificate_27.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_78.upper ≤
      discrepancy (1 / 10) sample_1_26 ∧
    discrepancy (1 / 10) sample_1_26 ≤
      (logCertificate_27.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_78.lower := by
  have hr : radical (1 * 26 * 27) = 78 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_1_26.a * sample_1_26.b * sample_1_26.c)) :=
    ⟨logCertificate_78.lower, logCertificate_78.upper,
      by simpa only [sample_1_26, hr] using logCertificate_78.lower_le,
      by simpa only [sample_1_26, hr] using logCertificate_78.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_1_26 logCertificate_27 support
  simpa only [support] using h

theorem sample_1_26_upper : discrepancy (1 / 10) sample_1_26 ≤ (227 / 1000) := by
  have h := sample_1_26_interval.2
  norm_num [logCertificate_27, logCertificate_78] at h
  linarith

def sample_2_25 : Triple := ⟨2, 25, 27, by decide, by decide, by decide, by decide⟩
theorem sample_2_25_interval :
    (logCertificate_27.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_30.upper ≤
      discrepancy (1 / 10) sample_2_25 ∧
    discrepancy (1 / 10) sample_2_25 ≤
      (logCertificate_27.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_30.lower := by
  have hr : radical (2 * 25 * 27) = 30 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_2_25.a * sample_2_25.b * sample_2_25.c)) :=
    ⟨logCertificate_30.lower, logCertificate_30.upper,
      by simpa only [sample_2_25, hr] using logCertificate_30.lower_le,
      by simpa only [sample_2_25, hr] using logCertificate_30.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_2_25 logCertificate_27 support
  simpa only [support] using h

theorem sample_2_25_upper : discrepancy (1 / 10) sample_2_25 ≤ (227 / 1000) := by
  have h := sample_2_25_interval.2
  norm_num [logCertificate_27, logCertificate_30] at h
  linarith

def sample_4_23 : Triple := ⟨4, 23, 27, by decide, by decide, by decide, by decide⟩
theorem sample_4_23_interval :
    (logCertificate_27.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_138.upper ≤
      discrepancy (1 / 10) sample_4_23 ∧
    discrepancy (1 / 10) sample_4_23 ≤
      (logCertificate_27.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_138.lower := by
  have hr : radical (4 * 23 * 27) = 138 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_4_23.a * sample_4_23.b * sample_4_23.c)) :=
    ⟨logCertificate_138.lower, logCertificate_138.upper,
      by simpa only [sample_4_23, hr] using logCertificate_138.lower_le,
      by simpa only [sample_4_23, hr] using logCertificate_138.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_4_23 logCertificate_27 support
  simpa only [support] using h

theorem sample_4_23_upper : discrepancy (1 / 10) sample_4_23 ≤ (227 / 1000) := by
  have h := sample_4_23_interval.2
  norm_num [logCertificate_27, logCertificate_138] at h
  linarith

def sample_5_22 : Triple := ⟨5, 22, 27, by decide, by decide, by decide, by decide⟩
theorem sample_5_22_interval :
    (logCertificate_27.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_330.upper ≤
      discrepancy (1 / 10) sample_5_22 ∧
    discrepancy (1 / 10) sample_5_22 ≤
      (logCertificate_27.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_330.lower := by
  have hr : radical (5 * 22 * 27) = 330 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_5_22.a * sample_5_22.b * sample_5_22.c)) :=
    ⟨logCertificate_330.lower, logCertificate_330.upper,
      by simpa only [sample_5_22, hr] using logCertificate_330.lower_le,
      by simpa only [sample_5_22, hr] using logCertificate_330.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_5_22 logCertificate_27 support
  simpa only [support] using h

theorem sample_5_22_upper : discrepancy (1 / 10) sample_5_22 ≤ (227 / 1000) := by
  have h := sample_5_22_interval.2
  norm_num [logCertificate_27, logCertificate_330] at h
  linarith

def sample_7_20 : Triple := ⟨7, 20, 27, by decide, by decide, by decide, by decide⟩
theorem sample_7_20_interval :
    (logCertificate_27.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_210.upper ≤
      discrepancy (1 / 10) sample_7_20 ∧
    discrepancy (1 / 10) sample_7_20 ≤
      (logCertificate_27.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_210.lower := by
  have hr : radical (7 * 20 * 27) = 210 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_7_20.a * sample_7_20.b * sample_7_20.c)) :=
    ⟨logCertificate_210.lower, logCertificate_210.upper,
      by simpa only [sample_7_20, hr] using logCertificate_210.lower_le,
      by simpa only [sample_7_20, hr] using logCertificate_210.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_7_20 logCertificate_27 support
  simpa only [support] using h

theorem sample_7_20_upper : discrepancy (1 / 10) sample_7_20 ≤ (227 / 1000) := by
  have h := sample_7_20_interval.2
  norm_num [logCertificate_27, logCertificate_210] at h
  linarith

def sample_8_19 : Triple := ⟨8, 19, 27, by decide, by decide, by decide, by decide⟩
theorem sample_8_19_interval :
    (logCertificate_27.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_114.upper ≤
      discrepancy (1 / 10) sample_8_19 ∧
    discrepancy (1 / 10) sample_8_19 ≤
      (logCertificate_27.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_114.lower := by
  have hr : radical (8 * 19 * 27) = 114 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_8_19.a * sample_8_19.b * sample_8_19.c)) :=
    ⟨logCertificate_114.lower, logCertificate_114.upper,
      by simpa only [sample_8_19, hr] using logCertificate_114.lower_le,
      by simpa only [sample_8_19, hr] using logCertificate_114.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_8_19 logCertificate_27 support
  simpa only [support] using h

theorem sample_8_19_upper : discrepancy (1 / 10) sample_8_19 ≤ (227 / 1000) := by
  have h := sample_8_19_interval.2
  norm_num [logCertificate_27, logCertificate_114] at h
  linarith

def sample_10_17 : Triple := ⟨10, 17, 27, by decide, by decide, by decide, by decide⟩
theorem sample_10_17_interval :
    (logCertificate_27.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_510.upper ≤
      discrepancy (1 / 10) sample_10_17 ∧
    discrepancy (1 / 10) sample_10_17 ≤
      (logCertificate_27.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_510.lower := by
  have hr : radical (10 * 17 * 27) = 510 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_10_17.a * sample_10_17.b * sample_10_17.c)) :=
    ⟨logCertificate_510.lower, logCertificate_510.upper,
      by simpa only [sample_10_17, hr] using logCertificate_510.lower_le,
      by simpa only [sample_10_17, hr] using logCertificate_510.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_10_17 logCertificate_27 support
  simpa only [support] using h

theorem sample_10_17_upper : discrepancy (1 / 10) sample_10_17 ≤ (227 / 1000) := by
  have h := sample_10_17_interval.2
  norm_num [logCertificate_27, logCertificate_510] at h
  linarith

def sample_11_16 : Triple := ⟨11, 16, 27, by decide, by decide, by decide, by decide⟩
theorem sample_11_16_interval :
    (logCertificate_27.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_66.upper ≤
      discrepancy (1 / 10) sample_11_16 ∧
    discrepancy (1 / 10) sample_11_16 ≤
      (logCertificate_27.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_66.lower := by
  have hr : radical (11 * 16 * 27) = 66 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_11_16.a * sample_11_16.b * sample_11_16.c)) :=
    ⟨logCertificate_66.lower, logCertificate_66.upper,
      by simpa only [sample_11_16, hr] using logCertificate_66.lower_le,
      by simpa only [sample_11_16, hr] using logCertificate_66.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_11_16 logCertificate_27 support
  simpa only [support] using h

theorem sample_11_16_upper : discrepancy (1 / 10) sample_11_16 ≤ (227 / 1000) := by
  have h := sample_11_16_interval.2
  norm_num [logCertificate_27, logCertificate_66] at h
  linarith

def sample_13_14 : Triple := ⟨13, 14, 27, by decide, by decide, by decide, by decide⟩
theorem sample_13_14_interval :
    (logCertificate_27.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_546.upper ≤
      discrepancy (1 / 10) sample_13_14 ∧
    discrepancy (1 / 10) sample_13_14 ≤
      (logCertificate_27.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_546.lower := by
  have hr : radical (13 * 14 * 27) = 546 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_13_14.a * sample_13_14.b * sample_13_14.c)) :=
    ⟨logCertificate_546.lower, logCertificate_546.upper,
      by simpa only [sample_13_14, hr] using logCertificate_546.lower_le,
      by simpa only [sample_13_14, hr] using logCertificate_546.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_13_14 logCertificate_27 support
  simpa only [support] using h

theorem sample_13_14_upper : discrepancy (1 / 10) sample_13_14 ≤ (227 / 1000) := by
  have h := sample_13_14_interval.2
  norm_num [logCertificate_27, logCertificate_546] at h
  linarith

def sample_1_27 : Triple := ⟨1, 27, 28, by decide, by decide, by decide, by decide⟩
theorem sample_1_27_interval :
    (logCertificate_28.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_42.upper ≤
      discrepancy (1 / 10) sample_1_27 ∧
    discrepancy (1 / 10) sample_1_27 ≤
      (logCertificate_28.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_42.lower := by
  have hr : radical (1 * 27 * 28) = 42 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_1_27.a * sample_1_27.b * sample_1_27.c)) :=
    ⟨logCertificate_42.lower, logCertificate_42.upper,
      by simpa only [sample_1_27, hr] using logCertificate_42.lower_le,
      by simpa only [sample_1_27, hr] using logCertificate_42.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_1_27 logCertificate_28 support
  simpa only [support] using h

theorem sample_1_27_upper : discrepancy (1 / 10) sample_1_27 ≤ (227 / 1000) := by
  have h := sample_1_27_interval.2
  norm_num [logCertificate_28, logCertificate_42] at h
  linarith

def sample_3_25 : Triple := ⟨3, 25, 28, by decide, by decide, by decide, by decide⟩
theorem sample_3_25_interval :
    (logCertificate_28.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_210.upper ≤
      discrepancy (1 / 10) sample_3_25 ∧
    discrepancy (1 / 10) sample_3_25 ≤
      (logCertificate_28.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_210.lower := by
  have hr : radical (3 * 25 * 28) = 210 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_3_25.a * sample_3_25.b * sample_3_25.c)) :=
    ⟨logCertificate_210.lower, logCertificate_210.upper,
      by simpa only [sample_3_25, hr] using logCertificate_210.lower_le,
      by simpa only [sample_3_25, hr] using logCertificate_210.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_3_25 logCertificate_28 support
  simpa only [support] using h

theorem sample_3_25_upper : discrepancy (1 / 10) sample_3_25 ≤ (227 / 1000) := by
  have h := sample_3_25_interval.2
  norm_num [logCertificate_28, logCertificate_210] at h
  linarith

def sample_5_23 : Triple := ⟨5, 23, 28, by decide, by decide, by decide, by decide⟩
theorem sample_5_23_interval :
    (logCertificate_28.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1610.upper ≤
      discrepancy (1 / 10) sample_5_23 ∧
    discrepancy (1 / 10) sample_5_23 ≤
      (logCertificate_28.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1610.lower := by
  have hr : radical (5 * 23 * 28) = 1610 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_5_23.a * sample_5_23.b * sample_5_23.c)) :=
    ⟨logCertificate_1610.lower, logCertificate_1610.upper,
      by simpa only [sample_5_23, hr] using logCertificate_1610.lower_le,
      by simpa only [sample_5_23, hr] using logCertificate_1610.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_5_23 logCertificate_28 support
  simpa only [support] using h

theorem sample_5_23_upper : discrepancy (1 / 10) sample_5_23 ≤ (227 / 1000) := by
  have h := sample_5_23_interval.2
  norm_num [logCertificate_28, logCertificate_1610] at h
  linarith

def sample_9_19 : Triple := ⟨9, 19, 28, by decide, by decide, by decide, by decide⟩
theorem sample_9_19_interval :
    (logCertificate_28.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_798.upper ≤
      discrepancy (1 / 10) sample_9_19 ∧
    discrepancy (1 / 10) sample_9_19 ≤
      (logCertificate_28.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_798.lower := by
  have hr : radical (9 * 19 * 28) = 798 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_9_19.a * sample_9_19.b * sample_9_19.c)) :=
    ⟨logCertificate_798.lower, logCertificate_798.upper,
      by simpa only [sample_9_19, hr] using logCertificate_798.lower_le,
      by simpa only [sample_9_19, hr] using logCertificate_798.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_9_19 logCertificate_28 support
  simpa only [support] using h

theorem sample_9_19_upper : discrepancy (1 / 10) sample_9_19 ≤ (227 / 1000) := by
  have h := sample_9_19_interval.2
  norm_num [logCertificate_28, logCertificate_798] at h
  linarith

def sample_11_17 : Triple := ⟨11, 17, 28, by decide, by decide, by decide, by decide⟩
theorem sample_11_17_interval :
    (logCertificate_28.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_2618.upper ≤
      discrepancy (1 / 10) sample_11_17 ∧
    discrepancy (1 / 10) sample_11_17 ≤
      (logCertificate_28.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_2618.lower := by
  have hr : radical (11 * 17 * 28) = 2618 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_11_17.a * sample_11_17.b * sample_11_17.c)) :=
    ⟨logCertificate_2618.lower, logCertificate_2618.upper,
      by simpa only [sample_11_17, hr] using logCertificate_2618.lower_le,
      by simpa only [sample_11_17, hr] using logCertificate_2618.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_11_17 logCertificate_28 support
  simpa only [support] using h

theorem sample_11_17_upper : discrepancy (1 / 10) sample_11_17 ≤ (227 / 1000) := by
  have h := sample_11_17_interval.2
  norm_num [logCertificate_28, logCertificate_2618] at h
  linarith

def sample_13_15 : Triple := ⟨13, 15, 28, by decide, by decide, by decide, by decide⟩
theorem sample_13_15_interval :
    (logCertificate_28.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_2730.upper ≤
      discrepancy (1 / 10) sample_13_15 ∧
    discrepancy (1 / 10) sample_13_15 ≤
      (logCertificate_28.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_2730.lower := by
  have hr : radical (13 * 15 * 28) = 2730 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_13_15.a * sample_13_15.b * sample_13_15.c)) :=
    ⟨logCertificate_2730.lower, logCertificate_2730.upper,
      by simpa only [sample_13_15, hr] using logCertificate_2730.lower_le,
      by simpa only [sample_13_15, hr] using logCertificate_2730.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_13_15 logCertificate_28 support
  simpa only [support] using h

theorem sample_13_15_upper : discrepancy (1 / 10) sample_13_15 ≤ (227 / 1000) := by
  have h := sample_13_15_interval.2
  norm_num [logCertificate_28, logCertificate_2730] at h
  linarith

def sample_1_28 : Triple := ⟨1, 28, 29, by decide, by decide, by decide, by decide⟩
theorem sample_1_28_interval :
    (logCertificate_29.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_406.upper ≤
      discrepancy (1 / 10) sample_1_28 ∧
    discrepancy (1 / 10) sample_1_28 ≤
      (logCertificate_29.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_406.lower := by
  have hr : radical (1 * 28 * 29) = 406 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_1_28.a * sample_1_28.b * sample_1_28.c)) :=
    ⟨logCertificate_406.lower, logCertificate_406.upper,
      by simpa only [sample_1_28, hr] using logCertificate_406.lower_le,
      by simpa only [sample_1_28, hr] using logCertificate_406.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_1_28 logCertificate_29 support
  simpa only [support] using h

theorem sample_1_28_upper : discrepancy (1 / 10) sample_1_28 ≤ (227 / 1000) := by
  have h := sample_1_28_interval.2
  norm_num [logCertificate_29, logCertificate_406] at h
  linarith

def sample_2_27 : Triple := ⟨2, 27, 29, by decide, by decide, by decide, by decide⟩
theorem sample_2_27_interval :
    (logCertificate_29.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_174.upper ≤
      discrepancy (1 / 10) sample_2_27 ∧
    discrepancy (1 / 10) sample_2_27 ≤
      (logCertificate_29.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_174.lower := by
  have hr : radical (2 * 27 * 29) = 174 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_2_27.a * sample_2_27.b * sample_2_27.c)) :=
    ⟨logCertificate_174.lower, logCertificate_174.upper,
      by simpa only [sample_2_27, hr] using logCertificate_174.lower_le,
      by simpa only [sample_2_27, hr] using logCertificate_174.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_2_27 logCertificate_29 support
  simpa only [support] using h

theorem sample_2_27_upper : discrepancy (1 / 10) sample_2_27 ≤ (227 / 1000) := by
  have h := sample_2_27_interval.2
  norm_num [logCertificate_29, logCertificate_174] at h
  linarith

def sample_3_26 : Triple := ⟨3, 26, 29, by decide, by decide, by decide, by decide⟩
theorem sample_3_26_interval :
    (logCertificate_29.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_2262.upper ≤
      discrepancy (1 / 10) sample_3_26 ∧
    discrepancy (1 / 10) sample_3_26 ≤
      (logCertificate_29.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_2262.lower := by
  have hr : radical (3 * 26 * 29) = 2262 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_3_26.a * sample_3_26.b * sample_3_26.c)) :=
    ⟨logCertificate_2262.lower, logCertificate_2262.upper,
      by simpa only [sample_3_26, hr] using logCertificate_2262.lower_le,
      by simpa only [sample_3_26, hr] using logCertificate_2262.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_3_26 logCertificate_29 support
  simpa only [support] using h

theorem sample_3_26_upper : discrepancy (1 / 10) sample_3_26 ≤ (227 / 1000) := by
  have h := sample_3_26_interval.2
  norm_num [logCertificate_29, logCertificate_2262] at h
  linarith

def sample_4_25 : Triple := ⟨4, 25, 29, by decide, by decide, by decide, by decide⟩
theorem sample_4_25_interval :
    (logCertificate_29.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_290.upper ≤
      discrepancy (1 / 10) sample_4_25 ∧
    discrepancy (1 / 10) sample_4_25 ≤
      (logCertificate_29.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_290.lower := by
  have hr : radical (4 * 25 * 29) = 290 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_4_25.a * sample_4_25.b * sample_4_25.c)) :=
    ⟨logCertificate_290.lower, logCertificate_290.upper,
      by simpa only [sample_4_25, hr] using logCertificate_290.lower_le,
      by simpa only [sample_4_25, hr] using logCertificate_290.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_4_25 logCertificate_29 support
  simpa only [support] using h

theorem sample_4_25_upper : discrepancy (1 / 10) sample_4_25 ≤ (227 / 1000) := by
  have h := sample_4_25_interval.2
  norm_num [logCertificate_29, logCertificate_290] at h
  linarith

def sample_5_24 : Triple := ⟨5, 24, 29, by decide, by decide, by decide, by decide⟩
theorem sample_5_24_interval :
    (logCertificate_29.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_870.upper ≤
      discrepancy (1 / 10) sample_5_24 ∧
    discrepancy (1 / 10) sample_5_24 ≤
      (logCertificate_29.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_870.lower := by
  have hr : radical (5 * 24 * 29) = 870 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_5_24.a * sample_5_24.b * sample_5_24.c)) :=
    ⟨logCertificate_870.lower, logCertificate_870.upper,
      by simpa only [sample_5_24, hr] using logCertificate_870.lower_le,
      by simpa only [sample_5_24, hr] using logCertificate_870.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_5_24 logCertificate_29 support
  simpa only [support] using h

theorem sample_5_24_upper : discrepancy (1 / 10) sample_5_24 ≤ (227 / 1000) := by
  have h := sample_5_24_interval.2
  norm_num [logCertificate_29, logCertificate_870] at h
  linarith

def sample_6_23 : Triple := ⟨6, 23, 29, by decide, by decide, by decide, by decide⟩
theorem sample_6_23_interval :
    (logCertificate_29.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_4002.upper ≤
      discrepancy (1 / 10) sample_6_23 ∧
    discrepancy (1 / 10) sample_6_23 ≤
      (logCertificate_29.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_4002.lower := by
  have hr : radical (6 * 23 * 29) = 4002 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_6_23.a * sample_6_23.b * sample_6_23.c)) :=
    ⟨logCertificate_4002.lower, logCertificate_4002.upper,
      by simpa only [sample_6_23, hr] using logCertificate_4002.lower_le,
      by simpa only [sample_6_23, hr] using logCertificate_4002.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_6_23 logCertificate_29 support
  simpa only [support] using h

theorem sample_6_23_upper : discrepancy (1 / 10) sample_6_23 ≤ (227 / 1000) := by
  have h := sample_6_23_interval.2
  norm_num [logCertificate_29, logCertificate_4002] at h
  linarith

def sample_7_22 : Triple := ⟨7, 22, 29, by decide, by decide, by decide, by decide⟩
theorem sample_7_22_interval :
    (logCertificate_29.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_4466.upper ≤
      discrepancy (1 / 10) sample_7_22 ∧
    discrepancy (1 / 10) sample_7_22 ≤
      (logCertificate_29.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_4466.lower := by
  have hr : radical (7 * 22 * 29) = 4466 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_7_22.a * sample_7_22.b * sample_7_22.c)) :=
    ⟨logCertificate_4466.lower, logCertificate_4466.upper,
      by simpa only [sample_7_22, hr] using logCertificate_4466.lower_le,
      by simpa only [sample_7_22, hr] using logCertificate_4466.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_7_22 logCertificate_29 support
  simpa only [support] using h

theorem sample_7_22_upper : discrepancy (1 / 10) sample_7_22 ≤ (227 / 1000) := by
  have h := sample_7_22_interval.2
  norm_num [logCertificate_29, logCertificate_4466] at h
  linarith

def sample_8_21 : Triple := ⟨8, 21, 29, by decide, by decide, by decide, by decide⟩
theorem sample_8_21_interval :
    (logCertificate_29.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1218.upper ≤
      discrepancy (1 / 10) sample_8_21 ∧
    discrepancy (1 / 10) sample_8_21 ≤
      (logCertificate_29.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1218.lower := by
  have hr : radical (8 * 21 * 29) = 1218 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_8_21.a * sample_8_21.b * sample_8_21.c)) :=
    ⟨logCertificate_1218.lower, logCertificate_1218.upper,
      by simpa only [sample_8_21, hr] using logCertificate_1218.lower_le,
      by simpa only [sample_8_21, hr] using logCertificate_1218.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_8_21 logCertificate_29 support
  simpa only [support] using h

theorem sample_8_21_upper : discrepancy (1 / 10) sample_8_21 ≤ (227 / 1000) := by
  have h := sample_8_21_interval.2
  norm_num [logCertificate_29, logCertificate_1218] at h
  linarith

def sample_9_20 : Triple := ⟨9, 20, 29, by decide, by decide, by decide, by decide⟩
theorem sample_9_20_interval :
    (logCertificate_29.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_870.upper ≤
      discrepancy (1 / 10) sample_9_20 ∧
    discrepancy (1 / 10) sample_9_20 ≤
      (logCertificate_29.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_870.lower := by
  have hr : radical (9 * 20 * 29) = 870 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_9_20.a * sample_9_20.b * sample_9_20.c)) :=
    ⟨logCertificate_870.lower, logCertificate_870.upper,
      by simpa only [sample_9_20, hr] using logCertificate_870.lower_le,
      by simpa only [sample_9_20, hr] using logCertificate_870.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_9_20 logCertificate_29 support
  simpa only [support] using h

theorem sample_9_20_upper : discrepancy (1 / 10) sample_9_20 ≤ (227 / 1000) := by
  have h := sample_9_20_interval.2
  norm_num [logCertificate_29, logCertificate_870] at h
  linarith

def sample_10_19 : Triple := ⟨10, 19, 29, by decide, by decide, by decide, by decide⟩
theorem sample_10_19_interval :
    (logCertificate_29.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_5510.upper ≤
      discrepancy (1 / 10) sample_10_19 ∧
    discrepancy (1 / 10) sample_10_19 ≤
      (logCertificate_29.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_5510.lower := by
  have hr : radical (10 * 19 * 29) = 5510 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_10_19.a * sample_10_19.b * sample_10_19.c)) :=
    ⟨logCertificate_5510.lower, logCertificate_5510.upper,
      by simpa only [sample_10_19, hr] using logCertificate_5510.lower_le,
      by simpa only [sample_10_19, hr] using logCertificate_5510.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_10_19 logCertificate_29 support
  simpa only [support] using h

theorem sample_10_19_upper : discrepancy (1 / 10) sample_10_19 ≤ (227 / 1000) := by
  have h := sample_10_19_interval.2
  norm_num [logCertificate_29, logCertificate_5510] at h
  linarith

def sample_11_18 : Triple := ⟨11, 18, 29, by decide, by decide, by decide, by decide⟩
theorem sample_11_18_interval :
    (logCertificate_29.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1914.upper ≤
      discrepancy (1 / 10) sample_11_18 ∧
    discrepancy (1 / 10) sample_11_18 ≤
      (logCertificate_29.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1914.lower := by
  have hr : radical (11 * 18 * 29) = 1914 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_11_18.a * sample_11_18.b * sample_11_18.c)) :=
    ⟨logCertificate_1914.lower, logCertificate_1914.upper,
      by simpa only [sample_11_18, hr] using logCertificate_1914.lower_le,
      by simpa only [sample_11_18, hr] using logCertificate_1914.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_11_18 logCertificate_29 support
  simpa only [support] using h

theorem sample_11_18_upper : discrepancy (1 / 10) sample_11_18 ≤ (227 / 1000) := by
  have h := sample_11_18_interval.2
  norm_num [logCertificate_29, logCertificate_1914] at h
  linarith

def sample_12_17 : Triple := ⟨12, 17, 29, by decide, by decide, by decide, by decide⟩
theorem sample_12_17_interval :
    (logCertificate_29.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_2958.upper ≤
      discrepancy (1 / 10) sample_12_17 ∧
    discrepancy (1 / 10) sample_12_17 ≤
      (logCertificate_29.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_2958.lower := by
  have hr : radical (12 * 17 * 29) = 2958 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_12_17.a * sample_12_17.b * sample_12_17.c)) :=
    ⟨logCertificate_2958.lower, logCertificate_2958.upper,
      by simpa only [sample_12_17, hr] using logCertificate_2958.lower_le,
      by simpa only [sample_12_17, hr] using logCertificate_2958.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_12_17 logCertificate_29 support
  simpa only [support] using h

theorem sample_12_17_upper : discrepancy (1 / 10) sample_12_17 ≤ (227 / 1000) := by
  have h := sample_12_17_interval.2
  norm_num [logCertificate_29, logCertificate_2958] at h
  linarith

def sample_13_16 : Triple := ⟨13, 16, 29, by decide, by decide, by decide, by decide⟩
theorem sample_13_16_interval :
    (logCertificate_29.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_754.upper ≤
      discrepancy (1 / 10) sample_13_16 ∧
    discrepancy (1 / 10) sample_13_16 ≤
      (logCertificate_29.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_754.lower := by
  have hr : radical (13 * 16 * 29) = 754 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_13_16.a * sample_13_16.b * sample_13_16.c)) :=
    ⟨logCertificate_754.lower, logCertificate_754.upper,
      by simpa only [sample_13_16, hr] using logCertificate_754.lower_le,
      by simpa only [sample_13_16, hr] using logCertificate_754.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_13_16 logCertificate_29 support
  simpa only [support] using h

theorem sample_13_16_upper : discrepancy (1 / 10) sample_13_16 ≤ (227 / 1000) := by
  have h := sample_13_16_interval.2
  norm_num [logCertificate_29, logCertificate_754] at h
  linarith

def sample_14_15 : Triple := ⟨14, 15, 29, by decide, by decide, by decide, by decide⟩
theorem sample_14_15_interval :
    (logCertificate_29.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_6090.upper ≤
      discrepancy (1 / 10) sample_14_15 ∧
    discrepancy (1 / 10) sample_14_15 ≤
      (logCertificate_29.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_6090.lower := by
  have hr : radical (14 * 15 * 29) = 6090 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_14_15.a * sample_14_15.b * sample_14_15.c)) :=
    ⟨logCertificate_6090.lower, logCertificate_6090.upper,
      by simpa only [sample_14_15, hr] using logCertificate_6090.lower_le,
      by simpa only [sample_14_15, hr] using logCertificate_6090.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_14_15 logCertificate_29 support
  simpa only [support] using h

theorem sample_14_15_upper : discrepancy (1 / 10) sample_14_15 ≤ (227 / 1000) := by
  have h := sample_14_15_interval.2
  norm_num [logCertificate_29, logCertificate_6090] at h
  linarith

def sample_1_29 : Triple := ⟨1, 29, 30, by decide, by decide, by decide, by decide⟩
theorem sample_1_29_interval :
    (logCertificate_30.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_870.upper ≤
      discrepancy (1 / 10) sample_1_29 ∧
    discrepancy (1 / 10) sample_1_29 ≤
      (logCertificate_30.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_870.lower := by
  have hr : radical (1 * 29 * 30) = 870 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_1_29.a * sample_1_29.b * sample_1_29.c)) :=
    ⟨logCertificate_870.lower, logCertificate_870.upper,
      by simpa only [sample_1_29, hr] using logCertificate_870.lower_le,
      by simpa only [sample_1_29, hr] using logCertificate_870.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_1_29 logCertificate_30 support
  simpa only [support] using h

theorem sample_1_29_upper : discrepancy (1 / 10) sample_1_29 ≤ (227 / 1000) := by
  have h := sample_1_29_interval.2
  norm_num [logCertificate_30, logCertificate_870] at h
  linarith

def sample_7_23 : Triple := ⟨7, 23, 30, by decide, by decide, by decide, by decide⟩
theorem sample_7_23_interval :
    (logCertificate_30.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_4830.upper ≤
      discrepancy (1 / 10) sample_7_23 ∧
    discrepancy (1 / 10) sample_7_23 ≤
      (logCertificate_30.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_4830.lower := by
  have hr : radical (7 * 23 * 30) = 4830 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_7_23.a * sample_7_23.b * sample_7_23.c)) :=
    ⟨logCertificate_4830.lower, logCertificate_4830.upper,
      by simpa only [sample_7_23, hr] using logCertificate_4830.lower_le,
      by simpa only [sample_7_23, hr] using logCertificate_4830.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_7_23 logCertificate_30 support
  simpa only [support] using h

theorem sample_7_23_upper : discrepancy (1 / 10) sample_7_23 ≤ (227 / 1000) := by
  have h := sample_7_23_interval.2
  norm_num [logCertificate_30, logCertificate_4830] at h
  linarith

def sample_11_19 : Triple := ⟨11, 19, 30, by decide, by decide, by decide, by decide⟩
theorem sample_11_19_interval :
    (logCertificate_30.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_6270.upper ≤
      discrepancy (1 / 10) sample_11_19 ∧
    discrepancy (1 / 10) sample_11_19 ≤
      (logCertificate_30.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_6270.lower := by
  have hr : radical (11 * 19 * 30) = 6270 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_11_19.a * sample_11_19.b * sample_11_19.c)) :=
    ⟨logCertificate_6270.lower, logCertificate_6270.upper,
      by simpa only [sample_11_19, hr] using logCertificate_6270.lower_le,
      by simpa only [sample_11_19, hr] using logCertificate_6270.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_11_19 logCertificate_30 support
  simpa only [support] using h

theorem sample_11_19_upper : discrepancy (1 / 10) sample_11_19 ≤ (227 / 1000) := by
  have h := sample_11_19_interval.2
  norm_num [logCertificate_30, logCertificate_6270] at h
  linarith

def sample_13_17 : Triple := ⟨13, 17, 30, by decide, by decide, by decide, by decide⟩
theorem sample_13_17_interval :
    (logCertificate_30.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_6630.upper ≤
      discrepancy (1 / 10) sample_13_17 ∧
    discrepancy (1 / 10) sample_13_17 ≤
      (logCertificate_30.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_6630.lower := by
  have hr : radical (13 * 17 * 30) = 6630 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_13_17.a * sample_13_17.b * sample_13_17.c)) :=
    ⟨logCertificate_6630.lower, logCertificate_6630.upper,
      by simpa only [sample_13_17, hr] using logCertificate_6630.lower_le,
      by simpa only [sample_13_17, hr] using logCertificate_6630.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_13_17 logCertificate_30 support
  simpa only [support] using h

theorem sample_13_17_upper : discrepancy (1 / 10) sample_13_17 ≤ (227 / 1000) := by
  have h := sample_13_17_interval.2
  norm_num [logCertificate_30, logCertificate_6630] at h
  linarith

def sample_1_30 : Triple := ⟨1, 30, 31, by decide, by decide, by decide, by decide⟩
theorem sample_1_30_interval :
    (logCertificate_31.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_930.upper ≤
      discrepancy (1 / 10) sample_1_30 ∧
    discrepancy (1 / 10) sample_1_30 ≤
      (logCertificate_31.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_930.lower := by
  have hr : radical (1 * 30 * 31) = 930 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_1_30.a * sample_1_30.b * sample_1_30.c)) :=
    ⟨logCertificate_930.lower, logCertificate_930.upper,
      by simpa only [sample_1_30, hr] using logCertificate_930.lower_le,
      by simpa only [sample_1_30, hr] using logCertificate_930.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_1_30 logCertificate_31 support
  simpa only [support] using h

theorem sample_1_30_upper : discrepancy (1 / 10) sample_1_30 ≤ (227 / 1000) := by
  have h := sample_1_30_interval.2
  norm_num [logCertificate_31, logCertificate_930] at h
  linarith

def sample_2_29 : Triple := ⟨2, 29, 31, by decide, by decide, by decide, by decide⟩
theorem sample_2_29_interval :
    (logCertificate_31.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1798.upper ≤
      discrepancy (1 / 10) sample_2_29 ∧
    discrepancy (1 / 10) sample_2_29 ≤
      (logCertificate_31.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1798.lower := by
  have hr : radical (2 * 29 * 31) = 1798 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_2_29.a * sample_2_29.b * sample_2_29.c)) :=
    ⟨logCertificate_1798.lower, logCertificate_1798.upper,
      by simpa only [sample_2_29, hr] using logCertificate_1798.lower_le,
      by simpa only [sample_2_29, hr] using logCertificate_1798.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_2_29 logCertificate_31 support
  simpa only [support] using h

theorem sample_2_29_upper : discrepancy (1 / 10) sample_2_29 ≤ (227 / 1000) := by
  have h := sample_2_29_interval.2
  norm_num [logCertificate_31, logCertificate_1798] at h
  linarith

def sample_3_28 : Triple := ⟨3, 28, 31, by decide, by decide, by decide, by decide⟩
theorem sample_3_28_interval :
    (logCertificate_31.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1302.upper ≤
      discrepancy (1 / 10) sample_3_28 ∧
    discrepancy (1 / 10) sample_3_28 ≤
      (logCertificate_31.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1302.lower := by
  have hr : radical (3 * 28 * 31) = 1302 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_3_28.a * sample_3_28.b * sample_3_28.c)) :=
    ⟨logCertificate_1302.lower, logCertificate_1302.upper,
      by simpa only [sample_3_28, hr] using logCertificate_1302.lower_le,
      by simpa only [sample_3_28, hr] using logCertificate_1302.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_3_28 logCertificate_31 support
  simpa only [support] using h

theorem sample_3_28_upper : discrepancy (1 / 10) sample_3_28 ≤ (227 / 1000) := by
  have h := sample_3_28_interval.2
  norm_num [logCertificate_31, logCertificate_1302] at h
  linarith

def sample_4_27 : Triple := ⟨4, 27, 31, by decide, by decide, by decide, by decide⟩
theorem sample_4_27_interval :
    (logCertificate_31.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_186.upper ≤
      discrepancy (1 / 10) sample_4_27 ∧
    discrepancy (1 / 10) sample_4_27 ≤
      (logCertificate_31.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_186.lower := by
  have hr : radical (4 * 27 * 31) = 186 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_4_27.a * sample_4_27.b * sample_4_27.c)) :=
    ⟨logCertificate_186.lower, logCertificate_186.upper,
      by simpa only [sample_4_27, hr] using logCertificate_186.lower_le,
      by simpa only [sample_4_27, hr] using logCertificate_186.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_4_27 logCertificate_31 support
  simpa only [support] using h

theorem sample_4_27_upper : discrepancy (1 / 10) sample_4_27 ≤ (227 / 1000) := by
  have h := sample_4_27_interval.2
  norm_num [logCertificate_31, logCertificate_186] at h
  linarith

def sample_5_26 : Triple := ⟨5, 26, 31, by decide, by decide, by decide, by decide⟩
theorem sample_5_26_interval :
    (logCertificate_31.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_4030.upper ≤
      discrepancy (1 / 10) sample_5_26 ∧
    discrepancy (1 / 10) sample_5_26 ≤
      (logCertificate_31.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_4030.lower := by
  have hr : radical (5 * 26 * 31) = 4030 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_5_26.a * sample_5_26.b * sample_5_26.c)) :=
    ⟨logCertificate_4030.lower, logCertificate_4030.upper,
      by simpa only [sample_5_26, hr] using logCertificate_4030.lower_le,
      by simpa only [sample_5_26, hr] using logCertificate_4030.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_5_26 logCertificate_31 support
  simpa only [support] using h

theorem sample_5_26_upper : discrepancy (1 / 10) sample_5_26 ≤ (227 / 1000) := by
  have h := sample_5_26_interval.2
  norm_num [logCertificate_31, logCertificate_4030] at h
  linarith

def sample_6_25 : Triple := ⟨6, 25, 31, by decide, by decide, by decide, by decide⟩
theorem sample_6_25_interval :
    (logCertificate_31.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_930.upper ≤
      discrepancy (1 / 10) sample_6_25 ∧
    discrepancy (1 / 10) sample_6_25 ≤
      (logCertificate_31.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_930.lower := by
  have hr : radical (6 * 25 * 31) = 930 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_6_25.a * sample_6_25.b * sample_6_25.c)) :=
    ⟨logCertificate_930.lower, logCertificate_930.upper,
      by simpa only [sample_6_25, hr] using logCertificate_930.lower_le,
      by simpa only [sample_6_25, hr] using logCertificate_930.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_6_25 logCertificate_31 support
  simpa only [support] using h

theorem sample_6_25_upper : discrepancy (1 / 10) sample_6_25 ≤ (227 / 1000) := by
  have h := sample_6_25_interval.2
  norm_num [logCertificate_31, logCertificate_930] at h
  linarith

def sample_7_24 : Triple := ⟨7, 24, 31, by decide, by decide, by decide, by decide⟩
theorem sample_7_24_interval :
    (logCertificate_31.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1302.upper ≤
      discrepancy (1 / 10) sample_7_24 ∧
    discrepancy (1 / 10) sample_7_24 ≤
      (logCertificate_31.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1302.lower := by
  have hr : radical (7 * 24 * 31) = 1302 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_7_24.a * sample_7_24.b * sample_7_24.c)) :=
    ⟨logCertificate_1302.lower, logCertificate_1302.upper,
      by simpa only [sample_7_24, hr] using logCertificate_1302.lower_le,
      by simpa only [sample_7_24, hr] using logCertificate_1302.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_7_24 logCertificate_31 support
  simpa only [support] using h

theorem sample_7_24_upper : discrepancy (1 / 10) sample_7_24 ≤ (227 / 1000) := by
  have h := sample_7_24_interval.2
  norm_num [logCertificate_31, logCertificate_1302] at h
  linarith

def sample_8_23 : Triple := ⟨8, 23, 31, by decide, by decide, by decide, by decide⟩
theorem sample_8_23_interval :
    (logCertificate_31.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1426.upper ≤
      discrepancy (1 / 10) sample_8_23 ∧
    discrepancy (1 / 10) sample_8_23 ≤
      (logCertificate_31.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1426.lower := by
  have hr : radical (8 * 23 * 31) = 1426 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_8_23.a * sample_8_23.b * sample_8_23.c)) :=
    ⟨logCertificate_1426.lower, logCertificate_1426.upper,
      by simpa only [sample_8_23, hr] using logCertificate_1426.lower_le,
      by simpa only [sample_8_23, hr] using logCertificate_1426.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_8_23 logCertificate_31 support
  simpa only [support] using h

theorem sample_8_23_upper : discrepancy (1 / 10) sample_8_23 ≤ (227 / 1000) := by
  have h := sample_8_23_interval.2
  norm_num [logCertificate_31, logCertificate_1426] at h
  linarith

def sample_9_22 : Triple := ⟨9, 22, 31, by decide, by decide, by decide, by decide⟩
theorem sample_9_22_interval :
    (logCertificate_31.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_2046.upper ≤
      discrepancy (1 / 10) sample_9_22 ∧
    discrepancy (1 / 10) sample_9_22 ≤
      (logCertificate_31.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_2046.lower := by
  have hr : radical (9 * 22 * 31) = 2046 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_9_22.a * sample_9_22.b * sample_9_22.c)) :=
    ⟨logCertificate_2046.lower, logCertificate_2046.upper,
      by simpa only [sample_9_22, hr] using logCertificate_2046.lower_le,
      by simpa only [sample_9_22, hr] using logCertificate_2046.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_9_22 logCertificate_31 support
  simpa only [support] using h

theorem sample_9_22_upper : discrepancy (1 / 10) sample_9_22 ≤ (227 / 1000) := by
  have h := sample_9_22_interval.2
  norm_num [logCertificate_31, logCertificate_2046] at h
  linarith

def sample_10_21 : Triple := ⟨10, 21, 31, by decide, by decide, by decide, by decide⟩
theorem sample_10_21_interval :
    (logCertificate_31.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_6510.upper ≤
      discrepancy (1 / 10) sample_10_21 ∧
    discrepancy (1 / 10) sample_10_21 ≤
      (logCertificate_31.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_6510.lower := by
  have hr : radical (10 * 21 * 31) = 6510 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_10_21.a * sample_10_21.b * sample_10_21.c)) :=
    ⟨logCertificate_6510.lower, logCertificate_6510.upper,
      by simpa only [sample_10_21, hr] using logCertificate_6510.lower_le,
      by simpa only [sample_10_21, hr] using logCertificate_6510.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_10_21 logCertificate_31 support
  simpa only [support] using h

theorem sample_10_21_upper : discrepancy (1 / 10) sample_10_21 ≤ (227 / 1000) := by
  have h := sample_10_21_interval.2
  norm_num [logCertificate_31, logCertificate_6510] at h
  linarith

def sample_11_20 : Triple := ⟨11, 20, 31, by decide, by decide, by decide, by decide⟩
theorem sample_11_20_interval :
    (logCertificate_31.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_3410.upper ≤
      discrepancy (1 / 10) sample_11_20 ∧
    discrepancy (1 / 10) sample_11_20 ≤
      (logCertificate_31.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_3410.lower := by
  have hr : radical (11 * 20 * 31) = 3410 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_11_20.a * sample_11_20.b * sample_11_20.c)) :=
    ⟨logCertificate_3410.lower, logCertificate_3410.upper,
      by simpa only [sample_11_20, hr] using logCertificate_3410.lower_le,
      by simpa only [sample_11_20, hr] using logCertificate_3410.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_11_20 logCertificate_31 support
  simpa only [support] using h

theorem sample_11_20_upper : discrepancy (1 / 10) sample_11_20 ≤ (227 / 1000) := by
  have h := sample_11_20_interval.2
  norm_num [logCertificate_31, logCertificate_3410] at h
  linarith

def sample_12_19 : Triple := ⟨12, 19, 31, by decide, by decide, by decide, by decide⟩
theorem sample_12_19_interval :
    (logCertificate_31.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_3534.upper ≤
      discrepancy (1 / 10) sample_12_19 ∧
    discrepancy (1 / 10) sample_12_19 ≤
      (logCertificate_31.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_3534.lower := by
  have hr : radical (12 * 19 * 31) = 3534 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_12_19.a * sample_12_19.b * sample_12_19.c)) :=
    ⟨logCertificate_3534.lower, logCertificate_3534.upper,
      by simpa only [sample_12_19, hr] using logCertificate_3534.lower_le,
      by simpa only [sample_12_19, hr] using logCertificate_3534.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_12_19 logCertificate_31 support
  simpa only [support] using h

theorem sample_12_19_upper : discrepancy (1 / 10) sample_12_19 ≤ (227 / 1000) := by
  have h := sample_12_19_interval.2
  norm_num [logCertificate_31, logCertificate_3534] at h
  linarith

def sample_13_18 : Triple := ⟨13, 18, 31, by decide, by decide, by decide, by decide⟩
theorem sample_13_18_interval :
    (logCertificate_31.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_2418.upper ≤
      discrepancy (1 / 10) sample_13_18 ∧
    discrepancy (1 / 10) sample_13_18 ≤
      (logCertificate_31.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_2418.lower := by
  have hr : radical (13 * 18 * 31) = 2418 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_13_18.a * sample_13_18.b * sample_13_18.c)) :=
    ⟨logCertificate_2418.lower, logCertificate_2418.upper,
      by simpa only [sample_13_18, hr] using logCertificate_2418.lower_le,
      by simpa only [sample_13_18, hr] using logCertificate_2418.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_13_18 logCertificate_31 support
  simpa only [support] using h

theorem sample_13_18_upper : discrepancy (1 / 10) sample_13_18 ≤ (227 / 1000) := by
  have h := sample_13_18_interval.2
  norm_num [logCertificate_31, logCertificate_2418] at h
  linarith

def sample_14_17 : Triple := ⟨14, 17, 31, by decide, by decide, by decide, by decide⟩
theorem sample_14_17_interval :
    (logCertificate_31.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_7378.upper ≤
      discrepancy (1 / 10) sample_14_17 ∧
    discrepancy (1 / 10) sample_14_17 ≤
      (logCertificate_31.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_7378.lower := by
  have hr : radical (14 * 17 * 31) = 7378 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_14_17.a * sample_14_17.b * sample_14_17.c)) :=
    ⟨logCertificate_7378.lower, logCertificate_7378.upper,
      by simpa only [sample_14_17, hr] using logCertificate_7378.lower_le,
      by simpa only [sample_14_17, hr] using logCertificate_7378.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_14_17 logCertificate_31 support
  simpa only [support] using h

theorem sample_14_17_upper : discrepancy (1 / 10) sample_14_17 ≤ (227 / 1000) := by
  have h := sample_14_17_interval.2
  norm_num [logCertificate_31, logCertificate_7378] at h
  linarith

def sample_15_16 : Triple := ⟨15, 16, 31, by decide, by decide, by decide, by decide⟩
theorem sample_15_16_interval :
    (logCertificate_31.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_930.upper ≤
      discrepancy (1 / 10) sample_15_16 ∧
    discrepancy (1 / 10) sample_15_16 ≤
      (logCertificate_31.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_930.lower := by
  have hr : radical (15 * 16 * 31) = 930 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_15_16.a * sample_15_16.b * sample_15_16.c)) :=
    ⟨logCertificate_930.lower, logCertificate_930.upper,
      by simpa only [sample_15_16, hr] using logCertificate_930.lower_le,
      by simpa only [sample_15_16, hr] using logCertificate_930.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_15_16 logCertificate_31 support
  simpa only [support] using h

theorem sample_15_16_upper : discrepancy (1 / 10) sample_15_16 ≤ (227 / 1000) := by
  have h := sample_15_16_interval.2
  norm_num [logCertificate_31, logCertificate_930] at h
  linarith


end Imscribing.ABC.Window70E1_10
