import Imscribing.ABC_Window70_FromOS_Samples5

/-! Generated by scripts/abc_emit_window_certificate.py; all claims checked by Lean. -/
namespace Imscribing.ABC.Window70E1_10

set_option maxRecDepth 8192
set_option maxHeartbeats 4000000
set_option synthInstance.maxSize 16384
set_option synthInstance.maxHeartbeats 4000000

def sample_1_49 : Triple := ⟨1, 49, 50, by decide, by decide, by decide, by decide⟩
theorem sample_1_49_interval :
    (logCertificate_50.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_70.upper ≤
      discrepancy (1 / 10) sample_1_49 ∧
    discrepancy (1 / 10) sample_1_49 ≤
      (logCertificate_50.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_70.lower := by
  have hr : radical (1 * 49 * 50) = 70 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_1_49.a * sample_1_49.b * sample_1_49.c)) :=
    ⟨logCertificate_70.lower, logCertificate_70.upper,
      by simpa only [sample_1_49, hr] using logCertificate_70.lower_le,
      by simpa only [sample_1_49, hr] using logCertificate_70.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_1_49 logCertificate_50 support
  simpa only [support] using h

theorem sample_1_49_upper : discrepancy (1 / 10) sample_1_49 ≤ (227 / 1000) := by
  have h := sample_1_49_interval.2
  norm_num [logCertificate_50, logCertificate_70] at h
  linarith

def sample_3_47 : Triple := ⟨3, 47, 50, by decide, by decide, by decide, by decide⟩
theorem sample_3_47_interval :
    (logCertificate_50.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1410.upper ≤
      discrepancy (1 / 10) sample_3_47 ∧
    discrepancy (1 / 10) sample_3_47 ≤
      (logCertificate_50.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1410.lower := by
  have hr : radical (3 * 47 * 50) = 1410 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_3_47.a * sample_3_47.b * sample_3_47.c)) :=
    ⟨logCertificate_1410.lower, logCertificate_1410.upper,
      by simpa only [sample_3_47, hr] using logCertificate_1410.lower_le,
      by simpa only [sample_3_47, hr] using logCertificate_1410.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_3_47 logCertificate_50 support
  simpa only [support] using h

theorem sample_3_47_upper : discrepancy (1 / 10) sample_3_47 ≤ (227 / 1000) := by
  have h := sample_3_47_interval.2
  norm_num [logCertificate_50, logCertificate_1410] at h
  linarith

def sample_7_43 : Triple := ⟨7, 43, 50, by decide, by decide, by decide, by decide⟩
theorem sample_7_43_interval :
    (logCertificate_50.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_3010.upper ≤
      discrepancy (1 / 10) sample_7_43 ∧
    discrepancy (1 / 10) sample_7_43 ≤
      (logCertificate_50.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_3010.lower := by
  have hr : radical (7 * 43 * 50) = 3010 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_7_43.a * sample_7_43.b * sample_7_43.c)) :=
    ⟨logCertificate_3010.lower, logCertificate_3010.upper,
      by simpa only [sample_7_43, hr] using logCertificate_3010.lower_le,
      by simpa only [sample_7_43, hr] using logCertificate_3010.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_7_43 logCertificate_50 support
  simpa only [support] using h

theorem sample_7_43_upper : discrepancy (1 / 10) sample_7_43 ≤ (227 / 1000) := by
  have h := sample_7_43_interval.2
  norm_num [logCertificate_50, logCertificate_3010] at h
  linarith

def sample_9_41 : Triple := ⟨9, 41, 50, by decide, by decide, by decide, by decide⟩
theorem sample_9_41_interval :
    (logCertificate_50.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1230.upper ≤
      discrepancy (1 / 10) sample_9_41 ∧
    discrepancy (1 / 10) sample_9_41 ≤
      (logCertificate_50.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1230.lower := by
  have hr : radical (9 * 41 * 50) = 1230 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_9_41.a * sample_9_41.b * sample_9_41.c)) :=
    ⟨logCertificate_1230.lower, logCertificate_1230.upper,
      by simpa only [sample_9_41, hr] using logCertificate_1230.lower_le,
      by simpa only [sample_9_41, hr] using logCertificate_1230.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_9_41 logCertificate_50 support
  simpa only [support] using h

theorem sample_9_41_upper : discrepancy (1 / 10) sample_9_41 ≤ (227 / 1000) := by
  have h := sample_9_41_interval.2
  norm_num [logCertificate_50, logCertificate_1230] at h
  linarith

def sample_11_39 : Triple := ⟨11, 39, 50, by decide, by decide, by decide, by decide⟩
theorem sample_11_39_interval :
    (logCertificate_50.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_4290.upper ≤
      discrepancy (1 / 10) sample_11_39 ∧
    discrepancy (1 / 10) sample_11_39 ≤
      (logCertificate_50.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_4290.lower := by
  have hr : radical (11 * 39 * 50) = 4290 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_11_39.a * sample_11_39.b * sample_11_39.c)) :=
    ⟨logCertificate_4290.lower, logCertificate_4290.upper,
      by simpa only [sample_11_39, hr] using logCertificate_4290.lower_le,
      by simpa only [sample_11_39, hr] using logCertificate_4290.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_11_39 logCertificate_50 support
  simpa only [support] using h

theorem sample_11_39_upper : discrepancy (1 / 10) sample_11_39 ≤ (227 / 1000) := by
  have h := sample_11_39_interval.2
  norm_num [logCertificate_50, logCertificate_4290] at h
  linarith

def sample_13_37 : Triple := ⟨13, 37, 50, by decide, by decide, by decide, by decide⟩
theorem sample_13_37_interval :
    (logCertificate_50.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_4810.upper ≤
      discrepancy (1 / 10) sample_13_37 ∧
    discrepancy (1 / 10) sample_13_37 ≤
      (logCertificate_50.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_4810.lower := by
  have hr : radical (13 * 37 * 50) = 4810 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_13_37.a * sample_13_37.b * sample_13_37.c)) :=
    ⟨logCertificate_4810.lower, logCertificate_4810.upper,
      by simpa only [sample_13_37, hr] using logCertificate_4810.lower_le,
      by simpa only [sample_13_37, hr] using logCertificate_4810.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_13_37 logCertificate_50 support
  simpa only [support] using h

theorem sample_13_37_upper : discrepancy (1 / 10) sample_13_37 ≤ (227 / 1000) := by
  have h := sample_13_37_interval.2
  norm_num [logCertificate_50, logCertificate_4810] at h
  linarith

def sample_17_33 : Triple := ⟨17, 33, 50, by decide, by decide, by decide, by decide⟩
theorem sample_17_33_interval :
    (logCertificate_50.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_5610.upper ≤
      discrepancy (1 / 10) sample_17_33 ∧
    discrepancy (1 / 10) sample_17_33 ≤
      (logCertificate_50.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_5610.lower := by
  have hr : radical (17 * 33 * 50) = 5610 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_17_33.a * sample_17_33.b * sample_17_33.c)) :=
    ⟨logCertificate_5610.lower, logCertificate_5610.upper,
      by simpa only [sample_17_33, hr] using logCertificate_5610.lower_le,
      by simpa only [sample_17_33, hr] using logCertificate_5610.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_17_33 logCertificate_50 support
  simpa only [support] using h

theorem sample_17_33_upper : discrepancy (1 / 10) sample_17_33 ≤ (227 / 1000) := by
  have h := sample_17_33_interval.2
  norm_num [logCertificate_50, logCertificate_5610] at h
  linarith

def sample_19_31 : Triple := ⟨19, 31, 50, by decide, by decide, by decide, by decide⟩
theorem sample_19_31_interval :
    (logCertificate_50.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_5890.upper ≤
      discrepancy (1 / 10) sample_19_31 ∧
    discrepancy (1 / 10) sample_19_31 ≤
      (logCertificate_50.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_5890.lower := by
  have hr : radical (19 * 31 * 50) = 5890 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_19_31.a * sample_19_31.b * sample_19_31.c)) :=
    ⟨logCertificate_5890.lower, logCertificate_5890.upper,
      by simpa only [sample_19_31, hr] using logCertificate_5890.lower_le,
      by simpa only [sample_19_31, hr] using logCertificate_5890.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_19_31 logCertificate_50 support
  simpa only [support] using h

theorem sample_19_31_upper : discrepancy (1 / 10) sample_19_31 ≤ (227 / 1000) := by
  have h := sample_19_31_interval.2
  norm_num [logCertificate_50, logCertificate_5890] at h
  linarith

def sample_21_29 : Triple := ⟨21, 29, 50, by decide, by decide, by decide, by decide⟩
theorem sample_21_29_interval :
    (logCertificate_50.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_6090.upper ≤
      discrepancy (1 / 10) sample_21_29 ∧
    discrepancy (1 / 10) sample_21_29 ≤
      (logCertificate_50.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_6090.lower := by
  have hr : radical (21 * 29 * 50) = 6090 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_21_29.a * sample_21_29.b * sample_21_29.c)) :=
    ⟨logCertificate_6090.lower, logCertificate_6090.upper,
      by simpa only [sample_21_29, hr] using logCertificate_6090.lower_le,
      by simpa only [sample_21_29, hr] using logCertificate_6090.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_21_29 logCertificate_50 support
  simpa only [support] using h

theorem sample_21_29_upper : discrepancy (1 / 10) sample_21_29 ≤ (227 / 1000) := by
  have h := sample_21_29_interval.2
  norm_num [logCertificate_50, logCertificate_6090] at h
  linarith

def sample_23_27 : Triple := ⟨23, 27, 50, by decide, by decide, by decide, by decide⟩
theorem sample_23_27_interval :
    (logCertificate_50.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_690.upper ≤
      discrepancy (1 / 10) sample_23_27 ∧
    discrepancy (1 / 10) sample_23_27 ≤
      (logCertificate_50.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_690.lower := by
  have hr : radical (23 * 27 * 50) = 690 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_23_27.a * sample_23_27.b * sample_23_27.c)) :=
    ⟨logCertificate_690.lower, logCertificate_690.upper,
      by simpa only [sample_23_27, hr] using logCertificate_690.lower_le,
      by simpa only [sample_23_27, hr] using logCertificate_690.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_23_27 logCertificate_50 support
  simpa only [support] using h

theorem sample_23_27_upper : discrepancy (1 / 10) sample_23_27 ≤ (227 / 1000) := by
  have h := sample_23_27_interval.2
  norm_num [logCertificate_50, logCertificate_690] at h
  linarith

def sample_1_50 : Triple := ⟨1, 50, 51, by decide, by decide, by decide, by decide⟩
theorem sample_1_50_interval :
    (logCertificate_51.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_510.upper ≤
      discrepancy (1 / 10) sample_1_50 ∧
    discrepancy (1 / 10) sample_1_50 ≤
      (logCertificate_51.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_510.lower := by
  have hr : radical (1 * 50 * 51) = 510 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_1_50.a * sample_1_50.b * sample_1_50.c)) :=
    ⟨logCertificate_510.lower, logCertificate_510.upper,
      by simpa only [sample_1_50, hr] using logCertificate_510.lower_le,
      by simpa only [sample_1_50, hr] using logCertificate_510.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_1_50 logCertificate_51 support
  simpa only [support] using h

theorem sample_1_50_upper : discrepancy (1 / 10) sample_1_50 ≤ (227 / 1000) := by
  have h := sample_1_50_interval.2
  norm_num [logCertificate_51, logCertificate_510] at h
  linarith

def sample_2_49 : Triple := ⟨2, 49, 51, by decide, by decide, by decide, by decide⟩
theorem sample_2_49_interval :
    (logCertificate_51.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_714.upper ≤
      discrepancy (1 / 10) sample_2_49 ∧
    discrepancy (1 / 10) sample_2_49 ≤
      (logCertificate_51.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_714.lower := by
  have hr : radical (2 * 49 * 51) = 714 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_2_49.a * sample_2_49.b * sample_2_49.c)) :=
    ⟨logCertificate_714.lower, logCertificate_714.upper,
      by simpa only [sample_2_49, hr] using logCertificate_714.lower_le,
      by simpa only [sample_2_49, hr] using logCertificate_714.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_2_49 logCertificate_51 support
  simpa only [support] using h

theorem sample_2_49_upper : discrepancy (1 / 10) sample_2_49 ≤ (227 / 1000) := by
  have h := sample_2_49_interval.2
  norm_num [logCertificate_51, logCertificate_714] at h
  linarith

def sample_4_47 : Triple := ⟨4, 47, 51, by decide, by decide, by decide, by decide⟩
theorem sample_4_47_interval :
    (logCertificate_51.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_4794.upper ≤
      discrepancy (1 / 10) sample_4_47 ∧
    discrepancy (1 / 10) sample_4_47 ≤
      (logCertificate_51.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_4794.lower := by
  have hr : radical (4 * 47 * 51) = 4794 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_4_47.a * sample_4_47.b * sample_4_47.c)) :=
    ⟨logCertificate_4794.lower, logCertificate_4794.upper,
      by simpa only [sample_4_47, hr] using logCertificate_4794.lower_le,
      by simpa only [sample_4_47, hr] using logCertificate_4794.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_4_47 logCertificate_51 support
  simpa only [support] using h

theorem sample_4_47_upper : discrepancy (1 / 10) sample_4_47 ≤ (227 / 1000) := by
  have h := sample_4_47_interval.2
  norm_num [logCertificate_51, logCertificate_4794] at h
  linarith

def sample_5_46 : Triple := ⟨5, 46, 51, by decide, by decide, by decide, by decide⟩
theorem sample_5_46_interval :
    (logCertificate_51.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_11730.upper ≤
      discrepancy (1 / 10) sample_5_46 ∧
    discrepancy (1 / 10) sample_5_46 ≤
      (logCertificate_51.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_11730.lower := by
  have hr : radical (5 * 46 * 51) = 11730 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_5_46.a * sample_5_46.b * sample_5_46.c)) :=
    ⟨logCertificate_11730.lower, logCertificate_11730.upper,
      by simpa only [sample_5_46, hr] using logCertificate_11730.lower_le,
      by simpa only [sample_5_46, hr] using logCertificate_11730.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_5_46 logCertificate_51 support
  simpa only [support] using h

theorem sample_5_46_upper : discrepancy (1 / 10) sample_5_46 ≤ (227 / 1000) := by
  have h := sample_5_46_interval.2
  norm_num [logCertificate_51, logCertificate_11730] at h
  linarith

def sample_7_44 : Triple := ⟨7, 44, 51, by decide, by decide, by decide, by decide⟩
theorem sample_7_44_interval :
    (logCertificate_51.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_7854.upper ≤
      discrepancy (1 / 10) sample_7_44 ∧
    discrepancy (1 / 10) sample_7_44 ≤
      (logCertificate_51.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_7854.lower := by
  have hr : radical (7 * 44 * 51) = 7854 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_7_44.a * sample_7_44.b * sample_7_44.c)) :=
    ⟨logCertificate_7854.lower, logCertificate_7854.upper,
      by simpa only [sample_7_44, hr] using logCertificate_7854.lower_le,
      by simpa only [sample_7_44, hr] using logCertificate_7854.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_7_44 logCertificate_51 support
  simpa only [support] using h

theorem sample_7_44_upper : discrepancy (1 / 10) sample_7_44 ≤ (227 / 1000) := by
  have h := sample_7_44_interval.2
  norm_num [logCertificate_51, logCertificate_7854] at h
  linarith

def sample_8_43 : Triple := ⟨8, 43, 51, by decide, by decide, by decide, by decide⟩
theorem sample_8_43_interval :
    (logCertificate_51.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_4386.upper ≤
      discrepancy (1 / 10) sample_8_43 ∧
    discrepancy (1 / 10) sample_8_43 ≤
      (logCertificate_51.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_4386.lower := by
  have hr : radical (8 * 43 * 51) = 4386 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_8_43.a * sample_8_43.b * sample_8_43.c)) :=
    ⟨logCertificate_4386.lower, logCertificate_4386.upper,
      by simpa only [sample_8_43, hr] using logCertificate_4386.lower_le,
      by simpa only [sample_8_43, hr] using logCertificate_4386.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_8_43 logCertificate_51 support
  simpa only [support] using h

theorem sample_8_43_upper : discrepancy (1 / 10) sample_8_43 ≤ (227 / 1000) := by
  have h := sample_8_43_interval.2
  norm_num [logCertificate_51, logCertificate_4386] at h
  linarith

def sample_10_41 : Triple := ⟨10, 41, 51, by decide, by decide, by decide, by decide⟩
theorem sample_10_41_interval :
    (logCertificate_51.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_20910.upper ≤
      discrepancy (1 / 10) sample_10_41 ∧
    discrepancy (1 / 10) sample_10_41 ≤
      (logCertificate_51.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_20910.lower := by
  have hr : radical (10 * 41 * 51) = 20910 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_10_41.a * sample_10_41.b * sample_10_41.c)) :=
    ⟨logCertificate_20910.lower, logCertificate_20910.upper,
      by simpa only [sample_10_41, hr] using logCertificate_20910.lower_le,
      by simpa only [sample_10_41, hr] using logCertificate_20910.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_10_41 logCertificate_51 support
  simpa only [support] using h

theorem sample_10_41_upper : discrepancy (1 / 10) sample_10_41 ≤ (227 / 1000) := by
  have h := sample_10_41_interval.2
  norm_num [logCertificate_51, logCertificate_20910] at h
  linarith

def sample_11_40 : Triple := ⟨11, 40, 51, by decide, by decide, by decide, by decide⟩
theorem sample_11_40_interval :
    (logCertificate_51.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_5610.upper ≤
      discrepancy (1 / 10) sample_11_40 ∧
    discrepancy (1 / 10) sample_11_40 ≤
      (logCertificate_51.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_5610.lower := by
  have hr : radical (11 * 40 * 51) = 5610 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_11_40.a * sample_11_40.b * sample_11_40.c)) :=
    ⟨logCertificate_5610.lower, logCertificate_5610.upper,
      by simpa only [sample_11_40, hr] using logCertificate_5610.lower_le,
      by simpa only [sample_11_40, hr] using logCertificate_5610.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_11_40 logCertificate_51 support
  simpa only [support] using h

theorem sample_11_40_upper : discrepancy (1 / 10) sample_11_40 ≤ (227 / 1000) := by
  have h := sample_11_40_interval.2
  norm_num [logCertificate_51, logCertificate_5610] at h
  linarith

def sample_13_38 : Triple := ⟨13, 38, 51, by decide, by decide, by decide, by decide⟩
theorem sample_13_38_interval :
    (logCertificate_51.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_25194.upper ≤
      discrepancy (1 / 10) sample_13_38 ∧
    discrepancy (1 / 10) sample_13_38 ≤
      (logCertificate_51.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_25194.lower := by
  have hr : radical (13 * 38 * 51) = 25194 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_13_38.a * sample_13_38.b * sample_13_38.c)) :=
    ⟨logCertificate_25194.lower, logCertificate_25194.upper,
      by simpa only [sample_13_38, hr] using logCertificate_25194.lower_le,
      by simpa only [sample_13_38, hr] using logCertificate_25194.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_13_38 logCertificate_51 support
  simpa only [support] using h

theorem sample_13_38_upper : discrepancy (1 / 10) sample_13_38 ≤ (227 / 1000) := by
  have h := sample_13_38_interval.2
  norm_num [logCertificate_51, logCertificate_25194] at h
  linarith

def sample_14_37 : Triple := ⟨14, 37, 51, by decide, by decide, by decide, by decide⟩
theorem sample_14_37_interval :
    (logCertificate_51.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_26418.upper ≤
      discrepancy (1 / 10) sample_14_37 ∧
    discrepancy (1 / 10) sample_14_37 ≤
      (logCertificate_51.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_26418.lower := by
  have hr : radical (14 * 37 * 51) = 26418 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_14_37.a * sample_14_37.b * sample_14_37.c)) :=
    ⟨logCertificate_26418.lower, logCertificate_26418.upper,
      by simpa only [sample_14_37, hr] using logCertificate_26418.lower_le,
      by simpa only [sample_14_37, hr] using logCertificate_26418.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_14_37 logCertificate_51 support
  simpa only [support] using h

theorem sample_14_37_upper : discrepancy (1 / 10) sample_14_37 ≤ (227 / 1000) := by
  have h := sample_14_37_interval.2
  norm_num [logCertificate_51, logCertificate_26418] at h
  linarith

def sample_16_35 : Triple := ⟨16, 35, 51, by decide, by decide, by decide, by decide⟩
theorem sample_16_35_interval :
    (logCertificate_51.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_3570.upper ≤
      discrepancy (1 / 10) sample_16_35 ∧
    discrepancy (1 / 10) sample_16_35 ≤
      (logCertificate_51.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_3570.lower := by
  have hr : radical (16 * 35 * 51) = 3570 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_16_35.a * sample_16_35.b * sample_16_35.c)) :=
    ⟨logCertificate_3570.lower, logCertificate_3570.upper,
      by simpa only [sample_16_35, hr] using logCertificate_3570.lower_le,
      by simpa only [sample_16_35, hr] using logCertificate_3570.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_16_35 logCertificate_51 support
  simpa only [support] using h

theorem sample_16_35_upper : discrepancy (1 / 10) sample_16_35 ≤ (227 / 1000) := by
  have h := sample_16_35_interval.2
  norm_num [logCertificate_51, logCertificate_3570] at h
  linarith

def sample_19_32 : Triple := ⟨19, 32, 51, by decide, by decide, by decide, by decide⟩
theorem sample_19_32_interval :
    (logCertificate_51.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1938.upper ≤
      discrepancy (1 / 10) sample_19_32 ∧
    discrepancy (1 / 10) sample_19_32 ≤
      (logCertificate_51.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1938.lower := by
  have hr : radical (19 * 32 * 51) = 1938 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_19_32.a * sample_19_32.b * sample_19_32.c)) :=
    ⟨logCertificate_1938.lower, logCertificate_1938.upper,
      by simpa only [sample_19_32, hr] using logCertificate_1938.lower_le,
      by simpa only [sample_19_32, hr] using logCertificate_1938.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_19_32 logCertificate_51 support
  simpa only [support] using h

theorem sample_19_32_upper : discrepancy (1 / 10) sample_19_32 ≤ (227 / 1000) := by
  have h := sample_19_32_interval.2
  norm_num [logCertificate_51, logCertificate_1938] at h
  linarith

def sample_20_31 : Triple := ⟨20, 31, 51, by decide, by decide, by decide, by decide⟩
theorem sample_20_31_interval :
    (logCertificate_51.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_15810.upper ≤
      discrepancy (1 / 10) sample_20_31 ∧
    discrepancy (1 / 10) sample_20_31 ≤
      (logCertificate_51.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_15810.lower := by
  have hr : radical (20 * 31 * 51) = 15810 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_20_31.a * sample_20_31.b * sample_20_31.c)) :=
    ⟨logCertificate_15810.lower, logCertificate_15810.upper,
      by simpa only [sample_20_31, hr] using logCertificate_15810.lower_le,
      by simpa only [sample_20_31, hr] using logCertificate_15810.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_20_31 logCertificate_51 support
  simpa only [support] using h

theorem sample_20_31_upper : discrepancy (1 / 10) sample_20_31 ≤ (227 / 1000) := by
  have h := sample_20_31_interval.2
  norm_num [logCertificate_51, logCertificate_15810] at h
  linarith

def sample_22_29 : Triple := ⟨22, 29, 51, by decide, by decide, by decide, by decide⟩
theorem sample_22_29_interval :
    (logCertificate_51.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_32538.upper ≤
      discrepancy (1 / 10) sample_22_29 ∧
    discrepancy (1 / 10) sample_22_29 ≤
      (logCertificate_51.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_32538.lower := by
  have hr : radical (22 * 29 * 51) = 32538 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_22_29.a * sample_22_29.b * sample_22_29.c)) :=
    ⟨logCertificate_32538.lower, logCertificate_32538.upper,
      by simpa only [sample_22_29, hr] using logCertificate_32538.lower_le,
      by simpa only [sample_22_29, hr] using logCertificate_32538.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_22_29 logCertificate_51 support
  simpa only [support] using h

theorem sample_22_29_upper : discrepancy (1 / 10) sample_22_29 ≤ (227 / 1000) := by
  have h := sample_22_29_interval.2
  norm_num [logCertificate_51, logCertificate_32538] at h
  linarith

def sample_23_28 : Triple := ⟨23, 28, 51, by decide, by decide, by decide, by decide⟩
theorem sample_23_28_interval :
    (logCertificate_51.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_16422.upper ≤
      discrepancy (1 / 10) sample_23_28 ∧
    discrepancy (1 / 10) sample_23_28 ≤
      (logCertificate_51.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_16422.lower := by
  have hr : radical (23 * 28 * 51) = 16422 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_23_28.a * sample_23_28.b * sample_23_28.c)) :=
    ⟨logCertificate_16422.lower, logCertificate_16422.upper,
      by simpa only [sample_23_28, hr] using logCertificate_16422.lower_le,
      by simpa only [sample_23_28, hr] using logCertificate_16422.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_23_28 logCertificate_51 support
  simpa only [support] using h

theorem sample_23_28_upper : discrepancy (1 / 10) sample_23_28 ≤ (227 / 1000) := by
  have h := sample_23_28_interval.2
  norm_num [logCertificate_51, logCertificate_16422] at h
  linarith

def sample_25_26 : Triple := ⟨25, 26, 51, by decide, by decide, by decide, by decide⟩
theorem sample_25_26_interval :
    (logCertificate_51.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_6630.upper ≤
      discrepancy (1 / 10) sample_25_26 ∧
    discrepancy (1 / 10) sample_25_26 ≤
      (logCertificate_51.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_6630.lower := by
  have hr : radical (25 * 26 * 51) = 6630 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_25_26.a * sample_25_26.b * sample_25_26.c)) :=
    ⟨logCertificate_6630.lower, logCertificate_6630.upper,
      by simpa only [sample_25_26, hr] using logCertificate_6630.lower_le,
      by simpa only [sample_25_26, hr] using logCertificate_6630.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_25_26 logCertificate_51 support
  simpa only [support] using h

theorem sample_25_26_upper : discrepancy (1 / 10) sample_25_26 ≤ (227 / 1000) := by
  have h := sample_25_26_interval.2
  norm_num [logCertificate_51, logCertificate_6630] at h
  linarith

def sample_1_51 : Triple := ⟨1, 51, 52, by decide, by decide, by decide, by decide⟩
theorem sample_1_51_interval :
    (logCertificate_52.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1326.upper ≤
      discrepancy (1 / 10) sample_1_51 ∧
    discrepancy (1 / 10) sample_1_51 ≤
      (logCertificate_52.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1326.lower := by
  have hr : radical (1 * 51 * 52) = 1326 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_1_51.a * sample_1_51.b * sample_1_51.c)) :=
    ⟨logCertificate_1326.lower, logCertificate_1326.upper,
      by simpa only [sample_1_51, hr] using logCertificate_1326.lower_le,
      by simpa only [sample_1_51, hr] using logCertificate_1326.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_1_51 logCertificate_52 support
  simpa only [support] using h

theorem sample_1_51_upper : discrepancy (1 / 10) sample_1_51 ≤ (227 / 1000) := by
  have h := sample_1_51_interval.2
  norm_num [logCertificate_52, logCertificate_1326] at h
  linarith

def sample_3_49 : Triple := ⟨3, 49, 52, by decide, by decide, by decide, by decide⟩
theorem sample_3_49_interval :
    (logCertificate_52.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_546.upper ≤
      discrepancy (1 / 10) sample_3_49 ∧
    discrepancy (1 / 10) sample_3_49 ≤
      (logCertificate_52.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_546.lower := by
  have hr : radical (3 * 49 * 52) = 546 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_3_49.a * sample_3_49.b * sample_3_49.c)) :=
    ⟨logCertificate_546.lower, logCertificate_546.upper,
      by simpa only [sample_3_49, hr] using logCertificate_546.lower_le,
      by simpa only [sample_3_49, hr] using logCertificate_546.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_3_49 logCertificate_52 support
  simpa only [support] using h

theorem sample_3_49_upper : discrepancy (1 / 10) sample_3_49 ≤ (227 / 1000) := by
  have h := sample_3_49_interval.2
  norm_num [logCertificate_52, logCertificate_546] at h
  linarith

def sample_5_47 : Triple := ⟨5, 47, 52, by decide, by decide, by decide, by decide⟩
theorem sample_5_47_interval :
    (logCertificate_52.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_6110.upper ≤
      discrepancy (1 / 10) sample_5_47 ∧
    discrepancy (1 / 10) sample_5_47 ≤
      (logCertificate_52.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_6110.lower := by
  have hr : radical (5 * 47 * 52) = 6110 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_5_47.a * sample_5_47.b * sample_5_47.c)) :=
    ⟨logCertificate_6110.lower, logCertificate_6110.upper,
      by simpa only [sample_5_47, hr] using logCertificate_6110.lower_le,
      by simpa only [sample_5_47, hr] using logCertificate_6110.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_5_47 logCertificate_52 support
  simpa only [support] using h

theorem sample_5_47_upper : discrepancy (1 / 10) sample_5_47 ≤ (227 / 1000) := by
  have h := sample_5_47_interval.2
  norm_num [logCertificate_52, logCertificate_6110] at h
  linarith

def sample_7_45 : Triple := ⟨7, 45, 52, by decide, by decide, by decide, by decide⟩
theorem sample_7_45_interval :
    (logCertificate_52.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_2730.upper ≤
      discrepancy (1 / 10) sample_7_45 ∧
    discrepancy (1 / 10) sample_7_45 ≤
      (logCertificate_52.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_2730.lower := by
  have hr : radical (7 * 45 * 52) = 2730 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_7_45.a * sample_7_45.b * sample_7_45.c)) :=
    ⟨logCertificate_2730.lower, logCertificate_2730.upper,
      by simpa only [sample_7_45, hr] using logCertificate_2730.lower_le,
      by simpa only [sample_7_45, hr] using logCertificate_2730.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_7_45 logCertificate_52 support
  simpa only [support] using h

theorem sample_7_45_upper : discrepancy (1 / 10) sample_7_45 ≤ (227 / 1000) := by
  have h := sample_7_45_interval.2
  norm_num [logCertificate_52, logCertificate_2730] at h
  linarith

def sample_9_43 : Triple := ⟨9, 43, 52, by decide, by decide, by decide, by decide⟩
theorem sample_9_43_interval :
    (logCertificate_52.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_3354.upper ≤
      discrepancy (1 / 10) sample_9_43 ∧
    discrepancy (1 / 10) sample_9_43 ≤
      (logCertificate_52.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_3354.lower := by
  have hr : radical (9 * 43 * 52) = 3354 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_9_43.a * sample_9_43.b * sample_9_43.c)) :=
    ⟨logCertificate_3354.lower, logCertificate_3354.upper,
      by simpa only [sample_9_43, hr] using logCertificate_3354.lower_le,
      by simpa only [sample_9_43, hr] using logCertificate_3354.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_9_43 logCertificate_52 support
  simpa only [support] using h

theorem sample_9_43_upper : discrepancy (1 / 10) sample_9_43 ≤ (227 / 1000) := by
  have h := sample_9_43_interval.2
  norm_num [logCertificate_52, logCertificate_3354] at h
  linarith

def sample_11_41 : Triple := ⟨11, 41, 52, by decide, by decide, by decide, by decide⟩
theorem sample_11_41_interval :
    (logCertificate_52.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_11726.upper ≤
      discrepancy (1 / 10) sample_11_41 ∧
    discrepancy (1 / 10) sample_11_41 ≤
      (logCertificate_52.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_11726.lower := by
  have hr : radical (11 * 41 * 52) = 11726 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_11_41.a * sample_11_41.b * sample_11_41.c)) :=
    ⟨logCertificate_11726.lower, logCertificate_11726.upper,
      by simpa only [sample_11_41, hr] using logCertificate_11726.lower_le,
      by simpa only [sample_11_41, hr] using logCertificate_11726.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_11_41 logCertificate_52 support
  simpa only [support] using h

theorem sample_11_41_upper : discrepancy (1 / 10) sample_11_41 ≤ (227 / 1000) := by
  have h := sample_11_41_interval.2
  norm_num [logCertificate_52, logCertificate_11726] at h
  linarith

def sample_15_37 : Triple := ⟨15, 37, 52, by decide, by decide, by decide, by decide⟩
theorem sample_15_37_interval :
    (logCertificate_52.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_14430.upper ≤
      discrepancy (1 / 10) sample_15_37 ∧
    discrepancy (1 / 10) sample_15_37 ≤
      (logCertificate_52.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_14430.lower := by
  have hr : radical (15 * 37 * 52) = 14430 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_15_37.a * sample_15_37.b * sample_15_37.c)) :=
    ⟨logCertificate_14430.lower, logCertificate_14430.upper,
      by simpa only [sample_15_37, hr] using logCertificate_14430.lower_le,
      by simpa only [sample_15_37, hr] using logCertificate_14430.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_15_37 logCertificate_52 support
  simpa only [support] using h

theorem sample_15_37_upper : discrepancy (1 / 10) sample_15_37 ≤ (227 / 1000) := by
  have h := sample_15_37_interval.2
  norm_num [logCertificate_52, logCertificate_14430] at h
  linarith

def sample_17_35 : Triple := ⟨17, 35, 52, by decide, by decide, by decide, by decide⟩
theorem sample_17_35_interval :
    (logCertificate_52.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_15470.upper ≤
      discrepancy (1 / 10) sample_17_35 ∧
    discrepancy (1 / 10) sample_17_35 ≤
      (logCertificate_52.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_15470.lower := by
  have hr : radical (17 * 35 * 52) = 15470 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_17_35.a * sample_17_35.b * sample_17_35.c)) :=
    ⟨logCertificate_15470.lower, logCertificate_15470.upper,
      by simpa only [sample_17_35, hr] using logCertificate_15470.lower_le,
      by simpa only [sample_17_35, hr] using logCertificate_15470.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_17_35 logCertificate_52 support
  simpa only [support] using h

theorem sample_17_35_upper : discrepancy (1 / 10) sample_17_35 ≤ (227 / 1000) := by
  have h := sample_17_35_interval.2
  norm_num [logCertificate_52, logCertificate_15470] at h
  linarith

def sample_19_33 : Triple := ⟨19, 33, 52, by decide, by decide, by decide, by decide⟩
theorem sample_19_33_interval :
    (logCertificate_52.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_16302.upper ≤
      discrepancy (1 / 10) sample_19_33 ∧
    discrepancy (1 / 10) sample_19_33 ≤
      (logCertificate_52.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_16302.lower := by
  have hr : radical (19 * 33 * 52) = 16302 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_19_33.a * sample_19_33.b * sample_19_33.c)) :=
    ⟨logCertificate_16302.lower, logCertificate_16302.upper,
      by simpa only [sample_19_33, hr] using logCertificate_16302.lower_le,
      by simpa only [sample_19_33, hr] using logCertificate_16302.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_19_33 logCertificate_52 support
  simpa only [support] using h

theorem sample_19_33_upper : discrepancy (1 / 10) sample_19_33 ≤ (227 / 1000) := by
  have h := sample_19_33_interval.2
  norm_num [logCertificate_52, logCertificate_16302] at h
  linarith

def sample_21_31 : Triple := ⟨21, 31, 52, by decide, by decide, by decide, by decide⟩
theorem sample_21_31_interval :
    (logCertificate_52.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_16926.upper ≤
      discrepancy (1 / 10) sample_21_31 ∧
    discrepancy (1 / 10) sample_21_31 ≤
      (logCertificate_52.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_16926.lower := by
  have hr : radical (21 * 31 * 52) = 16926 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_21_31.a * sample_21_31.b * sample_21_31.c)) :=
    ⟨logCertificate_16926.lower, logCertificate_16926.upper,
      by simpa only [sample_21_31, hr] using logCertificate_16926.lower_le,
      by simpa only [sample_21_31, hr] using logCertificate_16926.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_21_31 logCertificate_52 support
  simpa only [support] using h

theorem sample_21_31_upper : discrepancy (1 / 10) sample_21_31 ≤ (227 / 1000) := by
  have h := sample_21_31_interval.2
  norm_num [logCertificate_52, logCertificate_16926] at h
  linarith

def sample_23_29 : Triple := ⟨23, 29, 52, by decide, by decide, by decide, by decide⟩
theorem sample_23_29_interval :
    (logCertificate_52.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_17342.upper ≤
      discrepancy (1 / 10) sample_23_29 ∧
    discrepancy (1 / 10) sample_23_29 ≤
      (logCertificate_52.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_17342.lower := by
  have hr : radical (23 * 29 * 52) = 17342 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_23_29.a * sample_23_29.b * sample_23_29.c)) :=
    ⟨logCertificate_17342.lower, logCertificate_17342.upper,
      by simpa only [sample_23_29, hr] using logCertificate_17342.lower_le,
      by simpa only [sample_23_29, hr] using logCertificate_17342.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_23_29 logCertificate_52 support
  simpa only [support] using h

theorem sample_23_29_upper : discrepancy (1 / 10) sample_23_29 ≤ (227 / 1000) := by
  have h := sample_23_29_interval.2
  norm_num [logCertificate_52, logCertificate_17342] at h
  linarith

def sample_25_27 : Triple := ⟨25, 27, 52, by decide, by decide, by decide, by decide⟩
theorem sample_25_27_interval :
    (logCertificate_52.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_390.upper ≤
      discrepancy (1 / 10) sample_25_27 ∧
    discrepancy (1 / 10) sample_25_27 ≤
      (logCertificate_52.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_390.lower := by
  have hr : radical (25 * 27 * 52) = 390 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_25_27.a * sample_25_27.b * sample_25_27.c)) :=
    ⟨logCertificate_390.lower, logCertificate_390.upper,
      by simpa only [sample_25_27, hr] using logCertificate_390.lower_le,
      by simpa only [sample_25_27, hr] using logCertificate_390.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_25_27 logCertificate_52 support
  simpa only [support] using h

theorem sample_25_27_upper : discrepancy (1 / 10) sample_25_27 ≤ (227 / 1000) := by
  have h := sample_25_27_interval.2
  norm_num [logCertificate_52, logCertificate_390] at h
  linarith

def sample_1_52 : Triple := ⟨1, 52, 53, by decide, by decide, by decide, by decide⟩
theorem sample_1_52_interval :
    (logCertificate_53.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1378.upper ≤
      discrepancy (1 / 10) sample_1_52 ∧
    discrepancy (1 / 10) sample_1_52 ≤
      (logCertificate_53.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1378.lower := by
  have hr : radical (1 * 52 * 53) = 1378 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_1_52.a * sample_1_52.b * sample_1_52.c)) :=
    ⟨logCertificate_1378.lower, logCertificate_1378.upper,
      by simpa only [sample_1_52, hr] using logCertificate_1378.lower_le,
      by simpa only [sample_1_52, hr] using logCertificate_1378.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_1_52 logCertificate_53 support
  simpa only [support] using h

theorem sample_1_52_upper : discrepancy (1 / 10) sample_1_52 ≤ (227 / 1000) := by
  have h := sample_1_52_interval.2
  norm_num [logCertificate_53, logCertificate_1378] at h
  linarith

def sample_2_51 : Triple := ⟨2, 51, 53, by decide, by decide, by decide, by decide⟩
theorem sample_2_51_interval :
    (logCertificate_53.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_5406.upper ≤
      discrepancy (1 / 10) sample_2_51 ∧
    discrepancy (1 / 10) sample_2_51 ≤
      (logCertificate_53.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_5406.lower := by
  have hr : radical (2 * 51 * 53) = 5406 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_2_51.a * sample_2_51.b * sample_2_51.c)) :=
    ⟨logCertificate_5406.lower, logCertificate_5406.upper,
      by simpa only [sample_2_51, hr] using logCertificate_5406.lower_le,
      by simpa only [sample_2_51, hr] using logCertificate_5406.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_2_51 logCertificate_53 support
  simpa only [support] using h

theorem sample_2_51_upper : discrepancy (1 / 10) sample_2_51 ≤ (227 / 1000) := by
  have h := sample_2_51_interval.2
  norm_num [logCertificate_53, logCertificate_5406] at h
  linarith

def sample_3_50 : Triple := ⟨3, 50, 53, by decide, by decide, by decide, by decide⟩
theorem sample_3_50_interval :
    (logCertificate_53.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1590.upper ≤
      discrepancy (1 / 10) sample_3_50 ∧
    discrepancy (1 / 10) sample_3_50 ≤
      (logCertificate_53.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1590.lower := by
  have hr : radical (3 * 50 * 53) = 1590 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_3_50.a * sample_3_50.b * sample_3_50.c)) :=
    ⟨logCertificate_1590.lower, logCertificate_1590.upper,
      by simpa only [sample_3_50, hr] using logCertificate_1590.lower_le,
      by simpa only [sample_3_50, hr] using logCertificate_1590.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_3_50 logCertificate_53 support
  simpa only [support] using h

theorem sample_3_50_upper : discrepancy (1 / 10) sample_3_50 ≤ (227 / 1000) := by
  have h := sample_3_50_interval.2
  norm_num [logCertificate_53, logCertificate_1590] at h
  linarith

def sample_4_49 : Triple := ⟨4, 49, 53, by decide, by decide, by decide, by decide⟩
theorem sample_4_49_interval :
    (logCertificate_53.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_742.upper ≤
      discrepancy (1 / 10) sample_4_49 ∧
    discrepancy (1 / 10) sample_4_49 ≤
      (logCertificate_53.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_742.lower := by
  have hr : radical (4 * 49 * 53) = 742 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_4_49.a * sample_4_49.b * sample_4_49.c)) :=
    ⟨logCertificate_742.lower, logCertificate_742.upper,
      by simpa only [sample_4_49, hr] using logCertificate_742.lower_le,
      by simpa only [sample_4_49, hr] using logCertificate_742.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_4_49 logCertificate_53 support
  simpa only [support] using h

theorem sample_4_49_upper : discrepancy (1 / 10) sample_4_49 ≤ (227 / 1000) := by
  have h := sample_4_49_interval.2
  norm_num [logCertificate_53, logCertificate_742] at h
  linarith

def sample_5_48 : Triple := ⟨5, 48, 53, by decide, by decide, by decide, by decide⟩
theorem sample_5_48_interval :
    (logCertificate_53.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1590.upper ≤
      discrepancy (1 / 10) sample_5_48 ∧
    discrepancy (1 / 10) sample_5_48 ≤
      (logCertificate_53.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1590.lower := by
  have hr : radical (5 * 48 * 53) = 1590 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_5_48.a * sample_5_48.b * sample_5_48.c)) :=
    ⟨logCertificate_1590.lower, logCertificate_1590.upper,
      by simpa only [sample_5_48, hr] using logCertificate_1590.lower_le,
      by simpa only [sample_5_48, hr] using logCertificate_1590.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_5_48 logCertificate_53 support
  simpa only [support] using h

theorem sample_5_48_upper : discrepancy (1 / 10) sample_5_48 ≤ (227 / 1000) := by
  have h := sample_5_48_interval.2
  norm_num [logCertificate_53, logCertificate_1590] at h
  linarith

def sample_6_47 : Triple := ⟨6, 47, 53, by decide, by decide, by decide, by decide⟩
theorem sample_6_47_interval :
    (logCertificate_53.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_14946.upper ≤
      discrepancy (1 / 10) sample_6_47 ∧
    discrepancy (1 / 10) sample_6_47 ≤
      (logCertificate_53.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_14946.lower := by
  have hr : radical (6 * 47 * 53) = 14946 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_6_47.a * sample_6_47.b * sample_6_47.c)) :=
    ⟨logCertificate_14946.lower, logCertificate_14946.upper,
      by simpa only [sample_6_47, hr] using logCertificate_14946.lower_le,
      by simpa only [sample_6_47, hr] using logCertificate_14946.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_6_47 logCertificate_53 support
  simpa only [support] using h

theorem sample_6_47_upper : discrepancy (1 / 10) sample_6_47 ≤ (227 / 1000) := by
  have h := sample_6_47_interval.2
  norm_num [logCertificate_53, logCertificate_14946] at h
  linarith

def sample_7_46 : Triple := ⟨7, 46, 53, by decide, by decide, by decide, by decide⟩
theorem sample_7_46_interval :
    (logCertificate_53.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_17066.upper ≤
      discrepancy (1 / 10) sample_7_46 ∧
    discrepancy (1 / 10) sample_7_46 ≤
      (logCertificate_53.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_17066.lower := by
  have hr : radical (7 * 46 * 53) = 17066 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_7_46.a * sample_7_46.b * sample_7_46.c)) :=
    ⟨logCertificate_17066.lower, logCertificate_17066.upper,
      by simpa only [sample_7_46, hr] using logCertificate_17066.lower_le,
      by simpa only [sample_7_46, hr] using logCertificate_17066.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_7_46 logCertificate_53 support
  simpa only [support] using h

theorem sample_7_46_upper : discrepancy (1 / 10) sample_7_46 ≤ (227 / 1000) := by
  have h := sample_7_46_interval.2
  norm_num [logCertificate_53, logCertificate_17066] at h
  linarith

def sample_8_45 : Triple := ⟨8, 45, 53, by decide, by decide, by decide, by decide⟩
theorem sample_8_45_interval :
    (logCertificate_53.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1590.upper ≤
      discrepancy (1 / 10) sample_8_45 ∧
    discrepancy (1 / 10) sample_8_45 ≤
      (logCertificate_53.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1590.lower := by
  have hr : radical (8 * 45 * 53) = 1590 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_8_45.a * sample_8_45.b * sample_8_45.c)) :=
    ⟨logCertificate_1590.lower, logCertificate_1590.upper,
      by simpa only [sample_8_45, hr] using logCertificate_1590.lower_le,
      by simpa only [sample_8_45, hr] using logCertificate_1590.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_8_45 logCertificate_53 support
  simpa only [support] using h

theorem sample_8_45_upper : discrepancy (1 / 10) sample_8_45 ≤ (227 / 1000) := by
  have h := sample_8_45_interval.2
  norm_num [logCertificate_53, logCertificate_1590] at h
  linarith

def sample_9_44 : Triple := ⟨9, 44, 53, by decide, by decide, by decide, by decide⟩
theorem sample_9_44_interval :
    (logCertificate_53.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_3498.upper ≤
      discrepancy (1 / 10) sample_9_44 ∧
    discrepancy (1 / 10) sample_9_44 ≤
      (logCertificate_53.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_3498.lower := by
  have hr : radical (9 * 44 * 53) = 3498 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_9_44.a * sample_9_44.b * sample_9_44.c)) :=
    ⟨logCertificate_3498.lower, logCertificate_3498.upper,
      by simpa only [sample_9_44, hr] using logCertificate_3498.lower_le,
      by simpa only [sample_9_44, hr] using logCertificate_3498.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_9_44 logCertificate_53 support
  simpa only [support] using h

theorem sample_9_44_upper : discrepancy (1 / 10) sample_9_44 ≤ (227 / 1000) := by
  have h := sample_9_44_interval.2
  norm_num [logCertificate_53, logCertificate_3498] at h
  linarith

def sample_10_43 : Triple := ⟨10, 43, 53, by decide, by decide, by decide, by decide⟩
theorem sample_10_43_interval :
    (logCertificate_53.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_22790.upper ≤
      discrepancy (1 / 10) sample_10_43 ∧
    discrepancy (1 / 10) sample_10_43 ≤
      (logCertificate_53.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_22790.lower := by
  have hr : radical (10 * 43 * 53) = 22790 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_10_43.a * sample_10_43.b * sample_10_43.c)) :=
    ⟨logCertificate_22790.lower, logCertificate_22790.upper,
      by simpa only [sample_10_43, hr] using logCertificate_22790.lower_le,
      by simpa only [sample_10_43, hr] using logCertificate_22790.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_10_43 logCertificate_53 support
  simpa only [support] using h

theorem sample_10_43_upper : discrepancy (1 / 10) sample_10_43 ≤ (227 / 1000) := by
  have h := sample_10_43_interval.2
  norm_num [logCertificate_53, logCertificate_22790] at h
  linarith

def sample_11_42 : Triple := ⟨11, 42, 53, by decide, by decide, by decide, by decide⟩
theorem sample_11_42_interval :
    (logCertificate_53.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_24486.upper ≤
      discrepancy (1 / 10) sample_11_42 ∧
    discrepancy (1 / 10) sample_11_42 ≤
      (logCertificate_53.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_24486.lower := by
  have hr : radical (11 * 42 * 53) = 24486 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_11_42.a * sample_11_42.b * sample_11_42.c)) :=
    ⟨logCertificate_24486.lower, logCertificate_24486.upper,
      by simpa only [sample_11_42, hr] using logCertificate_24486.lower_le,
      by simpa only [sample_11_42, hr] using logCertificate_24486.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_11_42 logCertificate_53 support
  simpa only [support] using h

theorem sample_11_42_upper : discrepancy (1 / 10) sample_11_42 ≤ (227 / 1000) := by
  have h := sample_11_42_interval.2
  norm_num [logCertificate_53, logCertificate_24486] at h
  linarith

def sample_12_41 : Triple := ⟨12, 41, 53, by decide, by decide, by decide, by decide⟩
theorem sample_12_41_interval :
    (logCertificate_53.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_13038.upper ≤
      discrepancy (1 / 10) sample_12_41 ∧
    discrepancy (1 / 10) sample_12_41 ≤
      (logCertificate_53.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_13038.lower := by
  have hr : radical (12 * 41 * 53) = 13038 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_12_41.a * sample_12_41.b * sample_12_41.c)) :=
    ⟨logCertificate_13038.lower, logCertificate_13038.upper,
      by simpa only [sample_12_41, hr] using logCertificate_13038.lower_le,
      by simpa only [sample_12_41, hr] using logCertificate_13038.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_12_41 logCertificate_53 support
  simpa only [support] using h

theorem sample_12_41_upper : discrepancy (1 / 10) sample_12_41 ≤ (227 / 1000) := by
  have h := sample_12_41_interval.2
  norm_num [logCertificate_53, logCertificate_13038] at h
  linarith

def sample_13_40 : Triple := ⟨13, 40, 53, by decide, by decide, by decide, by decide⟩
theorem sample_13_40_interval :
    (logCertificate_53.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_6890.upper ≤
      discrepancy (1 / 10) sample_13_40 ∧
    discrepancy (1 / 10) sample_13_40 ≤
      (logCertificate_53.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_6890.lower := by
  have hr : radical (13 * 40 * 53) = 6890 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_13_40.a * sample_13_40.b * sample_13_40.c)) :=
    ⟨logCertificate_6890.lower, logCertificate_6890.upper,
      by simpa only [sample_13_40, hr] using logCertificate_6890.lower_le,
      by simpa only [sample_13_40, hr] using logCertificate_6890.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_13_40 logCertificate_53 support
  simpa only [support] using h

theorem sample_13_40_upper : discrepancy (1 / 10) sample_13_40 ≤ (227 / 1000) := by
  have h := sample_13_40_interval.2
  norm_num [logCertificate_53, logCertificate_6890] at h
  linarith

def sample_14_39 : Triple := ⟨14, 39, 53, by decide, by decide, by decide, by decide⟩
theorem sample_14_39_interval :
    (logCertificate_53.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_28938.upper ≤
      discrepancy (1 / 10) sample_14_39 ∧
    discrepancy (1 / 10) sample_14_39 ≤
      (logCertificate_53.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_28938.lower := by
  have hr : radical (14 * 39 * 53) = 28938 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_14_39.a * sample_14_39.b * sample_14_39.c)) :=
    ⟨logCertificate_28938.lower, logCertificate_28938.upper,
      by simpa only [sample_14_39, hr] using logCertificate_28938.lower_le,
      by simpa only [sample_14_39, hr] using logCertificate_28938.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_14_39 logCertificate_53 support
  simpa only [support] using h

theorem sample_14_39_upper : discrepancy (1 / 10) sample_14_39 ≤ (227 / 1000) := by
  have h := sample_14_39_interval.2
  norm_num [logCertificate_53, logCertificate_28938] at h
  linarith

def sample_15_38 : Triple := ⟨15, 38, 53, by decide, by decide, by decide, by decide⟩
theorem sample_15_38_interval :
    (logCertificate_53.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_30210.upper ≤
      discrepancy (1 / 10) sample_15_38 ∧
    discrepancy (1 / 10) sample_15_38 ≤
      (logCertificate_53.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_30210.lower := by
  have hr : radical (15 * 38 * 53) = 30210 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_15_38.a * sample_15_38.b * sample_15_38.c)) :=
    ⟨logCertificate_30210.lower, logCertificate_30210.upper,
      by simpa only [sample_15_38, hr] using logCertificate_30210.lower_le,
      by simpa only [sample_15_38, hr] using logCertificate_30210.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_15_38 logCertificate_53 support
  simpa only [support] using h

theorem sample_15_38_upper : discrepancy (1 / 10) sample_15_38 ≤ (227 / 1000) := by
  have h := sample_15_38_interval.2
  norm_num [logCertificate_53, logCertificate_30210] at h
  linarith

def sample_16_37 : Triple := ⟨16, 37, 53, by decide, by decide, by decide, by decide⟩
theorem sample_16_37_interval :
    (logCertificate_53.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_3922.upper ≤
      discrepancy (1 / 10) sample_16_37 ∧
    discrepancy (1 / 10) sample_16_37 ≤
      (logCertificate_53.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_3922.lower := by
  have hr : radical (16 * 37 * 53) = 3922 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_16_37.a * sample_16_37.b * sample_16_37.c)) :=
    ⟨logCertificate_3922.lower, logCertificate_3922.upper,
      by simpa only [sample_16_37, hr] using logCertificate_3922.lower_le,
      by simpa only [sample_16_37, hr] using logCertificate_3922.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_16_37 logCertificate_53 support
  simpa only [support] using h

theorem sample_16_37_upper : discrepancy (1 / 10) sample_16_37 ≤ (227 / 1000) := by
  have h := sample_16_37_interval.2
  norm_num [logCertificate_53, logCertificate_3922] at h
  linarith

def sample_17_36 : Triple := ⟨17, 36, 53, by decide, by decide, by decide, by decide⟩
theorem sample_17_36_interval :
    (logCertificate_53.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_5406.upper ≤
      discrepancy (1 / 10) sample_17_36 ∧
    discrepancy (1 / 10) sample_17_36 ≤
      (logCertificate_53.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_5406.lower := by
  have hr : radical (17 * 36 * 53) = 5406 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_17_36.a * sample_17_36.b * sample_17_36.c)) :=
    ⟨logCertificate_5406.lower, logCertificate_5406.upper,
      by simpa only [sample_17_36, hr] using logCertificate_5406.lower_le,
      by simpa only [sample_17_36, hr] using logCertificate_5406.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_17_36 logCertificate_53 support
  simpa only [support] using h

theorem sample_17_36_upper : discrepancy (1 / 10) sample_17_36 ≤ (227 / 1000) := by
  have h := sample_17_36_interval.2
  norm_num [logCertificate_53, logCertificate_5406] at h
  linarith

def sample_18_35 : Triple := ⟨18, 35, 53, by decide, by decide, by decide, by decide⟩
theorem sample_18_35_interval :
    (logCertificate_53.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_11130.upper ≤
      discrepancy (1 / 10) sample_18_35 ∧
    discrepancy (1 / 10) sample_18_35 ≤
      (logCertificate_53.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_11130.lower := by
  have hr : radical (18 * 35 * 53) = 11130 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_18_35.a * sample_18_35.b * sample_18_35.c)) :=
    ⟨logCertificate_11130.lower, logCertificate_11130.upper,
      by simpa only [sample_18_35, hr] using logCertificate_11130.lower_le,
      by simpa only [sample_18_35, hr] using logCertificate_11130.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_18_35 logCertificate_53 support
  simpa only [support] using h

theorem sample_18_35_upper : discrepancy (1 / 10) sample_18_35 ≤ (227 / 1000) := by
  have h := sample_18_35_interval.2
  norm_num [logCertificate_53, logCertificate_11130] at h
  linarith

def sample_19_34 : Triple := ⟨19, 34, 53, by decide, by decide, by decide, by decide⟩
theorem sample_19_34_interval :
    (logCertificate_53.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_34238.upper ≤
      discrepancy (1 / 10) sample_19_34 ∧
    discrepancy (1 / 10) sample_19_34 ≤
      (logCertificate_53.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_34238.lower := by
  have hr : radical (19 * 34 * 53) = 34238 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_19_34.a * sample_19_34.b * sample_19_34.c)) :=
    ⟨logCertificate_34238.lower, logCertificate_34238.upper,
      by simpa only [sample_19_34, hr] using logCertificate_34238.lower_le,
      by simpa only [sample_19_34, hr] using logCertificate_34238.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_19_34 logCertificate_53 support
  simpa only [support] using h

theorem sample_19_34_upper : discrepancy (1 / 10) sample_19_34 ≤ (227 / 1000) := by
  have h := sample_19_34_interval.2
  norm_num [logCertificate_53, logCertificate_34238] at h
  linarith

def sample_20_33 : Triple := ⟨20, 33, 53, by decide, by decide, by decide, by decide⟩
theorem sample_20_33_interval :
    (logCertificate_53.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_17490.upper ≤
      discrepancy (1 / 10) sample_20_33 ∧
    discrepancy (1 / 10) sample_20_33 ≤
      (logCertificate_53.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_17490.lower := by
  have hr : radical (20 * 33 * 53) = 17490 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_20_33.a * sample_20_33.b * sample_20_33.c)) :=
    ⟨logCertificate_17490.lower, logCertificate_17490.upper,
      by simpa only [sample_20_33, hr] using logCertificate_17490.lower_le,
      by simpa only [sample_20_33, hr] using logCertificate_17490.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_20_33 logCertificate_53 support
  simpa only [support] using h

theorem sample_20_33_upper : discrepancy (1 / 10) sample_20_33 ≤ (227 / 1000) := by
  have h := sample_20_33_interval.2
  norm_num [logCertificate_53, logCertificate_17490] at h
  linarith

def sample_21_32 : Triple := ⟨21, 32, 53, by decide, by decide, by decide, by decide⟩
theorem sample_21_32_interval :
    (logCertificate_53.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_2226.upper ≤
      discrepancy (1 / 10) sample_21_32 ∧
    discrepancy (1 / 10) sample_21_32 ≤
      (logCertificate_53.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_2226.lower := by
  have hr : radical (21 * 32 * 53) = 2226 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_21_32.a * sample_21_32.b * sample_21_32.c)) :=
    ⟨logCertificate_2226.lower, logCertificate_2226.upper,
      by simpa only [sample_21_32, hr] using logCertificate_2226.lower_le,
      by simpa only [sample_21_32, hr] using logCertificate_2226.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_21_32 logCertificate_53 support
  simpa only [support] using h

theorem sample_21_32_upper : discrepancy (1 / 10) sample_21_32 ≤ (227 / 1000) := by
  have h := sample_21_32_interval.2
  norm_num [logCertificate_53, logCertificate_2226] at h
  linarith

def sample_22_31 : Triple := ⟨22, 31, 53, by decide, by decide, by decide, by decide⟩
theorem sample_22_31_interval :
    (logCertificate_53.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_36146.upper ≤
      discrepancy (1 / 10) sample_22_31 ∧
    discrepancy (1 / 10) sample_22_31 ≤
      (logCertificate_53.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_36146.lower := by
  have hr : radical (22 * 31 * 53) = 36146 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_22_31.a * sample_22_31.b * sample_22_31.c)) :=
    ⟨logCertificate_36146.lower, logCertificate_36146.upper,
      by simpa only [sample_22_31, hr] using logCertificate_36146.lower_le,
      by simpa only [sample_22_31, hr] using logCertificate_36146.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_22_31 logCertificate_53 support
  simpa only [support] using h

theorem sample_22_31_upper : discrepancy (1 / 10) sample_22_31 ≤ (227 / 1000) := by
  have h := sample_22_31_interval.2
  norm_num [logCertificate_53, logCertificate_36146] at h
  linarith

def sample_23_30 : Triple := ⟨23, 30, 53, by decide, by decide, by decide, by decide⟩
theorem sample_23_30_interval :
    (logCertificate_53.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_36570.upper ≤
      discrepancy (1 / 10) sample_23_30 ∧
    discrepancy (1 / 10) sample_23_30 ≤
      (logCertificate_53.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_36570.lower := by
  have hr : radical (23 * 30 * 53) = 36570 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_23_30.a * sample_23_30.b * sample_23_30.c)) :=
    ⟨logCertificate_36570.lower, logCertificate_36570.upper,
      by simpa only [sample_23_30, hr] using logCertificate_36570.lower_le,
      by simpa only [sample_23_30, hr] using logCertificate_36570.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_23_30 logCertificate_53 support
  simpa only [support] using h

theorem sample_23_30_upper : discrepancy (1 / 10) sample_23_30 ≤ (227 / 1000) := by
  have h := sample_23_30_interval.2
  norm_num [logCertificate_53, logCertificate_36570] at h
  linarith

def sample_24_29 : Triple := ⟨24, 29, 53, by decide, by decide, by decide, by decide⟩
theorem sample_24_29_interval :
    (logCertificate_53.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_9222.upper ≤
      discrepancy (1 / 10) sample_24_29 ∧
    discrepancy (1 / 10) sample_24_29 ≤
      (logCertificate_53.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_9222.lower := by
  have hr : radical (24 * 29 * 53) = 9222 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_24_29.a * sample_24_29.b * sample_24_29.c)) :=
    ⟨logCertificate_9222.lower, logCertificate_9222.upper,
      by simpa only [sample_24_29, hr] using logCertificate_9222.lower_le,
      by simpa only [sample_24_29, hr] using logCertificate_9222.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_24_29 logCertificate_53 support
  simpa only [support] using h

theorem sample_24_29_upper : discrepancy (1 / 10) sample_24_29 ≤ (227 / 1000) := by
  have h := sample_24_29_interval.2
  norm_num [logCertificate_53, logCertificate_9222] at h
  linarith

def sample_25_28 : Triple := ⟨25, 28, 53, by decide, by decide, by decide, by decide⟩
theorem sample_25_28_interval :
    (logCertificate_53.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_3710.upper ≤
      discrepancy (1 / 10) sample_25_28 ∧
    discrepancy (1 / 10) sample_25_28 ≤
      (logCertificate_53.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_3710.lower := by
  have hr : radical (25 * 28 * 53) = 3710 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_25_28.a * sample_25_28.b * sample_25_28.c)) :=
    ⟨logCertificate_3710.lower, logCertificate_3710.upper,
      by simpa only [sample_25_28, hr] using logCertificate_3710.lower_le,
      by simpa only [sample_25_28, hr] using logCertificate_3710.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_25_28 logCertificate_53 support
  simpa only [support] using h

theorem sample_25_28_upper : discrepancy (1 / 10) sample_25_28 ≤ (227 / 1000) := by
  have h := sample_25_28_interval.2
  norm_num [logCertificate_53, logCertificate_3710] at h
  linarith

def sample_26_27 : Triple := ⟨26, 27, 53, by decide, by decide, by decide, by decide⟩
theorem sample_26_27_interval :
    (logCertificate_53.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_4134.upper ≤
      discrepancy (1 / 10) sample_26_27 ∧
    discrepancy (1 / 10) sample_26_27 ≤
      (logCertificate_53.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_4134.lower := by
  have hr : radical (26 * 27 * 53) = 4134 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_26_27.a * sample_26_27.b * sample_26_27.c)) :=
    ⟨logCertificate_4134.lower, logCertificate_4134.upper,
      by simpa only [sample_26_27, hr] using logCertificate_4134.lower_le,
      by simpa only [sample_26_27, hr] using logCertificate_4134.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_26_27 logCertificate_53 support
  simpa only [support] using h

theorem sample_26_27_upper : discrepancy (1 / 10) sample_26_27 ≤ (227 / 1000) := by
  have h := sample_26_27_interval.2
  norm_num [logCertificate_53, logCertificate_4134] at h
  linarith

def sample_1_53 : Triple := ⟨1, 53, 54, by decide, by decide, by decide, by decide⟩
theorem sample_1_53_interval :
    (logCertificate_54.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_318.upper ≤
      discrepancy (1 / 10) sample_1_53 ∧
    discrepancy (1 / 10) sample_1_53 ≤
      (logCertificate_54.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_318.lower := by
  have hr : radical (1 * 53 * 54) = 318 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_1_53.a * sample_1_53.b * sample_1_53.c)) :=
    ⟨logCertificate_318.lower, logCertificate_318.upper,
      by simpa only [sample_1_53, hr] using logCertificate_318.lower_le,
      by simpa only [sample_1_53, hr] using logCertificate_318.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_1_53 logCertificate_54 support
  simpa only [support] using h

theorem sample_1_53_upper : discrepancy (1 / 10) sample_1_53 ≤ (227 / 1000) := by
  have h := sample_1_53_interval.2
  norm_num [logCertificate_54, logCertificate_318] at h
  linarith

def sample_5_49 : Triple := ⟨5, 49, 54, by decide, by decide, by decide, by decide⟩
theorem sample_5_49_interval :
    (logCertificate_54.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_210.upper ≤
      discrepancy (1 / 10) sample_5_49 ∧
    discrepancy (1 / 10) sample_5_49 ≤
      (logCertificate_54.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_210.lower := by
  have hr : radical (5 * 49 * 54) = 210 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_5_49.a * sample_5_49.b * sample_5_49.c)) :=
    ⟨logCertificate_210.lower, logCertificate_210.upper,
      by simpa only [sample_5_49, hr] using logCertificate_210.lower_le,
      by simpa only [sample_5_49, hr] using logCertificate_210.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_5_49 logCertificate_54 support
  simpa only [support] using h

theorem sample_5_49_upper : discrepancy (1 / 10) sample_5_49 ≤ (227 / 1000) := by
  have h := sample_5_49_interval.2
  norm_num [logCertificate_54, logCertificate_210] at h
  linarith

def sample_7_47 : Triple := ⟨7, 47, 54, by decide, by decide, by decide, by decide⟩
theorem sample_7_47_interval :
    (logCertificate_54.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1974.upper ≤
      discrepancy (1 / 10) sample_7_47 ∧
    discrepancy (1 / 10) sample_7_47 ≤
      (logCertificate_54.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1974.lower := by
  have hr : radical (7 * 47 * 54) = 1974 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_7_47.a * sample_7_47.b * sample_7_47.c)) :=
    ⟨logCertificate_1974.lower, logCertificate_1974.upper,
      by simpa only [sample_7_47, hr] using logCertificate_1974.lower_le,
      by simpa only [sample_7_47, hr] using logCertificate_1974.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_7_47 logCertificate_54 support
  simpa only [support] using h

theorem sample_7_47_upper : discrepancy (1 / 10) sample_7_47 ≤ (227 / 1000) := by
  have h := sample_7_47_interval.2
  norm_num [logCertificate_54, logCertificate_1974] at h
  linarith

def sample_11_43 : Triple := ⟨11, 43, 54, by decide, by decide, by decide, by decide⟩
theorem sample_11_43_interval :
    (logCertificate_54.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_2838.upper ≤
      discrepancy (1 / 10) sample_11_43 ∧
    discrepancy (1 / 10) sample_11_43 ≤
      (logCertificate_54.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_2838.lower := by
  have hr : radical (11 * 43 * 54) = 2838 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_11_43.a * sample_11_43.b * sample_11_43.c)) :=
    ⟨logCertificate_2838.lower, logCertificate_2838.upper,
      by simpa only [sample_11_43, hr] using logCertificate_2838.lower_le,
      by simpa only [sample_11_43, hr] using logCertificate_2838.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_11_43 logCertificate_54 support
  simpa only [support] using h

theorem sample_11_43_upper : discrepancy (1 / 10) sample_11_43 ≤ (227 / 1000) := by
  have h := sample_11_43_interval.2
  norm_num [logCertificate_54, logCertificate_2838] at h
  linarith

def sample_13_41 : Triple := ⟨13, 41, 54, by decide, by decide, by decide, by decide⟩
theorem sample_13_41_interval :
    (logCertificate_54.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_3198.upper ≤
      discrepancy (1 / 10) sample_13_41 ∧
    discrepancy (1 / 10) sample_13_41 ≤
      (logCertificate_54.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_3198.lower := by
  have hr : radical (13 * 41 * 54) = 3198 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_13_41.a * sample_13_41.b * sample_13_41.c)) :=
    ⟨logCertificate_3198.lower, logCertificate_3198.upper,
      by simpa only [sample_13_41, hr] using logCertificate_3198.lower_le,
      by simpa only [sample_13_41, hr] using logCertificate_3198.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_13_41 logCertificate_54 support
  simpa only [support] using h

theorem sample_13_41_upper : discrepancy (1 / 10) sample_13_41 ≤ (227 / 1000) := by
  have h := sample_13_41_interval.2
  norm_num [logCertificate_54, logCertificate_3198] at h
  linarith

def sample_17_37 : Triple := ⟨17, 37, 54, by decide, by decide, by decide, by decide⟩
theorem sample_17_37_interval :
    (logCertificate_54.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_3774.upper ≤
      discrepancy (1 / 10) sample_17_37 ∧
    discrepancy (1 / 10) sample_17_37 ≤
      (logCertificate_54.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_3774.lower := by
  have hr : radical (17 * 37 * 54) = 3774 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_17_37.a * sample_17_37.b * sample_17_37.c)) :=
    ⟨logCertificate_3774.lower, logCertificate_3774.upper,
      by simpa only [sample_17_37, hr] using logCertificate_3774.lower_le,
      by simpa only [sample_17_37, hr] using logCertificate_3774.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_17_37 logCertificate_54 support
  simpa only [support] using h

theorem sample_17_37_upper : discrepancy (1 / 10) sample_17_37 ≤ (227 / 1000) := by
  have h := sample_17_37_interval.2
  norm_num [logCertificate_54, logCertificate_3774] at h
  linarith

def sample_19_35 : Triple := ⟨19, 35, 54, by decide, by decide, by decide, by decide⟩
theorem sample_19_35_interval :
    (logCertificate_54.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_3990.upper ≤
      discrepancy (1 / 10) sample_19_35 ∧
    discrepancy (1 / 10) sample_19_35 ≤
      (logCertificate_54.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_3990.lower := by
  have hr : radical (19 * 35 * 54) = 3990 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_19_35.a * sample_19_35.b * sample_19_35.c)) :=
    ⟨logCertificate_3990.lower, logCertificate_3990.upper,
      by simpa only [sample_19_35, hr] using logCertificate_3990.lower_le,
      by simpa only [sample_19_35, hr] using logCertificate_3990.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_19_35 logCertificate_54 support
  simpa only [support] using h

theorem sample_19_35_upper : discrepancy (1 / 10) sample_19_35 ≤ (227 / 1000) := by
  have h := sample_19_35_interval.2
  norm_num [logCertificate_54, logCertificate_3990] at h
  linarith

def sample_23_31 : Triple := ⟨23, 31, 54, by decide, by decide, by decide, by decide⟩
theorem sample_23_31_interval :
    (logCertificate_54.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_4278.upper ≤
      discrepancy (1 / 10) sample_23_31 ∧
    discrepancy (1 / 10) sample_23_31 ≤
      (logCertificate_54.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_4278.lower := by
  have hr : radical (23 * 31 * 54) = 4278 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_23_31.a * sample_23_31.b * sample_23_31.c)) :=
    ⟨logCertificate_4278.lower, logCertificate_4278.upper,
      by simpa only [sample_23_31, hr] using logCertificate_4278.lower_le,
      by simpa only [sample_23_31, hr] using logCertificate_4278.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_23_31 logCertificate_54 support
  simpa only [support] using h

theorem sample_23_31_upper : discrepancy (1 / 10) sample_23_31 ≤ (227 / 1000) := by
  have h := sample_23_31_interval.2
  norm_num [logCertificate_54, logCertificate_4278] at h
  linarith

def sample_25_29 : Triple := ⟨25, 29, 54, by decide, by decide, by decide, by decide⟩
theorem sample_25_29_interval :
    (logCertificate_54.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_870.upper ≤
      discrepancy (1 / 10) sample_25_29 ∧
    discrepancy (1 / 10) sample_25_29 ≤
      (logCertificate_54.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_870.lower := by
  have hr : radical (25 * 29 * 54) = 870 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_25_29.a * sample_25_29.b * sample_25_29.c)) :=
    ⟨logCertificate_870.lower, logCertificate_870.upper,
      by simpa only [sample_25_29, hr] using logCertificate_870.lower_le,
      by simpa only [sample_25_29, hr] using logCertificate_870.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_25_29 logCertificate_54 support
  simpa only [support] using h

theorem sample_25_29_upper : discrepancy (1 / 10) sample_25_29 ≤ (227 / 1000) := by
  have h := sample_25_29_interval.2
  norm_num [logCertificate_54, logCertificate_870] at h
  linarith


end Imscribing.ABC.Window70E1_10
