import Imscribing.ABC_Window70_FromOS_Samples2

/-! Generated by scripts/abc_emit_window_certificate.py; all claims checked by Lean. -/
namespace Imscribing.ABC.Window70E1_10

set_option maxRecDepth 8192
set_option maxHeartbeats 4000000
set_option synthInstance.maxSize 16384
set_option synthInstance.maxHeartbeats 4000000

def sample_1_31 : Triple := ⟨1, 31, 32, by decide, by decide, by decide, by decide⟩
theorem sample_1_31_interval :
    (logCertificate_32.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_62.upper ≤
      discrepancy (1 / 10) sample_1_31 ∧
    discrepancy (1 / 10) sample_1_31 ≤
      (logCertificate_32.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_62.lower := by
  have hr : radical (1 * 31 * 32) = 62 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_1_31.a * sample_1_31.b * sample_1_31.c)) :=
    ⟨logCertificate_62.lower, logCertificate_62.upper,
      by simpa only [sample_1_31, hr] using logCertificate_62.lower_le,
      by simpa only [sample_1_31, hr] using logCertificate_62.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_1_31 logCertificate_32 support
  simpa only [support] using h

theorem sample_1_31_upper : discrepancy (1 / 10) sample_1_31 ≤ (227 / 1000) := by
  have h := sample_1_31_interval.2
  norm_num [logCertificate_32, logCertificate_62] at h
  linarith

def sample_3_29 : Triple := ⟨3, 29, 32, by decide, by decide, by decide, by decide⟩
theorem sample_3_29_interval :
    (logCertificate_32.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_174.upper ≤
      discrepancy (1 / 10) sample_3_29 ∧
    discrepancy (1 / 10) sample_3_29 ≤
      (logCertificate_32.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_174.lower := by
  have hr : radical (3 * 29 * 32) = 174 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_3_29.a * sample_3_29.b * sample_3_29.c)) :=
    ⟨logCertificate_174.lower, logCertificate_174.upper,
      by simpa only [sample_3_29, hr] using logCertificate_174.lower_le,
      by simpa only [sample_3_29, hr] using logCertificate_174.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_3_29 logCertificate_32 support
  simpa only [support] using h

theorem sample_3_29_upper : discrepancy (1 / 10) sample_3_29 ≤ (227 / 1000) := by
  have h := sample_3_29_interval.2
  norm_num [logCertificate_32, logCertificate_174] at h
  linarith

def sample_5_27 : Triple := ⟨5, 27, 32, by decide, by decide, by decide, by decide⟩
theorem sample_5_27_interval :
    (logCertificate_32.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_30.upper ≤
      discrepancy (1 / 10) sample_5_27 ∧
    discrepancy (1 / 10) sample_5_27 ≤
      (logCertificate_32.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_30.lower := by
  have hr : radical (5 * 27 * 32) = 30 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_5_27.a * sample_5_27.b * sample_5_27.c)) :=
    ⟨logCertificate_30.lower, logCertificate_30.upper,
      by simpa only [sample_5_27, hr] using logCertificate_30.lower_le,
      by simpa only [sample_5_27, hr] using logCertificate_30.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_5_27 logCertificate_32 support
  simpa only [support] using h

theorem sample_5_27_upper : discrepancy (1 / 10) sample_5_27 ≤ (227 / 1000) := by
  have h := sample_5_27_interval.2
  norm_num [logCertificate_32, logCertificate_30] at h
  linarith

def sample_7_25 : Triple := ⟨7, 25, 32, by decide, by decide, by decide, by decide⟩
theorem sample_7_25_interval :
    (logCertificate_32.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_70.upper ≤
      discrepancy (1 / 10) sample_7_25 ∧
    discrepancy (1 / 10) sample_7_25 ≤
      (logCertificate_32.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_70.lower := by
  have hr : radical (7 * 25 * 32) = 70 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_7_25.a * sample_7_25.b * sample_7_25.c)) :=
    ⟨logCertificate_70.lower, logCertificate_70.upper,
      by simpa only [sample_7_25, hr] using logCertificate_70.lower_le,
      by simpa only [sample_7_25, hr] using logCertificate_70.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_7_25 logCertificate_32 support
  simpa only [support] using h

theorem sample_7_25_upper : discrepancy (1 / 10) sample_7_25 ≤ (227 / 1000) := by
  have h := sample_7_25_interval.2
  norm_num [logCertificate_32, logCertificate_70] at h
  linarith

def sample_9_23 : Triple := ⟨9, 23, 32, by decide, by decide, by decide, by decide⟩
theorem sample_9_23_interval :
    (logCertificate_32.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_138.upper ≤
      discrepancy (1 / 10) sample_9_23 ∧
    discrepancy (1 / 10) sample_9_23 ≤
      (logCertificate_32.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_138.lower := by
  have hr : radical (9 * 23 * 32) = 138 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_9_23.a * sample_9_23.b * sample_9_23.c)) :=
    ⟨logCertificate_138.lower, logCertificate_138.upper,
      by simpa only [sample_9_23, hr] using logCertificate_138.lower_le,
      by simpa only [sample_9_23, hr] using logCertificate_138.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_9_23 logCertificate_32 support
  simpa only [support] using h

theorem sample_9_23_upper : discrepancy (1 / 10) sample_9_23 ≤ (227 / 1000) := by
  have h := sample_9_23_interval.2
  norm_num [logCertificate_32, logCertificate_138] at h
  linarith

def sample_11_21 : Triple := ⟨11, 21, 32, by decide, by decide, by decide, by decide⟩
theorem sample_11_21_interval :
    (logCertificate_32.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_462.upper ≤
      discrepancy (1 / 10) sample_11_21 ∧
    discrepancy (1 / 10) sample_11_21 ≤
      (logCertificate_32.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_462.lower := by
  have hr : radical (11 * 21 * 32) = 462 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_11_21.a * sample_11_21.b * sample_11_21.c)) :=
    ⟨logCertificate_462.lower, logCertificate_462.upper,
      by simpa only [sample_11_21, hr] using logCertificate_462.lower_le,
      by simpa only [sample_11_21, hr] using logCertificate_462.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_11_21 logCertificate_32 support
  simpa only [support] using h

theorem sample_11_21_upper : discrepancy (1 / 10) sample_11_21 ≤ (227 / 1000) := by
  have h := sample_11_21_interval.2
  norm_num [logCertificate_32, logCertificate_462] at h
  linarith

def sample_13_19 : Triple := ⟨13, 19, 32, by decide, by decide, by decide, by decide⟩
theorem sample_13_19_interval :
    (logCertificate_32.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_494.upper ≤
      discrepancy (1 / 10) sample_13_19 ∧
    discrepancy (1 / 10) sample_13_19 ≤
      (logCertificate_32.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_494.lower := by
  have hr : radical (13 * 19 * 32) = 494 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_13_19.a * sample_13_19.b * sample_13_19.c)) :=
    ⟨logCertificate_494.lower, logCertificate_494.upper,
      by simpa only [sample_13_19, hr] using logCertificate_494.lower_le,
      by simpa only [sample_13_19, hr] using logCertificate_494.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_13_19 logCertificate_32 support
  simpa only [support] using h

theorem sample_13_19_upper : discrepancy (1 / 10) sample_13_19 ≤ (227 / 1000) := by
  have h := sample_13_19_interval.2
  norm_num [logCertificate_32, logCertificate_494] at h
  linarith

def sample_15_17 : Triple := ⟨15, 17, 32, by decide, by decide, by decide, by decide⟩
theorem sample_15_17_interval :
    (logCertificate_32.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_510.upper ≤
      discrepancy (1 / 10) sample_15_17 ∧
    discrepancy (1 / 10) sample_15_17 ≤
      (logCertificate_32.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_510.lower := by
  have hr : radical (15 * 17 * 32) = 510 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_15_17.a * sample_15_17.b * sample_15_17.c)) :=
    ⟨logCertificate_510.lower, logCertificate_510.upper,
      by simpa only [sample_15_17, hr] using logCertificate_510.lower_le,
      by simpa only [sample_15_17, hr] using logCertificate_510.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_15_17 logCertificate_32 support
  simpa only [support] using h

theorem sample_15_17_upper : discrepancy (1 / 10) sample_15_17 ≤ (227 / 1000) := by
  have h := sample_15_17_interval.2
  norm_num [logCertificate_32, logCertificate_510] at h
  linarith

def sample_1_32 : Triple := ⟨1, 32, 33, by decide, by decide, by decide, by decide⟩
theorem sample_1_32_interval :
    (logCertificate_33.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_66.upper ≤
      discrepancy (1 / 10) sample_1_32 ∧
    discrepancy (1 / 10) sample_1_32 ≤
      (logCertificate_33.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_66.lower := by
  have hr : radical (1 * 32 * 33) = 66 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_1_32.a * sample_1_32.b * sample_1_32.c)) :=
    ⟨logCertificate_66.lower, logCertificate_66.upper,
      by simpa only [sample_1_32, hr] using logCertificate_66.lower_le,
      by simpa only [sample_1_32, hr] using logCertificate_66.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_1_32 logCertificate_33 support
  simpa only [support] using h

theorem sample_1_32_upper : discrepancy (1 / 10) sample_1_32 ≤ (227 / 1000) := by
  have h := sample_1_32_interval.2
  norm_num [logCertificate_33, logCertificate_66] at h
  linarith

def sample_2_31 : Triple := ⟨2, 31, 33, by decide, by decide, by decide, by decide⟩
theorem sample_2_31_interval :
    (logCertificate_33.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_2046.upper ≤
      discrepancy (1 / 10) sample_2_31 ∧
    discrepancy (1 / 10) sample_2_31 ≤
      (logCertificate_33.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_2046.lower := by
  have hr : radical (2 * 31 * 33) = 2046 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_2_31.a * sample_2_31.b * sample_2_31.c)) :=
    ⟨logCertificate_2046.lower, logCertificate_2046.upper,
      by simpa only [sample_2_31, hr] using logCertificate_2046.lower_le,
      by simpa only [sample_2_31, hr] using logCertificate_2046.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_2_31 logCertificate_33 support
  simpa only [support] using h

theorem sample_2_31_upper : discrepancy (1 / 10) sample_2_31 ≤ (227 / 1000) := by
  have h := sample_2_31_interval.2
  norm_num [logCertificate_33, logCertificate_2046] at h
  linarith

def sample_4_29 : Triple := ⟨4, 29, 33, by decide, by decide, by decide, by decide⟩
theorem sample_4_29_interval :
    (logCertificate_33.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1914.upper ≤
      discrepancy (1 / 10) sample_4_29 ∧
    discrepancy (1 / 10) sample_4_29 ≤
      (logCertificate_33.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1914.lower := by
  have hr : radical (4 * 29 * 33) = 1914 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_4_29.a * sample_4_29.b * sample_4_29.c)) :=
    ⟨logCertificate_1914.lower, logCertificate_1914.upper,
      by simpa only [sample_4_29, hr] using logCertificate_1914.lower_le,
      by simpa only [sample_4_29, hr] using logCertificate_1914.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_4_29 logCertificate_33 support
  simpa only [support] using h

theorem sample_4_29_upper : discrepancy (1 / 10) sample_4_29 ≤ (227 / 1000) := by
  have h := sample_4_29_interval.2
  norm_num [logCertificate_33, logCertificate_1914] at h
  linarith

def sample_5_28 : Triple := ⟨5, 28, 33, by decide, by decide, by decide, by decide⟩
theorem sample_5_28_interval :
    (logCertificate_33.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_2310.upper ≤
      discrepancy (1 / 10) sample_5_28 ∧
    discrepancy (1 / 10) sample_5_28 ≤
      (logCertificate_33.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_2310.lower := by
  have hr : radical (5 * 28 * 33) = 2310 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_5_28.a * sample_5_28.b * sample_5_28.c)) :=
    ⟨logCertificate_2310.lower, logCertificate_2310.upper,
      by simpa only [sample_5_28, hr] using logCertificate_2310.lower_le,
      by simpa only [sample_5_28, hr] using logCertificate_2310.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_5_28 logCertificate_33 support
  simpa only [support] using h

theorem sample_5_28_upper : discrepancy (1 / 10) sample_5_28 ≤ (227 / 1000) := by
  have h := sample_5_28_interval.2
  norm_num [logCertificate_33, logCertificate_2310] at h
  linarith

def sample_7_26 : Triple := ⟨7, 26, 33, by decide, by decide, by decide, by decide⟩
theorem sample_7_26_interval :
    (logCertificate_33.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_6006.upper ≤
      discrepancy (1 / 10) sample_7_26 ∧
    discrepancy (1 / 10) sample_7_26 ≤
      (logCertificate_33.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_6006.lower := by
  have hr : radical (7 * 26 * 33) = 6006 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_7_26.a * sample_7_26.b * sample_7_26.c)) :=
    ⟨logCertificate_6006.lower, logCertificate_6006.upper,
      by simpa only [sample_7_26, hr] using logCertificate_6006.lower_le,
      by simpa only [sample_7_26, hr] using logCertificate_6006.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_7_26 logCertificate_33 support
  simpa only [support] using h

theorem sample_7_26_upper : discrepancy (1 / 10) sample_7_26 ≤ (227 / 1000) := by
  have h := sample_7_26_interval.2
  norm_num [logCertificate_33, logCertificate_6006] at h
  linarith

def sample_8_25 : Triple := ⟨8, 25, 33, by decide, by decide, by decide, by decide⟩
theorem sample_8_25_interval :
    (logCertificate_33.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_330.upper ≤
      discrepancy (1 / 10) sample_8_25 ∧
    discrepancy (1 / 10) sample_8_25 ≤
      (logCertificate_33.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_330.lower := by
  have hr : radical (8 * 25 * 33) = 330 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_8_25.a * sample_8_25.b * sample_8_25.c)) :=
    ⟨logCertificate_330.lower, logCertificate_330.upper,
      by simpa only [sample_8_25, hr] using logCertificate_330.lower_le,
      by simpa only [sample_8_25, hr] using logCertificate_330.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_8_25 logCertificate_33 support
  simpa only [support] using h

theorem sample_8_25_upper : discrepancy (1 / 10) sample_8_25 ≤ (227 / 1000) := by
  have h := sample_8_25_interval.2
  norm_num [logCertificate_33, logCertificate_330] at h
  linarith

def sample_10_23 : Triple := ⟨10, 23, 33, by decide, by decide, by decide, by decide⟩
theorem sample_10_23_interval :
    (logCertificate_33.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_7590.upper ≤
      discrepancy (1 / 10) sample_10_23 ∧
    discrepancy (1 / 10) sample_10_23 ≤
      (logCertificate_33.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_7590.lower := by
  have hr : radical (10 * 23 * 33) = 7590 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_10_23.a * sample_10_23.b * sample_10_23.c)) :=
    ⟨logCertificate_7590.lower, logCertificate_7590.upper,
      by simpa only [sample_10_23, hr] using logCertificate_7590.lower_le,
      by simpa only [sample_10_23, hr] using logCertificate_7590.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_10_23 logCertificate_33 support
  simpa only [support] using h

theorem sample_10_23_upper : discrepancy (1 / 10) sample_10_23 ≤ (227 / 1000) := by
  have h := sample_10_23_interval.2
  norm_num [logCertificate_33, logCertificate_7590] at h
  linarith

def sample_13_20 : Triple := ⟨13, 20, 33, by decide, by decide, by decide, by decide⟩
theorem sample_13_20_interval :
    (logCertificate_33.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_4290.upper ≤
      discrepancy (1 / 10) sample_13_20 ∧
    discrepancy (1 / 10) sample_13_20 ≤
      (logCertificate_33.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_4290.lower := by
  have hr : radical (13 * 20 * 33) = 4290 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_13_20.a * sample_13_20.b * sample_13_20.c)) :=
    ⟨logCertificate_4290.lower, logCertificate_4290.upper,
      by simpa only [sample_13_20, hr] using logCertificate_4290.lower_le,
      by simpa only [sample_13_20, hr] using logCertificate_4290.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_13_20 logCertificate_33 support
  simpa only [support] using h

theorem sample_13_20_upper : discrepancy (1 / 10) sample_13_20 ≤ (227 / 1000) := by
  have h := sample_13_20_interval.2
  norm_num [logCertificate_33, logCertificate_4290] at h
  linarith

def sample_14_19 : Triple := ⟨14, 19, 33, by decide, by decide, by decide, by decide⟩
theorem sample_14_19_interval :
    (logCertificate_33.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_8778.upper ≤
      discrepancy (1 / 10) sample_14_19 ∧
    discrepancy (1 / 10) sample_14_19 ≤
      (logCertificate_33.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_8778.lower := by
  have hr : radical (14 * 19 * 33) = 8778 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_14_19.a * sample_14_19.b * sample_14_19.c)) :=
    ⟨logCertificate_8778.lower, logCertificate_8778.upper,
      by simpa only [sample_14_19, hr] using logCertificate_8778.lower_le,
      by simpa only [sample_14_19, hr] using logCertificate_8778.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_14_19 logCertificate_33 support
  simpa only [support] using h

theorem sample_14_19_upper : discrepancy (1 / 10) sample_14_19 ≤ (227 / 1000) := by
  have h := sample_14_19_interval.2
  norm_num [logCertificate_33, logCertificate_8778] at h
  linarith

def sample_16_17 : Triple := ⟨16, 17, 33, by decide, by decide, by decide, by decide⟩
theorem sample_16_17_interval :
    (logCertificate_33.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1122.upper ≤
      discrepancy (1 / 10) sample_16_17 ∧
    discrepancy (1 / 10) sample_16_17 ≤
      (logCertificate_33.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1122.lower := by
  have hr : radical (16 * 17 * 33) = 1122 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_16_17.a * sample_16_17.b * sample_16_17.c)) :=
    ⟨logCertificate_1122.lower, logCertificate_1122.upper,
      by simpa only [sample_16_17, hr] using logCertificate_1122.lower_le,
      by simpa only [sample_16_17, hr] using logCertificate_1122.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_16_17 logCertificate_33 support
  simpa only [support] using h

theorem sample_16_17_upper : discrepancy (1 / 10) sample_16_17 ≤ (227 / 1000) := by
  have h := sample_16_17_interval.2
  norm_num [logCertificate_33, logCertificate_1122] at h
  linarith

def sample_1_33 : Triple := ⟨1, 33, 34, by decide, by decide, by decide, by decide⟩
theorem sample_1_33_interval :
    (logCertificate_34.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1122.upper ≤
      discrepancy (1 / 10) sample_1_33 ∧
    discrepancy (1 / 10) sample_1_33 ≤
      (logCertificate_34.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1122.lower := by
  have hr : radical (1 * 33 * 34) = 1122 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_1_33.a * sample_1_33.b * sample_1_33.c)) :=
    ⟨logCertificate_1122.lower, logCertificate_1122.upper,
      by simpa only [sample_1_33, hr] using logCertificate_1122.lower_le,
      by simpa only [sample_1_33, hr] using logCertificate_1122.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_1_33 logCertificate_34 support
  simpa only [support] using h

theorem sample_1_33_upper : discrepancy (1 / 10) sample_1_33 ≤ (227 / 1000) := by
  have h := sample_1_33_interval.2
  norm_num [logCertificate_34, logCertificate_1122] at h
  linarith

def sample_3_31 : Triple := ⟨3, 31, 34, by decide, by decide, by decide, by decide⟩
theorem sample_3_31_interval :
    (logCertificate_34.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_3162.upper ≤
      discrepancy (1 / 10) sample_3_31 ∧
    discrepancy (1 / 10) sample_3_31 ≤
      (logCertificate_34.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_3162.lower := by
  have hr : radical (3 * 31 * 34) = 3162 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_3_31.a * sample_3_31.b * sample_3_31.c)) :=
    ⟨logCertificate_3162.lower, logCertificate_3162.upper,
      by simpa only [sample_3_31, hr] using logCertificate_3162.lower_le,
      by simpa only [sample_3_31, hr] using logCertificate_3162.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_3_31 logCertificate_34 support
  simpa only [support] using h

theorem sample_3_31_upper : discrepancy (1 / 10) sample_3_31 ≤ (227 / 1000) := by
  have h := sample_3_31_interval.2
  norm_num [logCertificate_34, logCertificate_3162] at h
  linarith

def sample_5_29 : Triple := ⟨5, 29, 34, by decide, by decide, by decide, by decide⟩
theorem sample_5_29_interval :
    (logCertificate_34.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_4930.upper ≤
      discrepancy (1 / 10) sample_5_29 ∧
    discrepancy (1 / 10) sample_5_29 ≤
      (logCertificate_34.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_4930.lower := by
  have hr : radical (5 * 29 * 34) = 4930 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_5_29.a * sample_5_29.b * sample_5_29.c)) :=
    ⟨logCertificate_4930.lower, logCertificate_4930.upper,
      by simpa only [sample_5_29, hr] using logCertificate_4930.lower_le,
      by simpa only [sample_5_29, hr] using logCertificate_4930.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_5_29 logCertificate_34 support
  simpa only [support] using h

theorem sample_5_29_upper : discrepancy (1 / 10) sample_5_29 ≤ (227 / 1000) := by
  have h := sample_5_29_interval.2
  norm_num [logCertificate_34, logCertificate_4930] at h
  linarith

def sample_7_27 : Triple := ⟨7, 27, 34, by decide, by decide, by decide, by decide⟩
theorem sample_7_27_interval :
    (logCertificate_34.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_714.upper ≤
      discrepancy (1 / 10) sample_7_27 ∧
    discrepancy (1 / 10) sample_7_27 ≤
      (logCertificate_34.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_714.lower := by
  have hr : radical (7 * 27 * 34) = 714 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_7_27.a * sample_7_27.b * sample_7_27.c)) :=
    ⟨logCertificate_714.lower, logCertificate_714.upper,
      by simpa only [sample_7_27, hr] using logCertificate_714.lower_le,
      by simpa only [sample_7_27, hr] using logCertificate_714.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_7_27 logCertificate_34 support
  simpa only [support] using h

theorem sample_7_27_upper : discrepancy (1 / 10) sample_7_27 ≤ (227 / 1000) := by
  have h := sample_7_27_interval.2
  norm_num [logCertificate_34, logCertificate_714] at h
  linarith

def sample_9_25 : Triple := ⟨9, 25, 34, by decide, by decide, by decide, by decide⟩
theorem sample_9_25_interval :
    (logCertificate_34.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_510.upper ≤
      discrepancy (1 / 10) sample_9_25 ∧
    discrepancy (1 / 10) sample_9_25 ≤
      (logCertificate_34.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_510.lower := by
  have hr : radical (9 * 25 * 34) = 510 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_9_25.a * sample_9_25.b * sample_9_25.c)) :=
    ⟨logCertificate_510.lower, logCertificate_510.upper,
      by simpa only [sample_9_25, hr] using logCertificate_510.lower_le,
      by simpa only [sample_9_25, hr] using logCertificate_510.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_9_25 logCertificate_34 support
  simpa only [support] using h

theorem sample_9_25_upper : discrepancy (1 / 10) sample_9_25 ≤ (227 / 1000) := by
  have h := sample_9_25_interval.2
  norm_num [logCertificate_34, logCertificate_510] at h
  linarith

def sample_11_23 : Triple := ⟨11, 23, 34, by decide, by decide, by decide, by decide⟩
theorem sample_11_23_interval :
    (logCertificate_34.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_8602.upper ≤
      discrepancy (1 / 10) sample_11_23 ∧
    discrepancy (1 / 10) sample_11_23 ≤
      (logCertificate_34.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_8602.lower := by
  have hr : radical (11 * 23 * 34) = 8602 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_11_23.a * sample_11_23.b * sample_11_23.c)) :=
    ⟨logCertificate_8602.lower, logCertificate_8602.upper,
      by simpa only [sample_11_23, hr] using logCertificate_8602.lower_le,
      by simpa only [sample_11_23, hr] using logCertificate_8602.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_11_23 logCertificate_34 support
  simpa only [support] using h

theorem sample_11_23_upper : discrepancy (1 / 10) sample_11_23 ≤ (227 / 1000) := by
  have h := sample_11_23_interval.2
  norm_num [logCertificate_34, logCertificate_8602] at h
  linarith

def sample_13_21 : Triple := ⟨13, 21, 34, by decide, by decide, by decide, by decide⟩
theorem sample_13_21_interval :
    (logCertificate_34.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_9282.upper ≤
      discrepancy (1 / 10) sample_13_21 ∧
    discrepancy (1 / 10) sample_13_21 ≤
      (logCertificate_34.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_9282.lower := by
  have hr : radical (13 * 21 * 34) = 9282 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_13_21.a * sample_13_21.b * sample_13_21.c)) :=
    ⟨logCertificate_9282.lower, logCertificate_9282.upper,
      by simpa only [sample_13_21, hr] using logCertificate_9282.lower_le,
      by simpa only [sample_13_21, hr] using logCertificate_9282.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_13_21 logCertificate_34 support
  simpa only [support] using h

theorem sample_13_21_upper : discrepancy (1 / 10) sample_13_21 ≤ (227 / 1000) := by
  have h := sample_13_21_interval.2
  norm_num [logCertificate_34, logCertificate_9282] at h
  linarith

def sample_15_19 : Triple := ⟨15, 19, 34, by decide, by decide, by decide, by decide⟩
theorem sample_15_19_interval :
    (logCertificate_34.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_9690.upper ≤
      discrepancy (1 / 10) sample_15_19 ∧
    discrepancy (1 / 10) sample_15_19 ≤
      (logCertificate_34.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_9690.lower := by
  have hr : radical (15 * 19 * 34) = 9690 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_15_19.a * sample_15_19.b * sample_15_19.c)) :=
    ⟨logCertificate_9690.lower, logCertificate_9690.upper,
      by simpa only [sample_15_19, hr] using logCertificate_9690.lower_le,
      by simpa only [sample_15_19, hr] using logCertificate_9690.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_15_19 logCertificate_34 support
  simpa only [support] using h

theorem sample_15_19_upper : discrepancy (1 / 10) sample_15_19 ≤ (227 / 1000) := by
  have h := sample_15_19_interval.2
  norm_num [logCertificate_34, logCertificate_9690] at h
  linarith

def sample_1_34 : Triple := ⟨1, 34, 35, by decide, by decide, by decide, by decide⟩
theorem sample_1_34_interval :
    (logCertificate_35.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1190.upper ≤
      discrepancy (1 / 10) sample_1_34 ∧
    discrepancy (1 / 10) sample_1_34 ≤
      (logCertificate_35.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1190.lower := by
  have hr : radical (1 * 34 * 35) = 1190 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_1_34.a * sample_1_34.b * sample_1_34.c)) :=
    ⟨logCertificate_1190.lower, logCertificate_1190.upper,
      by simpa only [sample_1_34, hr] using logCertificate_1190.lower_le,
      by simpa only [sample_1_34, hr] using logCertificate_1190.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_1_34 logCertificate_35 support
  simpa only [support] using h

theorem sample_1_34_upper : discrepancy (1 / 10) sample_1_34 ≤ (227 / 1000) := by
  have h := sample_1_34_interval.2
  norm_num [logCertificate_35, logCertificate_1190] at h
  linarith

def sample_2_33 : Triple := ⟨2, 33, 35, by decide, by decide, by decide, by decide⟩
theorem sample_2_33_interval :
    (logCertificate_35.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_2310.upper ≤
      discrepancy (1 / 10) sample_2_33 ∧
    discrepancy (1 / 10) sample_2_33 ≤
      (logCertificate_35.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_2310.lower := by
  have hr : radical (2 * 33 * 35) = 2310 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_2_33.a * sample_2_33.b * sample_2_33.c)) :=
    ⟨logCertificate_2310.lower, logCertificate_2310.upper,
      by simpa only [sample_2_33, hr] using logCertificate_2310.lower_le,
      by simpa only [sample_2_33, hr] using logCertificate_2310.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_2_33 logCertificate_35 support
  simpa only [support] using h

theorem sample_2_33_upper : discrepancy (1 / 10) sample_2_33 ≤ (227 / 1000) := by
  have h := sample_2_33_interval.2
  norm_num [logCertificate_35, logCertificate_2310] at h
  linarith

def sample_3_32 : Triple := ⟨3, 32, 35, by decide, by decide, by decide, by decide⟩
theorem sample_3_32_interval :
    (logCertificate_35.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_210.upper ≤
      discrepancy (1 / 10) sample_3_32 ∧
    discrepancy (1 / 10) sample_3_32 ≤
      (logCertificate_35.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_210.lower := by
  have hr : radical (3 * 32 * 35) = 210 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_3_32.a * sample_3_32.b * sample_3_32.c)) :=
    ⟨logCertificate_210.lower, logCertificate_210.upper,
      by simpa only [sample_3_32, hr] using logCertificate_210.lower_le,
      by simpa only [sample_3_32, hr] using logCertificate_210.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_3_32 logCertificate_35 support
  simpa only [support] using h

theorem sample_3_32_upper : discrepancy (1 / 10) sample_3_32 ≤ (227 / 1000) := by
  have h := sample_3_32_interval.2
  norm_num [logCertificate_35, logCertificate_210] at h
  linarith

def sample_4_31 : Triple := ⟨4, 31, 35, by decide, by decide, by decide, by decide⟩
theorem sample_4_31_interval :
    (logCertificate_35.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_2170.upper ≤
      discrepancy (1 / 10) sample_4_31 ∧
    discrepancy (1 / 10) sample_4_31 ≤
      (logCertificate_35.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_2170.lower := by
  have hr : radical (4 * 31 * 35) = 2170 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_4_31.a * sample_4_31.b * sample_4_31.c)) :=
    ⟨logCertificate_2170.lower, logCertificate_2170.upper,
      by simpa only [sample_4_31, hr] using logCertificate_2170.lower_le,
      by simpa only [sample_4_31, hr] using logCertificate_2170.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_4_31 logCertificate_35 support
  simpa only [support] using h

theorem sample_4_31_upper : discrepancy (1 / 10) sample_4_31 ≤ (227 / 1000) := by
  have h := sample_4_31_interval.2
  norm_num [logCertificate_35, logCertificate_2170] at h
  linarith

def sample_6_29 : Triple := ⟨6, 29, 35, by decide, by decide, by decide, by decide⟩
theorem sample_6_29_interval :
    (logCertificate_35.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_6090.upper ≤
      discrepancy (1 / 10) sample_6_29 ∧
    discrepancy (1 / 10) sample_6_29 ≤
      (logCertificate_35.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_6090.lower := by
  have hr : radical (6 * 29 * 35) = 6090 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_6_29.a * sample_6_29.b * sample_6_29.c)) :=
    ⟨logCertificate_6090.lower, logCertificate_6090.upper,
      by simpa only [sample_6_29, hr] using logCertificate_6090.lower_le,
      by simpa only [sample_6_29, hr] using logCertificate_6090.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_6_29 logCertificate_35 support
  simpa only [support] using h

theorem sample_6_29_upper : discrepancy (1 / 10) sample_6_29 ≤ (227 / 1000) := by
  have h := sample_6_29_interval.2
  norm_num [logCertificate_35, logCertificate_6090] at h
  linarith

def sample_8_27 : Triple := ⟨8, 27, 35, by decide, by decide, by decide, by decide⟩
theorem sample_8_27_interval :
    (logCertificate_35.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_210.upper ≤
      discrepancy (1 / 10) sample_8_27 ∧
    discrepancy (1 / 10) sample_8_27 ≤
      (logCertificate_35.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_210.lower := by
  have hr : radical (8 * 27 * 35) = 210 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_8_27.a * sample_8_27.b * sample_8_27.c)) :=
    ⟨logCertificate_210.lower, logCertificate_210.upper,
      by simpa only [sample_8_27, hr] using logCertificate_210.lower_le,
      by simpa only [sample_8_27, hr] using logCertificate_210.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_8_27 logCertificate_35 support
  simpa only [support] using h

theorem sample_8_27_upper : discrepancy (1 / 10) sample_8_27 ≤ (227 / 1000) := by
  have h := sample_8_27_interval.2
  norm_num [logCertificate_35, logCertificate_210] at h
  linarith

def sample_9_26 : Triple := ⟨9, 26, 35, by decide, by decide, by decide, by decide⟩
theorem sample_9_26_interval :
    (logCertificate_35.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_2730.upper ≤
      discrepancy (1 / 10) sample_9_26 ∧
    discrepancy (1 / 10) sample_9_26 ≤
      (logCertificate_35.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_2730.lower := by
  have hr : radical (9 * 26 * 35) = 2730 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_9_26.a * sample_9_26.b * sample_9_26.c)) :=
    ⟨logCertificate_2730.lower, logCertificate_2730.upper,
      by simpa only [sample_9_26, hr] using logCertificate_2730.lower_le,
      by simpa only [sample_9_26, hr] using logCertificate_2730.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_9_26 logCertificate_35 support
  simpa only [support] using h

theorem sample_9_26_upper : discrepancy (1 / 10) sample_9_26 ≤ (227 / 1000) := by
  have h := sample_9_26_interval.2
  norm_num [logCertificate_35, logCertificate_2730] at h
  linarith

def sample_11_24 : Triple := ⟨11, 24, 35, by decide, by decide, by decide, by decide⟩
theorem sample_11_24_interval :
    (logCertificate_35.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_2310.upper ≤
      discrepancy (1 / 10) sample_11_24 ∧
    discrepancy (1 / 10) sample_11_24 ≤
      (logCertificate_35.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_2310.lower := by
  have hr : radical (11 * 24 * 35) = 2310 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_11_24.a * sample_11_24.b * sample_11_24.c)) :=
    ⟨logCertificate_2310.lower, logCertificate_2310.upper,
      by simpa only [sample_11_24, hr] using logCertificate_2310.lower_le,
      by simpa only [sample_11_24, hr] using logCertificate_2310.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_11_24 logCertificate_35 support
  simpa only [support] using h

theorem sample_11_24_upper : discrepancy (1 / 10) sample_11_24 ≤ (227 / 1000) := by
  have h := sample_11_24_interval.2
  norm_num [logCertificate_35, logCertificate_2310] at h
  linarith

def sample_12_23 : Triple := ⟨12, 23, 35, by decide, by decide, by decide, by decide⟩
theorem sample_12_23_interval :
    (logCertificate_35.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_4830.upper ≤
      discrepancy (1 / 10) sample_12_23 ∧
    discrepancy (1 / 10) sample_12_23 ≤
      (logCertificate_35.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_4830.lower := by
  have hr : radical (12 * 23 * 35) = 4830 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_12_23.a * sample_12_23.b * sample_12_23.c)) :=
    ⟨logCertificate_4830.lower, logCertificate_4830.upper,
      by simpa only [sample_12_23, hr] using logCertificate_4830.lower_le,
      by simpa only [sample_12_23, hr] using logCertificate_4830.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_12_23 logCertificate_35 support
  simpa only [support] using h

theorem sample_12_23_upper : discrepancy (1 / 10) sample_12_23 ≤ (227 / 1000) := by
  have h := sample_12_23_interval.2
  norm_num [logCertificate_35, logCertificate_4830] at h
  linarith

def sample_13_22 : Triple := ⟨13, 22, 35, by decide, by decide, by decide, by decide⟩
theorem sample_13_22_interval :
    (logCertificate_35.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_10010.upper ≤
      discrepancy (1 / 10) sample_13_22 ∧
    discrepancy (1 / 10) sample_13_22 ≤
      (logCertificate_35.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_10010.lower := by
  have hr : radical (13 * 22 * 35) = 10010 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_13_22.a * sample_13_22.b * sample_13_22.c)) :=
    ⟨logCertificate_10010.lower, logCertificate_10010.upper,
      by simpa only [sample_13_22, hr] using logCertificate_10010.lower_le,
      by simpa only [sample_13_22, hr] using logCertificate_10010.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_13_22 logCertificate_35 support
  simpa only [support] using h

theorem sample_13_22_upper : discrepancy (1 / 10) sample_13_22 ≤ (227 / 1000) := by
  have h := sample_13_22_interval.2
  norm_num [logCertificate_35, logCertificate_10010] at h
  linarith

def sample_16_19 : Triple := ⟨16, 19, 35, by decide, by decide, by decide, by decide⟩
theorem sample_16_19_interval :
    (logCertificate_35.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1330.upper ≤
      discrepancy (1 / 10) sample_16_19 ∧
    discrepancy (1 / 10) sample_16_19 ≤
      (logCertificate_35.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1330.lower := by
  have hr : radical (16 * 19 * 35) = 1330 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_16_19.a * sample_16_19.b * sample_16_19.c)) :=
    ⟨logCertificate_1330.lower, logCertificate_1330.upper,
      by simpa only [sample_16_19, hr] using logCertificate_1330.lower_le,
      by simpa only [sample_16_19, hr] using logCertificate_1330.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_16_19 logCertificate_35 support
  simpa only [support] using h

theorem sample_16_19_upper : discrepancy (1 / 10) sample_16_19 ≤ (227 / 1000) := by
  have h := sample_16_19_interval.2
  norm_num [logCertificate_35, logCertificate_1330] at h
  linarith

def sample_17_18 : Triple := ⟨17, 18, 35, by decide, by decide, by decide, by decide⟩
theorem sample_17_18_interval :
    (logCertificate_35.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_3570.upper ≤
      discrepancy (1 / 10) sample_17_18 ∧
    discrepancy (1 / 10) sample_17_18 ≤
      (logCertificate_35.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_3570.lower := by
  have hr : radical (17 * 18 * 35) = 3570 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_17_18.a * sample_17_18.b * sample_17_18.c)) :=
    ⟨logCertificate_3570.lower, logCertificate_3570.upper,
      by simpa only [sample_17_18, hr] using logCertificate_3570.lower_le,
      by simpa only [sample_17_18, hr] using logCertificate_3570.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_17_18 logCertificate_35 support
  simpa only [support] using h

theorem sample_17_18_upper : discrepancy (1 / 10) sample_17_18 ≤ (227 / 1000) := by
  have h := sample_17_18_interval.2
  norm_num [logCertificate_35, logCertificate_3570] at h
  linarith

def sample_1_35 : Triple := ⟨1, 35, 36, by decide, by decide, by decide, by decide⟩
theorem sample_1_35_interval :
    (logCertificate_36.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_210.upper ≤
      discrepancy (1 / 10) sample_1_35 ∧
    discrepancy (1 / 10) sample_1_35 ≤
      (logCertificate_36.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_210.lower := by
  have hr : radical (1 * 35 * 36) = 210 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_1_35.a * sample_1_35.b * sample_1_35.c)) :=
    ⟨logCertificate_210.lower, logCertificate_210.upper,
      by simpa only [sample_1_35, hr] using logCertificate_210.lower_le,
      by simpa only [sample_1_35, hr] using logCertificate_210.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_1_35 logCertificate_36 support
  simpa only [support] using h

theorem sample_1_35_upper : discrepancy (1 / 10) sample_1_35 ≤ (227 / 1000) := by
  have h := sample_1_35_interval.2
  norm_num [logCertificate_36, logCertificate_210] at h
  linarith

def sample_5_31 : Triple := ⟨5, 31, 36, by decide, by decide, by decide, by decide⟩
theorem sample_5_31_interval :
    (logCertificate_36.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_930.upper ≤
      discrepancy (1 / 10) sample_5_31 ∧
    discrepancy (1 / 10) sample_5_31 ≤
      (logCertificate_36.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_930.lower := by
  have hr : radical (5 * 31 * 36) = 930 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_5_31.a * sample_5_31.b * sample_5_31.c)) :=
    ⟨logCertificate_930.lower, logCertificate_930.upper,
      by simpa only [sample_5_31, hr] using logCertificate_930.lower_le,
      by simpa only [sample_5_31, hr] using logCertificate_930.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_5_31 logCertificate_36 support
  simpa only [support] using h

theorem sample_5_31_upper : discrepancy (1 / 10) sample_5_31 ≤ (227 / 1000) := by
  have h := sample_5_31_interval.2
  norm_num [logCertificate_36, logCertificate_930] at h
  linarith

def sample_7_29 : Triple := ⟨7, 29, 36, by decide, by decide, by decide, by decide⟩
theorem sample_7_29_interval :
    (logCertificate_36.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1218.upper ≤
      discrepancy (1 / 10) sample_7_29 ∧
    discrepancy (1 / 10) sample_7_29 ≤
      (logCertificate_36.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1218.lower := by
  have hr : radical (7 * 29 * 36) = 1218 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_7_29.a * sample_7_29.b * sample_7_29.c)) :=
    ⟨logCertificate_1218.lower, logCertificate_1218.upper,
      by simpa only [sample_7_29, hr] using logCertificate_1218.lower_le,
      by simpa only [sample_7_29, hr] using logCertificate_1218.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_7_29 logCertificate_36 support
  simpa only [support] using h

theorem sample_7_29_upper : discrepancy (1 / 10) sample_7_29 ≤ (227 / 1000) := by
  have h := sample_7_29_interval.2
  norm_num [logCertificate_36, logCertificate_1218] at h
  linarith

def sample_11_25 : Triple := ⟨11, 25, 36, by decide, by decide, by decide, by decide⟩
theorem sample_11_25_interval :
    (logCertificate_36.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_330.upper ≤
      discrepancy (1 / 10) sample_11_25 ∧
    discrepancy (1 / 10) sample_11_25 ≤
      (logCertificate_36.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_330.lower := by
  have hr : radical (11 * 25 * 36) = 330 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_11_25.a * sample_11_25.b * sample_11_25.c)) :=
    ⟨logCertificate_330.lower, logCertificate_330.upper,
      by simpa only [sample_11_25, hr] using logCertificate_330.lower_le,
      by simpa only [sample_11_25, hr] using logCertificate_330.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_11_25 logCertificate_36 support
  simpa only [support] using h

theorem sample_11_25_upper : discrepancy (1 / 10) sample_11_25 ≤ (227 / 1000) := by
  have h := sample_11_25_interval.2
  norm_num [logCertificate_36, logCertificate_330] at h
  linarith

def sample_13_23 : Triple := ⟨13, 23, 36, by decide, by decide, by decide, by decide⟩
theorem sample_13_23_interval :
    (logCertificate_36.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1794.upper ≤
      discrepancy (1 / 10) sample_13_23 ∧
    discrepancy (1 / 10) sample_13_23 ≤
      (logCertificate_36.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1794.lower := by
  have hr : radical (13 * 23 * 36) = 1794 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_13_23.a * sample_13_23.b * sample_13_23.c)) :=
    ⟨logCertificate_1794.lower, logCertificate_1794.upper,
      by simpa only [sample_13_23, hr] using logCertificate_1794.lower_le,
      by simpa only [sample_13_23, hr] using logCertificate_1794.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_13_23 logCertificate_36 support
  simpa only [support] using h

theorem sample_13_23_upper : discrepancy (1 / 10) sample_13_23 ≤ (227 / 1000) := by
  have h := sample_13_23_interval.2
  norm_num [logCertificate_36, logCertificate_1794] at h
  linarith

def sample_17_19 : Triple := ⟨17, 19, 36, by decide, by decide, by decide, by decide⟩
theorem sample_17_19_interval :
    (logCertificate_36.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1938.upper ≤
      discrepancy (1 / 10) sample_17_19 ∧
    discrepancy (1 / 10) sample_17_19 ≤
      (logCertificate_36.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1938.lower := by
  have hr : radical (17 * 19 * 36) = 1938 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_17_19.a * sample_17_19.b * sample_17_19.c)) :=
    ⟨logCertificate_1938.lower, logCertificate_1938.upper,
      by simpa only [sample_17_19, hr] using logCertificate_1938.lower_le,
      by simpa only [sample_17_19, hr] using logCertificate_1938.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_17_19 logCertificate_36 support
  simpa only [support] using h

theorem sample_17_19_upper : discrepancy (1 / 10) sample_17_19 ≤ (227 / 1000) := by
  have h := sample_17_19_interval.2
  norm_num [logCertificate_36, logCertificate_1938] at h
  linarith

def sample_1_36 : Triple := ⟨1, 36, 37, by decide, by decide, by decide, by decide⟩
theorem sample_1_36_interval :
    (logCertificate_37.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_222.upper ≤
      discrepancy (1 / 10) sample_1_36 ∧
    discrepancy (1 / 10) sample_1_36 ≤
      (logCertificate_37.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_222.lower := by
  have hr : radical (1 * 36 * 37) = 222 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_1_36.a * sample_1_36.b * sample_1_36.c)) :=
    ⟨logCertificate_222.lower, logCertificate_222.upper,
      by simpa only [sample_1_36, hr] using logCertificate_222.lower_le,
      by simpa only [sample_1_36, hr] using logCertificate_222.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_1_36 logCertificate_37 support
  simpa only [support] using h

theorem sample_1_36_upper : discrepancy (1 / 10) sample_1_36 ≤ (227 / 1000) := by
  have h := sample_1_36_interval.2
  norm_num [logCertificate_37, logCertificate_222] at h
  linarith

def sample_2_35 : Triple := ⟨2, 35, 37, by decide, by decide, by decide, by decide⟩
theorem sample_2_35_interval :
    (logCertificate_37.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_2590.upper ≤
      discrepancy (1 / 10) sample_2_35 ∧
    discrepancy (1 / 10) sample_2_35 ≤
      (logCertificate_37.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_2590.lower := by
  have hr : radical (2 * 35 * 37) = 2590 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_2_35.a * sample_2_35.b * sample_2_35.c)) :=
    ⟨logCertificate_2590.lower, logCertificate_2590.upper,
      by simpa only [sample_2_35, hr] using logCertificate_2590.lower_le,
      by simpa only [sample_2_35, hr] using logCertificate_2590.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_2_35 logCertificate_37 support
  simpa only [support] using h

theorem sample_2_35_upper : discrepancy (1 / 10) sample_2_35 ≤ (227 / 1000) := by
  have h := sample_2_35_interval.2
  norm_num [logCertificate_37, logCertificate_2590] at h
  linarith

def sample_3_34 : Triple := ⟨3, 34, 37, by decide, by decide, by decide, by decide⟩
theorem sample_3_34_interval :
    (logCertificate_37.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_3774.upper ≤
      discrepancy (1 / 10) sample_3_34 ∧
    discrepancy (1 / 10) sample_3_34 ≤
      (logCertificate_37.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_3774.lower := by
  have hr : radical (3 * 34 * 37) = 3774 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_3_34.a * sample_3_34.b * sample_3_34.c)) :=
    ⟨logCertificate_3774.lower, logCertificate_3774.upper,
      by simpa only [sample_3_34, hr] using logCertificate_3774.lower_le,
      by simpa only [sample_3_34, hr] using logCertificate_3774.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_3_34 logCertificate_37 support
  simpa only [support] using h

theorem sample_3_34_upper : discrepancy (1 / 10) sample_3_34 ≤ (227 / 1000) := by
  have h := sample_3_34_interval.2
  norm_num [logCertificate_37, logCertificate_3774] at h
  linarith

def sample_4_33 : Triple := ⟨4, 33, 37, by decide, by decide, by decide, by decide⟩
theorem sample_4_33_interval :
    (logCertificate_37.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_2442.upper ≤
      discrepancy (1 / 10) sample_4_33 ∧
    discrepancy (1 / 10) sample_4_33 ≤
      (logCertificate_37.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_2442.lower := by
  have hr : radical (4 * 33 * 37) = 2442 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_4_33.a * sample_4_33.b * sample_4_33.c)) :=
    ⟨logCertificate_2442.lower, logCertificate_2442.upper,
      by simpa only [sample_4_33, hr] using logCertificate_2442.lower_le,
      by simpa only [sample_4_33, hr] using logCertificate_2442.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_4_33 logCertificate_37 support
  simpa only [support] using h

theorem sample_4_33_upper : discrepancy (1 / 10) sample_4_33 ≤ (227 / 1000) := by
  have h := sample_4_33_interval.2
  norm_num [logCertificate_37, logCertificate_2442] at h
  linarith

def sample_5_32 : Triple := ⟨5, 32, 37, by decide, by decide, by decide, by decide⟩
theorem sample_5_32_interval :
    (logCertificate_37.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_370.upper ≤
      discrepancy (1 / 10) sample_5_32 ∧
    discrepancy (1 / 10) sample_5_32 ≤
      (logCertificate_37.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_370.lower := by
  have hr : radical (5 * 32 * 37) = 370 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_5_32.a * sample_5_32.b * sample_5_32.c)) :=
    ⟨logCertificate_370.lower, logCertificate_370.upper,
      by simpa only [sample_5_32, hr] using logCertificate_370.lower_le,
      by simpa only [sample_5_32, hr] using logCertificate_370.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_5_32 logCertificate_37 support
  simpa only [support] using h

theorem sample_5_32_upper : discrepancy (1 / 10) sample_5_32 ≤ (227 / 1000) := by
  have h := sample_5_32_interval.2
  norm_num [logCertificate_37, logCertificate_370] at h
  linarith

def sample_6_31 : Triple := ⟨6, 31, 37, by decide, by decide, by decide, by decide⟩
theorem sample_6_31_interval :
    (logCertificate_37.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_6882.upper ≤
      discrepancy (1 / 10) sample_6_31 ∧
    discrepancy (1 / 10) sample_6_31 ≤
      (logCertificate_37.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_6882.lower := by
  have hr : radical (6 * 31 * 37) = 6882 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_6_31.a * sample_6_31.b * sample_6_31.c)) :=
    ⟨logCertificate_6882.lower, logCertificate_6882.upper,
      by simpa only [sample_6_31, hr] using logCertificate_6882.lower_le,
      by simpa only [sample_6_31, hr] using logCertificate_6882.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_6_31 logCertificate_37 support
  simpa only [support] using h

theorem sample_6_31_upper : discrepancy (1 / 10) sample_6_31 ≤ (227 / 1000) := by
  have h := sample_6_31_interval.2
  norm_num [logCertificate_37, logCertificate_6882] at h
  linarith

def sample_7_30 : Triple := ⟨7, 30, 37, by decide, by decide, by decide, by decide⟩
theorem sample_7_30_interval :
    (logCertificate_37.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_7770.upper ≤
      discrepancy (1 / 10) sample_7_30 ∧
    discrepancy (1 / 10) sample_7_30 ≤
      (logCertificate_37.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_7770.lower := by
  have hr : radical (7 * 30 * 37) = 7770 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_7_30.a * sample_7_30.b * sample_7_30.c)) :=
    ⟨logCertificate_7770.lower, logCertificate_7770.upper,
      by simpa only [sample_7_30, hr] using logCertificate_7770.lower_le,
      by simpa only [sample_7_30, hr] using logCertificate_7770.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_7_30 logCertificate_37 support
  simpa only [support] using h

theorem sample_7_30_upper : discrepancy (1 / 10) sample_7_30 ≤ (227 / 1000) := by
  have h := sample_7_30_interval.2
  norm_num [logCertificate_37, logCertificate_7770] at h
  linarith

def sample_8_29 : Triple := ⟨8, 29, 37, by decide, by decide, by decide, by decide⟩
theorem sample_8_29_interval :
    (logCertificate_37.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_2146.upper ≤
      discrepancy (1 / 10) sample_8_29 ∧
    discrepancy (1 / 10) sample_8_29 ≤
      (logCertificate_37.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_2146.lower := by
  have hr : radical (8 * 29 * 37) = 2146 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_8_29.a * sample_8_29.b * sample_8_29.c)) :=
    ⟨logCertificate_2146.lower, logCertificate_2146.upper,
      by simpa only [sample_8_29, hr] using logCertificate_2146.lower_le,
      by simpa only [sample_8_29, hr] using logCertificate_2146.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_8_29 logCertificate_37 support
  simpa only [support] using h

theorem sample_8_29_upper : discrepancy (1 / 10) sample_8_29 ≤ (227 / 1000) := by
  have h := sample_8_29_interval.2
  norm_num [logCertificate_37, logCertificate_2146] at h
  linarith

def sample_9_28 : Triple := ⟨9, 28, 37, by decide, by decide, by decide, by decide⟩
theorem sample_9_28_interval :
    (logCertificate_37.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1554.upper ≤
      discrepancy (1 / 10) sample_9_28 ∧
    discrepancy (1 / 10) sample_9_28 ≤
      (logCertificate_37.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1554.lower := by
  have hr : radical (9 * 28 * 37) = 1554 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_9_28.a * sample_9_28.b * sample_9_28.c)) :=
    ⟨logCertificate_1554.lower, logCertificate_1554.upper,
      by simpa only [sample_9_28, hr] using logCertificate_1554.lower_le,
      by simpa only [sample_9_28, hr] using logCertificate_1554.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_9_28 logCertificate_37 support
  simpa only [support] using h

theorem sample_9_28_upper : discrepancy (1 / 10) sample_9_28 ≤ (227 / 1000) := by
  have h := sample_9_28_interval.2
  norm_num [logCertificate_37, logCertificate_1554] at h
  linarith

def sample_10_27 : Triple := ⟨10, 27, 37, by decide, by decide, by decide, by decide⟩
theorem sample_10_27_interval :
    (logCertificate_37.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1110.upper ≤
      discrepancy (1 / 10) sample_10_27 ∧
    discrepancy (1 / 10) sample_10_27 ≤
      (logCertificate_37.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1110.lower := by
  have hr : radical (10 * 27 * 37) = 1110 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_10_27.a * sample_10_27.b * sample_10_27.c)) :=
    ⟨logCertificate_1110.lower, logCertificate_1110.upper,
      by simpa only [sample_10_27, hr] using logCertificate_1110.lower_le,
      by simpa only [sample_10_27, hr] using logCertificate_1110.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_10_27 logCertificate_37 support
  simpa only [support] using h

theorem sample_10_27_upper : discrepancy (1 / 10) sample_10_27 ≤ (227 / 1000) := by
  have h := sample_10_27_interval.2
  norm_num [logCertificate_37, logCertificate_1110] at h
  linarith

def sample_11_26 : Triple := ⟨11, 26, 37, by decide, by decide, by decide, by decide⟩
theorem sample_11_26_interval :
    (logCertificate_37.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_10582.upper ≤
      discrepancy (1 / 10) sample_11_26 ∧
    discrepancy (1 / 10) sample_11_26 ≤
      (logCertificate_37.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_10582.lower := by
  have hr : radical (11 * 26 * 37) = 10582 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_11_26.a * sample_11_26.b * sample_11_26.c)) :=
    ⟨logCertificate_10582.lower, logCertificate_10582.upper,
      by simpa only [sample_11_26, hr] using logCertificate_10582.lower_le,
      by simpa only [sample_11_26, hr] using logCertificate_10582.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_11_26 logCertificate_37 support
  simpa only [support] using h

theorem sample_11_26_upper : discrepancy (1 / 10) sample_11_26 ≤ (227 / 1000) := by
  have h := sample_11_26_interval.2
  norm_num [logCertificate_37, logCertificate_10582] at h
  linarith

def sample_12_25 : Triple := ⟨12, 25, 37, by decide, by decide, by decide, by decide⟩
theorem sample_12_25_interval :
    (logCertificate_37.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1110.upper ≤
      discrepancy (1 / 10) sample_12_25 ∧
    discrepancy (1 / 10) sample_12_25 ≤
      (logCertificate_37.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1110.lower := by
  have hr : radical (12 * 25 * 37) = 1110 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_12_25.a * sample_12_25.b * sample_12_25.c)) :=
    ⟨logCertificate_1110.lower, logCertificate_1110.upper,
      by simpa only [sample_12_25, hr] using logCertificate_1110.lower_le,
      by simpa only [sample_12_25, hr] using logCertificate_1110.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_12_25 logCertificate_37 support
  simpa only [support] using h

theorem sample_12_25_upper : discrepancy (1 / 10) sample_12_25 ≤ (227 / 1000) := by
  have h := sample_12_25_interval.2
  norm_num [logCertificate_37, logCertificate_1110] at h
  linarith

def sample_13_24 : Triple := ⟨13, 24, 37, by decide, by decide, by decide, by decide⟩
theorem sample_13_24_interval :
    (logCertificate_37.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_2886.upper ≤
      discrepancy (1 / 10) sample_13_24 ∧
    discrepancy (1 / 10) sample_13_24 ≤
      (logCertificate_37.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_2886.lower := by
  have hr : radical (13 * 24 * 37) = 2886 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_13_24.a * sample_13_24.b * sample_13_24.c)) :=
    ⟨logCertificate_2886.lower, logCertificate_2886.upper,
      by simpa only [sample_13_24, hr] using logCertificate_2886.lower_le,
      by simpa only [sample_13_24, hr] using logCertificate_2886.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_13_24 logCertificate_37 support
  simpa only [support] using h

theorem sample_13_24_upper : discrepancy (1 / 10) sample_13_24 ≤ (227 / 1000) := by
  have h := sample_13_24_interval.2
  norm_num [logCertificate_37, logCertificate_2886] at h
  linarith

def sample_14_23 : Triple := ⟨14, 23, 37, by decide, by decide, by decide, by decide⟩
theorem sample_14_23_interval :
    (logCertificate_37.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_11914.upper ≤
      discrepancy (1 / 10) sample_14_23 ∧
    discrepancy (1 / 10) sample_14_23 ≤
      (logCertificate_37.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_11914.lower := by
  have hr : radical (14 * 23 * 37) = 11914 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_14_23.a * sample_14_23.b * sample_14_23.c)) :=
    ⟨logCertificate_11914.lower, logCertificate_11914.upper,
      by simpa only [sample_14_23, hr] using logCertificate_11914.lower_le,
      by simpa only [sample_14_23, hr] using logCertificate_11914.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_14_23 logCertificate_37 support
  simpa only [support] using h

theorem sample_14_23_upper : discrepancy (1 / 10) sample_14_23 ≤ (227 / 1000) := by
  have h := sample_14_23_interval.2
  norm_num [logCertificate_37, logCertificate_11914] at h
  linarith

def sample_15_22 : Triple := ⟨15, 22, 37, by decide, by decide, by decide, by decide⟩
theorem sample_15_22_interval :
    (logCertificate_37.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_12210.upper ≤
      discrepancy (1 / 10) sample_15_22 ∧
    discrepancy (1 / 10) sample_15_22 ≤
      (logCertificate_37.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_12210.lower := by
  have hr : radical (15 * 22 * 37) = 12210 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_15_22.a * sample_15_22.b * sample_15_22.c)) :=
    ⟨logCertificate_12210.lower, logCertificate_12210.upper,
      by simpa only [sample_15_22, hr] using logCertificate_12210.lower_le,
      by simpa only [sample_15_22, hr] using logCertificate_12210.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_15_22 logCertificate_37 support
  simpa only [support] using h

theorem sample_15_22_upper : discrepancy (1 / 10) sample_15_22 ≤ (227 / 1000) := by
  have h := sample_15_22_interval.2
  norm_num [logCertificate_37, logCertificate_12210] at h
  linarith

def sample_16_21 : Triple := ⟨16, 21, 37, by decide, by decide, by decide, by decide⟩
theorem sample_16_21_interval :
    (logCertificate_37.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1554.upper ≤
      discrepancy (1 / 10) sample_16_21 ∧
    discrepancy (1 / 10) sample_16_21 ≤
      (logCertificate_37.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1554.lower := by
  have hr : radical (16 * 21 * 37) = 1554 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_16_21.a * sample_16_21.b * sample_16_21.c)) :=
    ⟨logCertificate_1554.lower, logCertificate_1554.upper,
      by simpa only [sample_16_21, hr] using logCertificate_1554.lower_le,
      by simpa only [sample_16_21, hr] using logCertificate_1554.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_16_21 logCertificate_37 support
  simpa only [support] using h

theorem sample_16_21_upper : discrepancy (1 / 10) sample_16_21 ≤ (227 / 1000) := by
  have h := sample_16_21_interval.2
  norm_num [logCertificate_37, logCertificate_1554] at h
  linarith

def sample_17_20 : Triple := ⟨17, 20, 37, by decide, by decide, by decide, by decide⟩
theorem sample_17_20_interval :
    (logCertificate_37.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_6290.upper ≤
      discrepancy (1 / 10) sample_17_20 ∧
    discrepancy (1 / 10) sample_17_20 ≤
      (logCertificate_37.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_6290.lower := by
  have hr : radical (17 * 20 * 37) = 6290 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_17_20.a * sample_17_20.b * sample_17_20.c)) :=
    ⟨logCertificate_6290.lower, logCertificate_6290.upper,
      by simpa only [sample_17_20, hr] using logCertificate_6290.lower_le,
      by simpa only [sample_17_20, hr] using logCertificate_6290.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_17_20 logCertificate_37 support
  simpa only [support] using h

theorem sample_17_20_upper : discrepancy (1 / 10) sample_17_20 ≤ (227 / 1000) := by
  have h := sample_17_20_interval.2
  norm_num [logCertificate_37, logCertificate_6290] at h
  linarith

def sample_18_19 : Triple := ⟨18, 19, 37, by decide, by decide, by decide, by decide⟩
theorem sample_18_19_interval :
    (logCertificate_37.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_4218.upper ≤
      discrepancy (1 / 10) sample_18_19 ∧
    discrepancy (1 / 10) sample_18_19 ≤
      (logCertificate_37.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_4218.lower := by
  have hr : radical (18 * 19 * 37) = 4218 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_18_19.a * sample_18_19.b * sample_18_19.c)) :=
    ⟨logCertificate_4218.lower, logCertificate_4218.upper,
      by simpa only [sample_18_19, hr] using logCertificate_4218.lower_le,
      by simpa only [sample_18_19, hr] using logCertificate_4218.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_18_19 logCertificate_37 support
  simpa only [support] using h

theorem sample_18_19_upper : discrepancy (1 / 10) sample_18_19 ≤ (227 / 1000) := by
  have h := sample_18_19_interval.2
  norm_num [logCertificate_37, logCertificate_4218] at h
  linarith

def sample_1_37 : Triple := ⟨1, 37, 38, by decide, by decide, by decide, by decide⟩
theorem sample_1_37_interval :
    (logCertificate_38.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1406.upper ≤
      discrepancy (1 / 10) sample_1_37 ∧
    discrepancy (1 / 10) sample_1_37 ≤
      (logCertificate_38.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1406.lower := by
  have hr : radical (1 * 37 * 38) = 1406 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_1_37.a * sample_1_37.b * sample_1_37.c)) :=
    ⟨logCertificate_1406.lower, logCertificate_1406.upper,
      by simpa only [sample_1_37, hr] using logCertificate_1406.lower_le,
      by simpa only [sample_1_37, hr] using logCertificate_1406.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_1_37 logCertificate_38 support
  simpa only [support] using h

theorem sample_1_37_upper : discrepancy (1 / 10) sample_1_37 ≤ (227 / 1000) := by
  have h := sample_1_37_interval.2
  norm_num [logCertificate_38, logCertificate_1406] at h
  linarith

def sample_3_35 : Triple := ⟨3, 35, 38, by decide, by decide, by decide, by decide⟩
theorem sample_3_35_interval :
    (logCertificate_38.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_3990.upper ≤
      discrepancy (1 / 10) sample_3_35 ∧
    discrepancy (1 / 10) sample_3_35 ≤
      (logCertificate_38.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_3990.lower := by
  have hr : radical (3 * 35 * 38) = 3990 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_3_35.a * sample_3_35.b * sample_3_35.c)) :=
    ⟨logCertificate_3990.lower, logCertificate_3990.upper,
      by simpa only [sample_3_35, hr] using logCertificate_3990.lower_le,
      by simpa only [sample_3_35, hr] using logCertificate_3990.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_3_35 logCertificate_38 support
  simpa only [support] using h

theorem sample_3_35_upper : discrepancy (1 / 10) sample_3_35 ≤ (227 / 1000) := by
  have h := sample_3_35_interval.2
  norm_num [logCertificate_38, logCertificate_3990] at h
  linarith

def sample_5_33 : Triple := ⟨5, 33, 38, by decide, by decide, by decide, by decide⟩
theorem sample_5_33_interval :
    (logCertificate_38.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_6270.upper ≤
      discrepancy (1 / 10) sample_5_33 ∧
    discrepancy (1 / 10) sample_5_33 ≤
      (logCertificate_38.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_6270.lower := by
  have hr : radical (5 * 33 * 38) = 6270 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_5_33.a * sample_5_33.b * sample_5_33.c)) :=
    ⟨logCertificate_6270.lower, logCertificate_6270.upper,
      by simpa only [sample_5_33, hr] using logCertificate_6270.lower_le,
      by simpa only [sample_5_33, hr] using logCertificate_6270.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_5_33 logCertificate_38 support
  simpa only [support] using h

theorem sample_5_33_upper : discrepancy (1 / 10) sample_5_33 ≤ (227 / 1000) := by
  have h := sample_5_33_interval.2
  norm_num [logCertificate_38, logCertificate_6270] at h
  linarith

def sample_7_31 : Triple := ⟨7, 31, 38, by decide, by decide, by decide, by decide⟩
theorem sample_7_31_interval :
    (logCertificate_38.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_8246.upper ≤
      discrepancy (1 / 10) sample_7_31 ∧
    discrepancy (1 / 10) sample_7_31 ≤
      (logCertificate_38.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_8246.lower := by
  have hr : radical (7 * 31 * 38) = 8246 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_7_31.a * sample_7_31.b * sample_7_31.c)) :=
    ⟨logCertificate_8246.lower, logCertificate_8246.upper,
      by simpa only [sample_7_31, hr] using logCertificate_8246.lower_le,
      by simpa only [sample_7_31, hr] using logCertificate_8246.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_7_31 logCertificate_38 support
  simpa only [support] using h

theorem sample_7_31_upper : discrepancy (1 / 10) sample_7_31 ≤ (227 / 1000) := by
  have h := sample_7_31_interval.2
  norm_num [logCertificate_38, logCertificate_8246] at h
  linarith

def sample_9_29 : Triple := ⟨9, 29, 38, by decide, by decide, by decide, by decide⟩
theorem sample_9_29_interval :
    (logCertificate_38.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_3306.upper ≤
      discrepancy (1 / 10) sample_9_29 ∧
    discrepancy (1 / 10) sample_9_29 ≤
      (logCertificate_38.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_3306.lower := by
  have hr : radical (9 * 29 * 38) = 3306 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_9_29.a * sample_9_29.b * sample_9_29.c)) :=
    ⟨logCertificate_3306.lower, logCertificate_3306.upper,
      by simpa only [sample_9_29, hr] using logCertificate_3306.lower_le,
      by simpa only [sample_9_29, hr] using logCertificate_3306.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_9_29 logCertificate_38 support
  simpa only [support] using h

theorem sample_9_29_upper : discrepancy (1 / 10) sample_9_29 ≤ (227 / 1000) := by
  have h := sample_9_29_interval.2
  norm_num [logCertificate_38, logCertificate_3306] at h
  linarith

def sample_11_27 : Triple := ⟨11, 27, 38, by decide, by decide, by decide, by decide⟩
theorem sample_11_27_interval :
    (logCertificate_38.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1254.upper ≤
      discrepancy (1 / 10) sample_11_27 ∧
    discrepancy (1 / 10) sample_11_27 ≤
      (logCertificate_38.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_1254.lower := by
  have hr : radical (11 * 27 * 38) = 1254 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_11_27.a * sample_11_27.b * sample_11_27.c)) :=
    ⟨logCertificate_1254.lower, logCertificate_1254.upper,
      by simpa only [sample_11_27, hr] using logCertificate_1254.lower_le,
      by simpa only [sample_11_27, hr] using logCertificate_1254.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_11_27 logCertificate_38 support
  simpa only [support] using h

theorem sample_11_27_upper : discrepancy (1 / 10) sample_11_27 ≤ (227 / 1000) := by
  have h := sample_11_27_interval.2
  norm_num [logCertificate_38, logCertificate_1254] at h
  linarith

def sample_13_25 : Triple := ⟨13, 25, 38, by decide, by decide, by decide, by decide⟩
theorem sample_13_25_interval :
    (logCertificate_38.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_2470.upper ≤
      discrepancy (1 / 10) sample_13_25 ∧
    discrepancy (1 / 10) sample_13_25 ≤
      (logCertificate_38.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_2470.lower := by
  have hr : radical (13 * 25 * 38) = 2470 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_13_25.a * sample_13_25.b * sample_13_25.c)) :=
    ⟨logCertificate_2470.lower, logCertificate_2470.upper,
      by simpa only [sample_13_25, hr] using logCertificate_2470.lower_le,
      by simpa only [sample_13_25, hr] using logCertificate_2470.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_13_25 logCertificate_38 support
  simpa only [support] using h

theorem sample_13_25_upper : discrepancy (1 / 10) sample_13_25 ≤ (227 / 1000) := by
  have h := sample_13_25_interval.2
  norm_num [logCertificate_38, logCertificate_2470] at h
  linarith

def sample_15_23 : Triple := ⟨15, 23, 38, by decide, by decide, by decide, by decide⟩
theorem sample_15_23_interval :
    (logCertificate_38.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_13110.upper ≤
      discrepancy (1 / 10) sample_15_23 ∧
    discrepancy (1 / 10) sample_15_23 ≤
      (logCertificate_38.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_13110.lower := by
  have hr : radical (15 * 23 * 38) = 13110 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_15_23.a * sample_15_23.b * sample_15_23.c)) :=
    ⟨logCertificate_13110.lower, logCertificate_13110.upper,
      by simpa only [sample_15_23, hr] using logCertificate_13110.lower_le,
      by simpa only [sample_15_23, hr] using logCertificate_13110.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_15_23 logCertificate_38 support
  simpa only [support] using h

theorem sample_15_23_upper : discrepancy (1 / 10) sample_15_23 ≤ (227 / 1000) := by
  have h := sample_15_23_interval.2
  norm_num [logCertificate_38, logCertificate_13110] at h
  linarith

def sample_17_21 : Triple := ⟨17, 21, 38, by decide, by decide, by decide, by decide⟩
theorem sample_17_21_interval :
    (logCertificate_38.lower : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_13566.upper ≤
      discrepancy (1 / 10) sample_17_21 ∧
    discrepancy (1 / 10) sample_17_21 ≤
      (logCertificate_38.upper : ℝ) - (1 + ((1 / 10) : ℝ)) * logCertificate_13566.lower := by
  have hr : radical (17 * 21 * 38) = 13566 := by
    rw [radical_eq_primeFactors]
    norm_num [Nat.primeFactors, Nat.primeFactorsList]
  let support : LogEnclosure (radical (sample_17_21.a * sample_17_21.b * sample_17_21.c)) :=
    ⟨logCertificate_13566.lower, logCertificate_13566.upper,
      by simpa only [sample_17_21, hr] using logCertificate_13566.lower_le,
      by simpa only [sample_17_21, hr] using logCertificate_13566.le_upper⟩
  have h := discrepancy_enclosure (1 / 10) (by norm_num) sample_17_21 logCertificate_38 support
  simpa only [support] using h

theorem sample_17_21_upper : discrepancy (1 / 10) sample_17_21 ≤ (227 / 1000) := by
  have h := sample_17_21_interval.2
  norm_num [logCertificate_38, logCertificate_13566] at h
  linarith


end Imscribing.ABC.Window70E1_10
