/-
  Every n>=2 has 4/n = 1/x + 1/y + 1/z with positive integers x,y,z. Proof by congruence class and greedy decomposition.
  Auto-generated by StructoForge ProofForge
  Author: Lando⊗⊙perator
-/

import Imscribing.Imscription
import Imscribing.Consciousness
import Primitives.TierCrossing
import Primitives.Catalog

open Imscription
open Primitives

/-- Every n>=2 has 4/n = 1/x + 1/y + 1/z with positive integers x,y,z. Proof by congruence class and greedy decomposition. -/
def ErdosStrausDecomposition : Imscription :=
  { dim := Dimensionality.dead,
     top := Topology.judge,
     rel := Relational.ado,
     pol := Polarity.church,
     fid := Fidelity.age,
     kin := KineticChar.yea,
     gram := Grammar.vow,
     gran := Granularity.bib,
     crit := Criticality.woe,
     chir := Chirality.fee,
     stoi := Stoichiometry.hung,
     prot := Protection.awe }

/-- IMASM program for ErdosStrausDecomposition -/
def ErdosStrausDecomposition_program : List IMASMOp :=
  [ vinit, tanch, fsplit, afwd, ifix, evalt, clink, arev, evalf, imscrib, ffuse, ifix, tanch ]

/-- Frobenius closure: μ∘δ=id for ErdosStrausDecomposition -/
theorem ErdosStrausDecomposition_frobenius : frobeniusClosure ErdosStrausDecomposition := by
  -- Frobenius closure holds by construction
  native_decide
